using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using System.Security.Cryptography;using System.Text.Json;using Mono.Cecil;using MD=Mono.Cecil.MethodDefinition;using MR=Mono.Cecil.MethodReference;using FR=Mono.Cecil.FieldReference;
static class RepairNative40{
 static void R(bool b,string s){if(!b)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Align(int x,int a)=>(x+a-1)/a*a;
 class IL{public List<byte>B=new();Dictionary<string,int>labels=new();List<(int,string)>branches=new();public IL O(params byte[]b){B.AddRange(b);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}public IL Ref(byte op,IMetadataTokenProvider t)=>O(op).I(t.MetadataToken.ToInt32());public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Arg(int i)=>O((byte)(2+i));public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Br(byte op,string s){O(op);branches.Add((B.Count,s));I(0);return this;}public byte[]Done(){foreach(var(p,s)in branches)BitConverter.GetBytes(labels[s]-p-4).CopyTo(B,p);return B.ToArray();}}
 static void CopyTo(this byte[]b,List<byte>l,int p){for(int i=0;i<b.Length;i++)l[p+i]=b[i];}
 static int Off(PEReader pe,int rva){var s=pe.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static int Main(string[]args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[]args){R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh input/output/report");byte[]before=File.ReadAllBytes(args[0]);R(H(before)=="79345f3a8114e8f4e52c2add7b8c337334cc0bc5435c700c2ff6e731bce0c2ba","Pinned Native39 input");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);var module=asm.MainModule;using var pe=new PEReader(new MemoryStream(before));var md=pe.GetMetadataReader();var m=(MD)module.LookupToken(0x06000447);R(m.Body.ExceptionHandlers.Count==0&&m.HasThis&&m.Parameters[0].ParameterType.FullName=="Damage&","Pinned ref Damage signature");
  FR Field(string owner,string name)=>module.Types.Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);
  MR Call(string owner,string name)=>module.GetMemberReferences().OfType<MR>().Single(c=>c.DeclaringType.FullName==owner&&c.Name==name);
  var x=module.GetMemberReferences().OfType<FR>().Single(f=>f.FullName=="System.Single UnityEngine.Vector3::x");var il=new IL();R(m.Body.Variables[6].VariableType.FullName=="System.Int32","Existing dispatch scratch");il.Arg(0).Ref(0x7B,Field("Zombie","ID")).O(0x13,6);
  // Decode the full original ID dispatch explicitly; negative/out-of-range IDs
  // perform no Damage dereference. All original in-action rereads are retained.
  foreach(int id in new[]{3,11,16})il.O(0x11,6).Int(id).Br(0x3B,"full");
  il.O(0x11,6).Int(17).Br(0x3B,"camp").O(0x11,6).Int(18).Br(0x3B,"special").O(0x11,6).Int(13).Br(0x3B,"left");
  foreach(int id in new[]{6,7,8,9,19,20,21,22})il.O(0x11,6).Int(id).Br(0x3B,"right");il.O(0x2A);
  void Write(string name,int value){il.Arg(1).O(0x50).Int(value).Ref(0x7D,Field("Damage",name));}
  void Flags(bool submarine){Write("anti_air_able",1);Write("anti_ground_able",1);if(submarine)Write("anti_submarine_able",1);}
  il.Label("full");Write("damageAttribute",3);Flags(true);il.O(0x2A);
  il.Label("camp").Arg(2).Int(0).Br(0x3F,"ret");Write("damageAttribute",3);Flags(true);Write("camp",0);il.O(0x2A);
  il.Label("special").Arg(3).Br(0x39,"threeFlags").Arg(3).Int(1).Br(0x40,"ret");Write("oppositeDirection",1);Flags(false);il.O(0x2A);il.Label("threeFlags");Flags(true);il.O(0x2A);
  void Scale(){il.Arg(1).O(0x50).Arg(0).Ref(0x28,Call("UnityEngine.Component","get_transform")).Ref(0x6F,Call("UnityEngine.Transform","get_localScale")).Ref(0x7B,x).Int(0).O(0x6B);}
  il.Label("right").Arg(2).Int(0).Br(0x3F,"ret");Scale();il.O(0xFE,0x02).Ref(0x7D,Field("Damage","oppositeDirection")).O(0x2A);
  il.Label("left");Scale();il.O(0xFE,0x04).Ref(0x7D,Field("Damage","oppositeDirection")).O(0x2A).Label("ret").O(0x2A);
  byte[]code=il.Done();R(code.Length>m.Body.CodeSize,"Append mechanism intentionally exercised by full reconstruction");var last=pe.PEHeaders.SectionHeaders.Last();var ph=pe.PEHeaders;var opt=ph.PEHeader!;R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==before.Length&&last.SectionCharacteristics==(SectionCharacteristics)0x40000040&&ph.CorHeader!.StrongNameSignatureDirectory.Size==0&&opt.CertificateTableDirectory.Size==0,"Pinned unsigned EOF section");
  int oldRoot=Off(pe,ph.CorHeader.MetadataDirectory.RelativeVirtualAddress),rootSize=ph.CorHeader.MetadataDirectory.Size;byte[]meta=before[oldRoot..(oldRoot+rootSize)];int bodyOffset=before.Length,newRva=last.VirtualAddress+bodyOffset-last.PointerToRawData,rootOffset=Align(bodyOffset+12+code.Length,4);var after=new byte[Align(rootOffset+rootSize,opt.FileAlignment)];before.CopyTo(after,0);
  ushort flags=(ushort)(0x3003|(m.Body.InitLocals?0x10:0));BitConverter.GetBytes(flags).CopyTo(after,bodyOffset);BitConverter.GetBytes((ushort)3).CopyTo(after,bodyOffset+2);BitConverter.GetBytes(code.Length).CopyTo(after,bodyOffset+4);BitConverter.GetBytes(m.Body.LocalVarToken.ToInt32()).CopyTo(after,bodyOffset+8);code.CopyTo(after,bodyOffset+12);
  int row=md.GetTableMetadataOffset(TableIndex.MethodDef)+(checked((int)m.MetadataToken.RID)-1)*md.GetTableRowSize(TableIndex.MethodDef);BitConverter.GetBytes(newRva).CopyTo(meta,row);meta.CopyTo(after,rootOffset);
  int sh=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40,virtualSize=rootOffset-last.PointerToRawData+rootSize;BitConverter.GetBytes(virtualSize).CopyTo(after,sh+8);BitConverter.GetBytes(after.Length-last.PointerToRawData).CopyTo(after,sh+16);BitConverter.GetBytes(opt.SizeOfInitializedData+after.Length-before.Length).CopyTo(after,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+virtualSize,opt.SectionAlignment)).CopyTo(after,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(after,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(last.VirtualAddress+rootOffset-last.PointerToRawData).CopyTo(after,ph.CorHeaderStartOffset+8);
  File.WriteAllBytes(args[1],after);var report=new{input_sha256=H(before),candidate_sha256=H(after),methods=new[]{new{token="0x06000447",method=m.FullName,old_rva=m.RVA,new_rva=newRva,body_offset=bodyOffset,code_size=code.Length,code_sha256=H(code),max_stack=3,local_sig=m.Body.LocalVarToken.ToInt32(),init_locals=m.Body.InitLocals}},metadata=new{old_root=oldRoot,new_root=rootOffset,size=rootSize},scope="One appended complete method body and one existing MethodDef RVA change; no other row/heap/old-body edit"};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(report));
 }
}
