using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Reflection.PortableExecutable;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using MD=Mono.Cecil.MethodDefinition;
using MR=Mono.Cecil.MethodReference;
using FR=Mono.Cecil.FieldReference;
static class RepairNative51 {
 static void R(bool x,string m){if(!x)throw new InvalidOperationException(m);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static int Align(int x,int a)=>checked((x+a-1)/a*a);
 class IL {
  public List<byte> B=new();Dictionary<string,int> labels=new();List<(int p,string l)> branches=new();
  public IL O(params byte[] x){B.AddRange(x);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}
  public IL Ref(byte op,IMetadataTokenProvider r)=>O(op).I(r.MetadataToken.ToInt32());public IL Ref(byte op,int t)=>O(op).I(t);
  public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Float(float x)=>O(0x22).I(BitConverter.SingleToInt32Bits(x));
  public IL L(int i)=>i<4?O((byte)(6+i)):O(0x11,(byte)i);public IL S(int i)=>i<4?O((byte)(10+i)):O(0x13,(byte)i);public IL A(int i)=>O(0x12,(byte)i);
  public IL Arg(int i)=>i<4?O((byte)(2+i)):O(0x0E,(byte)i);
  public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Branch(byte op,string s){O(op);branches.Add((B.Count,s));I(0);return this;}
  public byte[] Done(){foreach(var(p,l)in branches){BitConverter.GetBytes(labels[l]-p-4).CopyTo(B,p);}return B.ToArray();}
 }
 record Stream(string Name,byte[] Data);
 record Added(string Name,int Token,int Parent,int NameIndex,int SignatureIndex);
 static (byte[] Image,object Evidence) Metadata(byte[] input,PEReader pe,Mono.Cecil.ModuleDefinition module){
  var md=pe.GetMetadataReader();int rootRva=pe.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress;var section=pe.PEHeaders.SectionHeaders.Single(s=>rootRva>=s.VirtualAddress&&rootRva<s.VirtualAddress+s.SizeOfRawData);int rootOffset=section.PointerToRawData+rootRva-section.VirtualAddress;int rootSize=pe.PEHeaders.CorHeader.MetadataDirectory.Size;byte[] root=input[rootOffset..(rootOffset+rootSize)];R(BitConverter.ToUInt32(root,0)==0x424A5342,"Metadata root");int vlen=BitConverter.ToInt32(root,12);int countAt=Align(16+vlen,4)+2;int count=BitConverter.ToUInt16(root,countAt);int p=countAt+2;var streams=new List<Stream>();
  for(int i=0;i<count;i++){int off=BitConverter.ToInt32(root,p),len=BitConverter.ToInt32(root,p+4);int end=Array.IndexOf(root,(byte)0,p+8);R(end>=0,"Stream name");string name=Encoding.ASCII.GetString(root,p+8,end-p-8);streams.Add(new(name,root[off..(off+len)]));p=Align(end+1,4);}int headEnd=p;
  int ti=streams.FindIndex(s=>s.Name=="#~");R(ti>=0,"Compressed table stream required");var table=streams[ti].Data;var stringStream=streams.Single(s=>s.Name=="#Strings").Data;var blobStream=streams.Single(s=>s.Name=="#Blob").Data;R((table[6]&3)==0,"Pinned 2-byte string/blob indexes");int rows=md.GetTableRowCount(TableIndex.MemberRef);int rowSize=md.GetTableRowSize(TableIndex.MemberRef);R(rows==1038&&rowSize==6,"Pinned MemberRef layout");R(md.GetTableRowCount(TableIndex.TypeSpec)<8192&&md.GetTableRowCount(TableIndex.TypeDef)<8192&&md.GetTableRowCount(TableIndex.TypeRef)<8192&&md.GetTableRowCount(TableIndex.ModuleRef)<8192&&md.GetTableRowCount(TableIndex.MethodDef)<8192,"Parent index width");
  int ts(string name){var hits=Enumerable.Range(1,md.GetTableRowCount(TableIndex.TypeSpec)).Select(i=>module.LookupToken(0x1B000000+i)).OfType<Mono.Cecil.TypeReference>().Where(t=>t.FullName==name).ToArray();R(hits.Length==1,"Exact TypeSpec "+name);return hits[0].MetadataToken.RID is uint r?checked((int)r):throw new Exception();}
  int originalStringSize=stringStream.Length;int nameIndex(string name){for(int i=0;i<stringStream.Length-name.Length;i++){if(Encoding.UTF8.GetString(stringStream,i,name.Length)==name&&stringStream[i+name.Length]==0)return i;}throw new Exception("Existing member name required "+name);}
  int sig(byte[] desired){foreach(var h in md.MemberReferences){var m=md.GetMemberReference(h);if(md.GetBlobBytes(m.Signature).SequenceEqual(desired))return MetadataTokens.GetHeapOffset(m.Signature);}throw new Exception("Existing signature missing");}
  var specs=new[]{"Almanac_DeviceWindow","Almanac_ZombieWindow"}.Select(n=>("get_Count",ts("System.Collections.Generic.List`1<"+n+">")*8+4,sig(new byte[]{0x20,0,8}))).ToArray();
  ulong valid=BitConverter.ToUInt64(table,8);R((valid&(1UL<<10))!=0,"MemberRef missing");int countPos=24+4*Enumerable.Range(0,10).Count(i=>(valid&(1UL<<i))!=0);R(BitConverter.ToInt32(table,countPos)==rows,"Row count pin");int tableStart=md.GetTableMetadataOffset(TableIndex.MemberRef);int streamRootOffset=Array.FindIndex(root,_=>false); // replaced with exact stream offset below
  int scan=countAt+2;for(int i=0;i<count;i++){int e=Array.IndexOf(root,(byte)0,scan+8);if(Encoding.ASCII.GetString(root,scan+8,e-scan-8)=="#~")streamRootOffset=BitConverter.ToInt32(root,scan);scan=Align(e+1,4);}R(streamRootOffset>=0,"Table stream root offset");int insert=tableStart-streamRootOffset+rows*rowSize;R(insert>=24&&insert<=table.Length,"MemberRef table end");var add=new List<byte>();var added=new List<Added>();foreach(var(name,parent,signature)in specs){int ni=nameIndex(name);R(ni<65536&&signature<65536&&parent<65536,"Index overflow");int coded=parent;add.AddRange(BitConverter.GetBytes((ushort)coded));add.AddRange(BitConverter.GetBytes((ushort)ni));add.AddRange(BitConverter.GetBytes((ushort)signature));added.Add(new(name,0x0A000000+rows+added.Count+1,((coded&7)==1?0x01000000:0x1B000000)+(coded>>3),ni,signature));}
  byte[] expanded=table[..insert].Concat(add).Concat(table[insert..]).ToArray();BitConverter.GetBytes(rows+added.Count).CopyTo(expanded,countPos);ulong sorted=BitConverter.ToUInt64(expanded,16);BitConverter.GetBytes(sorted&~(1UL<<10)).CopyTo(expanded,16);streams[ti]=new("#~",expanded);streams[streams.FindIndex(s=>s.Name=="#Strings")]=new("#Strings",stringStream);
  var nr=new List<byte>(root[..headEnd]);scan=countAt+2;foreach(var s in streams){while(nr.Count%4!=0)nr.Add(0);BitConverter.GetBytes(nr.Count).CopyTo(nr,scan);BitConverter.GetBytes(s.Data.Length).CopyTo(nr,scan+4);nr.AddRange(s.Data);int e=Array.IndexOf(root,(byte)0,scan+8);scan=Align(e+1,4);}byte[] meta=nr.ToArray();
  // The qualified Native29 metadata section is already the last section.
  // Its header has no room for another section header. Extend that read-only
  // section at EOF while retaining all existing bytes, raw starts and RVAs.
  var ph=pe.PEHeaders;var opt=ph.PEHeader!;R(opt.Magic==PEMagic.PE32&&opt.CertificateTableDirectory.Size==0&&ph.CorHeader.StrongNameSignatureDirectory.Size==0&&(ph.CorHeader.Flags&CorFlags.StrongNameSigned)==0,"Unsupported signed/input layout");var last=ph.SectionHeaders.Last();R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==input.Length&&last.VirtualSize<=last.SizeOfRawData&&last.SectionCharacteristics==(SectionCharacteristics)0x40000040,"Pinned extensible metadata section");R(rootOffset>=last.PointerToRawData&&rootOffset+rootSize<=input.Length,"Parent metadata in last section");int header=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40;int raw=Align(input.Length,opt.FileAlignment),va=last.VirtualAddress+raw-last.PointerToRawData,append=Align(meta.Length,opt.FileAlignment);var output=new byte[raw+append];input.CopyTo(output,0);meta.CopyTo(output,raw);int newVirtual=raw-last.PointerToRawData+meta.Length,newRaw=output.Length-last.PointerToRawData;
  BitConverter.GetBytes(newVirtual).CopyTo(output,header+8);BitConverter.GetBytes(newRaw).CopyTo(output,header+16);BitConverter.GetBytes(opt.SizeOfInitializedData+output.Length-input.Length).CopyTo(output,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+newVirtual,opt.SectionAlignment)).CopyTo(output,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(output,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(va).CopyTo(output,ph.CorHeaderStartOffset+8);BitConverter.GetBytes(meta.Length).CopyTo(output,ph.CorHeaderStartOffset+12);
  return(output,new{old_root_offset=rootOffset,old_root_size=rootSize,new_root_offset=raw,new_root_size=meta.Length,extended_section_header=header,old_virtual_size=last.VirtualSize,new_virtual_size=newVirtual,old_raw_size=last.SizeOfRawData,new_raw_size=newRaw,added,table_sorted_bit_cleared=(sorted&(1UL<<10))!=0,existing_heap_prefixes_unchanged=true,string_heap_added_bytes=stringStream.Length-originalStringSize});

 }
 static void CopyTo(this byte[] b,List<byte> list,int p){for(int j=0;j<b.Length;j++)list[p+j]=b[j];}
 static int Main(string[] args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[] args){R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh output/report");byte[] before=File.ReadAllBytes(args[0]);R(H(before)=="3ac10e0894e3eb78bbb559c10951284eff32263e8d9e8de9c5a8c2ec2d31a397","Pinned Native50 parent");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(before));var module=asm.MainModule;var(after,metadata)=Metadata(before,pe,module);int first=0x0A000000+pe.GetMetadataReader().GetTableRowCount(TableIndex.MemberRef)+1;int Count(int i)=>new[]{0x0A0000D1,0x0A0000D7,0x0A0000DD,first,first+1}[i];foreach(var (t,n) in new[]{(0x0A0000D1,"Device"),(0x0A0000D7,"Plant"),(0x0A0000DD,"Zombie")})R(((MR)module.LookupToken(t)).FullName=="System.Int32 System.Collections.Generic.List`1<"+n+">::get_Count()","Existing closed public Count");
  FR F(string owner,string name)=>module.GetTypes().Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);
  MR Method(string owner,string name)=>module.GetTypes().Single(t=>t.FullName==owner).Methods.Single(m=>m.Name==name);
  MR Ref(MD m,string name,string ownerPrefix)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MR>().First(r=>r.Name==name&&r.DeclaringType.FullName.StartsWith(ownerPrefix));
  var targets=new Dictionary<int,byte[]>();
  foreach(var (rid,owner,list,element,destroy,count) in new[]{(0x182,"DeviceManager","deviceList","Device","DestroyThis",0),(0x1EF,"PlantManager","plants","Plant","DestroyThis",1),(0x279,"ZombieManager","zombieList","Zombie","DestroyZombie",2)}){
   var m=(MD)module.LookupToken(0x06000000+rid);R(m.Body.Variables[2].VariableType.FullName=="System.Int32","Pinned reverse index");
   var il=new IL().Arg(0).Ref(0x7B,F(owner,list)).Ref(0x6F,Count(count)).Int(1).O(0x59).S(2).Branch(0x38,"test").Label("body").Arg(0).Ref(0x7B,F(owner,list)).L(2).Ref(0x6F,Ref(m,"get_Item","System.Collections.Generic.List`1")).Ref(0x6F,Method(element,destroy)).L(2).Int(1).O(0x59).S(2).Label("test").L(2).Int(0).Branch(0x3C,"body").O(0x2A);targets.Add(0x06000000+rid,il.Done());
  }
  foreach(var (rid,owner,list,win,lockName,count,open) in new[]{(0x560,"Almanac_DeviceHome","deviceWindowList","Almanac_DeviceWindow","almanac_DeviceLock",3,true),(0x563,"Almanac_DeviceHome","deviceWindowList","Almanac_DeviceWindow","almanac_DeviceLock",3,false),(0x5AF,"Almanac_ZombieHome","zombieWindowList","Almanac_ZombieWindow","almanac_ZombieLock",4,true),(0x5B0,"Almanac_ZombieHome","zombieWindowList","Almanac_ZombieWindow","almanac_ZombieLock",4,false)}){
   var m=(MD)module.LookupToken(0x06000000+rid);int index=open?3:4,save=open?4:5;R(m.Body.Variables[index].VariableType.FullName=="System.Int32"&&m.Body.Variables[save].VariableType.FullName=="Save","Pinned forward locals");var il=new IL();
   if(open)il.Arg(0).Ref(0x6F,Ref(m,"get_gameObject","UnityEngine.Component")).Int(1).Ref(0x6F,Ref(m,"SetActive","UnityEngine.GameObject"));
   il.Ref(0x7E,F("GlobalStaticVars","gLawnApp")).Ref(0x7B,F("GlobalStaticVars/LawnApp","savesManager")).Ref(0x7B,F("SavesManager","playerSave")).S(save).L(save).Branch(0x39,"finish").Int(0).S(index).Branch(0x38,"test").Label("body").Arg(0).Ref(0x7B,F(owner,list)).L(index).Ref(0x6F,Ref(m,"get_Item","System.Collections.Generic.List`1")).L(save).Ref(0x7B,F("Save",lockName)).L(index).O(0x91).Int(0).O(0xFE,0x03).Ref(0x6F,Method(win,"SetState")).L(index).Int(1).O(0x58).S(index).Label("test").L(index).Arg(0).Ref(0x7B,F(owner,list)).Ref(0x6F,Count(count)).Branch(0x3F,"body").Label("finish");
   if(open)il.Arg(0).Arg(1).Ref(0x28,Method(owner,owner=="Almanac_DeviceHome"?"CheckDevice":"CheckZombie"));il.O(0x2A);targets.Add(0x06000000+rid,il.Done());
  }
  {var m=(MD)module.LookupToken(0x060002AA);R(m.Body.Variables[1].VariableType.FullName=="System.Int32"&&m.Body.Variables[3].VariableType.FullName=="ZombieManager","Pinned Board locals");var il=new IL().Arg(0).Ref(0x7B,F("Board","plantManager")).Ref(0x6F,Method("PlantManager","ClearPlants")).Arg(0).Ref(0x7B,F("Board","zombieManager")).S(3).L(3).Ref(0x7B,F("ZombieManager","zombieList")).Ref(0x6F,Count(2)).Int(1).O(0x59).S(1).Branch(0x38,"test").Label("body").L(3).Ref(0x7B,F("ZombieManager","zombieList")).L(1).Ref(0x6F,Ref(m,"get_Item","System.Collections.Generic.List`1")).Ref(0x6F,Method("Zombie","DestroyZombie")).L(1).Int(1).O(0x59).S(1).Label("test").L(1).Int(0).Branch(0x3C,"body").Arg(0).Ref(0x7B,F("Board","deviceManager")).Ref(0x6F,Method("DeviceManager","ClearDevices")).Arg(0).Ref(0x6F,Ref(m,"get_gameObject","UnityEngine.Component")).Ref(0x28,Ref(m,"Destroy","UnityEngine.Object")).O(0x2A);targets.Add(0x060002AA,il.Done());}
  var rows=new List<object>();foreach(var pair in targets){var m=(MD)module.LookupToken(pair.Key);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0&&pair.Value.Length<=m.Body.CodeSize,"Pinned target and reserved size");var section=pe.PEHeaders.SectionHeaders.Single(s=>m.RVA>=s.VirtualAddress&&m.RVA<s.VirtualAddress+s.SizeOfRawData);int h=section.PointerToRawData+m.RVA-section.VirtualAddress;R((before[h]&3)==3&&(BitConverter.ToUInt16(before,h)>>12)==3,"Fat header");Array.Clear(after,h+12,m.Body.CodeSize);pair.Value.CopyTo(after,h+12);BitConverter.GetBytes((ushort)3).CopyTo(after,h+2);BitConverter.GetBytes(pair.Value.Length).CopyTo(after,h+4);rows.Add(new{token=$"0x{pair.Key:X8}",method=m.FullName,header=h,code_start=h+12,reserved_code_size=m.Body.CodeSize,new_code_size=pair.Value.Length,old_max=m.Body.MaxStackSize,new_max=3,local_sig=m.Body.LocalVarToken.ToInt32(),code_sha256=H(pair.Value)});}
  File.WriteAllBytes(args[1],after);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(before),candidate_sha256=H(after),metadata,methods=rows,scope="Eight native-backed reverse-clear and forward-almanac bodies. Two public closed List.Count refs; three existing public Count refs reused. Existing local signatures, rows, heaps and all non-target bodies preserved; unused target slot padding zeroed."},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine("CANDIDATE "+H(after));
 }
}
