using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;
public class Project {public int value;public int marker;}
public class SunManager {public int sunPoint;public List<Project>? suns;}
public class NodeAstar {public int marker;}
public class SwfManager {public Dictionary<string,float>? _groupRateScales;}
public static class Fixture{
 static Dictionary<string,Type> Map=new(){["Project"]=typeof(Project),["SunManager"]=typeof(SunManager),["NodeAstar"]=typeof(NodeAstar),["FTRuntime.SwfManager"]=typeof(SwfManager),["System.Collections.Generic.List`1"]=typeof(List<>),["System.Collections.Generic.Dictionary`2"]=typeof(Dictionary<,>),["System.String"]=typeof(string),["System.Single"]=typeof(float),["System.Object"]=typeof(object),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void),["System.NullReferenceException"]=typeof(NullReferenceException)};
 static Type T(TypeReference t)=>t is GenericInstanceType g?T(g.ElementType).MakeGenericType(g.GenericArguments.Select(T).ToArray()):Map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static Type Bound(TypeReference t,MethodReference m)=>t is GenericParameter p?T(((GenericInstanceType)m.DeclaringType).GenericArguments[p.Position]):T(t);
 static DynamicMethod Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,T(m.ReturnType),(m.HasThis?new[]{T(m.DeclaringType)}:Array.Empty<Type>()).Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray(),typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="missing_operation"){if(m.ReturnType.FullName!="System.Void")il.Emit(RO.Ldnull);il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="wrong_arithmetic"&&(op==RO.Add&&m.MetadataToken.ToInt32()==0x06000264||op==RO.Mul)){op=op==RO.Mul?RO.Add:RO.Sub;changed=true;}
   if(mutation=="checked_product"&&op==RO.Mul){op=RO.Mul_Ovf;changed=true;}
   if(mutation=="unordered_clamp"&&(op==RO.Blt_S||op==RO.Bgt_S)){op=op==RO.Blt_S?RO.Blt_Un_S:RO.Bgt_Un_S;changed=true;}
   if(mutation=="wrong_guard"&&op==RO.Brtrue_S){op=RO.Brfalse_S;changed=true;}
   if(mutation=="unsigned_gate"&&op==RO.Bge_S){op=RO.Bge_Un_S;changed=true;}
   if(mutation=="unsigned_count"&&op==RO.Ble_S){op=RO.Ble_Un_S;changed=true;}
   if(mutation=="missing_remove"&&a is MethodReference mr0&&mr0.Name=="Remove"){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;continue;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition p){il.Emit(op,(short)(p.Index+(m.HasThis?1:0)));continue;}
   if(a is MethodReference mr){var mi=T(mr.DeclaringType).GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,mr.Parameters.Select(p=>Bound(p.ParameterType,mr)).ToArray(),null)??throw new Exception("Missing public method "+mr);il.Emit(op,mi);continue;}
   if(a is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}if(a is float fv){il.Emit(op,fv);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation did not apply");return dm;
 }
 record Result(int Cases,List<string> Failures);
 static Result Cases(MethodDefinition m,DynamicMethod dm,List<long[]> rows,bool stop=false){var failures=new List<string>();int count=0,token=m.MetadataToken.ToInt32();void Check(bool pass,string msg){count++;if(!pass)failures.Add(msg);}object? Invoke(params object?[]args)=>dm.Invoke(null,args);
  void Throws(Type kind,params object?[]args){bool got=false;try{Invoke(args);}catch(TargetInvocationException e)when(e.InnerException?.GetType()==kind){got=true;}Check(got,"exception:"+kind.Name);}
  int ix=0;foreach(var r in rows){bool match=false;try{
   if(token==0x06000264){var p=new Project{value=(int)r[1],marker=123};var other=new Project{value=7,marker=456};var l=new List<Project>{other};if(r[2]!=0)l.Insert(0,p);var h=new SunManager{sunPoint=(int)r[0],suns=l};var e=l.GetEnumerator();Invoke(h,p);bool versionOK;if(r[2]!=0){try{e.MoveNext();versionOK=false;}catch(InvalidOperationException){versionOK=true;}}else{e.MoveNext();versionOK=true;}match=h.sunPoint==(int)r[5]&&l.Count==1&&ReferenceEquals(l[0],other)&&ReferenceEquals(h.suns,l)&&p.value==(int)r[1]&&p.marker==123&&other.marker==456&&r[3]==1&&r[4]==r[0]&&r[6]==1&&r[7]==1&&versionOK;}
   else if(token==0x06000890){string? key=r[0]==0?null:r[0]==1?string.Empty:new string('x',1);uint bits=(uint)r[1];float rate=BitConverter.Int32BitsToSingle(unchecked((int)bits));var dict=new Dictionary<string,float>{{"sentinel",1}};var h=new SwfManager{_groupRateScales=dict};Invoke(r[0]==2?h:null,key,rate);match=r[2]==0?dict.Count==1:dict.Count==2&&dict.TryGetValue(key!,out float actual)&&unchecked((uint)BitConverter.SingleToInt32Bits(actual))==(uint)r[3];match&=r[4]==1&&r[5]==1&&dict["sentinel"]==1&&ReferenceEquals(h._groupRateScales,dict);}
   else{NodeAstar?[]objects={null,new(){marker=1},new(){marker=2},new(){marker=3},new(){marker=4}};var l=r.Skip(5).Take((int)r[1]).Select(id=>objects[(int)id]!).ToList();var before=l.ToArray();var result=Invoke(r[0]!=0?l:null,(int)r[2],(int)r[3],(int)r[4]);match=ReferenceEquals(result,objects[(int)r[^1]])&&l.SequenceEqual(before)&&objects.Skip(1).Select(x=>x!.marker).SequenceEqual(new[]{1,2,3,4});}
  }catch(TargetInvocationException e)when(e.InnerException is not InvalidProgramException){match=false;}Check(match,"row:"+ix++);if(stop&&failures.Count>0)return new(count,failures);}
  if(token==0x06000264){Throws(typeof(NullReferenceException),null,new Project());Throws(typeof(NullReferenceException),new SunManager{sunPoint=7},new Project());var h=new SunManager{sunPoint=17,suns=new(){null!,new Project()}};Throws(typeof(NullReferenceException),h,null);Check(h.sunPoint==17&&h.suns.Count==1&&h.suns[0]!=null,"null-removed-before-value-failure");var p=new Project{value=1};h=new(){sunPoint=int.MaxValue,suns=new(){p,p}};Invoke(h,p);Check(h.sunPoint==int.MinValue&&h.suns.Count==1&&ReferenceEquals(h.suns[0],p),"first-duplicate-only-and-wrap");}
  else if(token==0x06000890){foreach(string? key in new string?[]{null,""}){Invoke(null,key,float.NaN);Check(true,"early-empty-no-this");}Throws(typeof(NullReferenceException),null,"x",1f);Throws(typeof(NullReferenceException),new SwfManager(),"x",-1f);var d=new Dictionary<string,float>{{"x",7}};var h=new SwfManager{_groupRateScales=d};foreach(string? key in new string?[]{null,""}){Invoke(h,key,1f);Check(d.Count==1&&d["x"]==7,"empty-preserves-dictionary");}Invoke(h,new string('x',1),-1f);Check(d.Count==1&&BitConverter.SingleToInt32Bits(d["x"])==0,"equal-key-overwrite-negative-clamp");Invoke(h,"x",float.PositiveInfinity);Check(d.Count==1&&d["x"]==float.MaxValue,"infinity-overwrite-max");}
  else{foreach(var(a,b,c)in new[]{(1,1,0),(0,0,0),(-1,0,int.MinValue)})Check(Invoke(null,a,b,c)==null,"signed-early-null");Throws(typeof(NullReferenceException),null,1,0,1);var l=new List<NodeAstar>{new(){marker=1}};foreach(var(a,b,c)in new[]{(1,-1,0),(1,0,-1),(0x40000000,0,2)})Throws(typeof(ArgumentOutOfRangeException),l,a,b,c);Check(Invoke(new List<NodeAstar>(),1,0,1)==null,"empty-upper-bound");}
  return new(count,failures);
 }
 public static int Main(string[] args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).GroupBy(l=>l[0]).ToDictionary(g=>g.Key,g=>g.Select(l=>l.Skip(1).Select(long.Parse).ToArray()).ToList());if(rows.Count!=3)throw new Exception("Expected3");int bad=0,errors=0,total=0;bool detected=true;var positives=new List<object>();var controls=new List<object>();foreach(var(key,rs)in rows){int token=Convert.ToInt32(key,16);var m=(MethodDefinition)a.MainModule.LookupToken(token);var result=Cases(m,Emit(m,"none"),rs);bad+=result.Failures.Count;total+=result.Cases;positives.Add(new{token=key,cases=result.Cases,failures=result.Failures});string[] mutations=token==0x06000264?new[]{"wrong_arithmetic","missing_remove"}:token==0x06000890?new[]{"unordered_clamp","wrong_guard"}:new[]{"wrong_arithmetic","checked_product","unsigned_gate","unsigned_count"};foreach(string mut in(args.Length>3?Array.Empty<string>():new[]{"missing_operation","illegal_stack"}.Concat(mutations))){bool reject=false;string? err=null;try{reject=Cases(m,Emit(m,mut),rs,true).Failures.Count>0;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){reject=true;}catch(InvalidProgramException){reject=true;}catch(Exception e){err=e.ToString();errors++;}detected&=reject&&err==null;controls.Add(new{token=key,mutation=mut,detected=reject,tool_error=err});}}
  bool pass=bad==0&&errors==0&&detected;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=3,positive_cases=total,positive_failures=bad,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Original caller instruction bodies and Find valid-path original List indexer execute unchanged; actual String.IsNullOrEmpty helper unchanged. Collect.Remove and Rate dictionary setter use controlled recording dependencies, not original engine proof. CLR uses actual public List/Dictionary/string APIs, public fixture fields, no visibility bypass; additionally checks order, null/bounds, signed overflow, list contents/enumerator, dictionary overwrite, NaN payloads/negative-zero bits. No original engine/Unity/iOS/device equivalence claim",positives,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
