from pathlib import Path
import subprocess,json,hashlib
w=Path('/workspaces/GodsPVZ-native24-codespace');n=w/'.validation/native28-2026-10-01';out=w/'Recovery/Native28-2026-10-01';repo='lyiming710-cloud/GodsPVZ-iOS';parent='74340d2fd33c5679e722ac747ec254971f50d82c';tag='native28-codespace-2026-10-01'
def run(args,cwd=w):
 r=subprocess.run(args,cwd=cwd,capture_output=True,text=True);assert r.returncode==0,r.stdout+r.stderr;return r.stdout.strip()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
assert run(['git','branch','--show-current'])=='repair/codex-native24-codespace' and run(['git','rev-parse','HEAD'])==parent
main_before=json.loads(run(['gh','api','repos/'+repo+'/git/ref/heads/main']))['object']['sha']
replay=json.loads((out/'validation/ARCHIVE-REPLAY.json').read_text());assert replay['reports']['normal']['gate_pass'] and replay['reports']['normal']['positive_cases']==854
v=out/'validation';(v/'SHA256.json').write_text(json.dumps({p.name:sha(p) for p in sorted(v.iterdir()) if p.name!='SHA256.json'},indent=2))
desc=json.loads((out/'EVIDENCE-ARCHIVE.json').read_text());desc['tag']=tag;(out/'EVIDENCE-ARCHIVE.json').write_text(json.dumps(desc,indent=2))
paths=['Recovery/STATUS.md','Recovery/HANDOFF_CURRENT.md','Recovery/Native28-2026-10-01','scripts/takeover/native28'];run(['git','add','--',*paths]);names=run(['git','diff','--cached','--name-only']).splitlines();assert names and all(any(name==p or name.startswith(p+'/') for p in paths) for name in names)
assert all(not any(x in name.split('/') for x in ['obj','bin','__pycache__']) for name in names);run(['git','diff','--cached','--check'])
for name,h in json.loads((v/'SHA256.json').read_text()).items():assert sha(v/name)==h
run(['git','commit','-m','fix(native28): repair twelve native-reviewed methods and quarantine semantic damage [skip ci]']);head=run(['git','rev-parse','HEAD']);assert run(['git','rev-parse','HEAD^'])==parent;run(['git','push','origin','HEAD:repair/codex-native24-codespace'])
asset=n/desc['file'];assert sha(asset)==desc['sha256'];notes=n/'release-notes.md';notes.write_text('Native28 twelve-method repair checkpoint. No IPA.\n\n30 raw bytes changed, exact non-target bodies and metadata retained; deterministic candidate '+json.loads((n/'QUALIFICATION.json').read_text())['candidate_sha256']+'. 854 actual CLR cases with explicit helper doubles; 28 negative controls, including type-valid wrong comparer receiver; tool-fault controls fail closed. 499 inherited cases continue to pass.\n\nFresh historical IL2CPP conversion and 264-TU Linux Clang syntax check: 6033 -> 6006 diagnostics, all 27 target diagnostics cleared, no new method failures. Type precheck PASS1454 / FAIL843. Still 24 failed TUs. No licensed Unity iOS export, Apple compile/link or device validation.\n\nFive methods with missing indirect event calls and one damaged dialogue dispatch quarantined for reconstruction. Complete native specifications, source, logs, 330 generated files and portable archive fixture replay included.\n\nArchive SHA-256 '+desc['sha256']+'.\nSource: https://github.com/'+repo+'/blob/'+head+'/Recovery/Native28-2026-10-01/README.md\n')
run(['gh','release','create',tag,'--repo',repo,'--target',head,'--title','Native28 native-reviewed batch and semantic counterexample — no IPA','--notes-file',str(notes),'--draft','--prerelease']);run(['gh','release','upload',tag,str(asset),'--repo',repo])
release=json.loads(run(['gh','release','view',tag,'--repo',repo,'--json','assets,isDraft,targetCommitish,url,tagName']));assert release['isDraft'] and release['targetCommitish']==head;row=next(x for x in release['assets'] if x['name']==desc['file']);assert row['size']==desc['bytes'] and row['digest']=='sha256:'+desc['sha256']
download=n/'provider-readback';download.mkdir(exist_ok=True);run(['gh','release','download',tag,'--repo',repo,'--pattern',desc['file'],'--dir',str(download)]);assert sha(download/desc['file'])==desc['sha256'];run(['gh','release','edit',tag,'--repo',repo,'--draft=false'])
result={'head':head,'parent':parent,'changed_paths':len(names),'main_before':main_before,'archive':desc,'provider_digest_verified':True,'provider_download_sha256_verified':True,'source_url':'https://github.com/'+repo+'/blob/'+head+'/Recovery/Native28-2026-10-01/README.md','release_url':'https://github.com/'+repo+'/releases/tag/'+tag};(n/'PUBLICATION-RESULT.json').write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
