using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}public class BoundsException:Exception{}
public class Obj{}public class Card:Obj{}public class Camera:Obj{}public class Clip:Obj{}public class Audio:Obj{}public class Game:Obj{}public class Transform:Obj{}public class Renderer:Obj{}public class GameList:Obj{}public class ClipList:Obj{}public class Plant:Obj{}public class Animator:Obj{}
public class Banks:Obj{public Game?cardList_Gameobject;}public class Device:Obj{public Game?shadow;public float fX,fY;}public class Project:Obj{public float flickeringTime;public int movementTracks;public GameList?animationSprites;}
public class Projectile:Obj{public float fX,fY,fZ,fZ_shadow,fW,fD,zSpeed,zAcceleration;public Vector3 speed,targetPosition;public Game?shadow,track,projectileSprite;}
public class Zombie:Obj{public Plant?targetPlant;public Animator?animator;public bool isEat;}public class Popup:Obj{public int P;}public class Prepare:Obj{}public static class Resource{public static ClipList?buttonClips,zombieClips;}
public static class State{
public static Obj self=new();public static Card card=new(),cardB=new();public static Camera camera=new();public static Clip clip=new(),clipB=new();public static Game game=new(),gameB=new(),track=new(),trackB=new(),sprite=new(),spriteB=new();public static Transform transform=new(),transformB=new(),transformC=new(),transformD=new();public static Renderer renderer=new();public static GameList listG=new(),listGB=new();public static ClipList listC=new(),listCB=new();public static Audio audio=new();public static Plant plant=new(),plantB=new();public static Animator animator=new(),animatorB=new();
public static int token,mode,hook,itemCalls,truthCalls,positionCalls,randomCalls,audioCalls,parentCalls;public static ulong trace;public static bool argsOK;public static Vector3 value,alternate,spare,output,scale;public static Color color;public static uint scalar,ra,rb,capturedVolume,eulerX,eulerY;public static Clip?audioClip;public static Transform?parentValue;public static Game?cardGame;
public static int Id(object?o){object?[]all={null,self,card,cardB,camera,clip,clipB,game,gameB,track,trackB,sprite,spriteB,transform,transformB,transformC,transformD,renderer,listG,listGB,listC,listCB,audio,plant,plantB,animator,animatorB};for(int i=0;i<all.Length;i++)if(ReferenceEquals(o,all[i]))return i;throw new Exception("Unknown identity");}
public static void Ev(int e,object?r=null)=>trace=unchecked(trace*131+(uint)(e*32+Id(r)));public static void Check(object?r){if(r==null)throw new NullReferenceException();}public static void Fail(){Ev(32);throw new DependencyException();}
public static Camera?MainCamera(){Ev(1);return mode==10?null:camera;}
public static Transform?ComponentTransform(Obj?r){Check(r);Ev(2,r);if(self is Banks b){if(hook==1)b.cardList_Gameobject=gameB;if(hook==2)b.cardList_Gameobject=null;}if(mode==4)return null;return ReferenceEquals(r,card)?transformC:ReferenceEquals(r,cardB)?transformD:token==0x06000331&&ReferenceEquals(r,self)?transformB:transform;}
public static Transform?GameTransform(Game?r){Check(r);Ev(3,r);if(token==0x06000331||token==0x060003D4){if(hook==1)SetShadow(gameB);if(hook==2)SetShadow(null);}if(token==0x060003D7){if(hook==5)((Projectile)self).projectileSprite=spriteB;if(hook==6)((Projectile)self).track=null;}if(mode==3)return null;return ReferenceEquals(r,gameB)||ReferenceEquals(r,spriteB)?transformB:ReferenceEquals(r,track)?transformC:ReferenceEquals(r,trackB)?transformD:transform;}
static void SetShadow(Game?g){if(self is Device d)d.shadow=g;else((Projectile)self).shadow=g;}
public static Game?ComponentGame(Obj?r){Check(r);Ev(4,r);return mode==15?null:cardGame;}
public static Vector3 Position(Transform?r){Check(r);Ev(5,r);if(mode==5)Fail();positionCalls++;var v=ReferenceEquals(r,transformB)||ReferenceEquals(r,transformD)?alternate:value;if(token==0x06000331||token==0x060003D4){if(hook==7)SetShadow(gameB);if(hook==8)SetShadow(null);}if(hook==11)value=spare;return v;}
public static void SetPosition(Transform?r,Vector3 v){Check(r);Ev(6,r);output=v;if(mode==6)Fail();}public static void SetLocalPosition(Transform?r,Vector3 v){Check(r);Ev(7,r);output=v;if(mode==6)Fail();}
public static void SetScale(Transform?r,Vector3 v){Check(r);Ev(8,r);scale=v;if(token==0x060003D4){if(hook==9)SetShadow(gameB);if(hook==10)SetShadow(null);}if(mode==6)Fail();}
public static void SetParent(Transform?r,Transform?p,bool world){Check(r);Ev(9,r);argsOK&=!world;parentValue=p;parentCalls++;if(hook==3)cardGame=gameB;if(mode==6)Fail();}
public static bool Implicit(Obj?r){Ev(10,r);truthCalls++;if(token==0x060003D7){var p=(Projectile)self;if(truthCalls==1){if(hook==1)p.track=trackB;if(hook==2)p.track=null;}else{if(hook==3)p.projectileSprite=spriteB;if(hook==4)p.projectileSprite=null;}}if(token==0x06000482){var z=(Zombie)self;if(hook==1)z.targetPlant=plantB;if(hook==2)z.targetPlant=null;}if(token==0x0600067C){if(hook==1)Resource.buttonClips=listCB;if(hook==2)Resource.buttonClips=null;}if(mode==21)Fail();return r!=null&&mode!=7;}
public static bool Inequality(Obj?r,Obj?other){argsOK&=other==null;return Implicit(r);}
public static float Range(float a,float b){Ev(11);argsOK&=randomCalls==0?Fixture.B(a)==Fixture.B(-540f)&&Fixture.B(b)==Fixture.B(400f):Fixture.B(a)==Fixture.B(330f)&&Fixture.B(b)==Fixture.B(360f);uint v=randomCalls++==0?ra:rb;if(hook==1)((Project)self).movementTracks=7;if(mode==22)Fail();return Fixture.F(v);}
public static float Ortho(Camera?r){Check(r);Ev(12,r);if(mode==11)Fail();return Fixture.F(scalar);}
public static float Delta(){Ev(13);if(hook==1)((Project)self).flickeringTime=Fixture.F(Fixture.B(alternate.x));if(mode==23)Fail();return Fixture.F(scalar);}
static void Item(Obj?r,int index){Check(r);Ev(14,r);itemCalls++;argsOK&=index==(token==0x0600066E?9:0);if(mode==14){Ev(31);throw new BoundsException();}}
public static Game?GameItem(GameList?r,int index){Item(r,index);if(token==0x060003C7&&hook==3)((Project)self).flickeringTime=alternate.x;return mode==17?null:ReferenceEquals(r,listGB)?gameB:game;}
public static Clip?ClipItem(ClipList?r,int index){Item(r,index);return mode==18?null:ReferenceEquals(r,listCB)?clipB:clip;}
public static Renderer?GetRenderer(Game?r){Check(r);Ev(15,r);if(token==0x060003C7&&hook==4)((Project)self).flickeringTime=alternate.y;return mode==13?null:renderer;}
public static void SetColor(Renderer?r,Color c){Check(r);Ev(16,r);color=c;if(mode==6)Fail();}
public static float Volume(){Ev(17);if(hook==5)value=alternate;if(mode==12)Fail();return Fixture.F(scalar);}
public static void PlayClip(Clip?c,Vector3 v,float vol){Ev(18,c);audioCalls++;audioClip=c;output=v;capturedVolume=Fixture.B(vol);if(mode==16)Fail();}
public static Audio?CreateSingle(Clip?c){Ev(19,c);audioCalls++;audioClip=c;if(mode==16)Fail();return mode==24?null:audio;}
public static bool OutOfMap(Projectile?r){Check(r);Ev(20,r);if(hook==1)r!.fZ=alternate.z;if(mode==25)Fail();return mode!=26;}
public static void SetEuler(Projectile?r,float a,float b){Check(r);Ev(21,r);eulerX=Fixture.B(a);eulerY=Fixture.B(b);argsOK&=eulerX==0&&eulerY==Fixture.B(-90f);if(hook==2)r!.targetPosition=alternate;if(mode==27)Fail();}
public static void Block(Plant?r,Zombie?z,bool attack){Check(r);Ev(22,r);argsOK&=ReferenceEquals(z,self)&&!attack;if(hook==3)((Zombie)self).animator=animatorB;if(hook==4)((Zombie)self).animator=null;if(mode==28)Fail();}
public static void SetBool(Animator?r,string s,bool b){Check(r);Ev(23,r);argsOK&=s=="isAttacking"&&!b;if(mode==29)Fail();}
public static Vector3 MoveDirection(Zombie?r){Check(r);Ev(24,r);var v=value;if(hook==6)value=alternate;if(mode==30)Fail();return v;}
public static void SetSpeed(Zombie?r,Vector3 v){Check(r);Ev(25,r);output=v;if(mode==31)Fail();}
public static void ResetSpeed(Zombie?r){Check(r);Ev(26,r);r!.isEat=true;if(hook==7)Fail();}
}
public static class Fixture{
static Type T(TypeReference r)=>r.FullName switch{"System.Void"=>typeof(void),"System.Object"=>typeof(object),"System.String"=>typeof(string),"System.Boolean"=>typeof(bool),"System.Int32"=>typeof(int),"System.Single"=>typeof(float),"System.IntPtr"=>typeof(IntPtr),"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Color"=>typeof(Color),"UnityEngine.Transform"=>typeof(Transform),"UnityEngine.GameObject"=>typeof(Game),"UnityEngine.Camera"=>typeof(Camera),"UnityEngine.AudioClip"=>typeof(Clip),"UnityEngine.AudioSource"=>typeof(Audio),"UnityEngine.SpriteRenderer"=>typeof(Renderer),"UnityEngine.Animator"=>typeof(Animator),"UnityEngine.Object" or "UnityEngine.Component"=>typeof(Obj),"System.Collections.Generic.List`1<UnityEngine.GameObject>"=>typeof(GameList),"System.Collections.Generic.List`1<UnityEngine.AudioClip>"=>typeof(ClipList),"Card"=>typeof(Card),"Banks"=>typeof(Banks),"Device"=>typeof(Device),"Project"=>typeof(Project),"Projectile"=>typeof(Projectile),"Zombie"=>typeof(Zombie),"Plant"=>typeof(Plant),"ResourceManager"=>typeof(Resource),"Popup"=>typeof(Popup),"PrepareUIController"=>typeof(Prepare),_=>throw new Exception("Unmapped type "+r)};
static Delegate Emit(MethodDefinition m,string mutation){int rid=(int)m.MetadataToken.RID;var pars=new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();var dm=new DynamicMethod(m.FullName+mutation,typeof(void),pars,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var cachedGame=il.DeclareLocal(typeof(Game));var cachedClip=il.DeclareLocal(typeof(Clip));var dt=il.DeclareLocal(typeof(float));var volume=il.DeclareLocal(typeof(float));int shadowReads=0,itemCalls=0;
if(mutation=="illegal_stack"&&rid==0xEC)il.Emit(RO.Pop);
foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];
if(i.Operand is FieldReference f){if(mutation=="shadow_cache"&&rid==0x3D4&&f.Name=="shadow"){shadowReads++;if(shadowReads>1){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cachedGame);continue;}}if(mutation=="track_wrong_source"&&rid==0x3D7&&f.Name=="projectileSprite")f=new FieldReference("track",f.FieldType,f.DeclaringType);if(mutation=="shadow_wrong_y"&&rid==0x3D4&&f.Name=="fZ_shadow")f=new FieldReference("fY",f.FieldType,f.DeclaringType);il.Emit(op,T(f.DeclaringType).GetField(f.Name)??throw new Exception("Field missing "+f));if(mutation=="shadow_cache"&&rid==0x3D4&&f.Name=="shadow"&&shadowReads==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cachedGame);}continue;}
if(i.Operand is MethodReference r){if(r.DeclaringType.FullName=="UnityEngine.Vector3"&&r.Name=="get_zero"){il.Emit(op,typeof(Vector3).GetProperty("zero")!.GetMethod!);continue;}if(r.Name is "op_Subtraction" or "op_Addition"&&r.DeclaringType.FullName=="UnityEngine.Vector3"){il.Emit(op,typeof(Vector3).GetMethod(mutation=="device_wrong_delta"?"op_Addition":r.Name,new[]{typeof(Vector3),typeof(Vector3)})!);continue;}if(r.Name=="Abs"&&r.DeclaringType.FullName=="UnityEngine.Mathf"){il.Emit(op,typeof(Mathf).GetMethod("Abs",new[]{typeof(float)})!);continue;}if(r.Name==".ctor"&&r.DeclaringType.FullName is "UnityEngine.Vector3" or "UnityEngine.Color"){il.Emit(op,T(r.DeclaringType).GetConstructor(r.Parameters.Select(p=>T(p.ParameterType)).ToArray())!);continue;}
string name=r.Name switch{"get_main"=>nameof(State.MainCamera),"get_transform" when r.DeclaringType.FullName=="UnityEngine.GameObject"=>nameof(State.GameTransform),"get_transform"=>nameof(State.ComponentTransform),"get_gameObject"=>nameof(State.ComponentGame),"get_position" or "get_localPosition"=>nameof(State.Position),"set_position"=>nameof(State.SetPosition),"set_localPosition"=>nameof(State.SetLocalPosition),"set_localScale"=>nameof(State.SetScale),"SetParent"=>nameof(State.SetParent),"op_Implicit"=>nameof(State.Implicit),"op_Inequality"=>nameof(State.Inequality),"Range"=>nameof(State.Range),"get_orthographicSize"=>nameof(State.Ortho),"get_deltaTime"=>nameof(State.Delta),"get_Item" when r.DeclaringType.FullName.Contains("AudioClip")=>nameof(State.ClipItem),"get_Item"=>nameof(State.GameItem),"GetComponent"=>nameof(State.GetRenderer),"set_color"=>nameof(State.SetColor),"AudioVolume"=>nameof(State.Volume),"PlayClipAtPoint"=>nameof(State.PlayClip),"CreateAudioAtPoint"=>nameof(State.CreateSingle),"TestOutofMap"=>nameof(State.OutOfMap),"SetEulerAngles"=>nameof(State.SetEuler),"BlockZombie"=>nameof(State.Block),"SetBool"=>nameof(State.SetBool),"GetMoveDirection"=>nameof(State.MoveDirection),"SetrSpeed"=>nameof(State.SetSpeed),"ResetMoveSpeed"=>nameof(State.ResetSpeed),_=>throw new Exception("Unmapped call "+r)};
if(mutation=="zombie_skip_reset"&&rid==0x482&&r.Name=="ResetMoveSpeed"){il.Emit(RO.Pop);continue;}
if(mutation=="bleep_cache_clip"&&rid==0x67C&&r.Name=="get_Item"){itemCalls++;if(itemCalls==2){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldloc,cachedClip);continue;}}
if(mutation=="bleep_zero_position"&&rid==0x67C&&r.Name=="PlayClipAtPoint"){il.Emit(RO.Stloc,volume);il.Emit(RO.Pop);il.Emit(RO.Call,typeof(Vector3).GetProperty("zero")!.GetMethod!);il.Emit(RO.Ldloc,volume);}
il.Emit(RO.Call,typeof(State).GetMethod(name)!);
if(mutation=="bleep_cache_clip"&&rid==0x67C&&r.Name=="get_Item"&&itemCalls==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cachedClip);}
if(mutation=="flicker_after_delta"&&rid==0x3C7&&r.Name=="get_deltaTime"){il.Emit(RO.Stloc,dt);il.Emit(RO.Pop);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(Project).GetField("flickeringTime")!);il.Emit(RO.Ldloc,dt);}continue;}
if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="missile_unordered"&&rid==0x3FB&&op.Value==RO.Bge_S.Value)op=RO.Bge_Un_S;il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(i.Operand is string str){il.Emit(op,str);continue;}if(i.Operand is float fv){if(mutation=="bank_wrong_x"&&rid==0xEC&&fv==92)fv=93;if(mutation=="flicker_wrong_gain"&&rid==0x3C7&&fv==0.6863f)fv=0.5f;if(mutation=="sun_wrong_z"&&rid==0x3CB&&fv==0&&i.Next.OpCode.Name=="mul")fv=1;if(mutation=="shadow_wrong_scale"&&rid==0x3D4&&fv==1.425f)fv=1;il.Emit(op,fv);continue;}if(i.Operand is sbyte sb){if(mutation=="popup_wrong_index"&&rid==0x66E&&sb==9)sb=8;il.Emit(op,sb);continue;}if(i.Operand!=null)throw new Exception("Unsupported operand "+i);il.Emit(op);
}return dm.CreateDelegate(System.Linq.Expressions.Expression.GetDelegateType(pars.Concat(new[]{typeof(void)}).ToArray()));}
public static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));public static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static int I(ulong v)=>unchecked((int)v);static Vector3 Vec(ulong[]r,int i)=>new(F(r[i]),F(r[i+1]),F(r[i+2]));static void Add(List<ulong>x,Vector3 v){x.Add(B(v.x));x.Add(B(v.y));x.Add(B(v.z));}
static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>functions,List<ulong[]>rows,bool stop=false){int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int t=(int)r[0];State.token=t;State.mode=(int)r[1];State.hook=(int)r[2];State.self=t switch{0x060000EC=>new Banks{cardList_Gameobject=State.mode==2?null:State.game},0x06000331=>new Device{shadow=State.mode==1?null:State.game,fX=F(0x12345678),fY=F(0x87654321)},0x060003C7=>new Project{flickeringTime=F(r[4]),animationSprites=State.mode==9?null:State.listG},0x060003CB=>new Project{movementTracks=I(r[3])},0x060003D4=>new Projectile{shadow=State.mode==1?null:State.game,fW=F(r[14]),fD=F(r[15]),fZ_shadow=F(r[16])},0x060003D7=>new Projectile{track=State.mode==1?null:State.track,projectileSprite=State.mode==2?null:State.sprite},0x060003FB=>new Projectile{fX=F(0x12345678),fY=F(0x87654321),fZ=F(r[4]),speed=Vec(r,8),zSpeed=F(0x11111111),zAcceleration=F(0x22222222),targetPosition=Vec(r,11)},0x06000482=>new Zombie{targetPlant=State.mode==19?null:State.plant,animator=State.mode==20?null:State.animator,isEat=true},0x0600066E=>new Popup{P=I(r[3])},0x0600067C=>new Prepare(),_=>throw new Exception("Token")};State.value=Vec(r,5);State.alternate=Vec(r,8);State.spare=Vec(r,11);State.scalar=(uint)r[17];State.ra=(uint)r[18];State.rb=(uint)r[19];State.trace=0;State.itemCalls=State.truthCalls=State.positionCalls=State.randomCalls=State.audioCalls=State.parentCalls=0;State.argsOK=true;State.output=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));State.scale=State.output;State.color=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));State.audioClip=null;State.parentValue=null;State.capturedVolume=State.eulerX=State.eulerY=0xdeadbeef;State.cardGame=State.game;Resource.buttonClips=Resource.zombieClips=State.mode==9?null:State.listC;int err=0;
try{if(t==0x060000EC)functions[t].DynamicInvoke(State.self,State.mode==1?null:State.card,I(r[3]));else if(t==0x06000331)functions[t].DynamicInvoke(State.self,State.spare);else functions[t].DynamicInvoke(State.self);}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(30);err=1;}catch(TargetInvocationException e)when(e.InnerException is BoundsException){err=2;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){err=3;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
var observed=new List<ulong>{State.trace,(uint)err,State.argsOK?1UL:0UL};Add(observed,State.output);Add(observed,State.scale);observed.AddRange(new ulong[]{B(State.color.r),B(State.color.g),B(State.color.b),B(State.color.a)});float fx=State.self is Device d?d.fX:t==0x060003FB?((Projectile)State.self).fX:0,fy=State.self is Device d2?d2.fY:t==0x060003FB?((Projectile)State.self).fY:0;observed.Add(B(fx));observed.Add(B(fy));observed.Add(t==0x060003FB?B(((Projectile)State.self).fZ):0);Add(observed,t==0x060003FB?((Projectile)State.self).speed:new Vector3());observed.Add(t==0x060003FB?B(((Projectile)State.self).zSpeed):0);observed.Add(t==0x060003FB?B(((Projectile)State.self).zAcceleration):0);observed.Add(t==0x060003C7?B(((Project)State.self).flickeringTime):0);observed.Add(t==0x06000482&&((Zombie)State.self).isEat?1UL:0);
object?child=t switch{0x060000EC=>((Banks)State.self).cardList_Gameobject,0x06000331=>((Device)State.self).shadow,0x060003D4=>((Projectile)State.self).shadow,0x060003D7=>((Projectile)State.self).track,0x06000482=>((Zombie)State.self).targetPlant,_=>null};object?other=t switch{0x060003D7=>((Projectile)State.self).projectileSprite,0x06000482=>((Zombie)State.self).animator,_=>null};observed.Add((uint)State.Id(child));observed.Add((uint)State.Id(other));observed.Add((uint)State.Id(t==0x0600067C?Resource.buttonClips:t==0x0600066E?Resource.zombieClips:null));observed.Add((uint)State.Id(t==0x060003C7?((Project)State.self).animationSprites:null));observed.Add((uint)State.Id(State.audioClip));observed.Add(State.capturedVolume);observed.Add((uint)State.audioCalls);observed.Add((uint)State.Id(State.parentValue));observed.Add((uint)State.parentCalls);observed.Add(0);observed.Add(State.eulerX);observed.Add(State.eulerY);observed.Add((uint)State.Id(t==0x060000EC?State.cardGame:null));if(observed.Count!=36)throw new Exception("Observation schema "+observed.Count);
var bad=observed.Select((v,i)=>(v,i)).Where(x=>x.v!=r[x.i+20]).ToArray();count++;if(bad.Length>0){fail++;if(samples.Count<10)samples.Add(t.ToString("X8")+" case="+count+" mode="+State.mode+" hook="+State.hook+" diffs="+string.Join(',',bad.Select(x=>(x.i+20)+":"+x.v+"/"+r[x.i+20])));if(stop)return(count,fail,samples);}}
return(count,fail,samples);}
public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x060000EC,0x06000331,0x060003C7,0x060003CB,0x060003D4,0x060003D7,0x060003FB,0x06000482,0x0600066E,0x0600067C};var ms=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=40960||rows.Any(r=>r.Length!=56)||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","bank_wrong_x","device_wrong_delta","flicker_wrong_gain","flicker_after_delta","sun_wrong_z","shadow_wrong_y","shadow_cache","shadow_wrong_scale","track_wrong_source","missile_unordered","zombie_skip_reset","popup_wrong_index","bleep_cache_clip","bleep_zero_position"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=10,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Ten actual candidate CIL callers compared with unchanged original PC native callers and explicit recording Unity/list/random/time/audio/exception dependencies. Actual pinned Core Vector3/Color constructors, Vector3 subtraction/get_zero and Mathf.Abs CLR code; original native zero initializer/accessor executed unchanged. Field/callback/null/argument and IEEE bits tested; no full Unity engine/class-init timing/game/iOS fidelity proof. Full conversion/all TU checks deferred to 100 accumulated methods."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures,report.controls}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
