using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher58{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int t){O(op);b.AddRange(BitConverter.GetBytes(t));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public void L(byte n)=>O(0x11,n);public void S(byte n)=>O(0x13,n);public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="6e2aa50c2127dc07e4d7f20bcb40faf28c1958db0d843a20ac9db0f17fd8ea12","Pinned Native57");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x0600017B,0x06000477,0x06000837,0x06000838}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>a.MainModule.GetTypes().Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);MethodReference exact(string name)=>a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName==name);FieldReference vf(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(r=>r.FullName=="System.Single UnityEngine.Vector3::"+name);
void Load(string owner,string name){il.O(2);il.Ref(0x7b,field(owner,name));}void StoreFloat(string owner,string name,float value){il.O(2);il.F(value);il.Ref(0x7d,field(owner,name));}void V3()=>il.Ref(0x73,exact("System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)"));void GetShadow(string owner){Load(owner,"shadow");il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));}void VecPart(byte local,string part){il.L(local);il.Ref(0x7b,vf(part));}void String(string value){var i=m.Body.Instructions.First(i=>i.OpCode.Name=="ldstr"&&i.Operand is string s&&s==value);il.Token(0x72,BitConverter.ToInt32(b,Off(pe,m.RVA)+12+i.Offset+1));}
int sig=m.Body.LocalVarToken.ToInt32(),max=3;
switch(token){
case 0x0600017B:{max=3;Load("DebugManager","DPSText");il.O(2);il.Ref(0x7c,field("DebugManager","dPS"));String("DPS:0.0");il.Ref(0x28,call("ToString"));il.Ref(0x6f,call("set_text"));StoreFloat("DebugManager","dPS",0);il.O(0x2a);break;}
case 0x06000477:{max=4;Load("Zombie","sortingGroup");il.O(0x14);il.Ref(0x28,call("op_Equality"));il.Br(0x2c,"set");il.O(2,2);il.Ref(0x28,call("get_gameObject"));il.Ref(0x6f,call("AddComponent"));il.Ref(0x7d,field("Zombie","sortingGroup"));il.Label("set");Load("Zombie","sortingGroup");String("Entity");il.Ref(0x6f,call("set_sortingLayerName"));Load("Zombie","sortingGroup");Load("Zombie","fY");il.F(-10);il.O(0x5a,0x25);il.F(2147483648f);il.Br(0x34,"min");il.O(0x25);il.F(-2147483648f);il.Br(0x32,"min");il.O(0x69);il.Br(0x2b,"apply");il.Label("min");il.O(0x26,0x20);il.b.AddRange(BitConverter.GetBytes(int.MinValue));il.Label("apply");il.Ref(0x6f,call("set_sortingOrder"));il.O(0x2a);break;}
case 0x06000837:{max=2;il.O(2);il.Ref(0x28,call("GetCurrentBakedFrame"));il.O(0x25);il.Br(0x2c,"zero");il.Ref(0x6f,call("get_CachedMesh"));il.Ref(0x6f,call("get_bounds"));il.O(0x2a);il.Label("zero");il.O(0x26,0x12,1,0xfe,0x15);il.b.AddRange(BitConverter.GetBytes(m.ReturnType.MetadataToken.ToInt32()));il.O(0x07,0x2a);break;}
case 0x06000838:{max=1;il.O(2);il.Ref(0x28,call("Internal_UpdateMesh"));Load("FTRuntime.SwfClip","_meshRenderer");il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"zero");Load("FTRuntime.SwfClip","_meshRenderer");il.Ref(0x6f,call("get_bounds"));il.O(0x2a);il.Label("zero");il.O(0x12,1,0xfe,0x15);il.b.AddRange(BitConverter.GetBytes(m.ReturnType.MetadataToken.ToInt32()));il.O(0x07,0x2a);break;}
}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot "+m.FullName+" "+code.Length+"/"+m.Body.CodeSize);int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
