using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}
public class Game{}
public class Transform{}
public class Zombie{public Vector3 previousPosition;public int armor1Type;public List<Game?>?animationSprites,anim_Armor2Sprites;}
public class Enemy{public int row;}
public class Preview{}
public static class State{
public static Zombie zombie=new();public static Enemy enemy=new();public static Game game=new();public static Transform transform=new();public static List<Game?>list=new(),listB=new();public static int token,mode,hook,armor,newrow,steps,ranges,times;public static ulong trace;public static bool argsOK;public static Vector3 value;public static float dt1,dt2,random1,random2,newprevious;public static readonly string[]names={"","anim_cone","anim_bucket","anim_brick","IceCube1","LadderSaboteurs_helmet1"};public static void Ev(int n)=>trace=unchecked(trace*16+(uint)n);
public static Transform?GetZombieTransform(Zombie?r){Ev(1);argsOK&=ReferenceEquals(r,zombie);if(mode==5)throw new DependencyException();if(hook==1)zombie.previousPosition.x=newprevious;return mode is 1 or 4?null:transform;}
public static Transform?GetGameTransform(Game?r){if(r==null)throw new NullReferenceException();Ev(1);argsOK&=ReferenceEquals(r,game);if(mode==5)throw new DependencyException();if(hook==1)zombie.previousPosition.x=newprevious;return mode is 1 or 4?null:transform;}
public static Vector3 Position(Transform?r){if(r==null)throw new NullReferenceException();Ev(2);argsOK&=ReferenceEquals(r,transform);if(hook==2)zombie.previousPosition.x=newprevious;if(mode==6)throw new DependencyException();return value;}
public static float Delta(){Ev(3);times++;if(hook==3)zombie.previousPosition.x=newprevious;if(mode==7)throw new DependencyException();return times==1?dt1:dt2;}
public static Game?Item(List<Game?>?l,int i){if(l==null)throw new NullReferenceException();Ev(4);steps++;argsOK&=ReferenceEquals(l,list)&&i==0;if(mode==7)throw new DependencyException();if(hook==1)zombie.anim_Armor2Sprites=listB;return l[i];}
public static Vector3 Sprite(List<Game?>?l,string name){Ev(5);int expected=armor==1?1:armor is 2 or 5?2:armor==3?3:armor==4?4:armor==6?5:0;argsOK&=ReferenceEquals(l,mode==1?null:list)&&name==names[expected];if(hook==1)zombie.armor1Type=6;if(hook==2)zombie.animationSprites=listB;if(mode==2)throw new DependencyException();return value;}
public static float Range(float min,float max){Ev(6);ranges++;argsOK&=Fixture.B(min)==Fixture.B(ranges==1?680f:-20f)&&Fixture.B(max)==Fixture.B(ranges==1?980f:100f);if(ranges==1&&hook==1)enemy.row=newrow;if(ranges==2&&hook==2)enemy.row=newrow;if(mode==2||(mode==3&&ranges==2))throw new DependencyException();return ranges==1?random1:random2;}
}
public static class Fixture{
static Type T(TypeReference r)=>r.FullName switch{"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Sprite"=>typeof(Sprite),"UnityEngine.Transform"=>typeof(Transform),"UnityEngine.GameObject"=>typeof(Game),"System.Collections.Generic.List`1<UnityEngine.GameObject>"=>typeof(List<Game>),"System.Object"=>typeof(object),"System.Boolean"=>typeof(bool),"System.Int32" or "Armor1Type"=>typeof(int),"System.Single"=>typeof(float),"System.String"=>typeof(string),"System.IntPtr"=>typeof(IntPtr),"System.NullReferenceException"=>typeof(NullReferenceException),"Zombie"=>typeof(Zombie),"Enemy"=>typeof(Enemy),"BoardPreview"=>typeof(Preview),_=>throw new Exception("Unmapped "+r)};
static FieldInfo Field(FieldReference r)=>r.DeclaringType.FullName=="System.String"?typeof(string).GetField("Empty")!:T(r.DeclaringType).GetField(r.Name)!;
static Delegate Emit(MethodDefinition m,string mutation){int rid=(int)m.MetadataToken.RID;var pars=new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();var ret=T(m.ReturnType);var dm=new DynamicMethod(m.FullName+mutation,ret,pars,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var dtCache=il.DeclareLocal(typeof(float));int delta=0;bool applied=mutation=="none";
if(mutation=="illegal_stack"&&rid==0x43D){il.Emit(RO.Pop);applied=true;}
foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];if(i.Operand is FieldReference f){if(mutation=="wrong_previous_axis"&&rid==0x43D&&f.Name=="x"&&i.Previous?.OpCode.Name=="ldflda"){il.Emit(op,typeof(Vector3).GetField("y")!);applied=true;}else il.Emit(op,Field(f));continue;}
if(i.Operand is MethodReference r){string name=r.Name switch{"get_transform" when r.DeclaringType.FullName=="UnityEngine.Component"=>nameof(State.GetZombieTransform),"get_transform"=>nameof(State.GetGameTransform),"get_position"=>nameof(State.Position),"get_deltaTime"=>nameof(State.Delta),"get_Item"=>nameof(State.Item),"GetAnimationSpritePosition"=>nameof(State.Sprite),"Range"=>nameof(State.Range),_=>throw new Exception("Unmapped "+r)};if(r.Name=="get_deltaTime"){delta++;if(mutation=="cache_delta"&&delta==2){il.Emit(RO.Ldloc,dtCache);applied=true;continue;}il.Emit(RO.Call,typeof(State).GetMethod(name)!);if(delta==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,dtCache);}continue;}il.Emit(RO.Call,typeof(State).GetMethod(name)!);if(mutation=="zero_position"&&rid==0x43F&&r.Name=="get_position"){il.Emit(RO.Pop);var v=il.DeclareLocal(typeof(Vector3));il.Emit(RO.Ldloca,v);il.Emit(RO.Initobj,typeof(Vector3));il.Emit(RO.Ldloc,v);applied=true;}continue;}
if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="flip_zero"&&rid==0x43D){op=RO.Brfalse_S;applied=true;}if(mutation=="helmet_map"&&rid==0x43E&&i.Previous?.OpCode.Name=="ldc.i4.5"){var target=m.Body.Instructions.First(x=>x.OpCode.Name=="ldstr"&&(string)x.Operand=="LadderSaboteurs_helmet1");il.Emit(op,labels[target]);applied=true;continue;}il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition vdef){il.Emit(op,locals[vdef.Index]);continue;}if(i.Operand is TypeReference tr){il.Emit(op,T(tr));continue;}if(i.Operand is string str){if(mutation=="cone_map"&&str=="anim_cone"){str="anim_bucket";applied=true;}il.Emit(op,str);continue;}if(i.Operand is float fval){if(mutation=="preview_row_factor"&&rid==0x5D9&&fval==134f){fval=135f;applied=true;}if(mutation=="preview_range"&&rid==0x5D9&&fval==680f){fval=681f;applied=true;}il.Emit(op,fval);continue;}if(i.Operand!=null)throw new Exception("Unsupported "+i);if(mutation=="preview_subtract"&&rid==0x5D9&&op.Value==RO.Sub.Value){op=RO.Add;applied=true;}il.Emit(op);}
if(!applied&&mutation!="none"&&((rid==0x43D&&mutation is "illegal_stack" or "wrong_previous_axis" or "cache_delta" or "flip_zero")||(rid==0x43E&&mutation is "helmet_map" or "cone_map")||(rid==0x43F&&mutation=="zero_position")||(rid==0x5D9&&mutation is "preview_row_factor" or "preview_range" or "preview_subtract")))throw new Exception("Mutation not applied "+mutation);return dm.CreateDelegate(System.Linq.Expressions.Expression.GetDelegateType(pars.Concat(new[]{ret}).ToArray()));}
static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));public static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static int I(ulong v)=>unchecked((int)v);
static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>functions,List<ulong[]>rows,bool stop=false){int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int token=(int)r[0];State.token=token;State.mode=(int)r[1];State.hook=(int)r[2];State.armor=I(r[3]);State.newrow=I(r[5]);State.value=new(F(r[8]),F(r[9]),F(r[10]));State.dt1=F(r[11]);State.dt2=F(r[12]);State.random1=F(r[13]);State.random2=F(r[14]);State.newprevious=F(r[7]);State.list=State.mode==2?new():new(){State.mode==3?null:State.game};State.listB=new(){State.game};State.zombie=new(){armor1Type=State.armor,previousPosition=new(F(r[6]),F(0x12345678),F(0x87654321)),animationSprites=State.mode==1?null:State.list,anim_Armor2Sprites=State.mode==1?null:State.list};State.enemy=new(){row=I(r[4])};State.trace=0;State.steps=State.ranges=State.times=0;State.argsOK=true;int err=0;Vector3 v=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));uint speed=0xdeadbeef;try{object?result=token==0x060005D9?functions[token].DynamicInvoke(null,State.mode==1?null:State.enemy):functions[token].DynamicInvoke(State.zombie);if(token==0x0600043D)speed=B((float)result!);else v=(Vector3)result!;}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(14);err=1;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){State.Ev(13);err=3;}catch(TargetInvocationException e)when(e.InnerException is ArgumentOutOfRangeException){State.Ev(12);err=4;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
bool outputMatch=token==0x060005D9&&err!=0||B(v.x)==r[17]&&B(v.y)==r[18]&&B(v.z)==r[19];bool ok=State.trace==r[15]&&err==(int)r[16]&&outputMatch&&speed==r[20]&&State.steps==(int)r[21]&&State.ranges==(int)r[22]&&State.times==(int)r[23]&&B(State.zombie.previousPosition.x)==r[24]&&unchecked((uint)State.enemy.row)==r[25]&&State.argsOK&&r[26]==1&&r[27]==1;count++;if(!ok){fail++;if(samples.Count<10)samples.Add(token.ToString("X8")+":"+count+" trace="+State.trace+"/"+r[15]+" err="+err+"/"+r[16]+" speed="+speed+"/"+r[20]+" vector="+outputMatch+" args="+State.argsOK);if(stop)return(count,fail,samples);}}return(count,fail,samples);}
public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x0600043D,0x0600043E,0x0600043F,0x060005D9};var ms=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=16384||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","wrong_previous_axis","cache_delta","flip_zero","helmet_map","cone_map","zero_position","preview_row_factor","preview_range","preview_subtract"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=4,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Actual four caller IL; original speed/armor switch/vector/preview arithmetic/order tested with initialized metadata and recording Unity/time/random/sprite/list/exception dependencies. Pinned public Vector3, CLR public List<Game>.get_Item, exact decoded original literal strings; enum int alias explicit. Preview exception partial native return buffer writes recorded but not exposed by managed return and excluded from value comparison; call/exception/field traces still compared. No original Unity/helpers/class-init/throw/full-game/iOS proof."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
