using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using Keyframe=UnityEngine.Keyframe;using System.Runtime.InteropServices;
public class DependencyException:Exception{}
public class SkewTextExample{}public class WarpTextExample{}
public class Curve {public Keyframe[]? backend;public int marker;public Curve(){State.trace.Add("C");State.created=this;State.latest=this;marker=7;if(State.failCtor)throw new DependencyException();backend=Array.Empty<Keyframe>();}public Curve(bool fixtureInput){}public Keyframe[]? keys {get{State.trace.Add("G");State.getReceiver=this;if(State.failGet)throw new DependencyException();if(State.swapLatest)State.latest=State.alternate;return State.returnArray;}set{State.trace.Add("S");State.setReceiver=this;State.setArray=value;if(State.failSet)throw new DependencyException();backend=value;}}}
public static class State {public static List<string>trace=new();public static Curve?created,latest,alternate,getReceiver,setReceiver;public static Keyframe[]?returnArray,setArray;public static bool failCtor,failGet,failSet,swapLatest;public static void Reset(){trace.Clear();created=latest=alternate=getReceiver=setReceiver=null;returnArray=setArray=null;failCtor=failGet=failSet=swapLatest=false;}}
public static class Fixture {
 static Dictionary<string,Type>map=new(){["TMPro.Examples.SkewTextExample"]=typeof(SkewTextExample),["TMPro.Examples.WarpTextExample"]=typeof(WarpTextExample),["UnityEngine.AnimationCurve"]=typeof(Curve),["UnityEngine.Keyframe"]=typeof(Keyframe),["System.Object"]=typeof(object),["System.Boolean"]=typeof(bool),["System.NullReferenceException"]=typeof(NullReferenceException),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>t is ArrayType a?T(a.ElementType).MakeArrayType():map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Type "+t.FullName);
 static Func<object?,Curve?,Curve?>Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,typeof(Curve),new[]{T(m.DeclaringType),typeof(Curve)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_input"){il.Emit(RO.Ldarg_1);il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="wrong_set_receiver"&&op==RO.Ldloc_1&&i.Next?.OpCode.Code==Mono.Cecil.Cil.Code.Ldarg_1){il.Emit(RO.Ldarg_1);changed=true;continue;}
   if(mutation=="wrong_return"&&op==RO.Ldloc_1&&i.Next?.OpCode.Code==Mono.Cecil.Cil.Code.Ret){il.Emit(RO.Ldarg_1);changed=true;continue;}
   if(a is MethodReference mr){if(mutation=="skip_getter"&&mr.Name=="get_keys"){il.Emit(RO.Pop);il.Emit(RO.Ldnull);changed=true;continue;}if(mutation=="skip_setter"&&mr.Name=="set_keys"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(mr.Name==".ctor"){il.Emit(op,T(mr.DeclaringType).GetConstructor(Type.EmptyTypes)!);continue;}var mi=T(mr.DeclaringType).GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,mr.Parameters.Select(p=>T(p.ParameterType)).ToArray(),null)??throw new Exception("Missing method "+mr);il.Emit(op,mi);continue;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition p){il.Emit(op,(short)(p.Index+1));continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Unapplied mutation");if(m.DeclaringType.Name=="SkewTextExample"){var d=(Func<SkewTextExample?,Curve?,Curve>)dm.CreateDelegate(typeof(Func<SkewTextExample,Curve,Curve>));return(a,b)=>d((SkewTextExample?)a,b);}else{var d=(Func<WarpTextExample?,Curve?,Curve>)dm.CreateDelegate(typeof(Func<WarpTextExample,Curve,Curve>));return(a,b)=>d((WarpTextExample?)a,b);}
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(Func<object?,Curve?,Curve?>fn,MethodDefinition m,List<int[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();void Check(bool pass,string msg){count++;if(!pass)failures.Add(msg);}var rng=new Random(m.MetadataToken.ToInt32());
  foreach(var r in rows){var arrays=new Keyframe[2][];for(int a=0;a<2;a++){arrays[a]=new Keyframe[rng.Next(33)];for(int j=0;j<arrays[a].Length;j++)arrays[a][j]=new Keyframe(BitConverter.Int32BitsToSingle((int)rng.NextInt64(int.MinValue,(long)int.MaxValue+1)),BitConverter.Int32BitsToSingle((int)rng.NextInt64(int.MinValue,(long)int.MaxValue+1)),BitConverter.Int32BitsToSingle((int)rng.NextInt64(int.MinValue,(long)int.MaxValue+1)),BitConverter.Int32BitsToSingle((int)rng.NextInt64(int.MinValue,(long)int.MaxValue+1)));}var before=arrays.Select(a=>MemoryMarshal.AsBytes(a.AsSpan()).ToArray()).ToArray();var input=new Curve(true){backend=arrays[0],marker=123};var alt=new Curve(true){marker=456};State.Reset();State.returnArray=r[1]==0?null:arrays[r[1]-1];State.swapLatest=r[2]!=0;State.alternate=alt;bool match=false;try{object?owner=r[0]==0?null:m.DeclaringType.Name=="SkewTextExample"?new SkewTextExample():new WarpTextExample();var output=fn(owner,input);match=r.Skip(3).All(v=>v==1)&&State.trace.SequenceEqual(new[]{"C","G","S"})&&ReferenceEquals(State.getReceiver,input)&&ReferenceEquals(State.setReceiver,State.created)&&ReferenceEquals(output,State.created)&&!ReferenceEquals(output,input)&&ReferenceEquals(State.setArray,State.returnArray)&&ReferenceEquals(output?.backend,State.returnArray)&&output?.marker==7&&input.marker==123&&ReferenceEquals(input.backend,arrays[0])&&alt.marker==456&&ReferenceEquals(State.latest,r[2]!=0?alt:output)&&arrays.Select((a,j)=>MemoryMarshal.AsBytes(a.AsSpan()).SequenceEqual(before[j])).All(v=>v);}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"row:"+index++);if(stop&&failures.Count>0)return new(count,failures);}
  foreach(bool hasOwner in new[]{false,true}){State.Reset();bool thrown=false;try{fn(hasOwner?(m.DeclaringType.Name=="SkewTextExample"?new SkewTextExample():new WarpTextExample()):null,null);}catch(NullReferenceException){thrown=true;}Check(thrown&&State.trace.SequenceEqual(new[]{"C"})&&State.created!=null,"null-input-creates-first");}
  foreach(string stage in new[]{"ctor","getter","setter"}){var input=new Curve(true){marker=123};State.Reset();State.returnArray=Array.Empty<Keyframe>();State.failCtor=stage=="ctor";State.failGet=stage=="getter";State.failSet=stage=="setter";bool thrown=false;try{fn(null,input);}catch(DependencyException){thrown=true;}var expected=stage=="ctor"?new[]{"C"}:stage=="getter"?new[]{"C","G"}:new[]{"C","G","S"};Check(thrown&&State.trace.SequenceEqual(expected)&&input.marker==123,"dependency-exception:"+stage);}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var input=File.ReadLines(args[1]).Select(l=>l.Split(' ')).GroupBy(r=>Convert.ToInt32(r[0],16)).ToDictionary(g=>g.Key,g=>g.Select(r=>r.Skip(1).Select(int.Parse).ToArray()).ToList());if(!input.Keys.Order().SequenceEqual(new[]{0x06000771,0x06000817}))throw new Exception("Scope");int cases=0,errors=0;var failures=new List<string>();var controls=new List<object>();bool controlsPass=true;foreach(var group in input){var m=(MethodDefinition)a.MainModule.LookupToken(group.Key);var result=Cases(Emit(m,"none"),m,group.Value);cases+=result.Cases;failures.AddRange(result.Failures.Select(f=>m.DeclaringType.Name+":"+f));foreach(string mut in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_input","wrong_set_receiver","wrong_return","skip_getter","skip_setter"}){bool detected=false;string?error=null;try{detected=Cases(Emit(m,mut),m,group.Value,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}controlsPass&=detected&&error==null;controls.Add(new{token=$"0x{group.Key:X8}",mutation=mut,detected,tool_error=error});}}bool pass=failures.Count==0&&errors==0&&controlsPass;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=cases,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,unity_core_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(typeof(Keyframe).Assembly.Location))).ToLowerInvariant(),scope="Original native caller execution uses recorded allocator/empty ctor/get/set with explicit metadata/layout preconditions. Actual candidate CIL executes through public Curve doubles and real Unity Keyframe value arrays from pinned CoreModule. Allocation-before-null, array forwarding/identity/data, fresh result, receiver capture, unused null this and dependency exception order tested. Original curve engine/allocator/throw/Unity/iOS acceptance not tested",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
