using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Reflection.PortableExecutable;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using MD=Mono.Cecil.MethodDefinition;
using MR=Mono.Cecil.MethodReference;
using FR=Mono.Cecil.FieldReference;
static class RepairNative41 {
 static void R(bool x,string m){if(!x)throw new InvalidOperationException(m);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static int Align(int x,int a)=>checked((x+a-1)/a*a);
 class IL {
  public List<byte> B=new();Dictionary<string,int> labels=new();List<(int p,string l)> branches=new();
  public IL O(params byte[] x){B.AddRange(x);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}
  public IL Ref(byte op,IMetadataTokenProvider r)=>O(op).I(r.MetadataToken.ToInt32());public IL Ref(byte op,int t)=>O(op).I(t);
  public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Float(float x)=>O(0x22).I(BitConverter.SingleToInt32Bits(x));
  public IL L(int i)=>i<4?O((byte)(6+i)):O(0x11,(byte)i);public IL S(int i)=>i<4?O((byte)(10+i)):O(0x13,(byte)i);public IL A(int i)=>O(0x12,(byte)i);
  public IL Arg(int i)=>i<4?O((byte)(2+i)):O(0x0E,(byte)i);
  public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Branch(byte op,string s){O(op);branches.Add((B.Count,s));O(0);return this;}
  public byte[] Done(){foreach(var(p,l)in branches){int d=labels[l]-p-1;R(d>=-128&&d<=127,"Short branch overflow");B[p]=unchecked((byte)(sbyte)d);}return B.ToArray();}
 }
 record Stream(string Name,byte[] Data);
 record Added(string Name,int Token,int Parent,int NameIndex,int SignatureIndex);
 static (byte[] Image,object Evidence) Metadata(byte[] input,PEReader pe,Mono.Cecil.ModuleDefinition module){
  var md=pe.GetMetadataReader();int rootRva=pe.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress;var section=pe.PEHeaders.SectionHeaders.Single(s=>rootRva>=s.VirtualAddress&&rootRva<s.VirtualAddress+s.SizeOfRawData);int rootOffset=section.PointerToRawData+rootRva-section.VirtualAddress;int rootSize=pe.PEHeaders.CorHeader.MetadataDirectory.Size;byte[] root=input[rootOffset..(rootOffset+rootSize)];R(BitConverter.ToUInt32(root,0)==0x424A5342,"Metadata root");int vlen=BitConverter.ToInt32(root,12);int countAt=Align(16+vlen,4)+2;int count=BitConverter.ToUInt16(root,countAt);int p=countAt+2;var streams=new List<Stream>();
  for(int i=0;i<count;i++){int off=BitConverter.ToInt32(root,p),len=BitConverter.ToInt32(root,p+4);int end=Array.IndexOf(root,(byte)0,p+8);R(end>=0,"Stream name");string name=Encoding.ASCII.GetString(root,p+8,end-p-8);streams.Add(new(name,root[off..(off+len)]));p=Align(end+1,4);}int headEnd=p;
  int ti=streams.FindIndex(s=>s.Name=="#~");R(ti>=0,"Compressed table stream required");var table=streams[ti].Data;var stringStream=streams.Single(s=>s.Name=="#Strings").Data;var blobStream=streams.Single(s=>s.Name=="#Blob").Data;R((table[6]&3)==0,"Pinned 2-byte string/blob indexes");int rows=md.GetTableRowCount(TableIndex.MemberRef);int rowSize=md.GetTableRowSize(TableIndex.MemberRef);R(rows==1031&&rowSize==6,"Pinned MemberRef layout");R(md.GetTableRowCount(TableIndex.TypeSpec)<8192&&md.GetTableRowCount(TableIndex.TypeDef)<8192&&md.GetTableRowCount(TableIndex.TypeRef)<8192&&md.GetTableRowCount(TableIndex.ModuleRef)<8192&&md.GetTableRowCount(TableIndex.MethodDef)<8192,"Parent index width");
  byte[] Compressed(uint v)=>v<=0x7F?new[]{(byte)v}:v<=0x3FFF?new[]{(byte)((v>>8)|0x80),(byte)v}:new[]{(byte)((v>>24)|0xC0),(byte)(v>>16),(byte)(v>>8),(byte)v};
  uint Coded(Mono.Cecil.TypeReference t)=>t.MetadataToken.TokenType==TokenType.TypeDef?t.MetadataToken.RID<<2:t.MetadataToken.TokenType==TokenType.TypeRef?(t.MetadataToken.RID<<2)|1:throw new Exception("TypeDefOrRef");
  var newSpecs=new Dictionary<string,int>();var typeRows=new List<byte>();int originalBlobSize=blobStream.Length;
  foreach(string name in new[]{"Device_boardEditor","Enemy_boardEditor"}){var instance=(GenericInstanceType)module.Types.Single(t=>t.Name=="Admin_system2_boardEdior").Fields.Single(f=>f.Name==(name=="Device_boardEditor"?"device_BoardEditors":"enemy_BoardEditors")).FieldType;byte[] signature=new byte[]{0x15,0x12}.Concat(Compressed(Coded(instance.ElementType))).Concat(new byte[]{1,0x12}).Concat(Compressed(Coded(instance.GenericArguments[0]))).ToArray();int ix=blobStream.Length;R(ix<65536,"Blob index width");blobStream=blobStream.Concat(Compressed((uint)signature.Length)).Concat(signature).ToArray();typeRows.AddRange(BitConverter.GetBytes((ushort)ix));newSpecs.Add(instance.FullName,md.GetTableRowCount(TableIndex.TypeSpec)+newSpecs.Count+1);}
  R(blobStream.Length<65536,"Blob heap width unchanged");
  int ts(string name){if(newSpecs.TryGetValue(name,out int nr))return nr;var hits=Enumerable.Range(1,md.GetTableRowCount(TableIndex.TypeSpec)).Select(i=>module.LookupToken(0x1B000000+i)).OfType<Mono.Cecil.TypeReference>().Where(t=>t.FullName==name).ToArray();R(hits.Length==1,"Exact TypeSpec "+name);return hits[0].MetadataToken.RID is uint r?checked((int)r):throw new Exception();}
  int originalStringSize=stringStream.Length;int nameIndex(string name){for(int i=0;i<stringStream.Length-name.Length;i++){if(Encoding.UTF8.GetString(stringStream,i,name.Length)==name&&stringStream[i+name.Length]==0)return i;}throw new Exception("Existing member name required "+name);}
  int sig(byte[] desired){foreach(var h in md.MemberReferences){var m=md.GetMemberReference(h);if(md.GetBlobBytes(m.Signature).SequenceEqual(desired))return MetadataTokens.GetHeapOffset(m.Signature);}throw new Exception("Existing signature missing");}
  var specs=new[]{"PreDevice","Device_boardEditor","Enemy","Enemy_boardEditor"}.Select(t=>("Remove",ts("System.Collections.Generic.List`1<"+t+">")*8+4,sig(new byte[]{0x20,1,2,0x13,0}))).ToArray();
  ulong valid=BitConverter.ToUInt64(table,8);R((valid&(1UL<<10))!=0,"MemberRef missing");int countPos=24+4*Enumerable.Range(0,10).Count(i=>(valid&(1UL<<i))!=0);R(BitConverter.ToInt32(table,countPos)==rows,"Row count pin");int tableStart=md.GetTableMetadataOffset(TableIndex.MemberRef);int streamRootOffset=Array.FindIndex(root,_=>false); // replaced with exact stream offset below
  int scan=countAt+2;for(int i=0;i<count;i++){int e=Array.IndexOf(root,(byte)0,scan+8);if(Encoding.ASCII.GetString(root,scan+8,e-scan-8)=="#~")streamRootOffset=BitConverter.ToInt32(root,scan);scan=Align(e+1,4);}R(streamRootOffset>=0,"Table stream root offset");int insert=tableStart-streamRootOffset+rows*rowSize;R(insert>=24&&insert<=table.Length,"MemberRef table end");var add=new List<byte>();var added=new List<Added>();foreach(var(name,parent,signature)in specs){int ni=nameIndex(name);R(ni<65536&&signature<65536&&parent<65536,"Index overflow");int coded=parent;add.AddRange(BitConverter.GetBytes((ushort)coded));add.AddRange(BitConverter.GetBytes((ushort)ni));add.AddRange(BitConverter.GetBytes((ushort)signature));added.Add(new(name,0x0A000000+rows+added.Count+1,((coded&7)==1?0x01000000:0x1B000000)+(coded>>3),ni,signature));}
  byte[] expanded=table[..insert].Concat(add).Concat(table[insert..]).ToArray();BitConverter.GetBytes(rows+added.Count).CopyTo(expanded,countPos);int typeEnd=md.GetTableMetadataOffset(TableIndex.TypeSpec)-streamRootOffset+md.GetTableRowCount(TableIndex.TypeSpec)*md.GetTableRowSize(TableIndex.TypeSpec)+add.Count;R(md.GetTableRowSize(TableIndex.TypeSpec)==2,"TypeSpec row width");expanded=expanded[..typeEnd].Concat(typeRows).Concat(expanded[typeEnd..]).ToArray();int typeCountPos=24+4*Enumerable.Range(0,27).Count(i=>(valid&(1UL<<i))!=0);BitConverter.GetBytes(md.GetTableRowCount(TableIndex.TypeSpec)+2).CopyTo(expanded,typeCountPos);ulong sorted=BitConverter.ToUInt64(expanded,16);BitConverter.GetBytes(sorted&~(1UL<<10)).CopyTo(expanded,16);streams[ti]=new("#~",expanded);streams[streams.FindIndex(s=>s.Name=="#Blob")]=new("#Blob",blobStream);streams[streams.FindIndex(s=>s.Name=="#Strings")]=new("#Strings",stringStream);
  var nr=new List<byte>(root[..headEnd]);scan=countAt+2;foreach(var s in streams){while(nr.Count%4!=0)nr.Add(0);BitConverter.GetBytes(nr.Count).CopyTo(nr,scan);BitConverter.GetBytes(s.Data.Length).CopyTo(nr,scan+4);nr.AddRange(s.Data);int e=Array.IndexOf(root,(byte)0,scan+8);scan=Align(e+1,4);}byte[] meta=nr.ToArray();
  // The qualified Native29 metadata section is already the last section.
  // Its header has no room for another section header. Extend that read-only
  // section at EOF while retaining all existing bytes, raw starts and RVAs.
  var ph=pe.PEHeaders;var opt=ph.PEHeader!;R(opt.Magic==PEMagic.PE32&&opt.CertificateTableDirectory.Size==0&&ph.CorHeader.StrongNameSignatureDirectory.Size==0&&(ph.CorHeader.Flags&CorFlags.StrongNameSigned)==0,"Unsupported signed/input layout");var last=ph.SectionHeaders.Last();R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==input.Length&&last.VirtualSize<=last.SizeOfRawData&&last.SectionCharacteristics==(SectionCharacteristics)0x40000040,"Pinned extensible metadata section");R(rootOffset>=last.PointerToRawData&&rootOffset+rootSize<=input.Length,"Parent metadata in last section");int header=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40;int raw=Align(input.Length,opt.FileAlignment),va=last.VirtualAddress+raw-last.PointerToRawData,append=Align(meta.Length,opt.FileAlignment);var output=new byte[raw+append];input.CopyTo(output,0);meta.CopyTo(output,raw);int newVirtual=raw-last.PointerToRawData+meta.Length,newRaw=output.Length-last.PointerToRawData;
  BitConverter.GetBytes(newVirtual).CopyTo(output,header+8);BitConverter.GetBytes(newRaw).CopyTo(output,header+16);BitConverter.GetBytes(opt.SizeOfInitializedData+output.Length-input.Length).CopyTo(output,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+newVirtual,opt.SectionAlignment)).CopyTo(output,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(output,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(va).CopyTo(output,ph.CorHeaderStartOffset+8);BitConverter.GetBytes(meta.Length).CopyTo(output,ph.CorHeaderStartOffset+12);
  return(output,new{old_root_offset=rootOffset,old_root_size=rootSize,new_root_offset=raw,new_root_size=meta.Length,extended_section_header=header,old_virtual_size=last.VirtualSize,new_virtual_size=newVirtual,old_raw_size=last.SizeOfRawData,new_raw_size=newRaw,added,added_typespecs=newSpecs,blob_heap_added_bytes=blobStream.Length-originalBlobSize,table_sorted_bit_cleared=(sorted&(1UL<<10))!=0,existing_heap_prefixes_unchanged=true,string_heap_added_bytes=stringStream.Length-originalStringSize});

 }
 static void CopyTo(this byte[] b,List<byte> list,int p){for(int j=0;j<b.Length;j++)list[p+j]=b[j];}
 static int Main(string[] args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[] args){R(args.Length==3,"input new-output report");R(!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs required");byte[] before=File.ReadAllBytes(args[0]);R(H(before)=="bb71c657d2a0f2e1155ef43b55f96c0355097c225c25b0d62aacfadc27fa7088","Pinned Native40 input");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);var module=asm.MainModule;using var fs=File.OpenRead(args[0]);using var pe=new PEReader(fs);var(after,metadata)=Metadata(before,pe,module);int first=0x0A000000+pe.GetMetadataReader().GetTableRowCount(TableIndex.MemberRef)+1;
  MD M(int t)=>(MD)module.LookupToken(t);FR F(MD m,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<FR>().Where(f=>f.Name==name).DistinctBy(f=>f.MetadataToken).Single();MR C(MD m,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MR>().First(c=>c.Name==name);var targets=new Dictionary<int,(byte[] code,int max)>();var report=new List<object>();void Set(int token,IL il,int max){targets.Add(token,(il.Done(),max));}
  MD m;
  foreach(int token in new[]{0x0600001B,0x0600001E,0x0600002B,0x06000040}){
   m=M(token);var code=pe.GetMethodBody(m.RVA).GetILBytes()!.ToArray();var calls=m.Body.Instructions.Where(i=>i.Operand is MR r&&r.Name=="Remove").ToArray();R(calls.Length==2&&calls.All(i=>i.OpCode==OpCodes.Call&&((MR)i.Operand).FullName=="System.Boolean System.Collections.Generic.List`1<System.Object>::Remove(!0)"),"Two pinned damaged calls");int kind=token is 0x0600001B or 0x0600002B?0:2;
   for(int j=0;j<2;j++)BitConverter.GetBytes(first+kind+j).CopyTo(code,calls[j].Offset+1);targets.Add(token,(code,m.Body.MaxStackSize));
  }
  foreach(var(token,(code,max))in targets){m=M(token);R(m.Body.ExceptionHandlers.Count==0,"EH relocation unsupported");var sec=pe.PEHeaders.SectionHeaders.Single(s=>m.RVA>=s.VirtualAddress&&m.RVA<s.VirtualAddress+s.SizeOfRawData);int h=sec.PointerToRawData+m.RVA-sec.VirtualAddress;int hs=(BitConverter.ToUInt16(before,h)>>12)*4;R((before[h]&3)==3&&hs==12,"Pinned fat body");R(code.Length<=m.Body.CodeSize,"Body exceeds reserved slot "+m.FullName);Array.Clear(after,h+hs,m.Body.CodeSize);code.CopyTo(after,h+hs);BitConverter.GetBytes(code.Length).CopyTo(after,h+4);BitConverter.GetBytes((ushort)max).CopyTo(after,h+2);report.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,code_start=h+hs,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,local_sig=m.Body.LocalVarToken.ToInt32(),code_sha256=H(code)});}
  R(targets.Count==4,"Pinned scope 4");File.WriteAllBytes(args[1],after);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(before),candidate_sha256=H(after),metadata,methods=report,scope="Eight call-token replacements in four methods; original opcode/branches/headers/locals unchanged; four appended public closed Remove refs"},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine("CANDIDATE "+H(after));
 }
}
