#!/usr/bin/env python3
"""Native18 exact-seed replay and Clang syntax qualification; repair Zombie method blockers."""
from pathlib import Path
import hashlib, json, runpy, subprocess, time, os, re, shutil

root = Path(__file__).resolve().parents[2]
base = root / '.validation/native18'; base.mkdir(parents=True, exist_ok=True)
report = {'status': 'RUNNING', 'full_unity_export': False, 'production_promotion': False}
(base / 'latest-result.json').write_text(json.dumps(report))
started = time.monotonic()

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

try:
    reuse_dir = os.environ.get('REUSE_REPLAY_DIR')
    expected = {
        'unlinked': '74c7474f0592d3f577f8376d75d26528624798794983b3f07db5fd973e7456b2',
        'linked': '9bf2d7a033632061e8e71d32c70312c3c234298649495afc384d0dfe7120a125'
    }

    if reuse_dir and (Path(reuse_dir) / 'native17-linked.dll').exists():
        work = Path(reuse_dir)
        C = work / 'canary'
        M = C / 'Library/Bee/artifacts/iOS/ManagedStripped'
        D = M / 'GodsPVZRuntime1.dll'
        exe = C / 'il2cpp/build/deploy/il2cpp'
        manifest = dict(line.split('=', 1) for line in (C / 'MANIFEST.txt').read_text().splitlines() if '=' in line)
        rsp = C / 'Library/Bee/artifacts/rsp' / manifest['rsp_basename']

        def run(args, log, **kw):
            with (work / log).open('w') as f:
                r = subprocess.run(args, cwd=root, stdout=f, stderr=subprocess.STDOUT, timeout=600, **kw)
            if r.returncode: raise RuntimeError(f'{log}: exit {r.returncode}; see {work/log}')

        def replay(label, dll):
            shutil.copy2(dll, D)
            output = C / 'Library/Bee/artifacts/iOS/il2cppOutput'
            if output.exists(): shutil.rmtree(output)
            (output / 'cpp/Symbols').mkdir(parents=True)
            (output / 'data').mkdir()
            with (work / (label + '.log')).open('w') as f:
                r = subprocess.run([str(exe), '--custom-il2-cpp-root=' + str(C / 'il2cpp'), '@' + str(rsp)],
                                   cwd=C, stdout=f, stderr=subprocess.STDOUT, timeout=180)
            s = (work / (label + '.log')).read_text(errors='replace')
            methods = sorted(set(re.findall(r"IL2CPP error for method '([^']+)'", s)))
            if r.returncode and not methods: raise RuntimeError(label + ' non-method failure; see ' + str(work / (label + '.log')))
            result = {'exit': r.returncode, 'methods': methods, 'input_sha256': sha(dll)}
            print(label + ' ' + json.dumps(result), flush=True)
            return result

        g = {'M': M}
        previous = {
            'g': g, 'work': work, 'run': run, 'replay': replay,
            'outputs': {
                'unlinked': {'path': str(work / 'native17-unlinked.dll')},
                'linked': {'path': str(work / 'native17-linked.dll')}
            }
        }
        native17_result = json.loads((work / 'native17-result.json').read_text())['native17']
    else:
        previous = runpy.run_path(str(root / 'scripts/codespaces/validate_native17.py'))
        g = previous['g']; work = previous['work']; run = previous['run']; replay = previous['replay']
        native17_result = previous.get('report', {}).get('native17', previous.get('result', {}))

    outputs = {}
    for label, args in [('unlinked', []), ('linked', ['linked'])]:
        source = Path(previous['outputs'][label]['path'])
        assert sha(source) == expected[label], f'{label} native17 differs: got {sha(source)}'
        first = work / f'native18-{label}.dll'
        second = work / f'native18-{label}-repeat.dll'
        for output, suffix in [(first, ''), (second, '-repeat')]:
            run(['dotnet', 'run', '--project', str(root / 'scripts/takeover/PatcherNative18'), '--', str(source), str(output)] + args,
                f'native18-{label}{suffix}.log', env=dict(os.environ, GODSPVZ_RESOLVER=str(g['M'])))
        assert first.read_bytes() == second.read_bytes(), label + ' nondeterministic'
        outputs[label] = {'path': str(first), 'input_sha256': sha(source), 'sha256': sha(first)}

    # Replay direct conversion in IL2CPP canary
    result = replay('native18', Path(outputs['linked']['path']))
    assert result['exit'] == 0, f"native18 IL2CPP conversion exit code {result['exit']}"
    assert len(result['methods']) == 0, f"native18 has unexpected IL2CPP method errors: {result['methods']}"

    # Verify generated GodsPVZRuntime1__9.cpp
    canary = work / 'canary'
    cpp_file = canary / 'Library/Bee/artifacts/iOS/il2cppOutput/cpp/GodsPVZRuntime1__9.cpp'
    assert cpp_file.exists(), "GodsPVZRuntime1__9.cpp was not generated by IL2CPP"

    cpp_text = cpp_file.read_text(errors='replace')
    # Verify no unmanaged memory load strings or stack warning comments in cpp
    assert "Unmanaged memory load" not in cpp_text, "Found leaked unmanaged memory string in cpp"
    assert "Warning: Method ends with non empty stack" not in cpp_text, "Found stack warning string in cpp"

    # Verify the 8 methods in C++ text
    assert "Zombie_PreviousPosition" in cpp_text, "Zombie_PreviousPosition missing in cpp"
    assert "Zombie_Start_PreviousPosition" in cpp_text, "Zombie_Start_PreviousPosition missing in cpp"
    assert "Zombie_Update_Move" in cpp_text, "Zombie_Update_Move missing in cpp"
    assert "Zombie_Update_PreviousPosition" in cpp_text, "Zombie_Update_PreviousPosition missing in cpp"
    assert "Zombie_ArmBroken" in cpp_text, "Zombie_ArmBroken missing in cpp"
    assert "Zombie_Ashe" in cpp_text, "Zombie_Ashe missing in cpp"
    assert "Zombie_CheckZombieWin" in cpp_text, "Zombie_CheckZombieWin missing in cpp"
    assert "Zombie_CreateStartPrePath" in cpp_text, "Zombie_CreateStartPrePath missing in cpp"

    report.update(
        status='NATIVE18_DIRECT_CONVERSION_PASS',
        native17=native17_result,
        native18=result,
        outputs=outputs,
        work_directory=str(work),
        elapsed_seconds=round(time.monotonic() - started, 2),
        source_commit=subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root, text=True).strip()
    )
    (work / 'native18-result.json').write_text(json.dumps(report, indent=2) + '\n')
    print("NATIVE18_VALIDATION_SUCCESS", flush=True)
except Exception as e:
    report.update(status='FAILED', error=str(e))
    raise
finally:
    (base / 'latest-result.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2), flush=True)

