using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher57{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int t){O(op);b.AddRange(BitConverter.GetBytes(t));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public void L(byte n)=>O(0x11,n);public void S(byte n)=>O(0x13,n);public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="fbcded9c104193cd40df6a0f7e76c3dc8e543dd845cced71cfaf74c052f91b02","Pinned Native56");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x06000045,0x060002C3,0x06000301,0x0600035D,0x06000378,0x06000409,0x060004A1,0x06000669}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>a.MainModule.GetTypes().Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);MethodReference exact(string name)=>a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName==name);FieldReference exactField(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(f=>f.FullName==name);FieldReference vf(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(r=>r.FullName=="System.Single UnityEngine.Vector3::"+name);
void Load(string owner,string name){il.O(2);il.Ref(0x7b,field(owner,name));}void StoreFloat(string owner,string name,float value){il.O(2);il.F(value);il.Ref(0x7d,field(owner,name));}void V3()=>il.Ref(0x73,exact("System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)"));void GetShadow(string owner){Load(owner,"shadow");il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));}void VecPart(byte local,string part){il.L(local);il.Ref(0x7b,vf(part));}void String(string value){var i=m.Body.Instructions.Single(i=>i.OpCode.Name=="ldstr"&&i.Operand is string s&&s==value);il.Token(0x72,BitConverter.ToInt32(b,Off(pe,m.RVA)+12+i.Offset+1));}
int sig=m.Body.LocalVarToken.ToInt32(),max=3;
switch(token){
case 0x06000045:{max=2;il.O(3,0x14);il.Ref(0x28,exact("System.Boolean UnityEngine.Object::op_Equality(UnityEngine.Object,UnityEngine.Object)"));il.Br(0x2d,"empty");il.O(2,3);il.Ref(0x6f,call("get_name"));il.Ref(0x7d,field("EnemyDataEditor","inputFieldName"));il.O(0x2a);il.Label("empty");il.O(2);il.Ref(0x7e,exactField("System.String System.String::Empty"));il.Ref(0x7d,field("EnemyDataEditor","inputFieldName"));il.O(0x2a);break;}
case 0x060002C3:{max=3;il.O(2,3);il.Ref(0x7d,field("Board","endTime"));StoreFloat("Board","gameSpeed",1);il.F(1);il.Ref(0x28,call("set_timeScale"));Load("Board","buttomButtons");il.O(0x16);il.Ref(0x6f,call("SetActive"));il.O(2,0x17);il.Ref(0x7d,field("Board","isWon"));il.Ref(0x7e,field("ResourceManager","boardClips"));il.O(0x1f,10);il.Ref(0x6f,call("get_Item"));il.O(0x0d);Load("Board","cameraPosition");il.S(6);il.O(0x09);il.L(6);il.Ref(0x28,call("AudioVolume"));il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26,0x2a);break;}
case 0x06000301:{max=2;il.O(2);il.Ref(0x7e,exactField("System.String System.String::Empty"));il.Ref(0x7d,field("DeviceContent/ContentDeviceData","name"));il.O(2,0x17);il.Ref(0x7d,field("DeviceContent/ContentDeviceData","camp"));il.O(2);il.Ref(0x28,exact("System.Void System.Object::.ctor()"));foreach(var name in new[]{"name","camp","num"}){il.O(2,3);il.Ref(0x7b,field("DeviceContent/ContentDeviceData",name));il.Ref(0x7d,field("DeviceContent/ContentDeviceData",name));}il.O(0x2a);break;}
case 0x0600035D:{max=3;Load("Plant","isDied");il.Br(0x2d,"false");Load("Plant","healthPoint");il.F(0);il.Br(0x34,"false");Load("Plant","ID");il.O(0x1c);il.Br(0x33,"true");Load("Plant","healthPoint");il.O(0x65);Load("Plant","pT_chomperviking_barrelsPoint");il.Br(0x30,"true");il.O(2);Load("Plant","pT_chomperviking_barrelsPoint");il.O(2);il.Ref(0x28,call("Healed"));StoreFloat("Plant","pT_chomperviking_barrelsPoint",0);il.O(2);il.Ref(0x28,call("PC_ChompervikingUpdateBarrels"));Load("Plant","healthPoint");il.F(0);il.Br(0x32,"true");il.Label("false");il.O(0x16,0x2a);il.Label("true");il.O(0x17,0x2a);break;}
case 0x06000378:{max=3;il.O(2);il.Ref(0x28,call("get_transform"));il.Ref(0x6f,call("get_position"));il.O(0x0d,0x12,3);Load("Plant","fZ");Load("Plant","fY");il.O(0x58);Load("Plant","fH");il.O(0x58);il.F(10);il.O(0x59);il.Ref(0x7d,vf("y"));il.O(3,0x17,0x09);il.Ref(0x28,call("CreatDamageText"));il.O(0x26,3);Load("Plant","healthPoint");il.O(0x58);il.S(6);il.O(2);il.L(6);il.Ref(0x7d,field("Plant","healthPoint"));il.L(6);Load("Plant","maxHealthPoint");il.Br(0x37,"end");il.O(2);Load("Plant","maxHealthPoint");il.Ref(0x7d,field("Plant","healthPoint"));il.Label("end");il.O(0x2a);break;}
case 0x06000409:{max=2;Load("Prop","prop");il.Ref(0x6f,call("get_transform"));Load("Prop","originalPosition");il.Ref(0x6f,call("set_localPosition"));StoreFloat("Prop","alTime",0);il.O(2,0x16);il.Ref(0x7d,field("Prop","propState"));Load("Prop","propImagex");il.O(0x14);il.Ref(0x28,call("op_Inequality"));il.Br(0x2c,"state");Load("Prop","propImagex");il.Ref(0x28,call("Destroy"));il.Label("state");il.O(2);il.Ref(0x28,call("PropBankStateSet"));il.O(0x2a);break;}
case 0x060004A1:{max=2;il.O(2,0x16);il.Ref(0x7d,field("Zombie","poleZombie_pole"));il.O(2,0x16);il.Ref(0x7d,field("Zombie","poleZombie_jump"));il.O(2,0x1f,100);il.Ref(0x7d,field("Zombie","passablePoint"));Load("Zombie","ID");il.O(0x19);il.Br(0x33,"path");Load("Zombie","buffManager");String("PoleCommander.speed");il.Ref(0x6f,call("FindBuff"));il.O(0x0d,0x09);il.Br(0x2c,"path");Load("Zombie","buffManager");il.O(0x09);il.Ref(0x6f,call("RemoveBuff"));il.Label("path");il.O(2);il.Ref(0x28,call("Path_Finding"));il.O(0x26,0x2a);break;}
case 0x06000669:{max=4;foreach(var item in new[]{("roll",-60f),("skillAuto",-75f)}){Load("Plant_DetaiPage",item.Item1);il.Ref(0x6f,call("get_transform"));il.O(0x0a);il.Ref(0x28,call("get_deltaTime"));il.F(item.Item2);il.O(0x5a,0x0b,0x06);il.F(0);il.F(0);il.F(1);V3();il.O(0x07,0x16);il.Ref(0x6f,call("Rotate"));}il.O(0x2a);break;}
}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot "+m.FullName+" "+code.Length+"/"+m.Body.CodeSize);int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
