using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Security.Cryptography;
using System.Text;

if (args.Length != 2) { Console.Error.WriteLine("Usage: Stage9PlantDataClonePatch <input.dll> <output.dll>"); return 2; }
const string ExpectedInputSha256 = "1c8b03824d1de8096fdf79028f69af5b28ab69ca51980dd0fb89ae0889e5a958";
const int ExpectedMethodDefCount = 2317;
static IEnumerable<TypeDefinition> AllTypes(IEnumerable<TypeDefinition> roots){foreach(var t in roots){yield return t;foreach(var n in AllTypes(t.NestedTypes))yield return n;}}
static uint Raw(IMetadataTokenProvider p)=>p.MetadataToken.ToUInt32();
static string OperandSemantic(object? operand, MethodDefinition owner){if(operand is null)return "";if(operand is Instruction bi)return $"I#{owner.Body.Instructions.IndexOf(bi)}";if(operand is Instruction[] sw)return "SW["+string.Join(',',sw.Select(x=>owner.Body.Instructions.IndexOf(x)))+"]";if(operand is MethodReference mr)return $"M:{mr.FullName}";if(operand is FieldReference fr)return $"F:{fr.FullName}";if(operand is TypeReference tr)return $"T:{tr.FullName}";if(operand is VariableDefinition vr)return $"V:{vr.Index}:{vr.VariableType.FullName}";if(operand is ParameterDefinition pr)return $"P:{pr.Index}:{pr.ParameterType.FullName}";if(operand is string s)return $"S:{Convert.ToBase64String(Encoding.UTF8.GetBytes(s))}";return $"C:{Convert.ToString(operand,System.Globalization.CultureInfo.InvariantCulture)}";}
static string MethodSemantic(MethodDefinition m){var sb=new StringBuilder();sb.Append(m.FullName).Append('|').Append(m.Attributes).Append('|').Append(m.ImplAttributes).Append('|');if(!m.HasBody)return sb.Append("NOBODY").ToString();sb.Append("init=").Append(m.Body.InitLocals).Append(";max=").Append(m.Body.MaxStackSize).Append(';');foreach(var v in m.Body.Variables)sb.Append("L:").Append(v.Index).Append(':').Append(v.VariableType.FullName).Append(';');foreach(var i in m.Body.Instructions)sb.Append("I:").Append(i.OpCode.Code).Append(':').Append(OperandSemantic(i.Operand,m)).Append(';');return sb.ToString();}
static Instruction At(MethodDefinition m,int offset)=>m.Body.Instructions.SingleOrDefault(i=>i.Offset==offset)??throw new InvalidDataException($"{m.FullName}: missing IL_{offset:X4}");

var input=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);var inputSha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(input))).ToLowerInvariant();Console.WriteLine($"INPUT_SHA256 {inputSha}");if(inputSha!=ExpectedInputSha256)throw new InvalidDataException($"input SHA mismatch: {inputSha}");
using var module=ModuleDefinition.ReadModule(input,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate});var methods=AllTypes(module.Types).SelectMany(t=>t.Methods).ToList();if(methods.Count!=ExpectedMethodDefCount)throw new InvalidDataException($"MethodDef count drifted: {methods.Count}");var target=methods.SingleOrDefault(m=>m.FullName=="System.Void PlantData::CloneData(PlantSave)")??methods.SingleOrDefault(m=>m.DeclaringType.FullName=="PlantData"&&m.Name=="CloneData"&&m.Parameters.Count==1&&m.Parameters[0].ParameterType.FullName=="PlantSave")??throw new InvalidDataException("PlantData.CloneData target missing or ambiguous");var targetToken=Raw(target);Console.WriteLine($"TARGET_METHOD token=0x{targetToken:X8} name={target.FullName}");if(targetToken!=0x06000256)throw new InvalidDataException($"target token drifted: 0x{targetToken:X8}");
int[] idx={12,13,15,16,17,18,19,20,21};foreach(var i in idx){if(target.Body.Variables.Count<=i||target.Body.Variables[i].VariableType.FullName!="System.Object")throw new InvalidDataException($"PlantData.CloneData V{i} layout drift");}
var guards=new (int off,int vi)[]{(0x003e,13),(0x005a,16),(0x0076,15),(0x00ad,17),(0x00bb,17),(0x00c9,17),(0x00d7,17),(0x00e5,17),(0x0142,18),(0x017a,19),(0x01b2,20),(0x020f,21),(0x02ac,12)};foreach(var (off,vi) in guards){var ins=At(target,off);if(ins.OpCode.Code!=Code.Stloc||ins.Operand is not VariableDefinition v||v.Index!=vi)throw new InvalidDataException($"PlantData.CloneData guard drift at IL_{off:X4}");}
var changed=new HashSet<uint>{targetToken};var untouchedBefore=methods.Where(m=>!changed.Contains(Raw(m))).ToDictionary(Raw,MethodSemantic);
foreach(var i in idx)target.Body.Variables[i].VariableType=module.TypeSystem.Int32;Console.WriteLine("PATCH_PLANTDATA_CLONEDATA_INT_LOCALS locals=V12,V13,V15,V16,V17,V18,V19,V20,V21 type=System.Int32");
module.Write(output);var outputSha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(output))).ToLowerInvariant();Console.WriteLine($"OUTPUT_SHA256 {outputSha}");
using var reopen=ModuleDefinition.ReadModule(output,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate});var after=AllTypes(reopen.Types).SelectMany(t=>t.Methods).ToList();if(after.Count!=ExpectedMethodDefCount)throw new InvalidDataException("reopen MethodDef count drift");var rt=after.SingleOrDefault(m=>Raw(m)==targetToken)??throw new InvalidDataException("reopen target missing");foreach(var i in idx)if(rt.Body.Variables[i].VariableType.FullName!="System.Int32")throw new InvalidDataException($"reopen V{i} repair missing");Console.WriteLine($"REOPEN_PLANTDATA_CLONEDATA_PASS int_locals=9 token=0x{targetToken:X8}");
var untouchedAfter=after.Where(m=>!changed.Contains(Raw(m))).ToDictionary(Raw,MethodSemantic);var drift=untouchedBefore.Where(kv=>!untouchedAfter.TryGetValue(kv.Key,out var sem)||sem!=kv.Value).Select(kv=>kv.Key).ToList();if(drift.Count!=0)throw new InvalidDataException("semantic drift outside PlantData.CloneData: "+string.Join(',',drift.Select(t=>$"0x{t:X8}")));Console.WriteLine($"SEMANTIC_ISOLATION_PASS untouched_methods={untouchedAfter.Count} changed_methods=1");
return 0;
