using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;using AssemblyDefinition=Mono.Cecil.AssemblyDefinition;
static class Audit58{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
// These code locks seal the four independently native/CIL-tested bodies, not a semantic inference from a patch report.
static readonly Dictionary<int,(int length,int max,string hash)>Approved=new(){
{0x0600017B,(39,3,"bb8ccc5748a0745944ade71c8eeff644acec5009079f3f175ec856d99c171d8e")},
{0x06000477,(96,4,"fa63834024bae80aa3b1c6a532b669dd77c9cf852a64f32da9e59678b2f82751")},
{0x06000837,(31,2,"667fee03e9ca65d5d0d6c70aef43cef327fcd8a9fb49a74fd7c77e2f1c157755")},
{0x06000838,(41,1,"73191476b270d216ac530b09f9c73f5cf5c70815e8f7d44dd66b02874b2c85d4")}};
static int Main(string[]args){try{R(args.Length==4&&!File.Exists(args[3]),"Fresh audit output");var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="6e2aa50c2127dc07e4d7f20bcb40faf28c1958db0d843a20ac9db0f17fd8ea12"&&b.Length==c.Length,"Pinned parent/extent");using var p=new PEReader(new MemoryStream(b));using var q=new PEReader(new MemoryStream(c));R(p.GetMetadata().GetContent().SequenceEqual(q.GetMetadata().GetContent()),"All metadata bytes unchanged");using var a=AssemblyDefinition.ReadAssembly(args[0]);using var ac=AssemblyDefinition.ReadAssembly(args[1]);var allowed=new HashSet<int>();var report=JsonDocument.Parse(File.ReadAllText(args[2])).RootElement;R(report.GetProperty("input_sha256").GetString()==H(b)&&report.GetProperty("candidate_sha256").GetString()==H(c),"Report hash");var rows=report.GetProperty("methods").EnumerateArray().ToArray();R(rows.Length==4&&rows.Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).SequenceEqual(Approved.Keys),"Exact target scope");int count=0;
foreach(var m in a.MainModule.GetTypes().SelectMany(t=>t.Methods).Where(m=>m.HasBody)){var t=(MD)ac.MainModule.LookupToken(m.MetadataToken);R(t.RVA==m.RVA,"RVA unchanged");int h=Off(p,m.RVA),token=m.MetadataToken.ToInt32();if(!Approved.TryGetValue(token,out var expected)){int len=p.GetMethodBody(m.RVA).Size;R(b[h..(h+len)].SequenceEqual(c[h..(h+len)]),"Non-target raw body");count++;continue;}
R(t.Body.ExceptionHandlers.Count==0&&m.Body.ExceptionHandlers.Count==0&&t.Body.InitLocals==m.Body.InitLocals&&b[h..(h+2)].SequenceEqual(c[h..(h+2)]),"Flags/EH");R(t.Body.MaxStackSize==expected.max&&t.Body.CodeSize==expected.length&&expected.length<=m.Body.CodeSize,"Approved stack/size");var sigSource=m;R(t.Body.LocalVarToken==sigSource.Body.LocalVarToken&&t.Body.Variables.Select(v=>v.VariableType.FullName).SequenceEqual(sigSource.Body.Variables.Select(v=>v.VariableType.FullName)),"Approved immutable local signature binding");R(H(c[(h+12)..(h+12+t.Body.CodeSize)])==expected.hash,"Behavior-approved code lock");R(c[(h+12+t.Body.CodeSize)..(h+12+m.Body.CodeSize)].All(x=>x==0),"Unused slot zero");for(int i=h+2;i<h+12;i++)allowed.Add(i);for(int i=h+12;i<h+12+m.Body.CodeSize;i++)allowed.Add(i);
foreach(var i in t.Body.Instructions){if(i.Operand is IMetadataTokenProvider r&&i.Operand is FieldReference or MethodReference){R(a.MainModule.LookupToken(r.MetadataToken).ToString()==r.ToString(),"Existing exact member identity");}}
var row=rows.Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==h&&row.GetProperty("new_code_size").GetInt32()==expected.length&&row.GetProperty("new_max").GetInt32()==expected.max&&row.GetProperty("local_sig").GetInt32()==t.Body.LocalVarToken.ToInt32()&&row.GetProperty("reserved_code_size").GetInt32()==m.Body.CodeSize&&row.GetProperty("code_sha256").GetString()==expected.hash,"Report checked independently");}
R(Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).All(allowed.Contains),"Outside four bounded slots");var result=new{candidate_sha256=H(c),targets=4,non_target_raw_bodies_equal=count,entire_metadata_and_pe_outside_allowed_slots_unchanged=true,existing_member_identities_preserved=true,approved_local_signature_rebinding="All target local signatures unchanged",behavior_approved_code_locks_pass=true,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(result));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}}
