using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using System.Security.Cryptography;using System.Text.Json;
static class AuditNative43{
 static void R(bool b,string s){if(!b)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Align(int x,int a)=>(x+a-1)/a*a;
 static int Off(PEReader pe,int rva){var s=pe.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static int Main(string[]args){try{R(args.Length==4&&!File.Exists(args[3]),"Fresh audit report");byte[]b=File.ReadAllBytes(args[0]),c=File.ReadAllBytes(args[1]);R(H(b)=="50959644506ab0bc33f8ca1d28cfe753fc7b29ca38d98142b2a015dd05ccaaa2","Pinned parent digest");using var pb=new PEReader(new MemoryStream(b));using var pc=new PEReader(new MemoryStream(c));var mb=pb.GetMetadataReader();var mc=pc.GetMetadataReader();int target=0x0600084F;var handle=MetadataTokens.MethodDefinitionHandle(target&0xFFFFFF);var old=mb.GetMethodDefinition(handle);var now=mc.GetMethodDefinition(handle);var ob=pb.GetMethodBody(old.RelativeVirtualAddress);var nb=pc.GetMethodBody(now.RelativeVirtualAddress);int body=Off(pc,now.RelativeVirtualAddress),oldRoot=Off(pb,pb.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress),newRoot=Off(pc,pc.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress),size=pb.PEHeaders.CorHeader.MetadataDirectory.Size;
  R(body==b.Length&&nb.LocalSignature==ob.LocalSignature&&nb.LocalVariablesInitialized==ob.LocalVariablesInitialized&&nb.ExceptionRegions.Length==0&&nb.MaxStack==5,"Approved target body location/header/local/EH");byte[]code=nb.GetILBytes()!;R(code.Length>ob.GetILBytes()!.Length&&nb.Size==12+code.Length,"Appended fat body without sections");ushort flags=(ushort)(0x3003|(ob.LocalVariablesInitialized?0x10:0));R(BitConverter.ToUInt16(c,body)==flags&&BitConverter.ToUInt16(c,body+2)==5&&BitConverter.ToInt32(c,body+4)==code.Length&&BitConverter.ToInt32(c,body+8)==MetadataTokens.GetToken(ob.LocalSignature),"Exact new header");
  R(newRoot==Align(body+nb.Size,4)&&pc.PEHeaders.CorHeader.MetadataDirectory.Size==size&&c[(body+nb.Size)..newRoot].All(v=>v==0),"Root follows exact body and zero alignment");byte[]root=b[oldRoot..(oldRoot+size)];int row=mb.GetTableMetadataOffset(TableIndex.MethodDef)+((target&0xFFFFFF)-1)*mb.GetTableRowSize(TableIndex.MethodDef);BitConverter.GetBytes(now.RelativeVirtualAddress).CopyTo(root,row);R(root.SequenceEqual(c[newRoot..(newRoot+size)]),"Entire root equal except one exact MethodDef RVA; all rows/heaps/padding/header preserved");
  var expected=(byte[])b.Clone();var ph=pb.PEHeaders;var opt=ph.PEHeader!;var last=ph.SectionHeaders.Last();var nlast=pc.PEHeaders.SectionHeaders.Last();R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==b.Length&&ph.CoffHeader.NumberOfSections==pc.PEHeaders.CoffHeader.NumberOfSections,"Pinned EOF section/count");int sh=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40,virtualSize=newRoot-last.PointerToRawData+size;R(c.Length==Align(newRoot+size,opt.FileAlignment)&&c[(newRoot+size)..].All(v=>v==0)&&nlast.VirtualAddress==last.VirtualAddress&&nlast.PointerToRawData==last.PointerToRawData,"New extent and trailing zero padding");R(now.RelativeVirtualAddress==last.VirtualAddress+body-last.PointerToRawData,"Appended target RVA translation");BitConverter.GetBytes(virtualSize).CopyTo(expected,sh+8);BitConverter.GetBytes(c.Length-last.PointerToRawData).CopyTo(expected,sh+16);BitConverter.GetBytes(opt.SizeOfInitializedData+c.Length-b.Length).CopyTo(expected,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+virtualSize,opt.SectionAlignment)).CopyTo(expected,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(expected,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(last.VirtualAddress+newRoot-last.PointerToRawData).CopyTo(expected,ph.CorHeaderStartOffset+8);R(expected.SequenceEqual(c[..b.Length]),"Every old-file byte preserved except independently calculated PE/CLI extent headers; old target slot untouched");
  int non=0;foreach(var h in mb.MethodDefinitions){if(h==handle)continue;var m=mb.GetMethodDefinition(h);var n=mc.GetMethodDefinition(h);R(m.RelativeVirtualAddress==n.RelativeVirtualAddress,"Non-target RVA");if(m.RelativeVirtualAddress==0)continue;var bb=pb.GetMethodBody(m.RelativeVirtualAddress);var cb=pc.GetMethodBody(n.RelativeVirtualAddress);int x=Off(pb,m.RelativeVirtualAddress),y=Off(pc,n.RelativeVirtualAddress);R(bb.Size==cb.Size&&b[x..(x+bb.Size)].SequenceEqual(c[y..(y+cb.Size)]),"Non-target raw body "+MetadataTokens.GetToken(h).ToString("X8"));non++;}
  using var report=JsonDocument.Parse(File.ReadAllText(args[2]));var r=report.RootElement;R(r.GetProperty("input_sha256").GetString()==H(b)&&r.GetProperty("candidate_sha256").GetString()==H(c),"Manifest digests");var methods=r.GetProperty("methods");R(methods.GetArrayLength()==1&&methods[0].GetProperty("token").GetString()=="0x0600084F"&&methods[0].GetProperty("code_sha256").GetString()==H(code)&&methods[0].GetProperty("body_offset").GetInt32()==body&&methods[0].GetProperty("new_rva").GetInt32()==now.RelativeVirtualAddress,"Pinned scope/content manifest");var result=new{input_sha256=H(b),candidate_sha256=H(c),targets=1,non_target_raw_bodies_equal=non,all_old_method_slots_untouched=true,all_existing_rows_heaps_root_equal_except_one_target_rva=true,local_signatures_unchanged=true,appended_bytes=c.Length-b.Length,body_offset=body,new_root=newRoot,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(result));return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
