using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;
public enum SenarioState:int{}
public class Map {public SenarioState senarioState;}
public class BoardConfig {public Map? map;}
public class System2 {public BoardConfig? boardConfig;}
public class SwfVersion{}
public class LogException:Exception{}
public static class Debug {public static object? value;public static int count;public static int state;public static Map? map;public static bool fail;public static void Reset(Map? m=null){value=null;count=0;state=0;map=m;fail=false;}public static void Log(object? o){value=o;count++;state=map==null?0:(int)map.senarioState;if(fail)throw new LogException();}}
public static class Fixture{
 static Dictionary<string,Type> MapTypes=new(){["System2"]=typeof(System2),["BoardConfig"]=typeof(BoardConfig),["Map"]=typeof(Map),["SenarioState"]=typeof(SenarioState),["FTRuntime.SwfVersion"]=typeof(SwfVersion),["UnityEngine.Debug"]=typeof(Debug),["System.String"]=typeof(string),["System.Object"]=typeof(object),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>MapTypes.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static DynamicMethod Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,T(m.ReturnType),(m.HasThis?new[]{T(m.DeclaringType)}:Array.Empty<Type>()).Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray(),typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="missing_operation"){if(m.ReturnType.FullName!="System.Void")il.Emit(RO.Ldnull);il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="wrong_argument"&&op==RO.Ldarg_1){op=RO.Ldc_I4_0;changed=true;}
   if(mutation=="wrong_constant"&&op==RO.Ldc_I4_3){op=RO.Ldc_I4_4;changed=true;}
   if(mutation=="wrong_order"&&(op==RO.Ldc_I4_1||op==RO.Ldc_I4_3)){op=op==RO.Ldc_I4_1?RO.Ldc_I4_3:RO.Ldc_I4_1;changed=true;}
   if(mutation=="missing_log"&&a is MethodReference mr0&&mr0.Name=="Log"){il.Emit(RO.Pop);changed=true;continue;}
   if(mutation=="wrong_box_type"&&op==RO.Box){il.Emit(op,typeof(uint));changed=true;continue;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition p){il.Emit(op,(short)(p.Index+(m.HasThis?1:0)));continue;}
   if(a is MethodReference mr){var mi=T(mr.DeclaringType).GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,mr.Parameters.Select(p=>T(p.ParameterType)).ToArray(),null)??throw new Exception("Missing public method "+mr);il.Emit(op,mi);continue;}
   if(a is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}if(a is TypeReference tr){il.Emit(op,T(tr));continue;}if(a is string text){il.Emit(op,text);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation did not apply");return dm;
 }
 record Result(int Cases,List<string> Failures);
 static Result Cases(MethodDefinition m,DynamicMethod dm,List<long[]> rows,bool stop=false){var failures=new List<string>();int count=0,token=m.MetadataToken.ToInt32();void Check(bool pass,string msg){count++;if(!pass)failures.Add(msg);}object? Invoke(params object?[]args)=>dm.Invoke(null,args);
  void Throws(Type kind,params object?[]args){bool got=false;try{Invoke(args);}catch(TargetInvocationException e)when(e.InnerException?.GetType()==kind){got=true;}Check(got,"exception:"+kind.Name);}
  if(token==0x06000091){int ix=0;foreach(var r in rows){var map=new Map{senarioState=(SenarioState)r[1]};var cfg=new BoardConfig{map=map};var h=new System2{boardConfig=cfg};Debug.Reset(map);Invoke(h,(int)r[0]);Check(Debug.count==(int)r[3]&&r[2]==1&&Debug.value is int v&&v==(int)r[4]&&Debug.state==(int)r[5]&&(int)map.senarioState==(int)r[6]&&r[7]==1&&ReferenceEquals(h.boardConfig,cfg)&&ReferenceEquals(cfg.map,map),"row:"+ix++);if(stop&&failures.Count>0)return new(count,failures);}
   foreach(var h in new System2?[]{null,new(),new(){boardConfig=new()}}){Debug.Reset();Throws(typeof(NullReferenceException),h,7);Check(Debug.count==1&&Debug.value is int v&&v==7,"log-before-null");}var map2=new Map{senarioState=(SenarioState)123};var h2=new System2{boardConfig=new(){map=map2}};Debug.Reset(map2);Debug.fail=true;Throws(typeof(LogException),h2,9);Check(Debug.count==1&&Debug.value is int vv&&vv==9&&(int)map2.senarioState==123,"log-exception-before-write");Debug.fail=false;
  }else{var prior=CultureInfo.CurrentCulture;try{foreach(string culture in new[]{"","en-US","zh-CN","ar-SA"}){var ci=CultureInfo.GetCultureInfo(culture);CultureInfo.CurrentCulture=ci;foreach(var r in rows){var text=Invoke();var expected=string.Join(".",r.Skip(1).Take(3).Select(x=>((int)x).ToString(ci)));Check(text is string s&&s==expected&&r[0]==3&&r[4]==1&&r.Skip(5).All(v=>v==1)&&ReferenceEquals(CultureInfo.CurrentCulture,ci),"version-arguments-culture:"+culture);if(stop&&failures.Count>0)return new(count,failures);}}}finally{CultureInfo.CurrentCulture=prior;}}
  return new(count,failures);
 }
 public static int Main(string[] args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).GroupBy(l=>l[0]).ToDictionary(g=>g.Key,g=>g.Select(l=>l.Skip(1).Select(long.Parse).ToArray()).ToList());if(rows.Count!=2)throw new Exception("Expected2");int bad=0,errors=0,total=0;bool detected=true;var positives=new List<object>();var controls=new List<object>();foreach(var(key,rs)in rows){int token=Convert.ToInt32(key,16);var m=(MethodDefinition)a.MainModule.LookupToken(token);var result=Cases(m,Emit(m,"none"),rs);bad+=result.Failures.Count;total+=result.Cases;positives.Add(new{token=key,cases=result.Cases,failures=result.Failures});string[] mutations=token==0x06000091?new[]{"wrong_argument","missing_log","wrong_box_type"}:new[]{"wrong_constant","wrong_order"};foreach(string mut in(args.Length>3?Array.Empty<string>():new[]{"missing_operation","illegal_stack"}.Concat(mutations))){bool reject=false;string? err=null;try{reject=Cases(m,Emit(m,mut),rs,true).Failures.Count>0;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){reject=true;}catch(InvalidProgramException){reject=true;}catch(Exception e){err=e.ToString();errors++;}detected&=reject&&err==null;controls.Add(new{token=key,mutation=mut,detected=reject,tool_error=err});}}
  bool pass=bad==0&&errors==0&&detected;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=total,positive_failures=bad,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Original native callers unchanged with supplied initialized metadata/Debug class/exact format literal and recording boxing/Log/Format dependencies. Native arguments, logging-before-write and boxed constant order verified; no original allocator/logger/formatter engine execution. CLR binds public int boxing/String.Format and controlled Debug logger; checks null/throw order and cultures. No Unity/Xcode/device equivalence",positives,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
