using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;using AssemblyDefinition=Mono.Cecil.AssemblyDefinition;
static class Audit59{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
// These code locks seal the six independently native/CIL-tested bodies, not a semantic inference from a patch report.
static readonly Dictionary<int,(int length,int max,string hash)>Approved=new(){
{0x06000356,(108,4,"7ac7da33b86925463162af241314004589f14a1ce3ac9006bfaedfcad7fcd4d1")},
{0x06000408,(71,3,"f26adc7dc03b7b3740d9bd5db3f9f24f779bbf6a33f8c3f2e2d2886d2064ffaa")},
{0x0600046E,(57,3,"7a938dd38c6959e561dce12196f028872e3996a184c6e94438c5e354b740c761")},
{0x0600046F,(158,4,"ee74e5f6c74d78024fdd97b800e2ade8a172faab8b6ef274bc50614ed11494a9")},
{0x06000726,(47,4,"453333e28a357edda786476b9f832c2f248010582c8f16f702aa8ca49b639548")},
{0x06000856,(61,3,"83eda97f3b2120882ad33cecf4560731ba40608176f77e335a7ee34ea6b0f092")}};
static int Main(string[]args){try{R(args.Length==4&&!File.Exists(args[3]),"Fresh audit output");var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="6e9c634587ffad5bc3b4cf8e9c20858c770c13eed8e99498333053c0f3cb3e64"&&b.Length==c.Length,"Pinned parent/extent");using var p=new PEReader(new MemoryStream(b));using var q=new PEReader(new MemoryStream(c));R(p.GetMetadata().GetContent().SequenceEqual(q.GetMetadata().GetContent()),"All metadata bytes unchanged");using var a=AssemblyDefinition.ReadAssembly(args[0]);using var ac=AssemblyDefinition.ReadAssembly(args[1]);var allowed=new HashSet<int>();var report=JsonDocument.Parse(File.ReadAllText(args[2])).RootElement;R(report.GetProperty("input_sha256").GetString()==H(b)&&report.GetProperty("candidate_sha256").GetString()==H(c),"Report hash");var rows=report.GetProperty("methods").EnumerateArray().ToArray();R(rows.Length==6&&rows.Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).SequenceEqual(Approved.Keys),"Exact target scope");int count=0;
foreach(var m in a.MainModule.GetTypes().SelectMany(t=>t.Methods).Where(m=>m.HasBody)){var t=(MD)ac.MainModule.LookupToken(m.MetadataToken);R(t.RVA==m.RVA,"RVA unchanged");int h=Off(p,m.RVA),token=m.MetadataToken.ToInt32();if(!Approved.TryGetValue(token,out var expected)){int len=p.GetMethodBody(m.RVA).Size;R(b[h..(h+len)].SequenceEqual(c[h..(h+len)]),"Non-target raw body");count++;continue;}
R(t.Body.ExceptionHandlers.Count==0&&m.Body.ExceptionHandlers.Count==0&&t.Body.InitLocals==m.Body.InitLocals&&b[h..(h+2)].SequenceEqual(c[h..(h+2)]),"Flags/EH");R(t.Body.MaxStackSize==expected.max&&t.Body.CodeSize==expected.length&&expected.length<=m.Body.CodeSize,"Approved stack/size");var sigSource=m;R(t.Body.LocalVarToken==sigSource.Body.LocalVarToken&&t.Body.Variables.Select(v=>v.VariableType.FullName).SequenceEqual(sigSource.Body.Variables.Select(v=>v.VariableType.FullName)),"Approved immutable local signature binding");R(H(c[(h+12)..(h+12+t.Body.CodeSize)])==expected.hash,"Behavior-approved code lock");R(c[(h+12+t.Body.CodeSize)..(h+12+m.Body.CodeSize)].All(x=>x==0),"Unused slot zero");for(int i=h+2;i<h+12;i++)allowed.Add(i);for(int i=h+12;i<h+12+m.Body.CodeSize;i++)allowed.Add(i);
foreach(var i in t.Body.Instructions){if(i.Operand is IMetadataTokenProvider r&&i.Operand is FieldReference or MethodReference){R(a.MainModule.LookupToken(r.MetadataToken).ToString()==r.ToString(),"Existing exact member identity");}}
var row=rows.Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==h&&row.GetProperty("new_code_size").GetInt32()==expected.length&&row.GetProperty("new_max").GetInt32()==expected.max&&row.GetProperty("local_sig").GetInt32()==t.Body.LocalVarToken.ToInt32()&&row.GetProperty("reserved_code_size").GetInt32()==m.Body.CodeSize&&row.GetProperty("code_sha256").GetString()==expected.hash,"Report checked independently");}
R(Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).All(allowed.Contains),"Outside six bounded slots");var result=new{candidate_sha256=H(c),targets=6,non_target_raw_bodies_equal=count,entire_metadata_and_pe_outside_allowed_slots_unchanged=true,existing_member_identities_preserved=true,approved_local_signature_rebinding="All target local signatures unchanged",behavior_approved_code_locks_pass=true,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(result));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}}
