using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;
public class DependencyException:Exception{}
public class Zombie_charred{public int id;}
public static class State{
 public static List<Zombie_charred?>?zombie_Charreds;public static List<Zombie_charred?>alternate=new();public static Zombie_charred[]pool={new(){id=1},new(){id=2},new(){id=3}};
 public static int hook,eqValue,input,getCalls,logs,formatted;public static ulong trace;public static bool indexOK,listOK,concatOK;public static string fail="";public static Zombie_charred?first;
 public static Zombie_charred?ItemFor(int id)=>id==0?null:pool[id-1];
 public static void Reset(int id,int initial,int h,int eq,int firstId,int secondId){input=id;hook=h;eqValue=eq;first=ItemFor(firstId);zombie_Charreds=initial==0?null:initial==1?new():new(){first,pool[2]};alternate=new(){ItemFor(secondId),pool[0]};getCalls=logs=0;formatted=-1;trace=0;indexOK=listOK=concatOK=true;fail="";}
 public static void Event(int n){trace=(trace<<4)|(uint)n;}public static void Throw(string s){if(fail==s)throw new DependencyException();}
 public static void Mutate(int stage){if(hook==stage)zombie_Charreds=alternate;if(hook==stage+2)zombie_Charreds=null;if(hook==stage+4){alternate.Clear();zombie_Charreds=alternate;}}
 public static Zombie_charred?Item(List<Zombie_charred?>r,int index){Event(1);getCalls++;indexOK&=index==0;listOK&=ReferenceEquals(r,zombie_Charreds);Throw(getCalls==1?"first":"second");return r[index];}
 public static bool Equality(Zombie_charred?r,Zombie_charred?other){Event(2);listOK&=ReferenceEquals(r,first)&&other==null;Throw("equality");Mutate(1);return eqValue!=0;}
 public static string Format(ref int value){Event(3);formatted=value;Throw("format");return value.ToString(CultureInfo.CurrentCulture);}
 public static string Concat(string a,string b,string c){Event(4);concatOK&=a=="ID"&&b==formatted.ToString(CultureInfo.CurrentCulture)&&c=="的僵尸灰烬加载失败";return string.Concat(a,b,c);}
 public static void Log(object o){Event(5);logs++;concatOK&=Equals(o,getCalls==0?"此僵尸灰烬暂未收录":"ID0的僵尸灰烬加载失败");Throw("log");if(getCalls>0)Mutate(2);}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["Zombie_charred"]=typeof(Zombie_charred),["UnityEngine.Object"]=typeof(Zombie_charred),["ResourceManager"]=typeof(State),["System.String"]=typeof(string),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.IntPtr"]=typeof(IntPtr),["System.NullReferenceException"]=typeof(NullReferenceException)};
 static Type T(TypeReference t)=>t is GenericInstanceType g&&g.ElementType.FullName=="System.Collections.Generic.List`1"?typeof(List<>).MakeGenericType(T(g.GenericArguments.Single())):map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t);
 static Func<int,Zombie_charred?>Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,typeof(Zombie_charred),new[]{typeof(int)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";int items=0;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ldnull);il.Emit(RO.Ret);changed=true;}
  for(int k=0;k<m.Body.Instructions.Count;k++){var i=m.Body.Instructions[k];il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(operand is FieldReference f){if(f.Name!="zombie_Charreds"||op!=RO.Ldsfld)throw new Exception("Only public static fixture field allowed "+f);if(mutation=="cached_second_list"&&i.Offset is 198 or 271){il.Emit(RO.Ldloc,locals[0]);changed=true;}else il.Emit(op,typeof(State).GetField(f.Name)!);continue;}
   if(operand is MethodReference mr){if(mr.Name==".ctor"){il.Emit(op,typeof(NullReferenceException).GetConstructor(Type.EmptyTypes)!);continue;}if(mr.Name=="get_Count"){if(mutation=="zero_count"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}else il.Emit(op,typeof(List<Zombie_charred>).GetProperty("Count")!.GetMethod!);continue;}
    string name=mr.Name switch{"get_Item"=>nameof(State.Item),"op_Equality"=>nameof(State.Equality),"ToString"=>nameof(State.Format),"Concat"=>nameof(State.Concat),"Log"=>nameof(State.Log),_=>throw new Exception("Unmapped method "+mr)};
    if(mr.Name=="get_Item"&&items++==1&&mutation=="skip_second_item"){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldloc,locals[8]);changed=true;continue;}if(mr.Name=="Log"&&mutation=="skip_log"){il.Emit(RO.Pop);changed=true;continue;}if(mr.Name=="ToString"&&mutation=="wrong_format"){il.Emit(RO.Pop);il.Emit(RO.Ldstr,"1");changed=true;continue;}
    if(op!=RO.Call)throw new Exception("Dependency expected original call "+mr);il.Emit(RO.Call,typeof(State).GetMethod(name)!);if(mr.Name=="op_Equality"&&mutation=="flip_equality"){il.Emit(RO.Ldc_I4_0);il.Emit(RO.Ceq);changed=true;}continue;
   }
   if(operand is Mono.Cecil.Cil.Instruction branch){il.Emit(op,labels[branch]);continue;}if(operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(operand is Mono.Cecil.ParameterDefinition pd){il.Emit(op,(short)pd.Index);continue;}
   if(operand is string s){if(mutation=="wrong_message"&&s=="ID"){s="WRONG";changed=true;}il.Emit(op,s);continue;}if(operand is int iv){if(mutation=="index_argument"&&i.Offset is 66 or 203){il.Emit(RO.Ldarg_0);changed=true;}else il.Emit(op,iv);continue;}
   if(operand==null){if(mutation=="empty_inverted"&&op==RO.Cgt){op=RO.Clt;changed=true;}if(mutation=="return_exception"&&op==RO.Throw){op=RO.Ret;changed=true;}il.Emit(op);continue;}throw new Exception("Unsupported "+operand);
  }if(!changed)throw new Exception("Mutation did not apply "+mutation);return (Func<int,Zombie_charred?>)dm.CreateDelegate(typeof(Func<int,Zombie_charred?>));
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(Func<int,Zombie_charred?>fn,List<ulong[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();void Check(bool ok,string label){count++;if(!ok)failures.Add(label);}
  foreach(var r in rows){State.Reset(unchecked((int)r[0]),(int)r[1],(int)r[2],(int)r[3],(int)r[4],(int)r[5]);int error=0;Zombie_charred?result=null;try{result=fn(State.input);}catch(NullReferenceException){error=1;State.Event(6);}catch(ArgumentOutOfRangeException){error=2;State.Event(7);}catch(Exception e)when(e is not InvalidProgramException){error=3;}
   bool ok=State.trace==r[6]&&State.getCalls==(int)r[7]&&State.logs==(int)r[8]&&State.formatted==unchecked((int)r[9])&&error==(int)r[10]&&(result?.id??0)==(int)r[11]&&State.indexOK&&r[12]==1&&State.listOK&&r[13]==1&&State.concatOK&&r[14]==1;Check(ok,"native-row:"+index++);if(stop&&failures.Count>0)return new(count,failures);
  }
  foreach(string stage in new[]{"first","equality","format","log","second"}){State.Reset(42,2,0,1,1,2);State.fail=stage;bool got=false;try{fn(42);}catch(DependencyException){got=true;}catch(Exception e)when(e is not InvalidProgramException){}ulong expected=stage switch{"first"=>0x1UL,"equality"=>0x12UL,"format"=>0x123UL,"log"=>0x12345UL,"second"=>0x123451UL,_=>0};Check(got&&State.trace==expected&&State.indexOK&&State.listOK&&State.concatOK,"partial-exception:"+stage);}
  var culture=CultureInfo.CurrentCulture;try{foreach(string name in new[]{"en-US","de-DE","ja-JP","ar-SA"})foreach(int id in new[]{int.MinValue,-1,0,1,int.MaxValue}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(name);State.Reset(id,2,0,1,1,2);bool ok=false;try{var result=fn(id);ok=result==State.pool[0]&&State.formatted==0&&State.concatOK&&State.logs==1&&State.indexOK;}catch(Exception e)when(e is not InvalidProgramException){}Check(ok,"constant-zero-culture:"+name+":"+id);}}finally{CultureInfo.CurrentCulture=culture;}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var m=(MethodDefinition)a.MainModule.LookupToken(0x06000219);var all=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();if(all.Length!=4096||all.Any(r=>r[0]!="0x06000219"))throw new Exception("Native row set");var rows=all.Select(r=>r.Skip(1).Select(ulong.Parse).ToArray()).ToList();var result=Cases(Emit(m,"none"),rows);var controls=new List<object>();int errors=0;bool cp=true;
  foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","index_argument","skip_second_item","skip_log","wrong_format","wrong_message","empty_inverted","flip_equality","cached_second_list","zero_count","return_exception"}){bool detected=false;string?error=null;try{detected=Cases(Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}
  bool pass=result.Failures.Count==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=1,positive_cases=result.Cases,positive_failures=result.Failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Actual candidate CIL emitted with public real List.Count and indexer (recording wrapper), real Int32/String, public static resource list. Original native caller with ready class-init and recording Unity equality/formatter/log/exception dependencies. Retains input-ID-independent index-zero behavior and rereads after callbacks. No original Unity/class-init/throw engine or iOS proof. CLR comparison encoding is nondiscriminative; sites rely on native/type/byte/Clang evidence.",failures=result.Failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
