using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text;
using Mono.Cecil;
static class AuditNative36 {
 static void R(bool b,string s){if(!b)throw new Exception(s);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static byte[] Root(PEReader p)=>p.GetMetadata().GetContent().ToArray();
 static int Offset(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static (int Offset,int Size) StreamInfo(byte[] r,string name){int v=BitConverter.ToInt32(r,12),p=((16+v+3)/4)*4+2,count=BitConverter.ToUInt16(r,p);p+=2;for(int i=0;i<count;i++){int e=Array.IndexOf(r,(byte)0,p+8);if(Encoding.ASCII.GetString(r,p+8,e-p-8)==name)return(BitConverter.ToInt32(r,p),BitConverter.ToInt32(r,p+4));p=((e+1+3)/4)*4;}throw new Exception("Missing stream "+name);}
 static int Main(string[] args){try{var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="55cf8ca5de4ee0a4eefa2a36ddf3d6df86f125a73cd5769a8558ea83cde2e0ea","Pinned parent");using var pb=new PEReader(new MemoryStream(b));using var pc=new PEReader(new MemoryStream(c));var mb=pb.GetMetadataReader();var mc=pc.GetMetadataReader();var rb=Root(pb);var rc=Root(pc);using var ab=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var ac=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[1]);var report=JsonDocument.Parse(File.ReadAllText(args[2]));var targets=report.RootElement.GetProperty("methods").EnumerateArray().Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).ToHashSet();R(targets.SetEquals(new[]{0x06000822,0x06000823,0x06000824,0x06000825,0x06000826,0x06000827,0x06000858,0x06000859,0x0600085A,0x0600085B,0x0600085C,0x0600085D}),"Target cardinality");var allowed=new HashSet<int>();void Allow(int p,int n){for(int j=0;j<n;j++)allowed.Add(p+j);}var tableRows=new List<object>();
  foreach(TableIndex t in Enum.GetValues<TableIndex>()){int n=mb.GetTableRowCount(t);int delta=t==TableIndex.TypeRef||t==TableIndex.MemberRef?1:t==TableIndex.MethodSpec?2:0;R(mc.GetTableRowCount(t)==n+delta,"Table count "+t);if(n==0)continue;int size=mb.GetTableRowSize(t);R(size==mc.GetTableRowSize(t),"Row width "+t);int x=mb.GetTableMetadataOffset(t),y=mc.GetTableMetadataOffset(t);R(rb[x..(x+n*size)].SequenceEqual(rc[y..(y+n*size)]),"Existing row drift "+t);tableRows.Add(new{table=t.ToString(),rows=n,row_size=size});}
  var sb=StreamInfo(rb,"#Strings");var sc=StreamInfo(rc,"#Strings");byte[] oldStrings=rb[sb.Offset..(sb.Offset+sb.Size)];var expectedNames=new List<byte>();foreach(string name in new[]{"Interlocked","System.Threading","CompareExchange"}){byte[] v=Encoding.UTF8.GetBytes(name+"\0");if(!Enumerable.Range(0,Math.Max(0,oldStrings.Length-v.Length+1)).Any(i=>oldStrings[i..(i+v.Length)].SequenceEqual(v)))expectedNames.AddRange(v);}int stringDelta=expectedNames.Count;R(sc.Size==sb.Size+stringDelta&&oldStrings.SequenceEqual(rc[sc.Offset..(sc.Offset+sb.Size)])&&expectedNames.SequenceEqual(rc[(sc.Offset+sb.Size)..(sc.Offset+sc.Size)]),"Only approved string names appended");
  var bb=StreamInfo(rb,"#Blob");var bc=StreamInfo(rc,"#Blob");var expectedBlob=new List<byte>();void AddBlob(byte[] v){R(v.Length<128,"Short new signature");expectedBlob.Add((byte)v.Length);expectedBlob.AddRange(v);}AddBlob(new byte[]{0x10,1,3,0x1e,0,0x10,0x1e,0,0x1e,0,0x1e,0});foreach(string name in new[]{"System.Action`1<FTRuntime.SwfClip>","System.Action`1<FTRuntime.SwfClipController>"}){int rid=Enumerable.Range(1,mb.GetTableRowCount(TableIndex.TypeSpec)).Single(i=>ab.MainModule.LookupToken(0x1B000000+i) is Mono.Cecil.TypeReference t&&t.FullName==name);AddBlob(new byte[]{0x0a,1}.Concat(mb.GetBlobBytes(mb.GetTypeSpecification(MetadataTokens.TypeSpecificationHandle(rid)).Signature)).ToArray());}R(bc.Size==bb.Size+expectedBlob.Count&&rb[bb.Offset..(bb.Offset+bb.Size)].SequenceEqual(rc[bc.Offset..(bc.Offset+bb.Size)])&&expectedBlob.SequenceEqual(rc[(bc.Offset+bb.Size)..(bc.Offset+bc.Size)]),"Only approved generic signature blobs appended");
  foreach(HeapIndex h in new[]{HeapIndex.UserString,HeapIndex.Guid}){int n=mb.GetHeapSize(h),x=mb.GetHeapMetadataOffset(h),y=mc.GetHeapMetadataOffset(h);R(mc.GetHeapSize(h)==n&&rb[x..(x+n)].SequenceEqual(rc[y..(y+n)]),"Unchanged heap "+h);}
  int vlen=BitConverter.ToInt32(rb,12),head=((16+vlen+3)/4)*4+4;R(rb[..head].SequenceEqual(rc[..head]),"Metadata root version/flags/stream count");var tb=StreamInfo(rb,"#~");var tc=StreamInfo(rc,"#~");R(rb[tb.Offset..(tb.Offset+16)].SequenceEqual(rc[tc.Offset..(tc.Offset+16)]),"Table header widths/versions/valid mask");ulong sorted=BitConverter.ToUInt64(rb,tb.Offset+16),mask=(1UL<<(int)TableIndex.TypeRef)|(1UL<<(int)TableIndex.MemberRef)|(1UL<<(int)TableIndex.MethodSpec);R(BitConverter.ToUInt64(rc,tc.Offset+16)==(sorted&~mask),"Only approved sorted bits cleared");
  int non=0;foreach(var h in mb.MethodDefinitions){int token=MetadataTokens.GetToken(h);var bm=mb.GetMethodDefinition(h);var cm=mc.GetMethodDefinition(h);R(bm.RelativeVirtualAddress==cm.RelativeVirtualAddress,"RVA drift");if(bm.RelativeVirtualAddress==0)continue;var ob=pb.GetMethodBody(bm.RelativeVirtualAddress);var nb=pc.GetMethodBody(cm.RelativeVirtualAddress);int off=Offset(pb,bm.RelativeVirtualAddress);if(targets.Contains(token)){R(ob.LocalSignature==nb.LocalSignature&&ob.LocalVariablesInitialized==nb.LocalVariablesInitialized&&ob.ExceptionRegions.Length==0&&nb.ExceptionRegions.Length==0,"Target local/header flags");var row=report.RootElement.GetProperty("methods").EnumerateArray().Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==off,"Pinned body offset");Allow(off+2,6);Allow(off+12,ob.GetILBytes()!.Length);var md=(Mono.Cecil.MethodDefinition)ac.MainModule.LookupToken(token);R(md.Body.Instructions.All(i=>i.Operand is not Mono.Cecil.Cil.Instruction j||md.Body.Instructions.Contains(j)),"Invalid branch");R(!md.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Ldstr&&i.Operand is string s&&(s.Contains("Indirect call:")||s.Contains("Warning:"))),"Unresolved reconstruction");R(H(nb.GetILBytes()!)==row.GetProperty("code_sha256").GetString(),"Reopened code digest");}else{R(ob.Size==nb.Size,"Non-target size");R(b[off..(off+ob.Size)].SequenceEqual(c[off..(off+nb.Size)]),"Non-target raw body "+token.ToString("X8"));non++;}}
  var pe=pb.PEHeaders;int lastHeader=pe.PEHeaderStartOffset+pe.CoffHeader.SizeOfOptionalHeader+(pe.CoffHeader.NumberOfSections-1)*40;Allow(lastHeader+8,4);Allow(lastHeader+16,4);Allow(pe.PEHeaderStartOffset+8,4);Allow(pe.PEHeaderStartOffset+56,4);Allow(pe.PEHeaderStartOffset+64,4);Allow(pe.CorHeaderStartOffset+8,8);var diffs=Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).ToArray();R(diffs.All(allowed.Contains),"Unapproved original-file difference");R(pc.PEHeaders.SectionHeaders.Length==pb.PEHeaders.SectionHeaders.Length,"Section count");for(int i=0;i<pb.PEHeaders.SectionHeaders.Length-1;i++)R(pb.PEHeaders.SectionHeaders[i].Equals(pc.PEHeaders.SectionHeaders[i]),"Original PE section changed");var tr=(Mono.Cecil.TypeReference)ac.MainModule.LookupToken(0x010000B1);R(tr.FullName=="System.Threading.Interlocked"&&tr.Scope is AssemblyNameReference core&&core.Name=="mscorlib","Interlocked public core reference");var mr=(MethodReference)ac.MainModule.LookupToken(0x0A000404);R(mr.FullName=="!!0 System.Threading.Interlocked::CompareExchange(!!0&,!!0,!!0)"&&!mr.HasThis&&mr.GenericParameters.Count==1&&mr.Parameters.Count==3,"Generic public atomic signature");var added=new List<object>();foreach(var(token,arg)in new[]{(0x2B0000B5,"System.Action`1<FTRuntime.SwfClip>"),(0x2B0000B6,"System.Action`1<FTRuntime.SwfClipController>")}){var m=(GenericInstanceMethod)ac.MainModule.LookupToken(token);R(m.ElementMethod.MetadataToken.ToInt32()==0x0A000404&&m.GenericArguments.Count==1&&m.GenericArguments[0].FullName==arg,"Closed atomic MethodSpec");added.Add(new{token=$"0x{token:X8}",name=m.FullName});}
  var ns=pc.PEHeaders.SectionHeaders.Last();var os=pb.PEHeaders.SectionHeaders.Last();R(ns.Name==".n29meta"&&ns.Name==os.Name&&ns.PointerToRawData==os.PointerToRawData&&ns.VirtualAddress==os.VirtualAddress&&ns.SectionCharacteristics==os.SectionCharacteristics&&ns.PointerToRelocations==os.PointerToRelocations&&ns.PointerToLineNumbers==os.PointerToLineNumbers&&ns.NumberOfRelocations==os.NumberOfRelocations&&ns.NumberOfLineNumbers==os.NumberOfLineNumbers,"Extended section identity");int rootRva=pc.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress,metaSize=pc.PEHeaders.CorHeader.MetadataDirectory.Size,raw=Offset(pc,rootRva);R(raw==b.Length&&ns.VirtualSize==raw-ns.PointerToRawData+metaSize&&c.Length==ns.PointerToRawData+ns.SizeOfRawData&&c[(raw+metaSize)..].All(z=>z==0),"Appended metadata root extent and padding");R(pc.PEHeaders.PEHeader!.SizeOfInitializedData==pb.PEHeaders.PEHeader!.SizeOfInitializedData+c.Length-b.Length,"Initialized data increment");R(pc.PEHeaders.PEHeader.SizeOfImage==((ns.VirtualAddress+ns.VirtualSize+pc.PEHeaders.PEHeader.SectionAlignment-1)/pc.PEHeaders.PEHeader.SectionAlignment)*pc.PEHeaders.PEHeader.SectionAlignment,"SizeOfImage extent");
  var r=new{input_sha256=H(b),candidate_sha256=H(c),targets=targets.Count,non_target_raw_bodies_equal=non,existing_table_rows_equal=tableRows,existing_heap_prefixes_equal=true,string_heap_added_bytes=stringDelta,blob_heap_added_bytes=expectedBlob.Count,original_section_locations_equal=true,non_metadata_sections_equal=true,metadata_section_extended=true,old_file_changed_bytes=diffs.Length,appended_bytes=c.Length-b.Length,new_member_refs=added,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{r.targets,r.non_target_raw_bodies_equal,r.old_file_changed_bytes,r.appended_bytes,r.pass}));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
