using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher55{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int token){O(op);b.AddRange(BitConverter.GetBytes(token));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="820e030be1a7f1f64ffcc8d73fa3c11b9daedfb95c0981f9f46f3f818d333c52","Pinned Native54");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x060000CD,0x060000DD,0x0600013B,0x06000390,0x060003F5,0x06000532,0x06000568,0x060005B8,0x06000632,0x0600066A}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis==(token!=0x0600013B)&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<FieldReference>().First(f=>f.DeclaringType.FullName==owner&&f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);MethodReference exact(string name)=>a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName==name);FieldReference vf(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(r=>r.FullName=="System.Single UnityEngine.Vector3::"+name);int sig=m.Body.LocalVarToken.ToInt32(),max=2;
switch(token){
case 0x060000CD:{max=3;il.O(3,2);il.Ref(0x28,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x28,call("AudioVolume"));il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26,0x2a);break;}
case 0x060000DD:{max=2;il.O(2);il.Ref(0x7b,field("AttackRange","rangeType"));il.O(0x25);il.Br(0x2c,"none");il.O(0x18);il.Br(0x2e,"circle");il.O(3,0x2a);il.Label("circle");il.O(2,3);il.Ref(0x28,call("RestraintTargetPosition_Circle"));il.O(0x2a);il.Label("none");il.O(0x26,2);il.Ref(0x7b,field("AttackRange","plant"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.O(0x2a);break;}
case 0x0600013B:{max=4;il.O(2);il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x28,call("AudioVolume"));il.F(1);il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x2a);break;}
case 0x06000390:{max=2;il.O(2);il.Ref(0x28,call("PC_SSI_TrySummon"));il.O(2);il.Ref(0x7b,field("Plant","skill"));il.Ref(0x7b,field("Skill","chargedLayer"));il.O(0x17);il.Br(0x2f,"end");il.O(2);il.Ref(0x7b,field("Plant","buffManager"));var st=m.Body.Instructions.Single(i=>i.OpCode.Name=="ldstr"&&(string)i.Operand=="SSI_Characteristic_Atk");il.Token(0x72,st.Operand is string?BitConverter.ToInt32(b,Off(pe,m.RVA)+12+st.Offset+1):0);il.Ref(0x6f,call("FindStatsIncreased"));il.O(0x13,4,0x11,4);il.Br(0x2c,"end");il.O(0x11,4);il.F(0);il.Ref(0x7d,field("StatsIncreased","value"));il.O(0x2a);il.Label("end");il.O(0x2a);break;}
case 0x060003F5:{max=2;il.O(2,0x1d);il.Ref(0x7d,field("Projectile","movementTracks"));il.O(2,3);il.Ref(0x7d,field("Projectile","index"));il.O(2);il.Ref(0x28,exact("UnityEngine.Vector3 UnityEngine.Vector3::get_zero()"));il.Ref(0x7d,field("Projectile","speed"));il.O(2,4);il.Ref(0x7d,field("Projectile","maxLivingTime"));il.O(2);il.F(0);il.Ref(0x7d,field("Projectile","livingTime"));il.O(0x2a);break;}
case 0x06000532:case 0x06000632:{max=3;string owner=m.DeclaringType.FullName;il.O(2);il.Ref(0x7b,field(owner,"button"));il.Ref(0x7b,field("UnityEngine.UI.Selectable","m_Interactable"));il.Br(0x2c,"end");il.O(3);il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"end");il.O(3);il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x28,call("AudioVolume"));il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26);il.Label("end");il.O(0x2a);break;}
case 0x06000568:case 0x060005B8:{max=5;string owner=m.DeclaringType.FullName,portrait=token==0x06000568?"devicePortrait":"zombiePortrait";il.O(2);il.Ref(0x7b,field(owner,"questionMark"));il.Ref(0x6f,call("get_gameObject"));il.O(3,0x16,0xfe,1);il.Ref(0x6f,call("SetActive"));il.O(3);il.Br(0x2d,"white");il.O(2);il.Ref(0x7b,field(owner,portrait));il.F(0);il.F(0);il.F(0);il.F(1);il.Ref(0x73,exact("System.Void UnityEngine.Color::.ctor(System.Single,System.Single,System.Single,System.Single)"));il.Ref(0x6f,call("set_color"));il.O(2);il.Ref(0x7b,field(owner,"button"));il.O(0x16);il.Ref(0x6f,call("set_enabled"));il.O(0x2a);il.Label("white");il.O(2);il.Ref(0x7b,field(owner,portrait));for(int j=0;j<4;j++)il.F(1);il.Ref(0x73,exact("System.Void UnityEngine.Color::.ctor(System.Single,System.Single,System.Single,System.Single)"));il.Ref(0x6f,call("set_color"));il.O(2);il.Ref(0x7b,field(owner,"button"));il.O(0x17);il.Ref(0x6f,call("set_enabled"));il.O(0x2a);break;}
case 0x0600066A:{max=4;il.O(2);il.Ref(0x7b,field("Plant_DetaiPage","plant"));il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"end");il.O(2);il.Ref(0x7b,field("Plant_DetaiPage","plant"));il.Ref(0x6f,m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().Single(r=>r.DeclaringType.FullName=="UnityEngine.Component"&&r.Name=="get_transform"));il.Ref(0x6f,call("get_position"));il.O(0x13,4,0x11,4);il.Ref(0x7b,vf("y"));il.F(30);il.O(0x58,0x13,6,2);il.Ref(0x7b,field("Plant_DetaiPage","skill"));il.Ref(0x6f,m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().Single(r=>r.DeclaringType.FullName=="UnityEngine.GameObject"&&r.Name=="get_transform"));il.O(0x11,4);il.Ref(0x7b,vf("x"));il.O(0x11,6);il.F(0);il.Ref(0x73,exact("System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)"));il.Ref(0x6f,call("set_position"));il.Label("end");il.O(0x2a);break;}
}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot");int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
