using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;
public enum Camp:int{}public enum DamageAttribute:int{}
public struct Vector3 {public float x,y,z;}
public class DependencyException:Exception{}
public class Transform {public Vector3 scale;public Vector3 localScale{get{State.scaleCalls++;if(State.failScale)throw new DependencyException();return scale;}}}
public class Component {public Transform? transform{get{State.getterCalls++;State.receiverOK&=ReferenceEquals(this,State.zombie);State.Hook?.Invoke();return State.transform;}}}
public class Zombie:Component {public int ID;public int marker;}
public class Damage {public float damagePoint;public Camp camp;public DamageAttribute damageAttribute;public bool acrossArmor1,acrossArmor2,oppositeDirection,anti_air_able,anti_ground_able,anti_submarine_able,noResidue,alloff;public int marker;}
public class Holder {public Damage? value;}
public static class State {public static Zombie? zombie;public static Transform? transform;public static int getterCalls,scaleCalls;public static bool receiverOK,failScale;public static Action? Hook;public static void Reset(Zombie? z,Transform? t){zombie=z;transform=t;getterCalls=scaleCalls=0;receiverOK=true;failScale=false;Hook=null;}}
public delegate void Change(Zombie? z,ref Damage? d,int attack,int state);
public static class Fixture{
 static Dictionary<string,Type> Map=new(){["Zombie"]=typeof(Zombie),["Damage"]=typeof(Damage),["Camp"]=typeof(Camp),["DamageAttribute"]=typeof(DamageAttribute),["UnityEngine.Vector3"]=typeof(Vector3),["UnityEngine.Component"]=typeof(Component),["UnityEngine.Transform"]=typeof(Transform),["System.Object"]=typeof(object),["System.Int32"]=typeof(int),["System.Single"]=typeof(float),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>t is ByReferenceType b?T(b.ElementType).MakeByRefType():Map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static Change Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{typeof(Zombie),typeof(Damage).MakeByRefType(),typeof(int),typeof(int)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var tmp=il.DeclareLocal(typeof(bool));var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="missing_operation"){il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="wrong_id"&&a is FieldReference f0&&f0.Name=="ID"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_3);changed=true;continue;}
   if(mutation=="wrong_attack_guard"&&op==RO.Blt){op=RO.Bge;changed=true;}
   if(mutation=="swap_direction"&&(op==RO.Cgt||op==RO.Clt)){op=op==RO.Cgt?RO.Clt:RO.Cgt;changed=true;}
   if(mutation=="missing_flag"&&op==RO.Ldc_I4_1&&i.Next?.Operand is FieldReference){op=RO.Ldc_I4_0;changed=true;}
   if(mutation=="wrong_camp"&&op==RO.Ldc_I4_0&&i.Next?.Operand is FieldReference fc&&fc.Name=="camp"){op=RO.Ldc_I4_1;changed=true;}
   if(mutation=="reread_ref"&&op==RO.Stfld&&a is FieldReference fd&&fd.Name=="oppositeDirection"&&i.Previous?.OpCode.Code is Mono.Cecil.Cil.Code.Cgt or Mono.Cecil.Cil.Code.Clt){il.Emit(RO.Stloc,tmp);il.Emit(RO.Pop);il.Emit(RO.Ldarg_1);il.Emit(RO.Ldind_Ref);il.Emit(RO.Ldloc,tmp);changed=true;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition p){il.Emit(op,(short)(p.Index+1));continue;}
   if(a is MethodReference mr){var mi=T(mr.DeclaringType).GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,mr.Parameters.Select(p=>T(p.ParameterType)).ToArray(),null)??throw new Exception("Missing public method "+mr);il.Emit(op,mi);continue;}
   if(a is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation did not apply");return(Change)dm.CreateDelegate(typeof(Change));
 }
 static void Flags(Damage d,int v){d.acrossArmor1=(v&1)!=0;d.acrossArmor2=(v&2)!=0;d.oppositeDirection=(v&4)!=0;d.anti_air_able=(v&8)!=0;d.anti_ground_able=(v&16)!=0;d.anti_submarine_able=(v&32)!=0;d.noResidue=(v&64)!=0;d.alloff=(v&128)!=0;}
 static int Flags(Damage d)=>(d.acrossArmor1?1:0)|(d.acrossArmor2?2:0)|(d.oppositeDirection?4:0)|(d.anti_air_able?8:0)|(d.anti_ground_able?16:0)|(d.anti_submarine_able?32:0)|(d.noResidue?64:0)|(d.alloff?128:0);
 record Result(int Cases,List<string> Failures);
 static Result Cases(Change fn,List<long[]>rows,bool stop=false){var failures=new List<string>();int count=0,ix=0;void Check(bool pass,string msg){count++;if(!pass)failures.Add(msg);}void Throws(Type kind,Zombie?z,Holder h,int a,int b){bool got=false;try{fn(z,ref h.value,a,b);}catch(Exception e)when(e.GetType()==kind){got=true;}Check(got,"exception:"+kind.Name);}
  foreach(var r in rows){var z=new Zombie{ID=(int)r[0],marker=987};var t=new Transform{scale=new Vector3{x=BitConverter.Int32BitsToSingle(unchecked((int)r[3])),y=3,z=4}};var d=new Damage{camp=(Camp)r[6],damageAttribute=(DamageAttribute)r[7],damagePoint=BitConverter.Int32BitsToSingle(0x7fc01234),marker=123};Flags(d,(int)r[8]);var alt=new Damage{camp=(Camp)778,damageAttribute=(DamageAttribute)889,marker=456,damagePoint=7};Flags(alt,0xAA);var h=new Holder{value=r[4]!=0?d:null};State.Reset(z,t);if(r[5]!=0)State.Hook=()=>h.value=alt;bool match=false;try{fn(z,ref h.value,(int)r[1],(int)r[2]);match=(int)d.camp==(int)r[9]&&(int)d.damageAttribute==(int)r[10]&&Flags(d)==(int)r[11]&&State.getterCalls==(int)r[12]&&State.scaleCalls==(int)r[13]&&ReferenceEquals(h.value,r[14]!=0?alt:r[4]!=0?d:null)&&alt.marker==456&&(int)alt.camp==778&&(int)alt.damageAttribute==889&&Flags(alt)==0xAA&&alt.damagePoint==7&&d.marker==123&&BitConverter.SingleToInt32Bits(d.damagePoint)==0x7fc01234&&z.ID==(int)r[0]&&z.marker==987&&t.scale.y==3&&t.scale.z==4&&unchecked((uint)BitConverter.SingleToInt32Bits(t.scale.x))==(uint)r[3]&&r.Skip(15).All(v=>v==1)&&State.receiverOK;}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"row:"+ix++);if(stop&&failures.Count>0)return new(count,failures);}
  var holder=new Holder{value=new()};State.Reset(null,new());Throws(typeof(NullReferenceException),null,holder,0,0);Check(State.getterCalls==0,"null-this-before-engine");
  foreach(int id in new[]{3,11,16,17,18,13,6}){var z=new Zombie{ID=id};State.Reset(z,new());var h=new Holder();Throws(typeof(NullReferenceException),z,h,0,0);int calls=id==13||id==6?1:0;Check(State.getterCalls==calls&&State.scaleCalls==calls,"null-damage-order:"+id);}
  foreach(int id in new[]{13,6}){var z=new Zombie{ID=id};var h=new Holder{value=new(){marker=1}};State.Reset(z,null);Throws(typeof(NullReferenceException),z,h,0,0);Check(State.getterCalls==1&&State.scaleCalls==0&&h.value.marker==1,"null-transform-order");State.Reset(z,new());State.failScale=true;Throws(typeof(DependencyException),z,h,0,0);Check(State.getterCalls==1&&State.scaleCalls==1&&h.value.marker==1,"dependency-exception-order");}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var m=(MethodDefinition)a.MainModule.LookupToken(0x06000447);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();if(rows.Any(r=>r[0]!="0x06000447"))throw new Exception("Scope");var values=rows.Select(r=>r.Skip(1).Select(long.Parse).ToArray()).ToList();var result=Cases(Emit(m,"none"),values);int errors=0;bool detected=true;var controls=new List<object>();foreach(string mut in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","missing_operation","wrong_id","wrong_attack_guard","swap_direction","missing_flag","wrong_camp","reread_ref"}){bool reject=false;string?err=null;try{reject=Cases(Emit(m,mut),values,true).Failures.Count>0;}catch(InvalidProgramException){reject=true;}catch(Exception e){err=e.ToString();errors++;}detected&=reject&&err==null;controls.Add(new{mutation=mut,detected=reject,tool_error=err});}bool pass=result.Failures.Count==0&&errors==0&&detected;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=1,positive_cases=result.Cases,positive_failures=result.Failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Original GetDamageType dispatch/body/jump table unchanged; transform/scale recording doubles with optional ref-slot mutation. CLR executes actual candidate IL through typed ref Damage delegate/public fixture fields and APIs; ID/signed gates/NaNs/flags/camp/ref alias/order/exceptions tested. No original Unity transform/throw engine or whole-game/iOS proof",failures=result.Failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
