using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher56{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int t){O(op);b.AddRange(BitConverter.GetBytes(t));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public void L(byte n)=>O(0x11,n);public void S(byte n)=>O(0x13,n);public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="c329074e4f3de510d8b7a3dfd22bade3178578a159846acc6b9eb26389770a73","Pinned Native55a");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x060000EC,0x06000331,0x060003C7,0x060003CB,0x060003D4,0x060003D7,0x060003FB,0x06000482,0x0600066E,0x0600067C}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>a.MainModule.GetTypes().Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);MethodReference exact(string name)=>a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName==name);FieldReference vf(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(r=>r.FullName=="System.Single UnityEngine.Vector3::"+name);
void Load(string owner,string name){il.O(2);il.Ref(0x7b,field(owner,name));}void StoreFloat(string owner,string name,float value){il.O(2);il.F(value);il.Ref(0x7d,field(owner,name));}void V3()=>il.Ref(0x73,exact("System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)"));void GetShadow(string owner){Load(owner,"shadow");il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));}void VecPart(byte local,string part){il.L(local);il.Ref(0x7b,vf(part));}void String(string value){var i=m.Body.Instructions.Single(i=>i.OpCode.Name=="ldstr"&&i.Operand is string s&&s==value);il.Token(0x72,BitConverter.ToInt32(b,Off(pe,m.RVA)+12+i.Offset+1));}
int sig=m.Body.LocalVarToken.ToInt32(),max=3;
switch(token){
case 0x060000EC:{max=4;sig=((MD)a.MainModule.LookupToken(0x060003D4)).Body.LocalVarToken.ToInt32();il.O(3);il.Ref(0x6f,call("get_transform"));Load("Banks","cardList_Gameobject");il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));il.O(0x16);il.Ref(0x6f,call("SetParent"));il.O(4,0x6b);il.F(92);il.O(0x5a);il.F(677);il.O(0x59);il.S(7);il.O(3);il.Ref(0x6f,call("get_gameObject"));il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));il.L(7);il.F(22);il.F(0);V3();il.Ref(0x6f,call("set_localPosition"));il.O(0x2a);break;}
case 0x06000331:{max=5;il.O(3);GetShadow("Device");il.Ref(0x6f,call("get_position"));il.Ref(0x28,exact("UnityEngine.Vector3 UnityEngine.Vector3::op_Subtraction(UnityEngine.Vector3,UnityEngine.Vector3)"));il.S(6);il.O(2);il.Ref(0x28,exact("UnityEngine.Transform UnityEngine.Component::get_transform()"));il.O(0x0c,0x08);il.Ref(0x6f,call("get_position"));il.S(8);il.O(0x08);VecPart(6,"x");VecPart(8,"x");il.O(0x58);VecPart(8,"y");VecPart(6,"y");il.O(0x58);VecPart(8,"z");VecPart(6,"z");il.O(0x58);V3();il.Ref(0x6f,call("set_position"));foreach(string part in new[]{"x","y"}){il.O(2);GetShadow("Device");il.Ref(0x6f,call("get_position"));il.Ref(0x7b,vf(part));il.Ref(0x7d,field("Device",part=="x"?"fX":"fY"));}il.O(0x2a);break;}
case 0x060003C7:{max=5;Load("Project","flickeringTime");il.Ref(0x28,call("get_deltaTime"));il.O(0x58);il.S(1);il.O(2);il.L(1);il.Ref(0x7d,field("Project","flickeringTime"));il.L(1);il.F(0.7f);il.Br(0x36,"color");StoreFloat("Project","flickeringTime",0);il.Label("color");il.F(1);Load("Project","flickeringTime");il.F(0.35f);il.O(0x59);il.Ref(0x28,exact("System.Single UnityEngine.Mathf::Abs(System.Single)"));il.F(0.35f);il.O(0x5b);il.F(0.6863f);il.O(0x5a,0x59);il.S(1);Load("Project","animationSprites");il.O(0x16);il.Ref(0x6f,call("get_Item"));il.Ref(0x6f,call("GetComponent"));il.L(1);il.L(1);il.L(1);il.F(1);il.Ref(0x73,exact("System.Void UnityEngine.Color::.ctor(System.Single,System.Single,System.Single,System.Single)"));il.Ref(0x6f,call("set_color"));il.O(0x2a);break;}
case 0x060003CB:{max=4;il.F(0);il.S(2);il.F(0);il.S(6);il.F(0);il.S(4);Load("Project","movementTracks");il.Br(0x2d,"set");il.F(-540);il.F(400);il.Ref(0x28,call("Range"));il.S(2);il.F(330);il.F(360);il.Ref(0x28,call("Range"));il.S(6);il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_orthographicSize"));il.F(540);il.O(0x5b);il.S(4);il.L(2);il.L(4);il.O(0x5a);il.S(2);il.L(6);il.L(4);il.O(0x5a);il.S(6);il.L(4);il.F(0);il.O(0x5a);il.S(4);il.Label("set");il.O(2);il.Ref(0x28,call("get_transform"));il.L(2);il.L(6);il.L(4);V3();il.Ref(0x6f,call("set_position"));il.O(0x2a);break;}
case 0x060003D4:{max=3;foreach(string name in new[]{"fW","fD"}){Load("Projectile",name);il.F(40);il.O(0x5b);il.F(1.425f);il.O(0x5a);}il.F(0);V3();il.S(3);GetShadow("Projectile");il.L(3);il.Ref(0x6f,call("set_localScale"));Load("Projectile","shadow");il.O(0x14);il.Ref(0x28,call("op_Inequality"));il.Br(0x2c,"end");GetShadow("Projectile");il.Ref(0x6f,call("get_localPosition"));il.S(3);il.O(0x12,3);Load("Projectile","fZ_shadow");il.Ref(0x7d,vf("y"));GetShadow("Projectile");il.L(3);il.Ref(0x6f,call("set_localPosition"));il.Label("end");il.O(0x2a);break;}
case 0x060003D7:{max=2;foreach(string name in new[]{"track","projectileSprite"}){Load("Projectile",name);il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"end");}Load("Projectile","track");il.Ref(0x6f,call("get_transform"));Load("Projectile","projectileSprite");il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x6f,call("set_position"));il.Label("end");il.O(0x2a);break;}
case 0x060003FB:{max=3;Load("Projectile","fZ");il.F(1200);il.Br(0x2f,"fall");il.O(2);il.Ref(0x28,call("TestOutofMap"));il.Br(0x2c,"end");il.Label("fall");il.O(2);il.F(0);il.F(-90);il.Ref(0x28,call("SetEulerAngles"));il.O(2);il.Ref(0x28,exact("UnityEngine.Vector3 UnityEngine.Vector3::get_zero()"));il.Ref(0x7d,field("Projectile","speed"));StoreFloat("Projectile","zSpeed",-3000);StoreFloat("Projectile","zAcceleration",0);foreach(string part in new[]{"x","y"}){il.O(2);Load("Projectile","targetPosition");il.Ref(0x7b,vf(part));il.Ref(0x7d,field("Projectile",part=="x"?"fX":"fY"));}StoreFloat("Projectile","fZ",1190);il.Label("end");il.O(0x2a);break;}
case 0x06000482:{max=3;Load("Zombie","targetPlant");il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"continue");Load("Zombie","targetPlant");il.O(2,0x16);il.Ref(0x6f,call("BlockZombie"));il.Label("continue");Load("Zombie","animator");String("isAttacking");il.O(0x16);il.Ref(0x6f,call("SetBool"));il.O(2);il.Ref(0x28,call("GetMoveDirection"));il.O(0x0d,2,0x09);il.Ref(0x28,call("SetrSpeed"));il.O(2);il.Ref(0x28,call("ResetMoveSpeed"));il.O(2,0x16);il.Ref(0x7d,field("Zombie","isEat"));il.O(0x2a);break;}
case 0x0600066E:{max=3;il.O(0x14,0x0d);Load("Popup","P");il.O(0x25,0x17);il.Br(0x2e,"one");il.O(0x19);il.Br(0x33,"after");il.Br(0x2b,"get");il.Label("one");il.O(0x26);il.Label("get");il.Ref(0x7e,field("ResourceManager","zombieClips"));il.O(0x1f,9);il.Ref(0x6f,call("get_Item"));il.O(0x0d);il.Label("after");il.O(0x09,0x14);il.Ref(0x28,call("op_Inequality"));il.Br(0x2c,"end");il.O(0x09);il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26);il.Label("end");il.O(0x2a);break;}
case 0x0600067C:{max=3;il.Ref(0x7e,field("ResourceManager","buttonClips"));il.O(0x16);il.Ref(0x6f,call("get_Item"));il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"end");il.Ref(0x7e,field("ResourceManager","buttonClips"));il.O(0x16);il.Ref(0x6f,call("get_Item"));il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x28,call("AudioVolume"));il.Ref(0x28,call("PlayClipAtPoint"));il.Label("end");il.O(0x2a);break;}
}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot "+m.FullName+" "+code.Length+"/"+m.Body.CodeSize);int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
