using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

if(args.Length!=2){Console.Error.WriteLine("Usage: Stage9MapImmediatePatch <input.dll> <output.dll>");return 2;}
const string ExpectedInputSha="1c62f969409ed16c9d7c7855f7b52e6b593701524e2b2d75ec0affbc3d05b209";
const int ExpectedMethods=2317, ExpectedFields=2802;
const uint TokCopy=0x06000285, TokGetX=0x06000289, TokGetY=0x0600028A;
static IEnumerable<TypeDefinition> AllTypes(IEnumerable<TypeDefinition> roots){foreach(var t in roots){yield return t;foreach(var n in AllTypes(t.NestedTypes))yield return n;}}
static uint Raw(IMetadataTokenProvider p)=>p.MetadataToken.ToUInt32();
static string Sha(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p))).ToLowerInvariant();
static string ScopeName(TypeReference t)=>t.Scope switch{AssemblyNameReference a=>a.Name,ModuleDefinition m=>m.Assembly?.Name?.Name??m.Name,ModuleReference mr=>mr.Name,_=>t.Scope?.ToString()??"<null>"};
static string TypeSig(TypeReference t)=>$"{t.FullName}@{ScopeName(t)}";
static string OperandSig(object? o,MethodDefinition owner){if(o is null)return"";if(o is Instruction i)return$"I#{owner.Body.Instructions.IndexOf(i)}";if(o is Instruction[] sw)return"SW["+string.Join(',',sw.Select(i=>owner.Body.Instructions.IndexOf(i)))+"]";if(o is MethodReference mr)return$"M:{mr.FullName}@{ScopeName(mr.DeclaringType)}";if(o is FieldReference fr)return$"F:{fr.FullName}@{ScopeName(fr.DeclaringType)}";if(o is TypeReference tr)return$"T:{TypeSig(tr)}";if(o is VariableDefinition vr)return$"V:{vr.Index}:{TypeSig(vr.VariableType)}";if(o is ParameterDefinition pr)return$"P:{pr.Index}:{TypeSig(pr.ParameterType)}";if(o is string s)return"S:"+Convert.ToBase64String(Encoding.UTF8.GetBytes(s));return"C:"+Convert.ToString(o,CultureInfo.InvariantCulture);}
static string MethodSemantic(MethodDefinition m){var sb=new StringBuilder();sb.Append(m.FullName).Append('|').Append(m.Attributes).Append('|').Append(m.ImplAttributes).Append('|');if(!m.HasBody)return sb.Append("NOBODY").ToString();sb.Append("init=").Append(m.Body.InitLocals).Append(";max=").Append(m.Body.MaxStackSize).Append(';');foreach(var v in m.Body.Variables)sb.Append("L:").Append(v.Index).Append(':').Append(TypeSig(v.VariableType)).Append(';');foreach(var i in m.Body.Instructions)sb.Append("I:").Append(i.OpCode.Code).Append(':').Append(OperandSig(i.Operand,m)).Append(';');foreach(var h in m.Body.ExceptionHandlers){int Idx(Instruction? x)=>x is null?-1:m.Body.Instructions.IndexOf(x);sb.Append("EH:").Append(h.HandlerType).Append(':').Append(Idx(h.TryStart)).Append(':').Append(Idx(h.TryEnd)).Append(':').Append(Idx(h.HandlerStart)).Append(':').Append(Idx(h.HandlerEnd)).Append(';');}return sb.ToString();}
static string FieldSemantic(FieldDefinition f){var attrs=string.Join(',',f.CustomAttributes.Select(a=>a.AttributeType.FullName).OrderBy(x=>x,StringComparer.Ordinal));var c=f.HasConstant?Convert.ToString(f.Constant,CultureInfo.InvariantCulture)??"<null>":"<none>";return$"{f.FullName}|{f.Attributes}|{TypeSig(f.FieldType)}|const={c}|ca={attrs}";}
static bool IsListOf(MethodReference mr,string elem)=>mr.DeclaringType is GenericInstanceType git&&git.ElementType.FullName=="System.Collections.Generic.List`1"&&git.GenericArguments.Count==1&&git.GenericArguments[0].FullName==elem;
static MethodReference FindRef(IEnumerable<MethodDefinition> ms,Func<MethodReference,bool> pred,string label){foreach(var m in ms)if(m.HasBody)foreach(var i in m.Body.Instructions)if((i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt||i.OpCode==OpCodes.Newobj)&&i.Operand is MethodReference mr&&pred(mr))return mr;throw new InvalidDataException("missing ref "+label);}
static MethodReference CloneOn(MethodReference src,TypeReference declaring){var m=new MethodReference(src.Name,src.ReturnType,declaring){HasThis=src.HasThis,ExplicitThis=src.ExplicitThis,CallingConvention=src.CallingConvention};foreach(var p in src.Parameters)m.Parameters.Add(new ParameterDefinition(p.Name,p.Attributes,p.ParameterType));foreach(var g in src.GenericParameters)m.GenericParameters.Add(new GenericParameter(g.Name,m));return m;}
static int CountPrivateListRefs(MethodDefinition m)=>m.Body.Instructions.Count(i=>i.Operand is FieldReference fr&&fr.DeclaringType.FullName.StartsWith("System.Collections.Generic.List`1",StringComparison.Ordinal)&&(fr.Name=="_size"||fr.Name=="_version"||fr.Name=="_items"));
static int CountCalls(MethodDefinition m,Func<MethodReference,bool> pred)=>m.Body.Instructions.Count(i=>(i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt||i.OpCode==OpCodes.Newobj)&&i.Operand is MethodReference mr&&pred(mr));

var input=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);var inputSha=Sha(input);Console.WriteLine($"INPUT_SHA256 {inputSha}");if(inputSha!=ExpectedInputSha)throw new InvalidDataException("input SHA mismatch");
var beforeM=new Dictionary<uint,string>();var beforeF=new Dictionary<uint,string>();
using(var module=ModuleDefinition.ReadModule(input,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(module.Types).ToList();var methods=types.SelectMany(t=>t.Methods).ToList();var fields=types.SelectMany(t=>t.Fields).ToList();if(methods.Count!=ExpectedMethods||fields.Count!=ExpectedFields)throw new InvalidDataException("metadata count drift");if(module.AssemblyReferences.Any(a=>a.Name=="System.Private.CoreLib"))throw new InvalidDataException("corelib present");foreach(var m in methods)beforeM[Raw(m)]=MethodSemantic(m);foreach(var f in fields)beforeF[Raw(f)]=FieldSemantic(f);
 var map=types.Single(t=>t.FullName=="Map");var row=types.Single(t=>t.FullName=="Row");var grid=types.Single(t=>t.FullName=="Grid");
 var copy=map.Methods.Single(m=>m.Name=="Copy"&&m.Parameters.Count==0);var gx=map.Methods.Single(m=>m.Name=="GetMapX"&&m.Parameters.Count==0);var gy=map.Methods.Single(m=>m.Name=="GetMapY"&&m.Parameters.Count==0);
 if(Raw(copy)!=TokCopy||Raw(gx)!=TokGetX||Raw(gy)!=TokGetY)throw new InvalidDataException("target token drift");if(copy.Body.CodeSize!=996||copy.Body.Variables.Count!=34||gx.Body.CodeSize!=207||gx.Body.Variables.Count!=9||gy.Body.CodeSize!=65||gy.Body.Variables.Count!=3)throw new InvalidDataException("target body fingerprint drift");
 if(CountPrivateListRefs(copy)<10||CountPrivateListRefs(gx)<2||CountPrivateListRefs(gy)<1)throw new InvalidDataException("expected corrupt list-private-field fingerprints missing");
 var rowsF=map.Fields.Single(f=>f.Name=="rows");var scenarioF=map.Fields.Single(f=>f.Name=="senarioState");var cameraF=map.Fields.Single(f=>f.Name=="cameraSize");var enemyF=row.Fields.Single(f=>f.Name=="EnemyType");var gridsF=row.Fields.Single(f=>f.Name=="grids");var gridXF=grid.Fields.Single(f=>f.Name=="gridX");var gridYF=grid.Fields.Single(f=>f.Name=="gridY");
 var mapCtor=map.Methods.Single(m=>m.IsConstructor&&m.Parameters.Count==2);var gridCopy=grid.Methods.Single(m=>m.Name=="Copy"&&m.Parameters.Count==0);var nreCtor=FindRef(methods,mr=>mr.DeclaringType.FullName=="System.NullReferenceException"&&mr.Name==".ctor"&&mr.Parameters.Count==0,"NRE ctor");
 var rowCount=FindRef(methods,mr=>mr.Name=="get_Count"&&mr.Parameters.Count==0&&IsListOf(mr,"Row"),"List<Row>.Count");var rowGet=FindRef(methods,mr=>mr.Name=="get_Item"&&mr.Parameters.Count==1&&IsListOf(mr,"Row"),"List<Row>.get_Item");var gridCount=FindRef(methods,mr=>mr.Name=="get_Count"&&mr.Parameters.Count==0&&IsListOf(mr,"Grid"),"List<Grid>.Count");var gridGet=FindRef(methods,mr=>mr.Name=="get_Item"&&mr.Parameters.Count==1&&IsListOf(mr,"Grid"),"List<Grid>.get_Item");
 var anySet=FindRef(methods,mr=>mr.Name=="set_Item"&&mr.Parameters.Count==2&&mr.DeclaringType is GenericInstanceType git&&git.ElementType.FullName=="System.Collections.Generic.List`1","List<T>.set_Item");var gridListType=(GenericInstanceType)gridsF.FieldType;var gridSet=CloneOn(anySet,gridListType);
 Console.WriteLine("NATIVE_AUTHORITY getx_token=0x06000289 getx_va=0x000000018032C3B0 gety_token=0x0600028A gety_va=0x000000018032C440 copy_token=0x06000285 copy_va=0x000000018032B8F0 copy_end=0x000000018032BC80 semantics=standard_List_Count_getItem_new_Map_dimensions_copy_rows_grids");
 // GetMapX
 gx.Body.Instructions.Clear();gx.Body.Variables.Clear();gx.Body.ExceptionHandlers.Clear();gx.Body.InitLocals=true;gx.Body.MaxStackSize=2;var xRow=new VariableDefinition(row);var xGrids=new VariableDefinition(gridsF.FieldType);gx.Body.Variables.Add(xRow);gx.Body.Variables.Add(xGrids);var xil=gx.Body.GetILProcessor();var xRet0=xil.Create(OpCodes.Ldc_I4_0);var xThrow=xil.Create(OpCodes.Newobj,nreCtor);xil.Append(xil.Create(OpCodes.Ldarg_0));xil.Append(xil.Create(OpCodes.Ldfld,rowsF));xil.Append(xil.Create(OpCodes.Brfalse,xRet0));xil.Append(xil.Create(OpCodes.Ldarg_0));xil.Append(xil.Create(OpCodes.Ldfld,rowsF));xil.Append(xil.Create(OpCodes.Callvirt,rowCount));xil.Append(xil.Create(OpCodes.Ldc_I4_0));xil.Append(xil.Create(OpCodes.Ble,xRet0));xil.Append(xil.Create(OpCodes.Ldarg_0));xil.Append(xil.Create(OpCodes.Ldfld,rowsF));xil.Append(xil.Create(OpCodes.Ldc_I4_0));xil.Append(xil.Create(OpCodes.Callvirt,rowGet));xil.Append(xil.Create(OpCodes.Stloc,xRow));xil.Append(xil.Create(OpCodes.Ldloc,xRow));xil.Append(xil.Create(OpCodes.Brfalse,xThrow));xil.Append(xil.Create(OpCodes.Ldloc,xRow));xil.Append(xil.Create(OpCodes.Ldfld,gridsF));xil.Append(xil.Create(OpCodes.Stloc,xGrids));xil.Append(xil.Create(OpCodes.Ldloc,xGrids));xil.Append(xil.Create(OpCodes.Brfalse,xThrow));xil.Append(xil.Create(OpCodes.Ldloc,xGrids));xil.Append(xil.Create(OpCodes.Callvirt,gridCount));xil.Append(xil.Create(OpCodes.Ret));xil.Append(xThrow);xil.Append(xil.Create(OpCodes.Throw));xil.Append(xRet0);xil.Append(xil.Create(OpCodes.Ret));
 // GetMapY
 gy.Body.Instructions.Clear();gy.Body.Variables.Clear();gy.Body.ExceptionHandlers.Clear();gy.Body.InitLocals=false;gy.Body.MaxStackSize=1;var yil=gy.Body.GetILProcessor();var yRet0=yil.Create(OpCodes.Ldc_I4_0);yil.Append(yil.Create(OpCodes.Ldarg_0));yil.Append(yil.Create(OpCodes.Ldfld,rowsF));yil.Append(yil.Create(OpCodes.Brfalse,yRet0));yil.Append(yil.Create(OpCodes.Ldarg_0));yil.Append(yil.Create(OpCodes.Ldfld,rowsF));yil.Append(yil.Create(OpCodes.Callvirt,rowCount));yil.Append(yil.Create(OpCodes.Ret));yil.Append(yRet0);yil.Append(yil.Create(OpCodes.Ret));
 // Copy
 copy.Body.Instructions.Clear();copy.Body.Variables.Clear();copy.Body.ExceptionHandlers.Clear();copy.Body.InitLocals=true;copy.Body.MaxStackSize=4;var vMapX=new VariableDefinition(module.TypeSystem.Int32);var vMapY=new VariableDefinition(module.TypeSystem.Int32);var vCopy=new VariableDefinition(map);var vI=new VariableDefinition(module.TypeSystem.Int32);var vDstRow=new VariableDefinition(row);var vSrcRow=new VariableDefinition(row);var vJ=new VariableDefinition(module.TypeSystem.Int32);var vSrcGrid=new VariableDefinition(grid);var vGridCopy=new VariableDefinition(grid);foreach(var v in new[]{vMapX,vMapY,vCopy,vI,vDstRow,vSrcRow,vJ,vSrcGrid,vGridCopy})copy.Body.Variables.Add(v);var il=copy.Body.GetILProcessor();var yNonNull=il.Create(OpCodes.Ldarg_0);var afterY=il.Create(OpCodes.Ldloc,vMapX);var rowCheck=il.Create(OpCodes.Ldloc,vI);var rowBody=il.Create(OpCodes.Ldloc,vCopy);var gridCheck=il.Create(OpCodes.Ldloc,vJ);var gridBody=il.Create(OpCodes.Ldarg_0);var done=il.Create(OpCodes.Ldloc,vCopy);var throwNre=il.Create(OpCodes.Newobj,nreCtor);
 il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Call,gx));il.Append(il.Create(OpCodes.Stloc,vMapX));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Brtrue,yNonNull));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Stloc,vMapY));il.Append(il.Create(OpCodes.Br,afterY));il.Append(yNonNull);il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Callvirt,rowCount));il.Append(il.Create(OpCodes.Stloc,vMapY));il.Append(afterY);il.Append(il.Create(OpCodes.Ldloc,vMapY));il.Append(il.Create(OpCodes.Newobj,mapCtor));il.Append(il.Create(OpCodes.Stloc,vCopy));il.Append(il.Create(OpCodes.Ldloc,vCopy));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,scenarioF));il.Append(il.Create(OpCodes.Stfld,scenarioF));il.Append(il.Create(OpCodes.Ldloc,vCopy));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,cameraF));il.Append(il.Create(OpCodes.Stfld,cameraF));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Brfalse,throwNre));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Stloc,vI));il.Append(il.Create(OpCodes.Br,rowCheck));
 il.Append(rowBody);il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Ldloc,vI));il.Append(il.Create(OpCodes.Callvirt,rowGet));il.Append(il.Create(OpCodes.Stloc,vDstRow));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Ldloc,vI));il.Append(il.Create(OpCodes.Callvirt,rowGet));il.Append(il.Create(OpCodes.Stloc,vSrcRow));il.Append(il.Create(OpCodes.Ldloc,vDstRow));il.Append(il.Create(OpCodes.Ldloc,vSrcRow));il.Append(il.Create(OpCodes.Ldfld,enemyF));il.Append(il.Create(OpCodes.Stfld,enemyF));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Stloc,vJ));il.Append(il.Create(OpCodes.Br,gridCheck));
 il.Append(gridBody);il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Ldloc,vI));il.Append(il.Create(OpCodes.Callvirt,rowGet));il.Append(il.Create(OpCodes.Ldfld,gridsF));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Callvirt,gridGet));il.Append(il.Create(OpCodes.Stloc,vSrcGrid));il.Append(il.Create(OpCodes.Ldloc,vSrcGrid));il.Append(il.Create(OpCodes.Callvirt,gridCopy));il.Append(il.Create(OpCodes.Stloc,vGridCopy));il.Append(il.Create(OpCodes.Ldloc,vDstRow));il.Append(il.Create(OpCodes.Ldfld,gridsF));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Ldloc,vGridCopy));il.Append(il.Create(OpCodes.Callvirt,gridSet));il.Append(il.Create(OpCodes.Ldloc,vDstRow));il.Append(il.Create(OpCodes.Ldfld,gridsF));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Callvirt,gridGet));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Stfld,gridXF));il.Append(il.Create(OpCodes.Ldloc,vDstRow));il.Append(il.Create(OpCodes.Ldfld,gridsF));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Callvirt,gridGet));il.Append(il.Create(OpCodes.Ldloc,vI));il.Append(il.Create(OpCodes.Stfld,gridYF));il.Append(il.Create(OpCodes.Ldloc,vJ));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Add));il.Append(il.Create(OpCodes.Stloc,vJ));
 il.Append(gridCheck);il.Append(il.Create(OpCodes.Ldloc,vDstRow));il.Append(il.Create(OpCodes.Ldfld,gridsF));il.Append(il.Create(OpCodes.Callvirt,gridCount));il.Append(il.Create(OpCodes.Blt,gridBody));il.Append(il.Create(OpCodes.Ldloc,vI));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Add));il.Append(il.Create(OpCodes.Stloc,vI));il.Append(rowCheck);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,rowsF));il.Append(il.Create(OpCodes.Callvirt,rowCount));il.Append(il.Create(OpCodes.Blt,rowBody));il.Append(done);il.Append(il.Create(OpCodes.Ret));il.Append(throwNre);il.Append(il.Create(OpCodes.Throw));
 Console.WriteLine("PATCH_MAP_IMMEDIATE methods=3 tokens=0x06000285,0x06000289,0x0600028A source=pc_native_immediate_gameplay_path");module.Write(output);
}
Console.WriteLine($"OUTPUT_SHA256 {Sha(output)}");
using(var module=ModuleDefinition.ReadModule(output,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(module.Types).ToList();var methods=types.SelectMany(t=>t.Methods).ToList();var fields=types.SelectMany(t=>t.Fields).ToList();var map=types.Single(t=>t.FullName=="Map");var copy=map.Methods.Single(m=>m.Name=="Copy"&&m.Parameters.Count==0);var gx=map.Methods.Single(m=>m.Name=="GetMapX"&&m.Parameters.Count==0);var gy=map.Methods.Single(m=>m.Name=="GetMapY"&&m.Parameters.Count==0);
 foreach(var m in new[]{copy,gx,gy})if(CountPrivateListRefs(m)!=0)throw new InvalidDataException($"private list refs remain {m.Name}");if(CountCalls(copy,mr=>mr.DeclaringType.FullName=="Map"&&mr.Name=="GetMapX")!=1||CountCalls(copy,mr=>mr.DeclaringType.FullName=="Grid"&&mr.Name=="Copy")!=1)throw new InvalidDataException("copy call shape mismatch");if(CountCalls(gx,mr=>mr.Name=="get_Count"&&IsListOf(mr,"Row"))!=1||CountCalls(gx,mr=>mr.Name=="get_Count"&&IsListOf(mr,"Grid"))!=1)throw new InvalidDataException("GetMapX count shape mismatch");if(CountCalls(gy,mr=>mr.Name=="get_Count"&&IsListOf(mr,"Row"))!=1)throw new InvalidDataException("GetMapY count shape mismatch");
 var targets=new HashSet<uint>{TokCopy,TokGetX,TokGetY};int changed=0,untouched=0;foreach(var m in methods){if(beforeM.TryGetValue(Raw(m),out var old)&&old==MethodSemantic(m))untouched++;else{changed++;if(!targets.Contains(Raw(m)))throw new InvalidDataException($"unexpected method drift 0x{Raw(m):X8} {m.FullName}");}}if(changed!=3||untouched!=2314)throw new InvalidDataException($"isolation mismatch {untouched}/{changed}");foreach(var f in fields)if(!beforeF.TryGetValue(Raw(f),out var old)||old!=FieldSemantic(f))throw new InvalidDataException($"field drift 0x{Raw(f):X8}");if(module.AssemblyReferences.Any(a=>a.Name=="System.Private.CoreLib"))throw new InvalidDataException("corelib introduced");
 Console.WriteLine("REOPEN_MAP_IMMEDIATE_PASS copy_private_list_refs=0 getx_private_list_refs=0 gety_private_list_refs=0 getx_calls=1 grid_copy_calls=1 corelib_refs=0");Console.WriteLine("SEMANTIC_ISOLATION_PASS untouched_methods=2314 changed_methods=3 target_tokens=0x06000285,0x06000289,0x0600028A");Console.WriteLine("FIELD_METADATA_ISOLATION_PASS unchanged_fields=2802 changed_fields=0");
}
return 0;
