using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher54{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int token){O(op);b.AddRange(BitConverter.GetBytes(token));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="8e40b7920c1f689b9b5c8460df06d3122adef94fe8c87bdebe6b56d894aa7b27","Pinned Native53");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x0600043D,0x0600043E,0x0600043F,0x060005D9}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<FieldReference>().First(f=>f.DeclaringType.FullName==owner&&f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);int sig=m.Body.LocalVarToken.ToInt32(),max=2;
switch(token){
case 0x0600043D:{max=2;var xfield=a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(f=>f.FullName=="System.Single UnityEngine.Vector3::x");il.O(2);il.Ref(0x28,call("get_transform"));il.Ref(0x6f,call("get_position"));il.O(0x0c,2);il.Ref(0x7c,field("Zombie","previousPosition"));il.Ref(0x7b,xfield);il.O(0x13,5);il.Ref(0x28,call("get_deltaTime"));il.F(0);il.O(0xfe,1);il.Br(0x2d,"zero");il.O(8);il.Ref(0x7b,xfield);il.O(0x11,5,0x59,0x13,6,0x11,6);il.Ref(0x28,call("get_deltaTime"));il.O(0x5b,0x2a);il.Label("zero");il.F(0);il.O(0x2a);break;}
case 0x0600043E:{max=2;sig=0x110001AA;il.O(2);il.Ref(0x7b,field("Zombie","armor1Type"));il.O(0x0b);il.Ref(0x7e,field("System.String","Empty"));il.O(0x0a);int[]labels={1,2,3,4,2,6};for(int j=1;j<=6;j++){il.O(7,(byte)(0x16+j));il.Br(0x2e,"case"+labels[j-1]);}il.Br(0x2b,"call");foreach(var(i,tok)in new[]{(1,1879117652),(2,1879117672),(3,1879117696),(4,1879081276),(6,1879082222)}){il.Label("case"+i);il.Token(0x72,tok);il.O(0x0a);il.Br(0x2b,"call");}il.Label("call");il.O(2);il.Ref(0x7b,field("Zombie","animationSprites"));il.O(6);il.Ref(0x28,call("GetAnimationSpritePosition"));il.O(0x2a);break;}
case 0x0600043F:{max=2;il.O(2);il.Ref(0x7b,field("Zombie","anim_Armor2Sprites"));il.O(0x16);il.Ref(0x6f,call("get_Item"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.O(0x2a);break;}
case 0x060005D9:{max=3;var vx=a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(f=>f.FullName=="System.Single UnityEngine.Vector3::x");var vy=a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(f=>f.FullName=="System.Single UnityEngine.Vector3::y");il.O(0x12,1,0xfe,0x15);il.b.AddRange(BitConverter.GetBytes(m.ReturnType.MetadataToken.ToInt32()));il.O(0x12,1);il.F(680);il.F(980);il.Ref(0x28,call("Range"));il.Ref(0x7d,vx);il.O(3);il.Ref(0x7b,field("Enemy","row"));il.O(0x6b);il.F(134);il.O(0x5a,0x13,4);il.F(286);il.O(0x11,4,0x59,0x13,5,0x12,1,0x11,5);il.Ref(0x7d,vy);il.O(0x12,1);il.F(-20);il.F(100);il.Ref(0x28,call("Range"));il.O(0x11,5,0x58);il.Ref(0x7d,vy);il.O(7,0x2a);break;}}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot");int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
