using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

if (args.Length != 2) { Console.Error.WriteLine("Usage: Stage9PlantDetailInitializePatch <input.dll> <output.dll>"); return 2; }
const string ExpectedInputSha = "1c62f969409ed16c9d7c7855f7b52e6b593701524e2b2d75ec0affbc3d05b209";
const int ExpectedMethods = 2317, ExpectedFields = 2802;
const uint TargetToken = 0x06000667;

static IEnumerable<TypeDefinition> AllTypes(IEnumerable<TypeDefinition> roots){foreach(var t in roots){yield return t;foreach(var n in AllTypes(t.NestedTypes))yield return n;}}
static uint Raw(IMetadataTokenProvider p)=>p.MetadataToken.ToUInt32();
static string Sha(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p))).ToLowerInvariant();
static string ScopeName(TypeReference t)=>t.Scope switch{AssemblyNameReference a=>a.Name,ModuleDefinition m=>m.Assembly?.Name?.Name??m.Name,ModuleReference mr=>mr.Name,_=>t.Scope?.ToString()??"<null>"};
static string TypeSig(TypeReference t)=>$"{t.FullName}@{ScopeName(t)}";
static string OperandSig(object? o,MethodDefinition owner){if(o is null)return"";if(o is Instruction i)return$"I#{owner.Body.Instructions.IndexOf(i)}";if(o is Instruction[] sw)return"SW["+string.Join(',',sw.Select(i=>owner.Body.Instructions.IndexOf(i)))+"]";if(o is MethodReference mr)return$"M:{mr.FullName}@{ScopeName(mr.DeclaringType)}";if(o is FieldReference fr)return$"F:{fr.FullName}@{ScopeName(fr.DeclaringType)}";if(o is TypeReference tr)return$"T:{TypeSig(tr)}";if(o is VariableDefinition vr)return$"V:{vr.Index}:{TypeSig(vr.VariableType)}";if(o is ParameterDefinition pr)return$"P:{pr.Index}:{TypeSig(pr.ParameterType)}";if(o is string s)return"S:"+Convert.ToBase64String(Encoding.UTF8.GetBytes(s));if(o is float f)return$"R4:{BitConverter.SingleToInt32Bits(f):X8}";return"C:"+Convert.ToString(o,CultureInfo.InvariantCulture);}
static string MethodSemantic(MethodDefinition m){var sb=new StringBuilder();sb.Append(m.FullName).Append('|').Append(m.Attributes).Append('|').Append(m.ImplAttributes).Append('|');if(!m.HasBody)return sb.Append("NOBODY").ToString();sb.Append("init=").Append(m.Body.InitLocals).Append(";max=").Append(m.Body.MaxStackSize).Append(';');foreach(var v in m.Body.Variables)sb.Append("L:").Append(v.Index).Append(':').Append(TypeSig(v.VariableType)).Append(';');foreach(var i in m.Body.Instructions)sb.Append("I:").Append(i.OpCode.Code).Append(':').Append(OperandSig(i.Operand,m)).Append(';');foreach(var h in m.Body.ExceptionHandlers){int Idx(Instruction? x)=>x is null?-1:m.Body.Instructions.IndexOf(x);sb.Append("EH:").Append(h.HandlerType).Append(':').Append(Idx(h.TryStart)).Append(':').Append(Idx(h.TryEnd)).Append(':').Append(Idx(h.HandlerStart)).Append(':').Append(Idx(h.HandlerEnd)).Append(';');}return sb.ToString();}
static string FieldSemantic(FieldDefinition f){var attrs=string.Join(',',f.CustomAttributes.Select(a=>a.AttributeType.FullName).OrderBy(x=>x,StringComparer.Ordinal));var c=f.HasConstant?Convert.ToString(f.Constant,CultureInfo.InvariantCulture)??"<null>":"<none>";return$"{f.FullName}|{f.Attributes}|{TypeSig(f.FieldType)}|const={c}|ca={attrs}";}
static MethodReference FindInMethod(MethodDefinition m,Func<MethodReference,bool> pred,string label){foreach(var i in m.Body.Instructions)if((i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt||i.OpCode==OpCodes.Newobj)&&i.Operand is MethodReference mr&&pred(mr))return mr;throw new InvalidDataException("missing ref "+label);}
static int CountCalls(MethodDefinition m,Func<MethodReference,bool> pred)=>m.Body.Instructions.Count(i=>(i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt||i.OpCode==OpCodes.Newobj)&&i.Operand is MethodReference mr&&pred(mr));

var input=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);var sha=Sha(input);Console.WriteLine($"INPUT_SHA256 {sha}");if(sha!=ExpectedInputSha)throw new InvalidDataException("input SHA mismatch");
var beforeM=new Dictionary<uint,string>();var beforeF=new Dictionary<uint,string>();
using(var module=ModuleDefinition.ReadModule(input,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(module.Types).ToList();var methods=types.SelectMany(t=>t.Methods).ToList();var fields=types.SelectMany(t=>t.Fields).ToList();if(methods.Count!=ExpectedMethods||fields.Count!=ExpectedFields)throw new InvalidDataException("metadata count drift");if(module.AssemblyReferences.Any(a=>a.Name=="System.Private.CoreLib"))throw new InvalidDataException("corelib present");foreach(var m in methods)beforeM[Raw(m)]=MethodSemantic(m);foreach(var f in fields)beforeF[Raw(f)]=FieldSemantic(f);
 var pd=types.Single(t=>t.FullName=="Plant_DetaiPage");var plantT=types.Single(t=>t.FullName=="Plant");var skillT=types.Single(t=>t.FullName=="Skill");var dataT=types.Single(t=>t.FullName=="Board_PlantDetail_PlantData");
 var target=pd.Methods.Single(m=>m.Name=="Initialize"&&m.Parameters.Count==1&&m.Parameters[0].ParameterType.FullName=="Plant");if(Raw(target)!=TargetToken||target.Body.CodeSize!=830||target.Body.Variables.Count!=25)throw new InvalidDataException($"target fingerprint drift token=0x{Raw(target):X8} size={target.Body.CodeSize} locals={target.Body.Variables.Count}");
 var plantF=pd.Fields.Single(f=>f.Name=="plant");var skillGoF=pd.Fields.Single(f=>f.Name=="skill");var pSkillF=pd.Fields.Single(f=>f.Name=="p_skill");var textNameF=pd.Fields.Single(f=>f.Name=="text_name");var skillButtonF=pd.Fields.Single(f=>f.Name=="skillButton");var skillAutoF=pd.Fields.Single(f=>f.Name=="skillAuto");var textKeyF=pd.Fields.Single(f=>f.Name=="text_key");var chargeLayerF=pd.Fields.Single(f=>f.Name=="chargeLayer");var dataPageF=pd.Fields.Single(f=>f.Name=="dataPage");var skillRangeF=pd.Fields.Single(f=>f.Name=="skillRange");var rangeImageF=pd.Fields.Single(f=>f.Name=="rangeIamge");
 var plantNameF=plantT.Fields.Single(f=>f.Name=="plantName");var plantSkillF=plantT.Fields.Single(f=>f.Name=="skill");var isOnFieldF=plantT.Fields.Single(f=>f.Name=="isOnField");var triggerF=skillT.Fields.Single(f=>f.Name=="skillTriggerType");var maxChargeF=skillT.Fields.Single(f=>f.Name=="maxChargedLayer");
 var objImplicit=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Object"&&mr.Name=="op_Implicit","Object.op_Implicit");var setActive=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.GameObject"&&mr.Name=="SetActive","GameObject.SetActive");var setText=FindInMethod(target,mr=>mr.DeclaringType.FullName=="TMPro.TMP_Text"&&mr.Name=="SetText"&&mr.Parameters.Count==2,"TMP_Text.SetText");var compTransform=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Component"&&mr.Name=="get_transform","Component.get_transform");var goTransform=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.GameObject"&&mr.Name=="get_transform","GameObject.get_transform");var getPosition=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Transform"&&mr.Name=="get_position","Transform.get_position");var setPosition=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Transform"&&mr.Name=="set_position","Transform.set_position");var loadSkill=pd.Methods.Single(m=>m.Name=="LoadSkillLogo"&&m.Parameters.Count==0);var setEnabled=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Behaviour"&&mr.Name=="set_enabled","Behaviour.set_enabled");var getGameObject=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.Component"&&mr.Name=="get_gameObject","Component.get_gameObject");var loadData=dataT.Methods.Single(m=>m.Name=="LoadData"&&m.Parameters.Count==1);var checkText=dataT.Methods.Single(m=>m.Name=="CheckText"&&m.Parameters.Count==1);var setColor=FindInMethod(target,mr=>mr.DeclaringType.FullName=="UnityEngine.UI.Graphic"&&mr.Name=="set_color","Graphic.set_color");
 var vectorT=getPosition.ReturnType;var colorT=setColor.Parameters[0].ParameterType;var vecX=new FieldReference("x",module.TypeSystem.Single,vectorT);var vecY=new FieldReference("y",module.TypeSystem.Single,vectorT);var vecCtor=new MethodReference(".ctor",module.TypeSystem.Void,vectorT){HasThis=true};vecCtor.Parameters.Add(new ParameterDefinition(module.TypeSystem.Single));vecCtor.Parameters.Add(new ParameterDefinition(module.TypeSystem.Single));vecCtor.Parameters.Add(new ParameterDefinition(module.TypeSystem.Single));var colorCtor=new MethodReference(".ctor",module.TypeSystem.Void,colorT){HasThis=true};for(int i=0;i<4;i++)colorCtor.Parameters.Add(new ParameterDefinition(module.TypeSystem.Single));
 Console.WriteLine("TARGET_METHOD token=0x06000667 type=Plant_DetaiPage method=Initialize code_size=830 locals=25 invalid_vector_color_fingerprint=1");Console.WriteLine("NATIVE_AUTHORITY token=0x06000667 address=0x00000001803A3E30 end=0x00000001803A41D0 semantics=assign_plant_skill_ui_position_y_plus_30_load_logo_manual_skill_charge_data_white_range");Console.WriteLine("NATIVE_CONSTANTS skill_position_y_offset=30 range_color=1,1,1,1");
 target.Body.Instructions.Clear();target.Body.Variables.Clear();target.Body.ExceptionHandlers.Clear();target.Body.InitLocals=true;target.Body.MaxStackSize=6;var pos=new VariableDefinition(vectorT);var newPos=new VariableDefinition(vectorT);var white=new VariableDefinition(colorT);target.Body.Variables.Add(pos);target.Body.Variables.Add(newPos);target.Body.Variables.Add(white);var il=target.Body.GetILProcessor();
 var present=il.Create(OpCodes.Nop);var afterPlant=il.Create(OpCodes.Nop);var afterPos=il.Create(OpCodes.Nop);var hasSkill=il.Create(OpCodes.Nop);var skipManual=il.Create(OpCodes.Nop);var afterCharge=il.Create(OpCodes.Nop);
 il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldarg_1));il.Append(il.Create(OpCodes.Stfld,plantF));il.Append(il.Create(OpCodes.Ldarg_1));il.Append(il.Create(OpCodes.Call,objImplicit));il.Append(il.Create(OpCodes.Brtrue,present));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillGoF));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldnull));il.Append(il.Create(OpCodes.Stfld,pSkillF));il.Append(il.Create(OpCodes.Br,afterPlant));
 il.Append(present);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,textNameF));il.Append(il.Create(OpCodes.Ldarg_1));il.Append(il.Create(OpCodes.Ldfld,plantNameF));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Callvirt,setText));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,plantF));il.Append(il.Create(OpCodes.Ldfld,plantSkillF));il.Append(il.Create(OpCodes.Stfld,pSkillF));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillGoF));il.Append(il.Create(OpCodes.Ldarg_1));il.Append(il.Create(OpCodes.Ldfld,isOnFieldF));il.Append(il.Create(OpCodes.Callvirt,setActive));
 il.Append(afterPlant);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,plantF));il.Append(il.Create(OpCodes.Call,objImplicit));il.Append(il.Create(OpCodes.Brfalse,afterPos));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,plantF));il.Append(il.Create(OpCodes.Callvirt,compTransform));il.Append(il.Create(OpCodes.Callvirt,getPosition));il.Append(il.Create(OpCodes.Stloc,pos));il.Append(il.Create(OpCodes.Ldloca,newPos));il.Append(il.Create(OpCodes.Ldloca,pos));il.Append(il.Create(OpCodes.Ldfld,vecX));il.Append(il.Create(OpCodes.Ldloca,pos));il.Append(il.Create(OpCodes.Ldfld,vecY));il.Append(il.Create(OpCodes.Ldc_R4,30f));il.Append(il.Create(OpCodes.Add));il.Append(il.Create(OpCodes.Ldc_R4,0f));il.Append(il.Create(OpCodes.Call,vecCtor));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillGoF));il.Append(il.Create(OpCodes.Callvirt,goTransform));il.Append(il.Create(OpCodes.Ldloc,newPos));il.Append(il.Create(OpCodes.Callvirt,setPosition));
 il.Append(afterPos);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Call,loadSkill));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,pSkillF));il.Append(il.Create(OpCodes.Brtrue,hasSkill));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillButtonF));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,setEnabled));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillAutoF));il.Append(il.Create(OpCodes.Callvirt,getGameObject));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,textKeyF));il.Append(il.Create(OpCodes.Callvirt,getGameObject));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,chargeLayerF));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(il.Create(OpCodes.Br,afterCharge));
 il.Append(hasSkill);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,pSkillF));il.Append(il.Create(OpCodes.Ldfld,triggerF));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Bne_Un,skipManual));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillButtonF));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Callvirt,setEnabled));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,skillAutoF));il.Append(il.Create(OpCodes.Callvirt,getGameObject));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,textKeyF));il.Append(il.Create(OpCodes.Callvirt,getGameObject));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Callvirt,setActive));il.Append(skipManual);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,chargeLayerF));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,pSkillF));il.Append(il.Create(OpCodes.Ldfld,maxChargeF));il.Append(il.Create(OpCodes.Ldc_I4_1));il.Append(il.Create(OpCodes.Cgt));il.Append(il.Create(OpCodes.Callvirt,setActive));
 il.Append(afterCharge);il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,dataPageF));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Callvirt,loadData));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,dataPageF));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Callvirt,checkText));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldc_I4_0));il.Append(il.Create(OpCodes.Stfld,skillRangeF));il.Append(il.Create(OpCodes.Ldloca,white));il.Append(il.Create(OpCodes.Ldc_R4,1f));il.Append(il.Create(OpCodes.Ldc_R4,1f));il.Append(il.Create(OpCodes.Ldc_R4,1f));il.Append(il.Create(OpCodes.Ldc_R4,1f));il.Append(il.Create(OpCodes.Call,colorCtor));il.Append(il.Create(OpCodes.Ldarg_0));il.Append(il.Create(OpCodes.Ldfld,rangeImageF));il.Append(il.Create(OpCodes.Ldloc,white));il.Append(il.Create(OpCodes.Callvirt,setColor));il.Append(il.Create(OpCodes.Ret));
 Console.WriteLine("PATCH_PLANT_DETAIL_INITIALIZE method_body_changes=1 source=pc_native_exact_constants");module.Write(output);
}
Console.WriteLine($"OUTPUT_SHA256 {Sha(output)}");
using(var module=ModuleDefinition.ReadModule(output,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(module.Types).ToList();var methods=types.SelectMany(t=>t.Methods).ToList();var fields=types.SelectMany(t=>t.Fields).ToList();var target=types.Single(t=>t.FullName=="Plant_DetaiPage").Methods.Single(m=>m.Name=="Initialize"&&m.Parameters.Count==1&&m.Parameters[0].ParameterType.FullName=="Plant");if(target.Body.Variables.Count!=3)throw new InvalidDataException("local count drift");if(CountCalls(target,mr=>mr.DeclaringType.FullName=="Plant_DetaiPage"&&mr.Name=="LoadSkillLogo")!=1||CountCalls(target,mr=>mr.DeclaringType.FullName=="Board_PlantDetail_PlantData"&&mr.Name=="LoadData")!=1||CountCalls(target,mr=>mr.DeclaringType.FullName=="Board_PlantDetail_PlantData"&&mr.Name=="CheckText")!=1)throw new InvalidDataException("call shape drift");int changed=0,untouched=0;foreach(var m in methods){if(beforeM.TryGetValue(Raw(m),out var old)&&old==MethodSemantic(m))untouched++;else{changed++;if(Raw(m)!=TargetToken)throw new InvalidDataException($"unexpected method drift 0x{Raw(m):X8} {m.FullName}");}}if(changed!=1||untouched!=2316)throw new InvalidDataException($"isolation mismatch {untouched}/{changed}");foreach(var f in fields)if(!beforeF.TryGetValue(Raw(f),out var old)||old!=FieldSemantic(f))throw new InvalidDataException($"field drift 0x{Raw(f):X8}");if(module.AssemblyReferences.Any(a=>a.Name=="System.Private.CoreLib"))throw new InvalidDataException("corelib introduced");Console.WriteLine("REOPEN_PLANT_DETAIL_INITIALIZE_PASS token=0x06000667 locals=3 load_skill_logo=1 load_data=1 check_text=1 y_offset_30=1 white_color=1 corelib_refs=0");Console.WriteLine("SEMANTIC_ISOLATION_PASS untouched_methods=2316 changed_methods=1 target_token=0x06000667");Console.WriteLine("FIELD_METADATA_ISOLATION_PASS unchanged_fields=2802 changed_fields=0");}
return 0;
