using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text;
using Mono.Cecil;
static class AuditNative41 {
 static void R(bool b,string s){if(!b)throw new Exception(s);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static byte[] Root(PEReader p)=>p.GetMetadata().GetContent().ToArray();
 static int Offset(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static (int Offset,int Size) StreamInfo(byte[] r,string name){int v=BitConverter.ToInt32(r,12),p=((16+v+3)/4)*4+2,count=BitConverter.ToUInt16(r,p);p+=2;for(int i=0;i<count;i++){int e=Array.IndexOf(r,(byte)0,p+8);if(Encoding.ASCII.GetString(r,p+8,e-p-8)==name)return(BitConverter.ToInt32(r,p),BitConverter.ToInt32(r,p+4));p=((e+1+3)/4)*4;}throw new Exception("Missing stream "+name);}
 static int Main(string[] args){try{var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="bb71c657d2a0f2e1155ef43b55f96c0355097c225c25b0d62aacfadc27fa7088","Pinned parent");using var pb=new PEReader(new MemoryStream(b));using var pc=new PEReader(new MemoryStream(c));var mb=pb.GetMetadataReader();var mc=pc.GetMetadataReader();var rb=Root(pb);var rc=Root(pc);using var ab=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var ac=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[1]);var report=JsonDocument.Parse(File.ReadAllText(args[2]));var targets=report.RootElement.GetProperty("methods").EnumerateArray().Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).ToHashSet();R(targets.SetEquals(new[]{0x0600001B,0x0600001E,0x0600002B,0x06000040}),"Target cardinality");var allowed=new HashSet<int>();void Allow(int p,int n){for(int j=0;j<n;j++)allowed.Add(p+j);}var tableRows=new List<object>();
  foreach(TableIndex t in Enum.GetValues<TableIndex>()){int n=mb.GetTableRowCount(t);int delta=t==TableIndex.MemberRef?4:t==TableIndex.TypeSpec?2:0;R(mc.GetTableRowCount(t)==n+delta,"Table count "+t);if(n==0)continue;int size=mb.GetTableRowSize(t);R(size==mc.GetTableRowSize(t),"Row width "+t);int x=mb.GetTableMetadataOffset(t),y=mc.GetTableMetadataOffset(t);R(rb[x..(x+n*size)].SequenceEqual(rc[y..(y+n*size)]),"Existing row drift "+t);tableRows.Add(new{table=t.ToString(),rows=n,row_size=size});}
  foreach(HeapIndex h in Enum.GetValues<HeapIndex>()){int n=mb.GetHeapSize(h);R(h==HeapIndex.Blob?mc.GetHeapSize(h)>=n:mc.GetHeapSize(h)==n,"Heap size "+h);int x=mb.GetHeapMetadataOffset(h),y=mc.GetHeapMetadataOffset(h);R(rb[x..(x+n)].SequenceEqual(rc[y..(y+n)]),"Heap bytes "+h);}foreach(string stream in new[]{"#Strings","#Blob","#US","#GUID"}){var x=StreamInfo(rb,stream);var y=StreamInfo(rc,stream);R((stream=="#Blob"?y.Size>x.Size:y.Size==x.Size)&&rb[x.Offset..(x.Offset+x.Size)].SequenceEqual(rc[y.Offset..(y.Offset+x.Size)]),"Entire stream prefix including padding "+stream);}
  int prefix=((16+BitConverter.ToInt32(rb,12)+3)/4)*4+4;R(rb[..prefix].SequenceEqual(rc[..prefix]),"Root version/flags/stream count");var tb=StreamInfo(rb,"#~");var tc=StreamInfo(rc,"#~");R(rb[tb.Offset..(tb.Offset+16)].SequenceEqual(rc[tc.Offset..(tc.Offset+16)]),"Tables header and valid mask");R(BitConverter.ToUInt64(rc,tc.Offset+16)==(BitConverter.ToUInt64(rb,tb.Offset+16)&~(1UL<<10)),"Only MemberRef sorted bit may clear");
  int non=0;foreach(var h in mb.MethodDefinitions){int token=MetadataTokens.GetToken(h);var bm=mb.GetMethodDefinition(h);var cm=mc.GetMethodDefinition(h);R(bm.RelativeVirtualAddress==cm.RelativeVirtualAddress,"RVA drift");if(bm.RelativeVirtualAddress==0)continue;var ob=pb.GetMethodBody(bm.RelativeVirtualAddress);var nb=pc.GetMethodBody(cm.RelativeVirtualAddress);int off=Offset(pb,bm.RelativeVirtualAddress);if(targets.Contains(token)){R(ob.LocalSignature==nb.LocalSignature&&ob.LocalVariablesInitialized==nb.LocalVariablesInitialized&&ob.ExceptionRegions.Length==0&&nb.ExceptionRegions.Length==0,"Target local/header flags");var row=report.RootElement.GetProperty("methods").EnumerateArray().Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==off,"Pinned body offset");var original=(Mono.Cecil.MethodDefinition)ab.MainModule.LookupToken(token);var expected=ob.GetILBytes()!.ToArray();var remove=original.Body.Instructions.Where(i=>i.Operand is MethodReference r&&r.Name=="Remove").ToArray();R(remove.Length==2,"Pinned two calls");int kind=token is 0x0600001B or 0x0600002B?0:2;for(int j=0;j<2;j++){int pos=remove[j].Offset+1;BitConverter.GetBytes(0x0A000000+mb.GetTableRowCount(TableIndex.MemberRef)+1+kind+j).CopyTo(expected,pos);Allow(off+12+pos,4);}R(expected.SequenceEqual(nb.GetILBytes()!)&&ob.MaxStack==nb.MaxStack&&ob.Size==nb.Size,"Only eight operand token edits; header/branch/code unchanged");var md=(Mono.Cecil.MethodDefinition)ac.MainModule.LookupToken(token);R(md.Body.Instructions.All(i=>i.Operand is not Mono.Cecil.Cil.Instruction j||md.Body.Instructions.Contains(j)),"Invalid branch");R(!md.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Ldstr&&i.Operand is string s&&(s.Contains("Indirect call:")||s.Contains("Warning:"))),"Unresolved reconstruction");R(H(nb.GetILBytes()!)==row.GetProperty("code_sha256").GetString(),"Reopened code digest");}else{R(ob.Size==nb.Size,"Non-target size");R(b[off..(off+ob.Size)].SequenceEqual(c[off..(off+nb.Size)]),"Non-target raw body "+token.ToString("X8"));non++;}}
  var pe=pb.PEHeaders;int lastHeader=pe.PEHeaderStartOffset+pe.CoffHeader.SizeOfOptionalHeader+(pe.CoffHeader.NumberOfSections-1)*40;Allow(lastHeader+8,4);Allow(lastHeader+16,4);Allow(pe.PEHeaderStartOffset+8,4);Allow(pe.PEHeaderStartOffset+56,4);Allow(pe.PEHeaderStartOffset+64,4);Allow(pe.CorHeaderStartOffset+8,8);var diffs=Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).ToArray();R(diffs.All(allowed.Contains),"Unapproved original-file difference");R(pc.PEHeaders.SectionHeaders.Length==pb.PEHeaders.SectionHeaders.Length,"Section count");for(int i=0;i<pb.PEHeaders.SectionHeaders.Length-1;i++)R(pb.PEHeaders.SectionHeaders[i].Equals(pc.PEHeaders.SectionHeaders[i]),"Original PE section changed");int first=mb.GetTableRowCount(TableIndex.MemberRef)+1;string[] elementNames={"PreDevice","Device_boardEditor","Enemy","Enemy_boardEditor"};var added=new List<object>();for(int i=0;i<4;i++){var m=(MethodReference)ac.MainModule.LookupToken(0x0A000000+first+i);string owner="System.Collections.Generic.List`1<"+elementNames[i]+">";R(m.FullName=="System.Boolean "+owner+"::Remove(!0)"&&m.HasThis&&m.Parameters.Count==1&&m.DeclaringType.FullName==owner&&m.DeclaringType.MetadataToken.TokenType==TokenType.TypeSpec,"Closed public Remove owner/signature");R(m.Parameters[0].ParameterType is Mono.Cecil.GenericParameter g&&g.Type==GenericParameterType.Type&&g.Position==0,"Exact !0 parameter");R(m.ReturnType.FullName=="System.Boolean","Exact bool return");added.Add(new{token=$"0x{m.MetadataToken.ToInt32():X8}",name=m.FullName});}
  var oldBlob=StreamInfo(rb,"#Blob");var newBlob=StreamInfo(rc,"#Blob");var expectedBlob=rb[oldBlob.Offset..(oldBlob.Offset+oldBlob.Size)].ToList();byte[] Enc(uint v)=>v<128?new[]{(byte)v}:v<16384?new[]{(byte)((v>>8)|0x80),(byte)v}:throw new Exception("Pinned compressed token range");uint TypeCode(Mono.Cecil.TypeReference t)=>t.MetadataToken.TokenType==TokenType.TypeDef?t.MetadataToken.RID*4:t.MetadataToken.TokenType==TokenType.TypeRef?t.MetadataToken.RID*4+1:throw new Exception("Expected named type");for(int i=0;i<2;i++){string field=i==0?"device_BoardEditors":"enemy_BoardEditors";var t=(GenericInstanceType)ab.MainModule.Types.Single(t=>t.Name=="Admin_system2_boardEdior").Fields.Single(f=>f.Name==field).FieldType;var sig=new byte[]{0x15,0x12}.Concat(Enc(TypeCode(t.ElementType))).Concat(new byte[]{1,0x12}).Concat(Enc(TypeCode(t.GenericArguments[0]))).ToArray();var row=mc.GetTypeSpecification(MetadataTokens.TypeSpecificationHandle(mb.GetTableRowCount(TableIndex.TypeSpec)+1+i));R(MetadataTokens.GetHeapOffset(row.Signature)==expectedBlob.Count&&mc.GetBlobBytes(row.Signature).SequenceEqual(sig),"Exact appended TypeSpec signature");expectedBlob.Add((byte)sig.Length);expectedBlob.AddRange(sig);}R(newBlob.Size==expectedBlob.Count&&rc[newBlob.Offset..(newBlob.Offset+newBlob.Size)].SequenceEqual(expectedBlob),"Exact appended blob bytes without other changes");
  var ns=pc.PEHeaders.SectionHeaders.Last();var os=pb.PEHeaders.SectionHeaders.Last();R(ns.Name==".n29meta"&&ns.Name==os.Name&&ns.PointerToRawData==os.PointerToRawData&&ns.VirtualAddress==os.VirtualAddress&&ns.SectionCharacteristics==os.SectionCharacteristics&&ns.PointerToRelocations==os.PointerToRelocations&&ns.PointerToLineNumbers==os.PointerToLineNumbers&&ns.NumberOfRelocations==os.NumberOfRelocations&&ns.NumberOfLineNumbers==os.NumberOfLineNumbers,"Extended section identity");int rootRva=pc.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress,metaSize=pc.PEHeaders.CorHeader.MetadataDirectory.Size,raw=Offset(pc,rootRva);R(raw==b.Length&&ns.VirtualSize==raw-ns.PointerToRawData+metaSize&&c.Length==ns.PointerToRawData+ns.SizeOfRawData&&c[(raw+metaSize)..].All(z=>z==0),"Appended metadata root extent and padding");R(pc.PEHeaders.PEHeader!.SizeOfInitializedData==pb.PEHeaders.PEHeader!.SizeOfInitializedData+c.Length-b.Length,"Initialized data increment");R(pc.PEHeaders.PEHeader.SizeOfImage==((ns.VirtualAddress+ns.VirtualSize+pc.PEHeaders.PEHeader.SectionAlignment-1)/pc.PEHeaders.PEHeader.SectionAlignment)*pc.PEHeaders.PEHeader.SectionAlignment,"SizeOfImage extent");
  var r=new{input_sha256=H(b),candidate_sha256=H(c),targets=targets.Count,non_target_raw_bodies_equal=non,existing_table_rows_equal=tableRows,existing_heap_prefixes_equal=true,string_heap_added_bytes=0,original_section_locations_equal=true,non_metadata_sections_equal=true,metadata_section_extended=true,old_file_changed_bytes=diffs.Length,appended_bytes=c.Length-b.Length,new_member_refs=added,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{r.targets,r.non_target_raw_bodies_equal,r.old_file_changed_bytes,r.appended_bytes,r.pass}));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
