using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

if (args.Length != 2) { Console.Error.WriteLine("Usage: patch <input.dll> <output.dll>"); return 2; }
const string ExpectedInputSha256 = "498b34ca2db493d42676a3283edac8126180fd624d6664b3c39e855abfa905ba";
const int ExpectedMethodDefCount = 2317;
const int ExpectedFieldCount = 2802;
const uint TargetToken = 0x06000222;

static IEnumerable<TypeDefinition> AllTypes(IEnumerable<TypeDefinition> roots){ foreach(var t in roots){ yield return t; foreach(var n in AllTypes(t.NestedTypes)) yield return n; } }
static uint Raw(IMetadataTokenProvider p)=>p.MetadataToken.ToUInt32();
static string Sha256(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p))).ToLowerInvariant();
static string OperandSemantic(object? o, MethodDefinition owner){ if(o is null)return ""; if(o is Instruction i)return $"I#{owner.Body.Instructions.IndexOf(i)}"; if(o is Instruction[] sw)return "SW["+string.Join(',',sw.Select(i=>owner.Body.Instructions.IndexOf(i)))+"]"; if(o is MethodReference mr)return "M:"+mr.FullName; if(o is FieldReference fr)return "F:"+fr.FullName; if(o is TypeReference tr)return "T:"+tr.FullName; if(o is VariableDefinition vr)return $"V:{vr.Index}:{vr.VariableType.FullName}"; if(o is ParameterDefinition pr)return $"P:{pr.Index}:{pr.ParameterType.FullName}"; if(o is string s)return "S:"+Convert.ToBase64String(Encoding.UTF8.GetBytes(s)); if(o is float f)return $"R4:{BitConverter.SingleToInt32Bits(f):X8}"; if(o is double d)return $"R8:{BitConverter.DoubleToInt64Bits(d):X16}"; return "C:"+Convert.ToString(o,CultureInfo.InvariantCulture); }
static string MethodSemantic(MethodDefinition m){ var sb=new StringBuilder(); sb.Append(m.FullName).Append('|').Append(m.Attributes).Append('|').Append(m.ImplAttributes).Append('|'); if(!m.HasBody)return sb.Append("NOBODY").ToString(); sb.Append("init=").Append(m.Body.InitLocals).Append(";max=").Append(m.Body.MaxStackSize).Append(';'); foreach(var v in m.Body.Variables)sb.Append("L:").Append(v.Index).Append(':').Append(v.VariableType.FullName).Append(';'); foreach(var i in m.Body.Instructions)sb.Append("I:").Append(i.OpCode.Code).Append(':').Append(OperandSemantic(i.Operand,m)).Append(';'); foreach(var h in m.Body.ExceptionHandlers){ int Idx(Instruction? x)=>x is null?-1:m.Body.Instructions.IndexOf(x); sb.Append("EH:").Append(h.HandlerType).Append(':').Append(Idx(h.TryStart)).Append(':').Append(Idx(h.TryEnd)).Append(':').Append(Idx(h.HandlerStart)).Append(':').Append(Idx(h.HandlerEnd)).Append(':').Append(Idx(h.FilterStart)).Append(':').Append(h.CatchType?.FullName??"").Append(';'); } return sb.ToString(); }
static string FieldSemantic(FieldDefinition f){ var attrs=string.Join(',',f.CustomAttributes.Select(a=>a.AttributeType.FullName).OrderBy(x=>x,StringComparer.Ordinal)); var c=f.HasConstant?Convert.ToString(f.Constant,CultureInfo.InvariantCulture)??"<null>":"<none>"; return $"{f.FullName}|{f.Attributes}|{f.FieldType.FullName}|const={c}|ca={attrs}"; }
static MethodReference FindRef(MethodDefinition m, Func<MethodReference,bool> pred, string label){ foreach(var i in m.Body.Instructions) if((i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt)&&i.Operand is MethodReference mr&&pred(mr)) return mr; throw new InvalidDataException("missing ref "+label); }
static int CountCalls(MethodDefinition m, Func<MethodReference,bool> pred)=>m.Body.Instructions.Count(i=>(i.OpCode==OpCodes.Call||i.OpCode==OpCodes.Callvirt)&&i.Operand is MethodReference mr&&pred(mr));
static FieldDefinition Field(TypeDefinition t,string n)=>t.Fields.Single(f=>f.Name==n);

var input=Path.GetFullPath(args[0]); var output=Path.GetFullPath(args[1]); var inputSha=Sha256(input); Console.WriteLine($"INPUT_SHA256 {inputSha}"); if(inputSha!=ExpectedInputSha256)throw new InvalidDataException("input SHA mismatch");
var beforeMethods=new Dictionary<uint,string>(); var beforeFields=new Dictionary<uint,string>();
using(var module=ModuleDefinition.ReadModule(input,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(module.Types).ToList(); var methods=types.SelectMany(t=>t.Methods).ToList(); var fields=types.SelectMany(t=>t.Fields).ToList();
 if(methods.Count!=ExpectedMethodDefCount||fields.Count!=ExpectedFieldCount)throw new InvalidDataException("metadata count drift"); foreach(var m in methods)beforeMethods[Raw(m)]=MethodSemantic(m); foreach(var f in fields)beforeFields[Raw(f)]=FieldSemantic(f);
 var rm=types.Single(t=>t.FullName=="ResourceManager"); var target=rm.Methods.Single(m=>m.Name=="Load_card_Choose_Sprites"&&m.IsStatic&&m.Parameters.Count==0); if(Raw(target)!=TargetToken)throw new InvalidDataException("token drift"); if(!target.HasBody||target.Body.CodeSize!=636||target.Body.Variables.Count!=37)throw new InvalidDataException($"prepatch fingerprint size={target.Body.CodeSize} locals={target.Body.Variables.Count}");
 var spriteType=Field(rm,"card_Choose_Data").FieldType.GetElementType(); const string Sprite="UnityEngine.Sprite"; if(spriteType.FullName!=Sprite)throw new InvalidDataException("sprite type drift");
 var combine2=FindRef(target,mr=>mr.DeclaringType.FullName=="System.IO.Path"&&mr.Name=="Combine"&&mr.Parameters.Count==2,"Path.Combine/2");
 var intToString=FindRef(target,mr=>mr.DeclaringType.FullName=="System.Int32"&&mr.Name=="ToString"&&mr.Parameters.Count==0,"Int32.ToString");
 var concat2=FindRef(target,mr=>mr.DeclaringType.FullName=="System.String"&&mr.Name=="Concat"&&mr.Parameters.Count==2,"String.Concat/2");
 var loadSprite=FindRef(target,mr=>mr is GenericInstanceMethod gim&&gim.GenericArguments.Count==1&&gim.GenericArguments[0].FullName==Sprite&&gim.ElementMethod.DeclaringType.FullName=="InternalResourceLoader"&&gim.ElementMethod.Name=="Load","Load<Sprite>");
 var arrays=new[]{("card_Choose_Data","data"),("card_Choose_LvBackgrounds","lv"),("card_Choose_Innerlining","innerlining"),("card_Choose_Outerlining","outerlining")}; var order=Field(rm,"card_Choose_OrderArabesques");
 Console.WriteLine("TARGET_METHOD token=0x06000222 type=ResourceManager method=Load_card_Choose_Sprites code_size=636 locals=37 invalid_offset=0x018D");
 Console.WriteLine("NATIVE_AUTHORITY token=0x06000222 address=0x0000000180338130 function_end=0x0000000180338500 load_sprite_calls=33 path_combine2_calls=34 int_tostring_calls=33 concat2_calls=33 array_stores=33 loops=7x4_plus_5x1");
 Console.WriteLine("RUNTIME_CAUSAL_EVIDENCE strict_run=34767194659 candidate=498b34ca2db493d42676a3283edac8126180fd624d6664b3c39e855abfa905ba exception=InvalidProgramException method=ResourceManager.Load_card_Choose_Sprites il_offset=0x018D opcode=stloc_2");
 target.Body.Instructions.Clear(); target.Body.Variables.Clear(); target.Body.ExceptionHandlers.Clear(); target.Body.InitLocals=true; target.Body.MaxStackSize=4;
 var pathVar=new VariableDefinition(module.TypeSystem.String); var iVar=new VariableDefinition(module.TypeSystem.Int32); target.Body.Variables.Add(pathVar); target.Body.Variables.Add(iVar); var il=target.Body.GetILProcessor();
 il.Append(il.Create(OpCodes.Ldstr,"sprites")); il.Append(il.Create(OpCodes.Ldstr,"Card_Choose")); il.Append(il.Create(OpCodes.Call,combine2)); il.Append(il.Create(OpCodes.Stloc,pathVar)); il.Append(il.Create(OpCodes.Ldc_I4_0)); il.Append(il.Create(OpCodes.Stloc,iVar));
 var body1=il.Create(OpCodes.Nop); var check1=il.Create(OpCodes.Ldloc,iVar); il.Append(il.Create(OpCodes.Br,check1)); il.Append(body1);
 foreach(var (fieldName,prefix) in arrays){ il.Append(il.Create(OpCodes.Ldsfld,Field(rm,fieldName))); il.Append(il.Create(OpCodes.Ldloc,iVar)); il.Append(il.Create(OpCodes.Ldloc,pathVar)); il.Append(il.Create(OpCodes.Ldstr,prefix)); il.Append(il.Create(OpCodes.Ldloca,iVar)); il.Append(il.Create(OpCodes.Call,intToString)); il.Append(il.Create(OpCodes.Call,concat2)); il.Append(il.Create(OpCodes.Call,combine2)); il.Append(il.Create(OpCodes.Call,loadSprite)); il.Append(il.Create(OpCodes.Stelem_Ref)); }
 il.Append(il.Create(OpCodes.Ldloc,iVar)); il.Append(il.Create(OpCodes.Ldc_I4_1)); il.Append(il.Create(OpCodes.Add)); il.Append(il.Create(OpCodes.Stloc,iVar)); il.Append(check1); il.Append(il.Create(OpCodes.Ldc_I4_7)); il.Append(il.Create(OpCodes.Blt,body1));
 il.Append(il.Create(OpCodes.Ldc_I4_0)); il.Append(il.Create(OpCodes.Stloc,iVar)); var body2=il.Create(OpCodes.Nop); var check2=il.Create(OpCodes.Ldloc,iVar); il.Append(il.Create(OpCodes.Br,check2)); il.Append(body2);
 il.Append(il.Create(OpCodes.Ldsfld,order)); il.Append(il.Create(OpCodes.Ldloc,iVar)); il.Append(il.Create(OpCodes.Ldloc,pathVar)); il.Append(il.Create(OpCodes.Ldstr,"orderArabesques")); il.Append(il.Create(OpCodes.Ldloca,iVar)); il.Append(il.Create(OpCodes.Call,intToString)); il.Append(il.Create(OpCodes.Call,concat2)); il.Append(il.Create(OpCodes.Call,combine2)); il.Append(il.Create(OpCodes.Call,loadSprite)); il.Append(il.Create(OpCodes.Stelem_Ref)); il.Append(il.Create(OpCodes.Ldloc,iVar)); il.Append(il.Create(OpCodes.Ldc_I4_1)); il.Append(il.Create(OpCodes.Add)); il.Append(il.Create(OpCodes.Stloc,iVar)); il.Append(check2); il.Append(il.Create(OpCodes.Ldc_I4_5)); il.Append(il.Create(OpCodes.Blt,body2)); il.Append(il.Create(OpCodes.Ret));
 module.Write(output); Console.WriteLine("PATCH_RESOURCE_MANAGER_CARD_CHOOSE_SPRITES method_body_changes=1 field_metadata_changes=0 source=pc_native_exact_two_loop_reconstruction");
}
Console.WriteLine($"OUTPUT_SHA256 {Sha256(output)}");
using(var after=ModuleDefinition.ReadModule(output,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate})){
 var types=AllTypes(after.Types).ToList(); var methods=types.SelectMany(t=>t.Methods).ToList(); var fields=types.SelectMany(t=>t.Fields).ToList(); var rm=types.Single(t=>t.FullName=="ResourceManager"); var target=rm.Methods.Single(m=>m.Name=="Load_card_Choose_Sprites"&&m.IsStatic&&m.Parameters.Count==0);
 int loads=CountCalls(target,mr=>mr is GenericInstanceMethod gim&&gim.GenericArguments.Count==1&&gim.GenericArguments[0].FullName=="UnityEngine.Sprite"&&gim.ElementMethod.DeclaringType.FullName=="InternalResourceLoader"&&gim.ElementMethod.Name=="Load"); int combines=CountCalls(target,mr=>mr.DeclaringType.FullName=="System.IO.Path"&&mr.Name=="Combine"&&mr.Parameters.Count==2); int tos=CountCalls(target,mr=>mr.DeclaringType.FullName=="System.Int32"&&mr.Name=="ToString"&&mr.Parameters.Count==0); int cats=CountCalls(target,mr=>mr.DeclaringType.FullName=="System.String"&&mr.Name=="Concat"&&mr.Parameters.Count==2); int stores=target.Body.Instructions.Count(i=>i.OpCode==OpCodes.Stelem_Ref); if(loads!=33||combines!=34||tos!=33||cats!=33||stores!=33||target.Body.Variables.Count!=2)throw new InvalidDataException($"reopen shape loads={loads} combines={combines} tos={tos} cats={cats} stores={stores} locals={target.Body.Variables.Count}"); Console.WriteLine("REOPEN_RESOURCE_MANAGER_CARD_CHOOSE_SPRITES_PASS token=0x06000222 load_sprite_calls=33 path_combine2_calls=34 int_tostring_calls=33 concat2_calls=33 array_stores=33 locals=2");
 int changed=0,unchanged=0; foreach(var m in methods){ if(!beforeMethods.TryGetValue(Raw(m),out var old))throw new InvalidDataException("new method"); if(old==MethodSemantic(m))unchanged++; else{changed++; if(Raw(m)!=TargetToken)throw new InvalidDataException($"unexpected method drift 0x{Raw(m):X8}");}} if(changed!=1||unchanged!=2316)throw new InvalidDataException($"isolation mismatch {unchanged}/{changed}"); Console.WriteLine("SEMANTIC_ISOLATION_PASS untouched_methods=2316 changed_methods=1 target_token=0x06000222");
 if(fields.Count!=beforeFields.Count)throw new InvalidDataException("field count drift"); foreach(var f in fields)if(!beforeFields.TryGetValue(Raw(f),out var old)||old!=FieldSemantic(f))throw new InvalidDataException($"field drift 0x{Raw(f):X8}"); Console.WriteLine("FIELD_METADATA_ISOLATION_PASS unchanged_fields=2802 changed_fields=0");
 var loadSprites=rm.Methods.Single(m=>m.Name=="LoadSprites"&&m.IsStatic&&m.Parameters.Count==0); var helperCalls=CountCalls(loadSprites,mr=>mr.FullName==target.FullName); if(helperCalls!=1)throw new InvalidDataException($"LoadSprites helper call count={helperCalls}"); Console.WriteLine("LOADSPRITES_RECOVERY_PRESERVATION_PASS helper_calls=1");
 var start=rm.Methods.Single(m=>m.Name=="Start"&&m.IsStatic&&m.Parameters.Count==0); if(CountCalls(start,mr=>mr.Name=="LoadSprites"&&mr.DeclaringType.FullName=="ResourceManager")!=1)throw new InvalidDataException("Start LoadSprites drift"); Console.WriteLine("START_RECOVERY_PRESERVATION_PASS load_sprites_calls=1");
 var cc=types.Single(t=>t.FullName=="Card_Choose"); if(cc.Fields.Count(f=>f.CustomAttributes.Any(a=>a.AttributeType.FullName=="UnityEngine.SerializeField"))!=17)throw new InvalidDataException("Card_Choose SerializeField drift"); Console.WriteLine("CARD_CHOOSE_SERIALIZEFIELD_PRESERVATION_PASS fields=17");
}
return 0;
