using Mono.Cecil;using Mono.Cecil.Cil;using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using MD=Mono.Cecil.MethodDefinition;
byte[]b=File.ReadAllBytes(args[0]);using var a=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var p=new PEReader(new MemoryStream(b));int off(int r){var s=p.PEHeaders.SectionHeaders.Single(s=>r>=s.VirtualAddress&&r<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+r-s.VirtualAddress;}MD method(int t)=>(MD)a.MainModule.LookupToken(t);void rf(int token,float old,float value){var m=method(token);var i=m.Body.Instructions.First(i=>i.OpCode==OpCodes.Ldc_R4&&(float)i.Operand==old);BitConverter.GetBytes(value).CopyTo(b,off(m.RVA)+12+i.Offset+1);}var first=method(0x060000EC);int h=off(first.RVA),root=off(p.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress);
switch(args[2]){
case "bank-x":rf(0x060000EC,92,93);break;
case "device-op":{var m=method(0x06000331);var i=m.Body.Instructions.Single(i=>i.Operand is MethodReference r&&r.Name=="op_Subtraction");int t=a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName=="UnityEngine.Vector3 UnityEngine.Vector3::op_Addition(UnityEngine.Vector3,UnityEngine.Vector3)").MetadataToken.ToInt32();BitConverter.GetBytes(t).CopyTo(b,off(m.RVA)+12+i.Offset+1);break;}
case "flicker-gain":rf(0x060003C7,0.6863f,0.5f);break;
case "sun-z":{var m=method(0x060003CB);var i=m.Body.Instructions.Single(i=>i.OpCode==OpCodes.Ldc_R4&&(float)i.Operand==0&&i.Next.OpCode==OpCodes.Mul);BitConverter.GetBytes(1f).CopyTo(b,off(m.RVA)+12+i.Offset+1);break;}
case "shadow-y":{var m=method(0x060003D4);var i=m.Body.Instructions.Single(i=>i.Operand is FieldReference f&&f.Name=="fZ_shadow");int t=a.MainModule.GetTypes().Single(t=>t.FullName=="Projectile").Fields.Single(f=>f.Name=="fY").MetadataToken.ToInt32();BitConverter.GetBytes(t).CopyTo(b,off(m.RVA)+12+i.Offset+1);break;}
case "track-source":{var m=method(0x060003D7);var i=m.Body.Instructions.First(i=>i.Operand is FieldReference f&&f.Name=="projectileSprite");int t=a.MainModule.GetTypes().Single(t=>t.FullName=="Projectile").Fields.Single(f=>f.Name=="track").MetadataToken.ToInt32();BitConverter.GetBytes(t).CopyTo(b,off(m.RVA)+12+i.Offset+1);break;}
case "missile-unordered":{var m=method(0x060003FB);var i=m.Body.Instructions.Single(i=>i.OpCode==OpCodes.Bge_S);b[off(m.RVA)+12+i.Offset]=0x34;break;}
case "zombie-reset":{var m=method(0x06000482);var i=m.Body.Instructions.Single(i=>i.Operand is MethodReference r&&r.Name=="ResetMoveSpeed");int at=off(m.RVA)+12+i.Offset;Array.Clear(b,at,5);b[at]=0x26;break;}
case "popup-index":{var m=method(0x0600066E);var i=m.Body.Instructions.Single(i=>i.OpCode==OpCodes.Ldc_I4_S&&(sbyte)i.Operand==9);b[off(m.RVA)+12+i.Offset+1]=8;break;}
case "bleep-zero":{var m=method(0x0600067C);var i=m.Body.Instructions.Single(i=>i.Operand is MethodReference r&&r.Name=="get_position");int zero=a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName=="UnityEngine.Vector3 UnityEngine.Vector3::get_zero()").MetadataToken.ToInt32();h=off(m.RVA);byte[]code=b[(h+12)..(h+12+m.Body.CodeSize)];var replacement=code[..i.Offset].Concat(new byte[]{0x26,0x28}).Concat(BitConverter.GetBytes(zero)).Concat(code[(i.Offset+5)..]).ToArray();foreach(var branch in m.Body.Instructions.Where(x=>x.Operand is Instruction j&&x.OpCode.OperandType==OperandType.ShortInlineBrTarget)){var target=(Instruction)branch.Operand;if(branch.Offset<i.Offset&&target.Offset>i.Offset)replacement[branch.Offset+1]++;}Array.Clear(b,h+12,m.Body.CodeSize+1);replacement.CopyTo(b,h+12);BitConverter.GetBytes(replacement.Length).CopyTo(b,h+4);break;}
case "old-heap":b[root+p.GetMetadataReader().GetHeapMetadataOffset(HeapIndex.String)+2]^=1;break;
case "locals":BitConverter.GetBytes(method(0x060003C7).Body.LocalVarToken.ToInt32()).CopyTo(b,off(first.RVA)+8);break;
case "section-flags":int sh=p.PEHeaders.PEHeaderStartOffset+p.PEHeaders.CoffHeader.SizeOfOptionalHeader+(p.PEHeaders.CoffHeader.NumberOfSections-1)*40;b[sh+36]^=1;break;
case "body-padding":b[h+12+first.Body.CodeSize]=1;break;
case "max-stack":BitConverter.GetBytes((ushort)9).CopyTo(b,h+2);break;
case "non-target":b[off(method(0x06000091).RVA)+12]^=1;break;
default:throw new Exception();}File.WriteAllBytes(args[1],b);
