using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Security.Cryptography;

if (args.Length != 2) return 2;
static string Sha(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p))).ToLowerInvariant();
static IEnumerable<TypeDefinition> All(IEnumerable<TypeDefinition> ts){foreach(var t in ts){yield return t;foreach(var n in All(t.NestedTypes))yield return n;}}
static string Scope(IMetadataScope? s)=>s switch{AssemblyNameReference a=>a.Name,ModuleDefinition m=>m.Assembly?.Name?.Name??m.Name,ModuleReference r=>r.Name,_=>s?.ToString()??"<null>"};
static string Op(object? o)=>o switch{null=>"",Instruction i=>$"IL_{i.Offset:X4}",Instruction[] a=>string.Join(',',a.Select(i=>$"IL_{i.Offset:X4}")),VariableDefinition v=>$"V_{v.Index}:{v.VariableType.FullName}",MethodReference m=>$"{m.FullName}@{Scope(m.DeclaringType.Scope)}",FieldReference f=>$"{f.FullName}@{Scope(f.DeclaringType.Scope)}",TypeReference t=>$"{t.FullName}@{Scope(t.Scope)}",_=>o.ToString()??""};
static void DumpMethod(MethodDefinition m){Console.WriteLine($"BEGIN_METHOD token=0x{m.MetadataToken.ToUInt32():X8} rid={m.MetadataToken.RID} method={m.FullName} rva=0x{m.RVA:X} hasbody={m.HasBody}");if(!m.HasBody){Console.WriteLine("END_METHOD");return;}Console.WriteLine($"BODY code_size={m.Body.CodeSize} maxstack={m.Body.MaxStackSize} locals={m.Body.Variables.Count} initlocals={m.Body.InitLocals} handlers={m.Body.ExceptionHandlers.Count}");foreach(var v in m.Body.Variables)Console.WriteLine($"MLOCAL index={v.Index} type={v.VariableType.FullName}");for(int i=0;i<m.Body.Instructions.Count;i++){var x=m.Body.Instructions[i];Console.WriteLine($"MIL index={i} offset=0x{x.Offset:X4} op={x.OpCode.Code} operand={Op(x.Operand)}");}Console.WriteLine("END_METHOD");}
var path=Path.GetFullPath(args[0]);var expected=args[1].ToLowerInvariant();var actual=Sha(path);if(actual!=expected)throw new InvalidDataException($"sha {actual}");Console.WriteLine($"INPUT_SHA256 {actual}");using var module=ModuleDefinition.ReadModule(path,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate});var types=All(module.Types).ToList();var methods=types.SelectMany(t=>t.Methods).ToList();
string[] typeNames={"Administrator","System0","System1","System2","System3","Admin_system2_boardEdior","SystemSkipLevel","MainUIController","BoardManager","Board","ResourceManager","InternalResourceLoader","SuppliesInitialValue","GlobalStaticVars"};
foreach(var name in typeNames){var matches=types.Where(t=>t.FullName==name).ToList();foreach(var t in matches){Console.WriteLine($"BEGIN_TYPE token=0x{t.MetadataToken.ToUInt32():X8} name={t.FullName}");foreach(var f in t.Fields)Console.WriteLine($"TYPE_FIELD token=0x{f.MetadataToken.ToUInt32():X8} rid={f.MetadataToken.RID} name={f.Name} type={f.FieldType.FullName} static={f.IsStatic}");foreach(var m in t.Methods)Console.WriteLine($"TYPE_METHOD token=0x{m.MetadataToken.ToUInt32():X8} rid={m.MetadataToken.RID} name={m.Name} sig={m.FullName}");Console.WriteLine("END_TYPE");}}
uint[] tokens={0x06000005,0x06000007,0x06000008,0x06000009,0x0600000A,0x06000073,0x06000081,0x06000088,0x0600009E,0x060000A4,0x06000169,0x0600016F,0x06000231,0x0600020A,0x06000154,0x06000636,0x06000647};
foreach(var tok in tokens){var m=methods.Single(x=>x.MetadataToken.ToUInt32()==tok);DumpMethod(m);}
Console.WriteLine($"READONLY_ADMINISTRATOR_START_DEPENDENCY_PROBE_PASS mutation=0 methods={tokens.Length} types={typeNames.Length}");return 0;
