using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;using System.Runtime.InteropServices;
public class DependencyException:Exception{}public class Obj{}public class Text:Obj{}public class Group:Obj{}public class Game:Obj{}public class Frame:Obj{}public class Mesh:Obj{}public class Renderer:Obj{}
public class DebugObj:Obj{public Text?DPSText;public float dPS;}public class Zombie:Obj{public Group?sortingGroup;public float fY,fZ;}public class Clip:Obj{public Renderer?_meshRenderer;}
public static class State{
public static Obj self=new();public static Text text=new(),textB=new();public static string formatted="formatted";public static Group group=new(),groupB=new();public static Game game=new();public static Frame frame=new();public static Mesh mesh=new();public static Renderer renderer=new(),rendererB=new();public static int token,mode,hook,order,setCalls,updateCalls;public static ulong trace;public static bool argsOK;public static uint input,formattedValue;public static Bounds value,alternate,output;
public static int Id(object?o){object?[]all={null,self,text,textB,formatted,group,groupB,game,frame,mesh,renderer,rendererB};for(int i=0;i<all.Length;i++)if(ReferenceEquals(o,all[i]))return i;throw new Exception("Unknown identity");}public static void Ev(int e,object?r=null)=>trace=unchecked(trace*131+(uint)(e*32+Id(r)));public static void Check(object?r){if(r==null)throw new NullReferenceException();}public static void Fail(){Ev(32);throw new DependencyException();}
public static string?Format(ref float p,string fmt){Ev(1);argsOK&=System.Runtime.CompilerServices.Unsafe.AreSame(ref p,ref((DebugObj)self).dPS)&&fmt=="DPS:0.0";formattedValue=Fixture.B(p);if(hook==1)((DebugObj)self).DPSText=textB;if(hook==2)((DebugObj)self).DPSText=null;if(hook==3)((DebugObj)self).dPS=Fixture.F(0x87654321);if(mode==3)Fail();return mode==4?null:formatted;}
public static void SetText(Text?r,string?s){Check(r);Ev(2,r);argsOK&=ReferenceEquals(s,mode==4?null:formatted);setCalls++;if(hook==4)((DebugObj)self).dPS=Fixture.F(0x12345678);if(mode==5)Fail();}
public static bool Equality(Obj?r,Obj?other){Ev(3,r);argsOK&=other==null;if(hook==1)((Zombie)self).sortingGroup=groupB;if(hook==2)((Zombie)self).sortingGroup=null;if(mode==6)Fail();return r==null||mode==7;}
public static Game?GameObject(Obj?r){Check(r);Ev(4,r);return mode==8?null:game;}public static Group?AddGroup(Game?r){Check(r);Ev(5,r);if(mode==9)Fail();return mode==10?null:groupB;}
public static void Layer(Group?r,string s){Check(r);Ev(6,r);argsOK&=s=="Entity";if(hook==3)((Zombie)self).sortingGroup=groupB;if(hook==4)((Zombie)self).sortingGroup=null;if(hook==5)((Zombie)self).fY=Fixture.F(0x87654321);if(mode==11)Fail();}
public static void SetOrder(Group?r,int v){Check(r);Ev(7,r);order=v;setCalls++;if(mode==12)Fail();}
public static Frame?GetFrame(Clip?r){Check(r);Ev(8,r);if(mode==13)Fail();return mode==1?null:frame;}public static Mesh?CachedMesh(Frame?r){Check(r);Ev(9,r);if(mode==14)Fail();return mode==2?null:mesh;}
public static Bounds MeshBounds(Mesh?r){Check(r);Ev(10,r);if(mode==15)Fail();return value;}public static Bounds RendererBounds(Renderer?r){Check(r);Ev(10,r);var b=ReferenceEquals(r,rendererB)?alternate:value;if(mode==15)Fail();return b;}
public static void Update(Clip?r){Check(r);Ev(11,r);updateCalls++;if(hook==1)r!._meshRenderer=rendererB;if(hook==2)r!._meshRenderer=null;if(mode==16)Fail();}
public static bool Truth(Obj?r){Ev(12,r);if(hook==3)((Clip)self)._meshRenderer=rendererB;if(hook==4)((Clip)self)._meshRenderer=null;if(mode==17)Fail();return r!=null&&mode!=7;}
}
public static class Fixture{
static Type T(TypeReference r)=>r.FullName switch{"System.Void"=>typeof(void),"System.Object"=>typeof(object),"System.Boolean"=>typeof(bool),"System.Single"=>typeof(float),"System.String"=>typeof(string),"System.Int32"=>typeof(int),"System.NullReferenceException"=>typeof(NullReferenceException),"UnityEngine.Bounds"=>typeof(Bounds),"UnityEngine.Mesh"=>typeof(Mesh),"UnityEngine.MeshRenderer" or "UnityEngine.Renderer"=>typeof(Renderer),"UnityEngine.GameObject"=>typeof(Game),"UnityEngine.Rendering.SortingGroup"=>typeof(Group),"UnityEngine.Object" or "UnityEngine.Component"=>typeof(Obj),"TMPro.TextMeshProUGUI" or "TMPro.TMP_Text"=>typeof(Text),"DebugManager"=>typeof(DebugObj),"Zombie"=>typeof(Zombie),"FTRuntime.SwfClip"=>typeof(Clip),"FTRuntime.SwfClipAsset/Frame"=>typeof(Frame),_=>throw new Exception("Unmapped type "+r)};
static Delegate Emit(MethodDefinition m,string mutation){int rid=(int)m.MetadataToken.RID;var ret=T(m.ReturnType);var dm=new DynamicMethod(m.FullName+mutation,ret,new[]{T(m.DeclaringType)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var strLocal=il.DeclareLocal(typeof(string));if(mutation=="illegal_stack"&&rid==0x17B)il.Emit(RO.Pop);
foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];if(i.Operand is FieldReference f){if(mutation=="group_wrong_y"&&rid==0x477&&f.Name=="fY")f=new FieldReference("fZ",f.FieldType,f.DeclaringType);il.Emit(op,T(f.DeclaringType).GetField(f.Name)??throw new Exception("Field "+f));continue;}if(i.Operand is TypeReference tr){il.Emit(op,T(tr));continue;}
if(i.Operand is MethodReference r){string name=r.Name switch{"ToString"=>nameof(State.Format),"set_text"=>nameof(State.SetText),"op_Equality"=>nameof(State.Equality),"get_gameObject"=>nameof(State.GameObject),"AddComponent"=>nameof(State.AddGroup),"set_sortingLayerName"=>nameof(State.Layer),"set_sortingOrder"=>nameof(State.SetOrder),"GetCurrentBakedFrame"=>nameof(State.GetFrame),"get_CachedMesh"=>nameof(State.CachedMesh),"get_bounds" when r.DeclaringType.FullName=="UnityEngine.Mesh"=>nameof(State.MeshBounds),"get_bounds"=>nameof(State.RendererBounds),"Internal_UpdateMesh"=>nameof(State.Update),"op_Implicit"=>nameof(State.Truth),_=>throw new Exception("Unmapped call "+r)};if(mutation=="world_skip_update"&&rid==0x838&&r.Name=="Internal_UpdateMesh"){il.Emit(RO.Pop);continue;}il.Emit(RO.Call,typeof(State).GetMethod(name)!);if(mutation=="debug_reread_receiver"&&rid==0x17B&&r.Name=="ToString"){il.Emit(RO.Stloc,strLocal);il.Emit(RO.Pop);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(DebugObj).GetField("DPSText")!);il.Emit(RO.Ldloc,strLocal);}continue;}
if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="local_wrong_branch"&&rid==0x837&&op.Value==RO.Brfalse_S.Value)op=RO.Brtrue_S;if(mutation=="world_wrong_branch"&&rid==0x838&&op.Value==RO.Brfalse_S.Value)op=RO.Brtrue_S;il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(i.Operand is string s){if(mutation=="group_wrong_name"&&rid==0x477)s="wrong";il.Emit(op,s);continue;}if(i.Operand is float fval){if(mutation=="debug_wrong_reset"&&rid==0x17B&&fval==0)fval=1;il.Emit(op,fval);continue;}if(i.Operand is int iv){if(mutation=="group_wrong_fallback"&&rid==0x477&&iv==int.MinValue)iv=0;il.Emit(op,iv);continue;}if(i.Operand!=null)throw new Exception("Unsupported operand "+i);il.Emit(op);}return dm.CreateDelegate(System.Linq.Expressions.Expression.GetDelegateType(new[]{T(m.DeclaringType),ret}));}
public static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));public static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static Bounds From(ulong[]r,int at){var bytes=new byte[24];for(int i=0;i<6;i++)BitConverter.GetBytes((uint)r[at+i]).CopyTo(bytes,i*4);return MemoryMarshal.Read<Bounds>(bytes);}static uint[]Bits(Bounds b){byte[]bytes=new byte[24];MemoryMarshal.Write(bytes,in b);return Enumerable.Range(0,6).Select(i=>BitConverter.ToUInt32(bytes,i*4)).ToArray();}
static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>fs,List<ulong[]>rows,bool stop=false){int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int t=(int)r[0];State.token=t;State.mode=(int)r[1];State.hook=(int)r[2];State.self=t switch{0x0600017B=>new DebugObj{DPSText=State.mode==1?null:State.text,dPS=F(r[3])},0x06000477=>new Zombie{sortingGroup=State.mode==1?null:State.group,fY=F(r[3])},_=>new Clip{_meshRenderer=State.mode==1?null:State.renderer}};State.value=From(r,4);State.alternate=From(r,10);State.output=From(Enumerable.Repeat(0xdeadbeefUL,6).ToArray(),0);State.trace=0;State.setCalls=State.updateCalls=0;State.order=unchecked((int)0xdeadbeef);State.formattedValue=0xdeadbeef;State.argsOK=true;int err=0;try{var ret=fs[t].DynamicInvoke(State.self);if(t is 0x06000837 or 0x06000838)State.output=(Bounds)ret!;}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(30);err=1;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){err=3;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
var observed=new List<ulong>{State.trace,(uint)err,State.argsOK?1UL:0};observed.AddRange(Bits(State.output).Select(x=>(ulong)x));observed.AddRange(new ulong[]{State.self is DebugObj d?B(d.dPS):0,(uint)State.Id((State.self as DebugObj)?.DPSText),State.self is Zombie z?B(z.fY):0,(uint)State.Id((State.self as Zombie)?.sortingGroup),unchecked((uint)State.order),(uint)State.setCalls,(uint)State.updateCalls,t==0x06000838?(uint)State.Id(((Clip)State.self)._meshRenderer):0,State.formattedValue});if(observed.Count!=18)throw new Exception("Schema");var bad=observed.Select((v,i)=>(v,i)).Where(x=>x.v!=r[x.i+16]).ToArray();count++;if(bad.Length>0){fail++;if(samples.Count<10)samples.Add(t.ToString("X8")+" case="+count+" mode="+State.mode+" hook="+State.hook+" diffs="+string.Join(',',bad.Select(x=>(x.i+16)+":"+x.v+"/"+r[x.i+16])));if(stop)return(count,fail,samples);}}return(count,fail,samples);}
public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]ts={0x0600017B,0x06000477,0x06000837,0x06000838};var ms=ts.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=16384||rows.Any(r=>r.Length!=34)||ts.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Rows");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","debug_wrong_reset","debug_reread_receiver","group_wrong_y","group_wrong_name","group_wrong_fallback","local_wrong_branch","world_skip_update","world_wrong_branch"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=4,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Four actual candidate CIL callers vs unchanged original native callers with ready metadata and recording formatter/text/Unity/mesh/frame/update/GC/exception helpers. Complete24-byte Bounds return; explicit original float/int edge behavior. No whole helper/engine/game/iOS proof; full conversion/all game units deferred to100."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures,report.controls}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
