using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;
public class DependencyException:Exception{}public class Info{public int id;public int marker;}
public class DeviceInfo:Info{public DeviceInfo(){State.Construct(this);}public DeviceInfo(bool silent){}}
public class ZombieInfo:Info{public ZombieInfo(){State.Construct(this);}public ZombieInfo(bool silent){}}
public static class Json{public static string ToJson(object o,bool pretty){State.Event(11);State.prettyOK&=pretty;State.Throw("serialize");State.serializedID=((Info)o).id;return State.serialized="SERIAL:"+((Info)o).id.ToString(CultureInfo.InvariantCulture);}public static T?FromJson<T>(string s)where T:class{State.Event(8);State.parseCalls++;State.argsOK&=typeof(T)==State.Kind&&s==State.readResult;State.Throw("parse");return State.mode==4?null:(T)(object)State.parsed;}}
public static class State{
 public static int token,mode,input,formatted,logs,writes,parseCalls,constructorCalls,serializedID;public static ulong trace;public static bool argsOK,prettyOK,realIO;public static string fail="",root="/fixture-root",finalPath="",parentPath="",readResult="",serialized="";public static Info?created;public static Info parsed=new();public static Type Kind=>token==0x06000225?typeof(DeviceInfo):typeof(ZombieInfo);
 public static void Reset(int t,int id,int mode0){token=t;input=id;mode=mode0;formatted=logs=writes=parseCalls=constructorCalls=serializedID=0;trace=0;argsOK=prettyOK=true;realIO=false;fail="";root="/fixture-root";finalPath=parentPath=readResult=serialized="";created=null;parsed=token==0x06000225?new DeviceInfo(true){id=777,marker=33}:new ZombieInfo(true){id=777,marker=33};}
 public static void Event(int n){trace=(trace<<4)|(uint)n;}public static void Throw(string s){if(fail==s)throw new DependencyException();}
 public static void Construct(Info o){Event(9);Event(10);constructorCalls++;created=o;o.id=-1;o.marker=17;argsOK&=o.GetType()==Kind;Throw("ctor");}
 public static string StreamingAssets(){Event(1);Throw("root");return root;}
 public static string Combine4(string a,string b,string c,string d){Event(2);argsOK&=a==root&&b=="jsons"&&c==(token==0x06000225?"DeviceData":"ZombieData")&&d==(token==0x06000225?"DeviceInfo":"ZombieInfo");Throw("path");return parentPath=Path.Combine(a,b,c,d);}
 public static string Format(ref int value){Event(3);formatted=value;argsOK&=value==input;Throw("format");return value.ToString(CultureInfo.CurrentCulture);}
 public static string Concat(string a,string b){Event(4);argsOK&=a==input.ToString(CultureInfo.CurrentCulture)&&b==".json";return string.Concat(a,b);}
 public static string Combine2(string a,string b){Event(5);argsOK&=a==parentPath&&b==input.ToString(CultureInfo.CurrentCulture)+".json";return finalPath=Path.Combine(a,b);}
 public static string?ReadJson_StreamingAssets(string p){Event(6);argsOK&=p==finalPath;Throw("read");return mode==0?null:readResult=mode==1?"":mode==3?" ":"{fixture}";}
 public static bool Empty(string?s){Event(7);return string.IsNullOrEmpty(s);}
 public static void Log(object o){Event(logs==0?12:logs==1?13:15);argsOK&=logs==0?Equals(o,finalPath):logs==1?Equals(o,token==0x06000225?"缺失装置信息文件":"缺失僵尸信息文件"):Equals(o,token==0x06000225?"已生成装置信息文件模板":"已生成缺失的僵尸信息文件模板");logs++;Throw("log"+logs);}
 public static void WriteAllText(string p,string s){Event(14);writes++;argsOK&=p==finalPath&&s==serialized;Throw("write");if(realIO){var full=Path.GetFullPath(p);if(!full.StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.Ordinal))throw new Exception("IO path outside owned fixture directory");File.WriteAllText(full,s);}}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["DeviceInfo"]=typeof(DeviceInfo),["ZombieInfo"]=typeof(ZombieInfo),["System.String"]=typeof(string),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.NullReferenceException"]=typeof(NullReferenceException)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t);
 static MethodInfo M(MethodReference m){if(m is GenericInstanceMethod g&&m.Name=="FromJson")return typeof(Json).GetMethod(nameof(Json.FromJson))!.MakeGenericMethod(T(g.GenericArguments.Single()));if(m.Name=="ToJson")return typeof(Json).GetMethod(nameof(Json.ToJson))!;string name=m.Name switch{"get_streamingAssetsPath"=>nameof(State.StreamingAssets),"ToString"=>nameof(State.Format),"Combine"=>m.Parameters.Count==4?nameof(State.Combine4):nameof(State.Combine2),"Concat"=>nameof(State.Concat),"ReadJson_StreamingAssets"=>nameof(State.ReadJson_StreamingAssets),"IsNullOrEmpty"=>nameof(State.Empty),"Log"=>nameof(State.Log),"WriteAllText"=>nameof(State.WriteAllText),_=>throw new Exception("Missing method "+m)};return typeof(State).GetMethod(name)!;}
 static Func<int,Info?>Emit(MethodDefinition m,string mutation){var ret=T(m.ReturnType);var dm=new DynamicMethod(m.Name+mutation,ret,new[]{typeof(int)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ldnull);il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(operand is FieldReference f){if(mutation=="wrong_id"&&op==RO.Stfld){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4,42);changed=true;}il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}
   if(operand is MethodReference method){if(method.Name==".ctor"){il.Emit(op,T(method.DeclaringType).GetConstructor(Type.EmptyTypes)!);continue;}if(method.Name=="ToJson"&&mutation=="wrong_pretty"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}if(method.Name=="WriteAllText"&&mutation=="skip_write"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(method.Name=="FromJson"&&mutation=="skip_parse"){il.Emit(RO.Pop);il.Emit(RO.Ldnull);changed=true;continue;}il.Emit(op,M(method));continue;}
   if(operand is Mono.Cecil.Cil.Instruction branch){if(mutation=="empty_inverted"&&op==RO.Brtrue){op=RO.Brfalse;changed=true;}il.Emit(op,labels[branch]);continue;}
   if(operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(operand is Mono.Cecil.ParameterDefinition parameter){if(mutation=="wrong_argument"&&op==RO.Ldarg){il.Emit(RO.Ldc_I4,42);changed=true;}else il.Emit(op,(short)parameter.Index);continue;}
   if(operand is string s){if(mutation=="wrong_suffix"&&s==".json"){s=".txt";changed=true;}if(mutation=="wrong_message"&&s.StartsWith("已生成")){s="wrong message";changed=true;}il.Emit(op,s);continue;}if(operand is int iv){il.Emit(op,iv);continue;}if(operand==null){il.Emit(op);continue;}throw new Exception("Unsupported "+operand);
  }
  if(!changed)throw new Exception("Mutation not applied "+mutation);if(ret==typeof(DeviceInfo)){var fn=(Func<int,DeviceInfo?>)dm.CreateDelegate(typeof(Func<int,DeviceInfo?>));return arg=>fn(arg);}else{var fn=(Func<int,ZombieInfo?>)dm.CreateDelegate(typeof(Func<int,ZombieInfo?>));return arg=>fn(arg);}
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(int token,Func<int,Info?>fn,List<ulong[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();void Check(bool ok,string label){count++;if(!ok)failures.Add(label);}
  foreach(var row in rows){int id=unchecked((int)row[0]);State.Reset(token,id,(int)row[1]);bool ok=false;try{var r=fn(id);int kind=r==null?0:ReferenceEquals(r,State.created)?1:ReferenceEquals(r,State.parsed)?2:3;ok=State.trace==row[2]&&State.formatted==unchecked((int)row[3])&&kind==(int)row[4]&&(r?.id??0)==unchecked((int)row[5])&&State.logs==(int)row[6]&&State.writes==(int)row[7]&&State.parseCalls==(int)row[8]&&State.constructorCalls==(int)row[9]&&State.serializedID==unchecked((int)row[10])&&State.argsOK&&row[11]==1&&State.prettyOK&&row[12]==1&&(r==null||r.GetType()==State.Kind&&r.marker==(kind==1?17:33));}catch(Exception e)when(e is not InvalidProgramException){ok=false;}Check(ok,"native-row:"+index++);if(stop&&failures.Count>0)return new(count,failures);}
  foreach(string stage in new[]{"read","ctor","serialize","log1","write","parse"}){State.Reset(token,123,stage=="parse"?2:0);State.fail=stage;bool thrown=false;try{fn(123);}catch(DependencyException){thrown=true;}bool ok=thrown&&State.argsOK&&State.logs==(stage=="log1"?1:stage=="write"?2:0)&&State.writes==(stage=="write"?1:0)&& (stage is "read" or "parse"?State.created==null:State.created!=null&&State.created.id==(stage=="ctor"?-1:123));Check(ok,"partial-error:"+stage);}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var all=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();var failures=new List<string>();var controls=new List<object>();int count=0,errors=0;bool cp=true;string ioRoot=Path.Combine(Path.GetTempPath(),"godspvz-native48-fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(ioRoot);
  foreach(int token in new[]{0x06000225,0x06000230}){var m=(MethodDefinition)a.MainModule.LookupToken(token);var rows=all.Where(r=>r[0]==$"0x{token:X8}").Select(r=>r.Skip(1).Select(ulong.Parse).ToArray()).ToList();if(rows.Count!=4096)throw new Exception("Native rows");var fn=Emit(m,"none");var result=Cases(token,fn,rows);count+=result.Cases;failures.AddRange(result.Failures);
   foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","wrong_id","wrong_pretty","skip_write","skip_parse","empty_inverted","wrong_argument","wrong_suffix","wrong_message"}){bool detected=false;string?error=null;try{detected=Cases(token,Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{token=$"0x{token:X8}",mutation,detected,tool_error=error});}
   var oldCulture=CultureInfo.CurrentCulture;try{foreach(string culture in new[]{"en-US","de-DE","ja-JP","ar-SA"})foreach(int id in new[]{int.MinValue,-1,0,1,int.MaxValue}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(culture);State.Reset(token,id,0);State.realIO=true;State.root=ioRoot;Directory.CreateDirectory(Path.Combine(ioRoot,"jsons",token==0x06000225?"DeviceData":"ZombieData",token==0x06000225?"DeviceInfo":"ZombieInfo"));var r=fn(id);count++;string expected=Path.Combine(ioRoot,"jsons",token==0x06000225?"DeviceData":"ZombieData",token==0x06000225?"DeviceInfo":"ZombieInfo",id.ToString(CultureInfo.CurrentCulture)+".json");if(r?.id!=id||State.finalPath!=expected||File.ReadAllText(expected)!=State.serialized||State.logs!=3||State.writes!=1||!State.prettyOK||!State.argsOK)failures.Add("actual-coreclr-IO:"+token+":"+culture+":"+id);}}finally{CultureInfo.CurrentCulture=oldCulture;}
  }
  bool pass=failures.Count==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=count,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,io_fixture_directory=ioRoot,scope="Original resource callers with supplied string/class/MethodInfo identities and complete class-init precondition; allocator/ctor/path/format/read/emptiness/JSON/log/write dependencies recorded. CLR CIL executes with public data constructors/JSON/reader/log doubles, actual Path/String/numeric operations and 40 real File.WriteAllText/ReadAllText cases under four cultures. Caller control/arguments/nullable parse/template/partial errors tested. Data constructors, Unity JSON/loader/class-init/native throw and whole game/iOS remain unproven; newobj-null branch is not CLR behavior-tested.",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
