using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}
public class Owner{public Board?board;}
public class Board{public Config?boardConfig;}
public class Config{}
public class Device{}
public class Grid{public Device?device_top,device_sheath,device_common,device_bottom;}
public class Frame{public string?[]?Labels;}
public class Clip{public string?_sequence;}
public class Ctrl{public Clip?_clip;}
public class Flower{public static string?[]?_idleSequences;}
public static class State{
public static Owner owner=new();public static Board board=new();public static Config config=new();public static Device[]devices=Enumerable.Range(0,5).Select(_=>new Device()).ToArray();public static Grid grid=new();public static Frame frame=new();public static Clip clip=new();public static Ctrl ctrl=new();public static int mode,hook,step,ranges,compares,gx,gy,mask,prev;public static ulong trace;public static int watchdogs;public static bool argsOK;public static Vector3 value;public static string?[] a=Array.Empty<string?>(),b=Array.Empty<string?>();public static readonly string?[] strings={null,"a","b",new string('a',1),string.Empty};
public static void Ev(int n)=>trace=unchecked(trace*16+(uint)n);public static string?S(int id)=>strings[id];public static int Id(object?o){if(o==null)return 0;for(int i=1;i<strings.Length;i++)if(ReferenceEquals(o,strings[i]))return i;throw new Exception("String identity");}public static int Did(object?o){if(o==null)return 0;for(int i=0;i<devices.Length;i++)if(ReferenceEquals(o,devices[i]))return i+1;throw new Exception("Device identity");}
public static Vector3 Position(Config?c,int x,int y){if(c==null)throw new NullReferenceException();Ev(1);argsOK&=ReferenceEquals(c,config)&&x==gx&&y==gy;if(hook==1)owner.board=null;if(hook==2)board.boardConfig=null;if(mode==3)throw new DependencyException();return value;}
public static Grid?GetGrid(Board?r,int x,int y){if(r==null)throw new NullReferenceException();Ev(2);argsOK&=ReferenceEquals(r,board)&&x==gx&&y==gy;if(mode==3)throw new DependencyException();if(hook==3)owner.board=null;return mode==2?null:grid;}
public static void ChangeDevice(int i,Device?d){if(i==0)grid.device_top=d;else if(i==1)grid.device_sheath=d;else if(i==2)grid.device_common=d;else grid.device_bottom=d;}
public static bool Truth(Device?d){Ev(3);argsOK&=ReferenceEquals(d,mode==5?null:devices[step]);int current=step++;if(mode==4&&current==hook)throw new DependencyException();if(hook==1)ChangeDevice(current,null);if(hook==2)ChangeDevice(current,devices[4]);return(mask&(1<<current))!=0;}
public static Frame?GetFrame(Clip?c){Ev(4);argsOK&=ReferenceEquals(c,clip);if(mode==3)throw new DependencyException();return mode==1?null:frame;}
public static int Range(int min,int max){if(ranges>=32){watchdogs++;throw new DependencyException();}Ev(5);ranges++;int expected=mode==3?0:mode==8?1:4;argsOK&=min==0&&max==expected;if(mode==13||((mode==8||mode==14)&&ranges==9))throw new DependencyException();if(mode==4)Flower._idleSequences=null;if(mode==5){b=new[]{S(1)};Flower._idleSequences=b;}if(mode==6){b=new[]{S(4),S(2),S(3),S(4)};Flower._idleSequences=b;}if(mode==3)return 0;if(mode==5)return 3;if(mode==7)return -1;if(mode==14)return 0;return ranges<=hook?0:mode==8?0:1;}
public static bool Unequal(string?c,string?p){Ev(6);compares++;argsOK&=Id(p)==prev;if(mode==12)throw new DependencyException();if(mode==9)clip._sequence=S(2);if(mode==10)Flower._idleSequences=b;return c!=p;}
public static string?Normalize(string?s)=>s??string.Empty;
}
public static class Fixture{
static Type T(TypeReference r)=>r.FullName switch{"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Sprite"=>typeof(Sprite),"System.Boolean"=>typeof(bool),"System.Int32"=>typeof(int),"System.Single"=>typeof(float),"System.String"=>typeof(string),"System.String[]"=>typeof(string[]),"System.IntPtr"=>typeof(IntPtr),"System.NullReferenceException"=>typeof(NullReferenceException),"System.IndexOutOfRangeException"=>typeof(IndexOutOfRangeException),"EnemySelecter" or "DeviceManager"=>typeof(Owner),"Board"=>typeof(Board),"BoardConfig"=>typeof(Config),"Grid"=>typeof(Grid),"Device"=>typeof(Device),"FTRuntime.SwfClip"=>typeof(Clip),"FTRuntime.SwfClipController"=>typeof(Ctrl),"FTRuntime.SwfClipAsset/Frame"=>typeof(Frame),"FlashTools.Examples.PurpleFlowerLogic"=>typeof(Flower),_=>throw new Exception("Unmapped "+r)};
static FieldInfo Field(FieldReference r)=>r.DeclaringType.FullName=="System.String"?typeof(string).GetField("Empty")!:T(r.DeclaringType).GetField(r.Name)!;
static Delegate Emit(MethodDefinition m,string mutation){var pars=new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();var ret=T(m.ReturnType);var dm=new DynamicMethod(m.FullName+mutation,ret,pars,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var cacheDev=il.DeclareLocal(typeof(Device));var cacheArray=il.DeclareLocal(typeof(string[]));int top=0,arrays=0;bool applied=mutation=="none";int rid=(int)m.MetadataToken.RID;
if(mutation=="illegal_stack"&&rid==0x1A9){il.Emit(RO.Pop);applied=true;}
foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];if(i.Operand is FieldReference f){if(rid==0x188&&f.Name=="device_top"){top++;if(mutation=="cache_device"&&top==2){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cacheDev);applied=true;continue;}}if(rid==0x903&&f.Name=="_idleSequences"){arrays++;if(mutation=="cache_array"&&arrays==2){il.Emit(RO.Ldloc,cacheArray);applied=true;continue;}}if(mutation=="priority"&&rid==0x188&&f.Name=="device_top"){il.Emit(op,typeof(Grid).GetField("device_bottom")!);applied=true;}else if(mutation=="empty_fallback"&&rid==0x83D&&f.Name=="Empty"){il.Emit(RO.Ldstr,"b");applied=true;}else il.Emit(op,Field(f));if(rid==0x188&&f.Name=="device_top"&&top==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cacheDev);}if(rid==0x903&&f.Name=="_idleSequences"&&arrays==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cacheArray);}continue;}
if(i.Operand is MethodReference r){string name=r.Name switch{"GetGridPosition"=>nameof(State.Position),"GetGrid"=>nameof(State.GetGrid),"op_Implicit"=>nameof(State.Truth),"GetCurrentBakedFrame"=>nameof(State.GetFrame),"Range"=>nameof(State.Range),"op_Inequality"=>nameof(State.Unequal),_=>throw new Exception("Unmapped "+r)};if(mutation=="reference_truth"&&rid==0x188&&r.Name=="op_Implicit"){il.Emit(RO.Ldnull);il.Emit(RO.Ceq);il.Emit(RO.Ldc_I4_0);il.Emit(RO.Ceq);applied=true;}else il.Emit(RO.Call,typeof(State).GetMethod(name)!);continue;}
if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="flip_loop"&&rid==0x903){op=RO.Brtrue_S;applied=true;}if(mutation=="flip_label_bound"&&rid==0x83D&&op.Value==RO.Bge_S.Value){op=RO.Bgt_S;applied=true;}il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(i.Operand is float fval){if(mutation=="offset"&&rid==0x1A9&&fval==57f){fval=58f;applied=true;}il.Emit(op,fval);continue;}if(i.Operand!=null)throw new Exception("Unsupported "+i);
if(mutation=="wrong_grid_arg"&&rid==0x1A9&&op.Value==RO.Ldarg_3.Value){op=RO.Ldarg_2;applied=true;}if(mutation=="recapture_previous"&&rid==0x903&&op.Value==RO.Ldloc_0.Value){il.Emit(RO.Ldarg_1);il.Emit(RO.Ldfld,typeof(Ctrl).GetField("_clip")!);il.Emit(RO.Ldfld,typeof(Clip).GetField("_sequence")!);applied=true;continue;}il.Emit(op);if(mutation=="normalize_null_label"&&rid==0x83D&&op.Value==RO.Ldelem_Ref.Value){il.Emit(RO.Call,typeof(State).GetMethod(nameof(State.Normalize))!);applied=true;}}
if(!applied&&mutation!="none"&&((rid==0x1A9&&mutation is "offset" or "wrong_grid_arg" or "illegal_stack")||(rid==0x188&&mutation is "cache_device" or "priority" or "reference_truth")||(rid==0x83D&&mutation is "empty_fallback" or "flip_label_bound" or "normalize_null_label")||(rid==0x903&&mutation is "cache_array" or "recapture_previous" or "flip_loop")))throw new Exception("Mutation not applied "+mutation);var dt=System.Linq.Expressions.Expression.GetDelegateType(pars.Concat(new[]{ret}).ToArray());return dm.CreateDelegate(dt);}
static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static int I(ulong v)=>unchecked((int)v);
static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>functions,List<ulong[]>rows,bool stop=false){State.watchdogs=0;int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int token=(int)r[0];State.mode=(int)r[1];State.hook=(int)r[2];State.gx=I(r[3]);State.gy=I(r[4]);State.mask=(int)r[8];State.prev=(int)r[9];State.value=new(F(r[10]),F(r[11]),F(r[12]));State.owner=new(){board=State.mode==1?null:State.board};State.board.boardConfig=State.mode==2?null:State.config;State.grid=new(){device_top=State.mode==5?null:State.devices[0],device_sheath=State.mode==5?null:State.devices[1],device_common=State.mode==5?null:State.devices[2],device_bottom=State.mode==5?null:State.devices[3]};State.a=Enumerable.Range(0,(int)r[7]).Select(i=>i==2?null:State.S(i+1)).ToArray();State.frame=new(){Labels=State.mode==2?null:State.a};State.clip=new(){_sequence=State.S(State.prev)};State.ctrl=new(){_clip=State.mode==1?null:State.clip};if(token==0x06000903){State.a=Enumerable.Range(0,State.mode==3?0:State.mode==8?1:4).Select(i=>State.S(i+1)).ToArray();State.b=new[]{State.S(2),State.S(2),State.S(3),State.S(4)};Flower._idleSequences=State.mode==2?null:State.a;}
State.trace=0;State.argsOK=true;State.step=State.ranges=State.compares=0;int err=0;object?output=null;var v=new Vector3(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));try{output=token switch{0x060001A9=>functions[token].DynamicInvoke(State.owner,I(r[5]),State.gy,State.gx),0x06000188=>functions[token].DynamicInvoke(State.owner,State.gx,State.gy),0x0600083D=>functions[token].DynamicInvoke(State.clip,I(r[6])),0x06000903=>functions[token].DynamicInvoke(null,State.mode==0?null:State.ctrl),_=>throw new Exception()};if(token==0x060001A9)v=(Vector3)output!;}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(14);err=1;}catch(TargetInvocationException e)when(e.InnerException is IndexOutOfRangeException){State.Ev(15);err=2;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){State.Ev(13);err=3;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
int result=err!=0?0:token==0x06000188?State.Did(output):token==0x060001A9?0:State.Id(output);bool ok=State.trace==r[13]&&err==(int)r[14]&&B(v.x)==r[15]&&B(v.y)==r[16]&&B(v.z)==r[17]&&result==(int)r[18]&&State.step==(int)r[19]&&State.ranges==(int)r[20]&&State.compares==(int)r[21]&&State.argsOK&&r[22]==1&&r[23]==1;count++;if(!ok){fail++;if(samples.Count<10)samples.Add(token.ToString("X8")+":"+count+" trace "+State.trace+"/"+r[13]+" err "+err+"/"+r[14]+" result "+result+"/"+r[18]+" args="+State.argsOK);if(stop)return(count,fail,samples);}}return(count,fail,samples);}
public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x060001A9,0x06000188,0x0600083D,0x06000903};var ms=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=16384||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int positiveWatchdogs=State.watchdogs;int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","offset","wrong_grid_arg","cache_device","priority","reference_truth","empty_fallback","flip_label_bound","normalize_null_label","cache_array","recapture_previous","flip_loop"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&positiveWatchdogs==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=4,positive_harness_watchdog_triggers=positiveWatchdogs,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Actual four caller CIL and original PC caller traces under recorded grid/Unity/random/string/exception dependencies, initialized metadata, typed aliases, pinned public Vector3 and CLR string fields/operators. Original static-array reloading, previous-sequence capture, null/bounds/priority/float operations and finite loop prefixes; extra 32-call harness guard is only mutant containment and was never reached by the positive candidate; no original Unity/random/class-init/throw or whole-game/iOS proof."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
