using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using System.Security.Cryptography;using System.Text.Json;using Mono.Cecil;using MD=Mono.Cecil.MethodDefinition;using MR=Mono.Cecil.MethodReference;using FR=Mono.Cecil.FieldReference;
static class RepairNative50{
 static void R(bool b,string s){if(!b)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Align(int x,int a)=>(x+a-1)/a*a;
 class IL{public List<byte>B=new();Dictionary<string,int>labels=new();List<(int,string)>branches=new();public IL O(params byte[]b){B.AddRange(b);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}public IL Ref(byte op,IMetadataTokenProvider t)=>O(op).I(t.MetadataToken.ToInt32());public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Arg(int i)=>O((byte)(2+i));public IL Float(float x)=>O(0x22).I(BitConverter.SingleToInt32Bits(x));public IL A(int i)=>O(0x12,(byte)i);public IL L(int i)=>O((byte)(6+i));public IL S(int i)=>O((byte)(10+i));public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Br(byte op,string s){O(op);branches.Add((B.Count,s));I(0);return this;}public byte[]Done(){foreach(var(p,s)in branches)BitConverter.GetBytes(labels[s]-p-4).CopyTo(B,p);return B.ToArray();}}
 static void CopyTo(this byte[]b,List<byte>l,int p){for(int i=0;i<b.Length;i++)l[p+i]=b[i];}
 static int Off(PEReader pe,int rva){var s=pe.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static int Main(string[]args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[]args){R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh input/output/report");byte[]before=File.ReadAllBytes(args[0]);R(H(before)=="d8b152232285ea317e288a076cc399e3cce560cb2ae3f94f707e6f3d4c2d955b","Pinned Native49 input");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);var module=asm.MainModule;using var pe=new PEReader(new MemoryStream(before));var md=pe.GetMetadataReader();var targets=new Dictionary<int,byte[]>();
  FR Field(string owner,string name)=>module.Types.Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);
  FR External(string owner,string name)=>Enumerable.Range(1,md.GetTableRowCount(TableIndex.MemberRef)).Select(i=>module.LookupToken(0x0A000000+i)).OfType<FR>().First(f=>f.DeclaringType.FullName==owner&&f.Name==name);
  MR Call(int token)=>(MR)module.LookupToken(token);var vector=Call(0x0A00009C);R(vector.FullName=="System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)","Pinned pure public Vector3 ctor");var sample=(MD)module.LookupToken(0x06000427);R(sample.Body.LocalVarToken.ToInt32()==0x110000A4&&sample.Body.Variables.Count==1&&sample.Body.Variables[0].VariableType.FullName=="UnityEngine.Vector3","Existing single Vector3 local signature");
  var il=new IL().Arg(0).Ref(0x7C,Field("Prop","mousePosition")).Ref(0x7B,External("UnityEngine.Vector2","x")).Arg(0).Ref(0x7C,Field("Prop","mousePosition")).Ref(0x7B,External("UnityEngine.Vector2","y")).Float(0).Ref(0x73,vector).S(0).Arg(0).Ref(0x7B,Field("Prop","propType")).Int(5).Br(0x40,"position");
  foreach(string f in new[]{"x","y"})il.A(0).O(0x25).Ref(0x7B,External("UnityEngine.Vector3",f)).Float(50).O(0x58).Ref(0x7D,External("UnityEngine.Vector3",f));
  il.Label("position").Arg(0).Ref(0x7B,Field("Prop","propImagex")).Ref(0x6F,Call(0x0A00002E)).L(0).Ref(0x6F,Call(0x0A000038)).O(0x2A);targets.Add(0x06000404,il.Done());
  // Signed int32 remainder/division, unchecked multiplication, then float conversion.
  // Compute before get_transform and retain the original zero Z and page store order.
  il=new IL().Arg(2).Int(3).O(0x5D).Int(230).O(0x5A,0x6B).Float(140).O(0x58).Float(-210).Arg(2).Int(3).O(0x5B).Int(360).O(0x5A,0x6B,0x59).Float(0).Ref(0x73,vector).S(0).Arg(1).Ref(0x6F,Call(0x0A00002E)).L(0).Ref(0x6F,Call(0x0A000042)).Arg(1).Ref(0x6F,Call(0x2B000090)).Int(0).Ref(0x7D,Field("Card_Choose","page")).O(0x2A);targets.Add(0x060006BE,il.Done());
  var ph=pe.PEHeaders;var opt=ph.PEHeader!;var last=ph.SectionHeaders.Last();R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==before.Length&&last.SectionCharacteristics==(SectionCharacteristics)0x40000040&&ph.CorHeader!.StrongNameSignatureDirectory.Size==0&&opt.CertificateTableDirectory.Size==0,"Pinned unsigned EOF section");
  int oldRoot=Off(pe,ph.CorHeader.MetadataDirectory.RelativeVirtualAddress),rootSize=ph.CorHeader.MetadataDirectory.Size;byte[]meta=before[oldRoot..(oldRoot+rootSize)];int cursor=before.Length;var locations=new Dictionary<int,int>();foreach(var pair in targets){cursor=Align(cursor,4);locations.Add(pair.Key,cursor);cursor+=12+pair.Value.Length;}int rootOffset=Align(cursor,4);var after=new byte[Align(rootOffset+rootSize,opt.FileAlignment)];before.CopyTo(after,0);var rows=new List<object>();
  foreach(var pair in targets){var m=(MD)module.LookupToken(pair.Key);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target signatures");int body=locations[pair.Key],newRva=last.VirtualAddress+body-last.PointerToRawData;byte[]code=pair.Value;ushort flags=(ushort)(0x3003|(m.Body.InitLocals?0x10:0));BitConverter.GetBytes(flags).CopyTo(after,body);BitConverter.GetBytes((ushort)4).CopyTo(after,body+2);BitConverter.GetBytes(code.Length).CopyTo(after,body+4);BitConverter.GetBytes(0x110000A4).CopyTo(after,body+8);code.CopyTo(after,body+12);int row=md.GetTableMetadataOffset(TableIndex.MethodDef)+(checked((int)m.MetadataToken.RID)-1)*md.GetTableRowSize(TableIndex.MethodDef);BitConverter.GetBytes(newRva).CopyTo(meta,row);rows.Add(new{token=$"0x{pair.Key:X8}",method=m.FullName,old_rva=m.RVA,new_rva=newRva,body_offset=body,code_size=code.Length,code_sha256=H(code),max_stack=4,local_sig=0x110000A4,init_locals=m.Body.InitLocals});}
  meta.CopyTo(after,rootOffset);int sh=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40,virtualSize=rootOffset-last.PointerToRawData+rootSize;BitConverter.GetBytes(virtualSize).CopyTo(after,sh+8);BitConverter.GetBytes(after.Length-last.PointerToRawData).CopyTo(after,sh+16);BitConverter.GetBytes(opt.SizeOfInitializedData+after.Length-before.Length).CopyTo(after,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+virtualSize,opt.SectionAlignment)).CopyTo(after,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(after,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(last.VirtualAddress+rootOffset-last.PointerToRawData).CopyTo(after,ph.CorHeaderStartOffset+8);
  File.WriteAllBytes(args[1],after);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(before),candidate_sha256=H(after),methods=rows,metadata=new{old_root=oldRoot,new_root=rootOffset,size=rootSize},scope="Two appended complete position bodies with existing single-Vector3 local signature and public references; two exact MethodDef RVAs change, every other existing row/heap and all old method slots remain unchanged."},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine("CANDIDATE "+H(after));
 }
}
