using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text;
using Mono.Cecil;
static class AuditNative42 {
 static void R(bool b,string s){if(!b)throw new Exception(s);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static byte[] Root(PEReader p)=>p.GetMetadata().GetContent().ToArray();
 static int Offset(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static (int Offset,int Size) StreamInfo(byte[] r,string name){int v=BitConverter.ToInt32(r,12),p=((16+v+3)/4)*4+2,count=BitConverter.ToUInt16(r,p);p+=2;for(int i=0;i<count;i++){int e=Array.IndexOf(r,(byte)0,p+8);if(Encoding.ASCII.GetString(r,p+8,e-p-8)==name)return(BitConverter.ToInt32(r,p),BitConverter.ToInt32(r,p+4));p=((e+1+3)/4)*4;}throw new Exception("Missing stream "+name);}
 static int Main(string[] args){try{var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="c0fc9c8162daeb526ab5508698fbcfd63d44bfa4cec4937c47cb65d73d809961","Pinned parent");using var pb=new PEReader(new MemoryStream(b));using var pc=new PEReader(new MemoryStream(c));var mb=pb.GetMetadataReader();var mc=pc.GetMetadataReader();var rb=Root(pb);var rc=Root(pc);using var ab=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var ac=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[1]);var report=JsonDocument.Parse(File.ReadAllText(args[2]));var targets=report.RootElement.GetProperty("methods").EnumerateArray().Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).ToHashSet();R(targets.SetEquals(new[]{0x06000771,0x06000817}),"Target cardinality");var allowed=new HashSet<int>();void Allow(int p,int n){for(int j=0;j<n;j++)allowed.Add(p+j);}var tableRows=new List<object>();
  foreach(TableIndex t in Enum.GetValues<TableIndex>()){int n=mb.GetTableRowCount(t);int delta=t==TableIndex.MemberRef?1:0;R(mc.GetTableRowCount(t)==n+delta,"Table count "+t);if(n==0)continue;int size=mb.GetTableRowSize(t);R(size==mc.GetTableRowSize(t),"Row width "+t);int x=mb.GetTableMetadataOffset(t),y=mc.GetTableMetadataOffset(t);R(rb[x..(x+n*size)].SequenceEqual(rc[y..(y+n*size)]),"Existing row drift "+t);tableRows.Add(new{table=t.ToString(),rows=n,row_size=size});}
  foreach(HeapIndex h in Enum.GetValues<HeapIndex>()){int n=mb.GetHeapSize(h);R(h is HeapIndex.Blob or HeapIndex.String?mc.GetHeapSize(h)>=n:mc.GetHeapSize(h)==n,"Heap size "+h);int x=mb.GetHeapMetadataOffset(h),y=mc.GetHeapMetadataOffset(h);R(rb[x..(x+n)].SequenceEqual(rc[y..(y+n)]),"Heap bytes "+h);}foreach(string stream in new[]{"#Strings","#Blob","#US","#GUID"}){var x=StreamInfo(rb,stream);var y=StreamInfo(rc,stream);R((stream is "#Blob" or "#Strings"?y.Size>=x.Size:y.Size==x.Size)&&rb[x.Offset..(x.Offset+x.Size)].SequenceEqual(rc[y.Offset..(y.Offset+x.Size)]),"Entire stream prefix including padding "+stream);}
  int prefix=((16+BitConverter.ToInt32(rb,12)+3)/4)*4+4;R(rb[..prefix].SequenceEqual(rc[..prefix]),"Root version/flags/stream count");var tb=StreamInfo(rb,"#~");var tc=StreamInfo(rc,"#~");R(rb[tb.Offset..(tb.Offset+16)].SequenceEqual(rc[tc.Offset..(tc.Offset+16)]),"Tables header and valid mask");R(BitConverter.ToUInt64(rc,tc.Offset+16)==(BitConverter.ToUInt64(rb,tb.Offset+16)&~(1UL<<10)),"Only MemberRef sorted bit may clear");
  int non=0;foreach(var h in mb.MethodDefinitions){int token=MetadataTokens.GetToken(h);var bm=mb.GetMethodDefinition(h);var cm=mc.GetMethodDefinition(h);R(bm.RelativeVirtualAddress==cm.RelativeVirtualAddress,"RVA drift");if(bm.RelativeVirtualAddress==0)continue;var ob=pb.GetMethodBody(bm.RelativeVirtualAddress);var nb=pc.GetMethodBody(cm.RelativeVirtualAddress);int off=Offset(pb,bm.RelativeVirtualAddress);if(targets.Contains(token)){R(ob.LocalSignature==nb.LocalSignature&&ob.LocalVariablesInitialized==nb.LocalVariablesInitialized&&ob.ExceptionRegions.Length==0&&nb.ExceptionRegions.Length==0,"Target local/header flags");var row=report.RootElement.GetProperty("methods").EnumerateArray().Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==off,"Pinned body offset");Allow(off+2,6);Allow(off+12,ob.GetILBytes()!.Length);var md=(Mono.Cecil.MethodDefinition)ac.MainModule.LookupToken(token);R(md.Body.Instructions.All(i=>i.Operand is not Mono.Cecil.Cil.Instruction j||md.Body.Instructions.Contains(j)),"Invalid branch");R(!md.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Ldstr&&i.Operand is string s&&(s.Contains("Indirect call:")||s.Contains("Warning:"))),"Unresolved reconstruction");R(H(nb.GetILBytes()!)==row.GetProperty("code_sha256").GetString(),"Reopened code digest");}else{R(ob.Size==nb.Size,"Non-target size");R(b[off..(off+ob.Size)].SequenceEqual(c[off..(off+nb.Size)]),"Non-target raw body "+token.ToString("X8"));non++;}}
  var pe=pb.PEHeaders;int lastHeader=pe.PEHeaderStartOffset+pe.CoffHeader.SizeOfOptionalHeader+(pe.CoffHeader.NumberOfSections-1)*40;Allow(lastHeader+8,4);Allow(lastHeader+16,4);Allow(pe.PEHeaderStartOffset+8,4);Allow(pe.PEHeaderStartOffset+56,4);Allow(pe.PEHeaderStartOffset+64,4);Allow(pe.CorHeaderStartOffset+8,8);var diffs=Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).ToArray();R(diffs.All(allowed.Contains),"Unapproved original-file difference");R(pc.PEHeaders.SectionHeaders.Length==pb.PEHeaders.SectionHeaders.Length,"Section count");for(int i=0;i<pb.PEHeaders.SectionHeaders.Length-1;i++)R(pb.PEHeaders.SectionHeaders[i].Equals(pc.PEHeaders.SectionHeaders[i]),"Original PE section changed");int first=mb.GetTableRowCount(TableIndex.MemberRef)+1;var m=(MethodReference)ac.MainModule.LookupToken(0x0A000000+first);R(m.FullName=="System.Void UnityEngine.AnimationCurve::set_keys(UnityEngine.Keyframe[])"&&m.HasThis&&m.DeclaringType.MetadataToken.ToInt32()==0x01000050&&m.ReturnType.FullName=="System.Void"&&m.Parameters.Count==1&&m.Parameters[0].ParameterType is ArrayType ar&&ar.ElementType.IsValueType&&ar.ElementType.MetadataToken.ToInt32()==0x01000092,"Exact public array setter binding");var added=new[]{new{token=$"0x{m.MetadataToken.ToInt32():X8}",name=m.FullName}};
  var stringOld=StreamInfo(rb,"#Strings");var stringNew=StreamInfo(rc,"#Strings");var blobOld=StreamInfo(rb,"#Blob");var blobNew=StreamInfo(rc,"#Blob");var member=mc.GetMemberReference(MetadataTokens.MemberReferenceHandle(first));byte[] nameBytes=Encoding.UTF8.GetBytes("set_keys\0"),signature=new byte[]{0x20,1,1,0x1D,0x11,0x82,0x49};int nameIndex=MetadataTokens.GetHeapOffset(member.Name),sigIndex=MetadataTokens.GetHeapOffset(member.Signature);R(mc.GetBlobBytes(member.Signature).SequenceEqual(signature),"Exact value-type Keyframe array signature");R(stringNew.Size==stringOld.Size+(nameIndex>=stringOld.Size?nameBytes.Length:0),"Exact added name length");if(nameIndex>=stringOld.Size)R(nameIndex==stringOld.Size&&rc[(stringNew.Offset+nameIndex)..(stringNew.Offset+stringNew.Size)].SequenceEqual(nameBytes),"Exact appended setter name");R(blobNew.Size==blobOld.Size+(sigIndex>=blobOld.Size?signature.Length+1:0),"Exact blob growth");if(sigIndex>=blobOld.Size)R(sigIndex==blobOld.Size&&rc[(blobNew.Offset+sigIndex)..(blobNew.Offset+blobNew.Size)].SequenceEqual(new[]{(byte)signature.Length}.Concat(signature)),"Exact appended signature bytes");
  var ns=pc.PEHeaders.SectionHeaders.Last();var os=pb.PEHeaders.SectionHeaders.Last();R(ns.Name==".n29meta"&&ns.Name==os.Name&&ns.PointerToRawData==os.PointerToRawData&&ns.VirtualAddress==os.VirtualAddress&&ns.SectionCharacteristics==os.SectionCharacteristics&&ns.PointerToRelocations==os.PointerToRelocations&&ns.PointerToLineNumbers==os.PointerToLineNumbers&&ns.NumberOfRelocations==os.NumberOfRelocations&&ns.NumberOfLineNumbers==os.NumberOfLineNumbers,"Extended section identity");int rootRva=pc.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress,metaSize=pc.PEHeaders.CorHeader.MetadataDirectory.Size,raw=Offset(pc,rootRva);R(raw==b.Length&&ns.VirtualSize==raw-ns.PointerToRawData+metaSize&&c.Length==ns.PointerToRawData+ns.SizeOfRawData&&c[(raw+metaSize)..].All(z=>z==0),"Appended metadata root extent and padding");R(pc.PEHeaders.PEHeader!.SizeOfInitializedData==pb.PEHeaders.PEHeader!.SizeOfInitializedData+c.Length-b.Length,"Initialized data increment");R(pc.PEHeaders.PEHeader.SizeOfImage==((ns.VirtualAddress+ns.VirtualSize+pc.PEHeaders.PEHeader.SectionAlignment-1)/pc.PEHeaders.PEHeader.SectionAlignment)*pc.PEHeaders.PEHeader.SectionAlignment,"SizeOfImage extent");
  var r=new{input_sha256=H(b),candidate_sha256=H(c),targets=targets.Count,non_target_raw_bodies_equal=non,existing_table_rows_equal=tableRows,existing_heap_prefixes_equal=true,string_heap_added_bytes=stringNew.Size-stringOld.Size,blob_heap_added_bytes=blobNew.Size-blobOld.Size,original_section_locations_equal=true,non_metadata_sections_equal=true,metadata_section_extended=true,old_file_changed_bytes=diffs.Length,appended_bytes=c.Length-b.Length,new_member_refs=added,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{r.targets,r.non_target_raw_bodies_equal,r.old_file_changed_bytes,r.appended_bytes,r.pass}));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
