using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using Vector3=UnityEngine.Vector3;
public class DependencyException:Exception{}
public class Clip{}public class Controller{}
public class Assoc<T>{public List<T>items=new();public Assoc(bool input){}public Assoc(){State.Record(typeof(T)==typeof(Clip)?1:2);}}
public class SafeList<T>{public List<T>items=new();public SafeList(bool input){}public SafeList(){State.Record(3);}}
public class MonoBehaviour{public MonoBehaviour(bool input){}public MonoBehaviour(){State.baseCalls++;State.receiver=this;State.cameraSnapshot=this is Camera c?Fixture.CameraBits(c):null;State.smoothingSnapshot=this is Camera s&&s.MovementSmoothing;State.managerRateSnapshot=this is Manager rate?rate._rateScale:0;State.managerSnapshot=this is Manager m?new object?[]{m._clips,m._controllers,m._safeUpdates,m._groupPauses,m._groupUnscales,m._groupRateScales}:null;if(State.failBase)throw new DependencyException();}}
public class Camera:MonoBehaviour{public Camera(bool input):base(input){}public float FollowDistance,MaxFollowDistance,MinFollowDistance,ElevationAngle,MaxElevationAngle,MovementSmoothingValue,RotationSmoothingValue,MoveSensitivity,MinElevationAngle;public bool MovementSmoothing,RotationSmoothing;public Vector3 currentVelocity;public int marker;}
public class Manager:MonoBehaviour{public Manager(bool input):base(input){}public Assoc<Clip>?_clips;public Assoc<Controller>?_controllers;public SafeList<Controller>?_safeUpdates;public float _rateScale;public HashSet<string>?_groupPauses,_groupUnscales;public Dictionary<string,float>?_groupRateScales;public bool _isPaused,_useUnscaledDt;public int marker;}
public static class State{public static int baseCalls,zeroCalls,failNth;public static bool failBase,smoothingSnapshot;public static float managerRateSnapshot;public static object?receiver;public static List<int>kinds=new();public static Vector3 zero;public static uint[]?cameraSnapshot;public static object?[]?managerSnapshot;public static void Reset(){baseCalls=zeroCalls=failNth=0;failBase=smoothingSnapshot=false;managerRateSnapshot=0;receiver=null;kinds.Clear();cameraSnapshot=null;managerSnapshot=null;}public static void Record(int kind){kinds.Add(kind);if(kinds.Count==failNth)throw new DependencyException();}public static Vector3 GetZero(){zeroCalls++;return zero;}public static Vector3 ConstantZero(){zeroCalls++;return new Vector3(0,0,0);}}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["TMPro.Examples.CameraController"]=typeof(Camera),["FTRuntime.SwfManager"]=typeof(Manager),["UnityEngine.MonoBehaviour"]=typeof(MonoBehaviour),["UnityEngine.Vector3"]=typeof(Vector3),["FTRuntime.Internal.SwfAssocList`1<FTRuntime.SwfClip>"]=typeof(Assoc<Clip>),["FTRuntime.Internal.SwfAssocList`1<FTRuntime.SwfClipController>"]=typeof(Assoc<Controller>),["FTRuntime.Internal.SwfList`1<FTRuntime.SwfClipController>"]=typeof(SafeList<Controller>),["System.Collections.Generic.HashSet`1<System.String>"]=typeof(HashSet<string>),["System.Collections.Generic.Dictionary`2<System.String,System.Single>"]=typeof(Dictionary<string,float>),["System.IntPtr"]=typeof(IntPtr),["System.Single"]=typeof(float),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);static FieldInfo F(FieldReference f)=>T(f.DeclaringType).GetField(f.Name)!;
 static Delegate Emit(MethodDefinition m,string mutation,bool real=false){var owner=T(m.DeclaringType);var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{owner},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i, i=>il.DefineLabel());bool changed=mutation=="none";int hashCtor=0;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}if(mutation=="base_first"){il.Emit(RO.Ldarg_0);il.Emit(RO.Call,typeof(MonoBehaviour).GetConstructor(Type.EmptyTypes)!);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(op==RO.Ldc_R4){float value=(float)a;if(mutation=="wrong_default"&&!changed){value=31;changed=true;}if(mutation=="wrong_rate"&&value==1){value=0;changed=true;}il.Emit(op,value);continue;}
   if(mutation=="smoothing_false"&&i.Next?.Operand is FieldReference flag&&flag.Name=="MovementSmoothing"){il.Emit(RO.Ldc_I4_0);changed=true;continue;}
   if(a is MethodReference mr){if(mr.Name=="get_zero"){MethodInfo getter=real?typeof(Vector3).GetProperty("zero")!.GetMethod!:typeof(State).GetMethod(mutation=="constant_zero"?nameof(State.ConstantZero):nameof(State.GetZero))!;if(mutation=="constant_zero")changed=true;il.Emit(op,getter);continue;}if(mr.Name!=".ctor")throw new Exception("Unmapped method "+mr);if(mr.DeclaringType.FullName=="UnityEngine.MonoBehaviour"&&mutation is "skip_base" or "base_first"){il.Emit(RO.Pop);changed=true;continue;}if(mr.DeclaringType.FullName=="System.Collections.Generic.HashSet`1<System.String>"){hashCtor++;if(mutation=="alias_sets"&&hashCtor==2){il.Emit(RO.Ldloc,locals[4]);changed=true;continue;}}il.Emit(op,T(mr.DeclaringType).GetConstructor(mr.Parameters.Select(p=>T(p.ParameterType)).ToArray())!);if(mutation=="late_smoothing"&&mr.DeclaringType.FullName=="UnityEngine.MonoBehaviour"){il.Emit(RO.Ldarg_0);il.Emit(RO.Ldc_I4_1);il.Emit(RO.Stfld,typeof(Camera).GetField(nameof(Camera.MovementSmoothing))!);}continue;}
   if(a is FieldReference field){if(mutation=="late_smoothing"&&op==RO.Stfld&&field.Name=="MovementSmoothing"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}il.Emit(op,F(field));continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is Mono.Cecil.Cil.Instruction target){il.Emit(op,labels[target]);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(!changed)throw new Exception("Mutation not applied");return dm.CreateDelegate(typeof(Action<>).MakeGenericType(owner));
 }
 static uint Bit(float v)=>(uint)BitConverter.SingleToInt32Bits(v);static float Float(uint bits)=>BitConverter.Int32BitsToSingle((int)bits);public static uint[]CameraBits(Camera c)=>new[]{Bit(c.FollowDistance),Bit(c.MaxFollowDistance),Bit(c.MinFollowDistance),Bit(c.ElevationAngle),Bit(c.MaxElevationAngle),Bit(c.MovementSmoothingValue),Bit(c.RotationSmoothingValue),Bit(c.MoveSensitivity),Bit(c.currentVelocity.x),Bit(c.currentVelocity.y),Bit(c.currentVelocity.z)};
 record Result(int Cases,List<string>Failures);
 static Camera CameraInput()=>new(true){marker=123,MinElevationAngle=Float(0x7fc01234),RotationSmoothing=true,FollowDistance=-1,currentVelocity=new Vector3(6,7,8)};
 static Manager ManagerInput()=>new(true){_clips=new(true),_controllers=new(true),_safeUpdates=new(true),_rateScale=9,_groupPauses=new(){"oldpause"},_groupUnscales=new(){"oldunscale"},_groupRateScales=new(){{"oldrate",2}},_isPaused=true,_useUnscaledDt=true,marker=456};
 static bool ManagerFinal(Manager m,object?[]old)=>State.baseCalls==1&&Bit(State.managerRateSnapshot)==0x3f800000&&ReferenceEquals(State.receiver,m)&&State.kinds.SequenceEqual(new[]{1,2,3})&&m._clips?.items.Count==0&&m._controllers?.items.Count==0&&m._safeUpdates?.items.Count==0&&m._groupPauses is{Count:0}&&m._groupUnscales is{Count:0}&&!ReferenceEquals(m._groupPauses,m._groupUnscales)&&m._groupRateScales is{Count:0}&&Bit(m._rateScale)==0x3f800000&&m._isPaused&&m._useUnscaledDt&&m.marker==456&&State.managerSnapshot is{}snap&&snap.Length==6&&snap.Select((o,i)=>!ReferenceEquals(o,old[i])).All(v=>v)&&ReferenceEquals(snap[0],m._clips)&&ReferenceEquals(snap[1],m._controllers)&&ReferenceEquals(snap[2],m._safeUpdates)&&ReferenceEquals(snap[3],m._groupPauses)&&ReferenceEquals(snap[4],m._groupUnscales)&&ReferenceEquals(snap[5],m._groupRateScales);
 static Result Cases(MethodDefinition m,Delegate fn,List<uint[]>rows,bool stop=false,bool extras=true){int count=0,index=0;var fails=new List<string>();void Check(bool yes,string label){count++;if(!yes)fails.Add(label);}if(m.MetadataToken.ToInt32()==0x0600075E){var call=(Action<Camera?>)fn;foreach(var row in rows){State.Reset();State.zero=new Vector3(Float(row[12]),Float(row[13]),Float(row[14]));var c=CameraInput();bool match=false;try{call(c);match=row.Take(4).All(v=>v==1)&&c.MovementSmoothing&&CameraBits(c).SequenceEqual(row.Skip(4))&&State.baseCalls==1&&State.zeroCalls==1&&State.smoothingSnapshot&&ReferenceEquals(State.receiver,c)&&State.cameraSnapshot!=null&&State.cameraSnapshot.SequenceEqual(row.Skip(4))&&c.marker==123&&Bit(c.MinElevationAngle)==0x7fc01234&&c.RotationSmoothing;}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"camera:"+index++);if(stop&&fails.Count>0)return new(count,fails);}
    if(extras){State.Reset();bool npe=false;try{call(null);}catch(NullReferenceException){npe=true;}Check(npe&&State.zeroCalls==0&&State.baseCalls==0,"camera-null-before-getter");State.Reset();State.zero=new Vector3(4,5,6);State.failBase=true;var c=CameraInput();bool thrown=false;try{call(c);}catch(DependencyException){thrown=true;}Check(thrown&&State.baseCalls==1&&State.cameraSnapshot!=null&&State.cameraSnapshot.SequenceEqual(CameraBits(c))&&c.MovementSmoothing&&c.FollowDistance==30&&c.currentVelocity.x==4&&c.marker==123,"camera-base-partial-state");}
   }else{var call=(Action<Manager?>)fn;foreach(var row in rows){var mgr=ManagerInput();object?[]old={mgr._clips,mgr._controllers,mgr._safeUpdates,mgr._groupPauses,mgr._groupUnscales,mgr._groupRateScales};State.Reset();bool match=false;try{call(mgr);match=row[0]==1&&row[1]==6&&row[2]==6&&row[3]==6&&row.Skip(4).Take(4).All(v=>v==1)&&row[8]==0x3f800000&&row.Skip(9).Take(6).SequenceEqual(new uint[]{1,2,3,4,4,5})&&row.Skip(15).SequenceEqual(new uint[]{1,2,3,4,4,5})&&ManagerFinal(mgr,old);}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"manager:"+index++);if(stop&&fails.Count>0)return new(count,fails);}
    if(extras){State.Reset();bool npe=false;try{call(null);}catch(NullReferenceException){npe=true;}Check(npe&&State.kinds.SequenceEqual(new[]{1})&&State.baseCalls==0,"manager-null-after-first-constructor");for(int nth=1;nth<=3;nth++){var mgr=ManagerInput();var oldClip=mgr._clips;var oldControllers=mgr._controllers;var oldUpdates=mgr._safeUpdates;State.Reset();State.failNth=nth;bool thrown=false;try{call(mgr);}catch(DependencyException){thrown=true;}Check(thrown&&State.kinds.Count==nth&&State.baseCalls==0&&(nth==1?ReferenceEquals(mgr._clips,oldClip):!ReferenceEquals(mgr._clips,oldClip))&&(nth<3?ReferenceEquals(mgr._controllers,oldControllers):!ReferenceEquals(mgr._controllers,oldControllers))&&ReferenceEquals(mgr._safeUpdates,oldUpdates)&&mgr._rateScale==9,"manager-collection-partial:"+nth);}
     var mgr2=ManagerInput();State.Reset();State.failBase=true;bool baseThrown=false;try{call(mgr2);}catch(DependencyException){baseThrown=true;}Check(baseThrown&&State.baseCalls==1&&mgr2._groupPauses?.Count==0&&mgr2._groupUnscales?.Count==0&&mgr2._rateScale==1&&State.managerSnapshot!=null,"manager-before-base-error");var first=ManagerInput();var second=ManagerInput();State.Reset();call(first);State.Reset();call(second);bool independent=first._groupPauses!.Add("g")&&first._groupPauses.Add(null!)&&first._groupUnscales!.Count==0&&second._groupPauses!.Count==0&&first._groupPauses.Comparer==EqualityComparer<string>.Default&&first._groupUnscales.Comparer==EqualityComparer<string>.Default;first._groupRateScales!["g"]=2;Check(independent&&second._groupRateScales!.Count==0&&first._groupRateScales.Comparer==EqualityComparer<string>.Default,"real-closed-collections-empty-independent-default-comparers");}
   }return new(count,fails);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var raw=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();var fails=new List<string>();var controls=new List<object>();int count=0,errors=0;bool cp=true;foreach(int token in new[]{0x0600075E,0x060008A0}){var m=(MethodDefinition)a.MainModule.LookupToken(token);var rows=raw.Where(r=>r[0]==$"0x{token:X8}").Select(r=>r.Skip(1).Select(uint.Parse).ToArray()).ToList();if(rows.Count!=4096)throw new Exception("Native row count");var result=Cases(m,Emit(m,"none"),rows);count+=result.Cases;fails.AddRange(result.Failures);foreach(string mutation in args.Length>3?Array.Empty<string>():token==0x0600075E?new[]{"illegal_stack","return_early","wrong_default","smoothing_false","constant_zero","skip_base","base_first","late_smoothing"}:new[]{"illegal_stack","return_early","alias_sets","wrong_rate","skip_base","base_first"}){bool detected=false;string?error=null;try{detected=Cases(m,Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{token=$"0x{token:X8}",mutation,detected,tool_error=error});}}
   State.Reset();var c=CameraInput();((Action<Camera?>)Emit((MethodDefinition)a.MainModule.LookupToken(0x0600075E),"none",true))(c);count++;if(Bit(c.currentVelocity.x)!=0||Bit(c.currentVelocity.y)!=0||Bit(c.currentVelocity.z)!=0||State.baseCalls!=1)fails.Add("actual-pinned-zero-getter");bool pass=fails.Count==0&&errors==0&&cp;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=count,positive_failures=fails.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,unity_core_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(typeof(Vector3).Assembly.Location))).ToLowerInvariant(),scope="Original constructor caller bodies unchanged; native allocator/collection ctors/GC/base recorded with supplied generic class/MethodInfo/static layouts. CLR actual candidate CIL and pinned Vector3 value type with controlled provider/Swf generic collections/base constructor; real public HashSet<string>/Dictionary<string,float> constructors and separate CoreModule zero getter execute. No original allocator/collection/GC/Unity/base/throw engine or device acceptance",failures=fails,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
  }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
