using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher53{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="f076b89e29dc563543e2f95e17b91e6cba25ed37f7b69a93ab82c61a71dbe69f","Pinned Native52");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x060001A9,0x06000188,0x0600083D,0x06000903}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<FieldReference>().First(f=>f.DeclaringType.FullName==owner&&f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);int sig=m.Body.LocalVarToken.ToInt32(),max=2;
switch(token){case 0x060001A9:{max=3;il.O(2);il.Ref(0x7b,field("EnemySelecter","board"));il.Ref(0x7b,field("Board","boardConfig"));il.O(5,4);il.Ref(0x6f,call("GetGridPosition"));il.O(0x0b);foreach(var(name,v)in new[]{("x",57f),("y",28f)}){var f=a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(f=>f.FullName=="System.Single UnityEngine.Vector3::"+name);il.O(0x12,1,0x25);il.Ref(0x7b,f);il.F(v);il.O(0x58);il.Ref(0x7d,f);}il.O(7,0x2a);break;}
case 0x06000188:{max=3;il.O(2);il.Ref(0x7b,field("DeviceManager","board"));il.O(3,4);il.Ref(0x6f,call("GetGrid"));il.O(0x0d,9);il.Br(0x2d,"grid");il.O(0x14,0x2a);il.Label("grid");int j=0;foreach(string name in new[]{"device_top","device_sheath","device_common","device_bottom"}){il.O(9);il.Ref(0x7b,field("Grid",name));il.Ref(0x28,call("op_Implicit"));il.Br(0x2c,"next"+j);il.O(9);il.Ref(0x7b,field("Grid",name));il.O(0x2a);il.Label("next"+j++);}il.O(0x14,0x2a);break;}
case 0x0600083D:{il.O(2);il.Ref(0x28,call("GetCurrentBakedFrame"));il.O(0x0c,8);il.Br(0x2c,"empty");il.O(8);il.Ref(0x7b,field("FTRuntime.SwfClipAsset/Frame","Labels"));il.O(0x13,4,0x11,4);il.Br(0x2c,"empty");il.O(3,0x16);il.Br(0x32,"empty");il.O(3,0x11,4,0x8e,0x69);il.Br(0x2f,"empty");il.O(0x11,4,3,0x9a,0x2a);il.Label("empty");il.Ref(0x7e,field("System.String","Empty"));il.O(0x2a);break;}
case 0x06000903:{sig=0x110001AA;var sm=(MD)a.MainModule.LookupToken(0x0600021C);R(sm.Body.LocalVarToken.ToInt32()==sig&&sm.Body.Variables.Select(v=>v.VariableType.FullName).SequenceEqual(new[]{"System.String","System.Int32","System.String","UnityEngine.Sprite"}),"Existing local signature proof");il.O(3);il.Ref(0x7b,field("FTRuntime.SwfClipController","_clip"));il.Ref(0x7b,field("FTRuntime.SwfClip","_sequence"));il.O(0x0a);il.Label("try");il.O(0x16);il.Ref(0x7e,field("FlashTools.Examples.PurpleFlowerLogic","_idleSequences"));il.O(0x8e,0x69);il.Ref(0x28,call("Range"));il.O(0x0b);il.Ref(0x7e,field("FlashTools.Examples.PurpleFlowerLogic","_idleSequences"));il.O(7,0x9a,0x0c,8,6);il.Ref(0x28,call("op_Inequality"));il.Br(0x2c,"try");il.O(8,0x2a);break;}}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot");int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
