from pathlib import Path
p=Path('Tools/HighFidelityPatch/Program.cs')
s=p.read_text()
repls={
''' var fProduce=F(plant,"produce_Brightness"), fFlash=F(plant,"flash_Brightness"), fBoard=F(plant,"board"), fPM=F(plant,"plantManager"), fEM=F(plant,"elementManager"), fUIs=F(plant,"elementUIControllers");''':''' var fProduce=F(plant,"produce_Brightness"); var fFlash=F(plant,"flash_Brightness"); var fBoard=F(plant,"board"); var fPM=F(plant,"plantManager"); var fEM=F(plant,"elementManager"); var fUIs=F(plant,"elementUIControllers");''',
''' var em=T("ElementManager"), elem=T("Element"), ui=T("ElementUIController");''':''' var em=T("ElementManager"); var elem=T("Element"); var ui=T("ElementUIController");''',
''' var fElems=F(em,"elements"), fElemType=F(elem,"type"), fElemUI=F(elem,"UIController"), fUIType=F(ui,"type");''':''' var fElems=F(em,"elements"); var fElemType=F(elem,"type"); var fElemUI=F(elem,"UIController"); var fUIType=F(ui,"type");''',
''' var i=new VariableDefinition(module.TypeSystem.Int32), j=new VariableDefinition(module.TypeSystem.Int32), e=new VariableDefinition(elem), u=new VariableDefinition(ui);b.Variables.Add(i);b.Variables.Add(j);b.Variables.Add(e);b.Variables.Add(u);''':''' var i=new VariableDefinition(module.TypeSystem.Int32); var j=new VariableDefinition(module.TypeSystem.Int32); var e=new VariableDefinition(elem); var u=new VariableDefinition(ui);b.Variables.Add(i);b.Variables.Add(j);b.Variables.Add(e);b.Variables.Add(u);''',
''' var afterBoard=Instruction.Create(OpCodes.Nop), outerCheck=Instruction.Create(OpCodes.Nop), outerBody=Instruction.Create(OpCodes.Nop), innerCheck=Instruction.Create(OpCodes.Nop), innerBody=Instruction.Create(OpCodes.Nop), noMatch=Instruction.Create(OpCodes.Nop), afterLoops=Instruction.Create(OpCodes.Nop);''':''' var afterBoard=Instruction.Create(OpCodes.Nop); var outerCheck=Instruction.Create(OpCodes.Nop); var outerBody=Instruction.Create(OpCodes.Nop); var innerCheck=Instruction.Create(OpCodes.Nop); var innerBody=Instruction.Create(OpCodes.Nop); var noMatch=Instruction.Create(OpCodes.Nop); var afterLoops=Instruction.Create(OpCodes.Nop);''',
''' var fID=F(plant,"ID"), fOrder=F(plant,"order"), fAtk=F(plant,"attackable"), fBlock=F(plant,"blockable"), fBarrel=F(plant,"pT_chomperviking_barrelsPoint"), fSprites=F(plant,"animationSprites"), fUIs=F(plant,"UI_Characteristic"), fBuffMgr=F(plant,"buffManager"), fBoard=F(plant,"board"), fAnimator=F(plant,"animator");''':''' var fID=F(plant,"ID"); var fOrder=F(plant,"order"); var fAtk=F(plant,"attackable"); var fBlock=F(plant,"blockable"); var fBarrel=F(plant,"pT_chomperviking_barrelsPoint"); var fSprites=F(plant,"animationSprites"); var fUIs=F(plant,"UI_Characteristic"); var fBuffMgr=F(plant,"buffManager"); var fBoard=F(plant,"board"); var fAnimator=F(plant,"animator");''',
''' var stats=T("StatsIncreased"), buff=T("Buff"), buffMgr=T("BuffManager");''':''' var stats=T("StatsIncreased"); var buff=T("Buff"); var buffMgr=T("BuffManager");''',
''' var fBuffType=F(buff,"buffType"), fBuffName=F(buff,"name");''':''' var fBuffType=F(buff,"buffType"); var fBuffName=F(buff,"name");''',
''' var id5=Instruction.Create(OpCodes.Nop), id6=Instruction.Create(OpCodes.Nop), id49=Instruction.Create(OpCodes.Nop), ret=Instruction.Create(OpCodes.Ret), id6NoOrder=Instruction.Create(OpCodes.Nop), id6AfterUI=Instruction.Create(OpCodes.Nop), id4After=Instruction.Create(OpCodes.Nop);''':''' var id5=Instruction.Create(OpCodes.Nop); var id6=Instruction.Create(OpCodes.Nop); var id49=Instruction.Create(OpCodes.Nop); var ret=Instruction.Create(OpCodes.Ret); var id6NoOrder=Instruction.Create(OpCodes.Nop); var id6AfterUI=Instruction.Create(OpCodes.Nop);''',
''' var fFlashT=F(plant,"flash_Time"), fFlashB=F(plant,"flash_Brightness"), fProduce=F(plant,"produce_Brightness"), fSelected=F(plant,"selected_Bright"), fActive=F(plant,"active"), fShadow=F(plant,"shadow"), fX=F(plant,"fX"), fY=F(plant,"fY"), fOn=F(plant,"isOnField"), fBoard=F(plant,"board"), fLiving=F(plant,"livingTime"), fRate=F(plant,"updateRate"), fSleep=F(plant,"isSleep"), fHpUI=F(plant,"hpUIController"), fEM=F(plant,"elementManager"), fDied=F(plant,"isDied"), fHP=F(plant,"healthPoint"), fID=F(plant,"ID"), fBarrel=F(plant,"pT_chomperviking_barrelsPoint"), fEaten=F(plant,"beEaten"), fState=F(plant,"state");''':''' var fFlashT=F(plant,"flash_Time"); var fFlashB=F(plant,"flash_Brightness"); var fProduce=F(plant,"produce_Brightness"); var fSelected=F(plant,"selected_Bright"); var fActive=F(plant,"active"); var fShadow=F(plant,"shadow"); var fX=F(plant,"fX"); var fY=F(plant,"fY"); var fOn=F(plant,"isOnField"); var fBoard=F(plant,"board"); var fLiving=F(plant,"livingTime"); var fRate=F(plant,"updateRate"); var fSleep=F(plant,"isSleep"); var fHpUI=F(plant,"hpUIController"); var fEM=F(plant,"elementManager"); var fDied=F(plant,"isDied"); var fHP=F(plant,"healthPoint"); var fID=F(plant,"ID"); var fBarrel=F(plant,"pT_chomperviking_barrelsPoint"); var fEaten=F(plant,"beEaten"); var fState=F(plant,"state");''',
''' var getTransform=AnyCall("UnityEngine.Component","get_transform",0); var getPos=AnyCall("UnityEngine.Transform","get_position",0); var v3=getPos.ReturnType; var vx=new FieldReference("x",module.TypeSystem.Single,v3), vy=new FieldReference("y",module.TypeSystem.Single,v3);''':''' var getTransform=AnyCall("UnityEngine.Component","get_transform",0); var getPos=AnyCall("UnityEngine.Transform","get_position",0); var v3=getPos.ReturnType; var vx=new FieldReference("x",module.TypeSystem.Single,v3); var vy=new FieldReference("y",module.TypeSystem.Single,v3);''',
''' var zm=T("ZombieManager"); var fZM=F(board,"zombieManager"), fAudio=F(zm,"audioClip_zombie");''':''' var zm=T("ZombieManager"); var fZM=F(board,"zombieManager"); var fAudio=F(zm,"audioClip_zombie");''',
''' var a=new VariableDefinition(module.TypeSystem.Single), bb=new VariableDefinition(module.TypeSystem.Single), pos=new VariableDefinition(v3);b.Variables.Add(a);b.Variables.Add(bb);b.Variables.Add(pos);''':''' var a=new VariableDefinition(module.TypeSystem.Single); var bb=new VariableDefinition(module.TypeSystem.Single); var pos=new VariableDefinition(v3);b.Variables.Add(a);b.Variables.Add(bb);b.Variables.Add(pos);''',
''' var noFlash=Instruction.Create(OpCodes.Nop), noSelected=Instruction.Create(OpCodes.Nop), noProduce=Instruction.Create(OpCodes.Nop), activeRet=Instruction.Create(OpCodes.Ret), afterRuntime=Instruction.Create(OpCodes.Nop), deathReset=Instruction.Create(OpCodes.Nop), notChomp=Instruction.Create(OpCodes.Nop), afterHeal=Instruction.Create(OpCodes.Nop), noEaten=Instruction.Create(OpCodes.Nop), normalDeath=Instruction.Create(OpCodes.Nop), reset=Instruction.Create(OpCodes.Nop), ret=Instruction.Create(OpCodes.Ret);''':''' var noFlash=Instruction.Create(OpCodes.Nop); var noSelected=Instruction.Create(OpCodes.Nop); var noProduce=Instruction.Create(OpCodes.Nop); var activeRet=Instruction.Create(OpCodes.Ret); var afterRuntime=Instruction.Create(OpCodes.Nop); var notChomp=Instruction.Create(OpCodes.Nop); var noEaten=Instruction.Create(OpCodes.Nop); var normalDeath=Instruction.Create(OpCodes.Nop); var reset=Instruction.Create(OpCodes.Nop); var ret=Instruction.Create(OpCodes.Ret);''',
''' var spriteRenderer=T("UnityEngine.SpriteRenderer");\n var getRenderer=AnyGeneric("UnityEngine.Component","GetComponent","SpriteRenderer");''':''' var getRenderer=AnyGeneric("UnityEngine.Component","GetComponent","SpriteRenderer");\n var spriteRenderer=getRenderer.ReturnType;'''
}
for a,b in repls.items():
    if a not in s: print('WARN missing pattern',a[:80])
    s=s.replace(a,b)
p.write_text(s)
print('HF2 cleanup applied')
