using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}
public class Obj{public int movementTracks=-55,index=-66;public Vector3 speed;public float maxLivingTime,livingTime;}
public class Clip:Obj{} public class Camera:Obj{} public class Audio:Obj{} public class Transform:Obj{} public class Game:Obj{} public class Image:Obj{} public class Button:Obj{public bool m_Interactable;}
public class ZombieAnimationEvent:Obj{} public class Range:Obj{public int rangeType;public Plant?plant;}
public class Skill:Obj{public int chargedLayer;} public class Stats:Obj{public float value;} public class Buff:Obj{}
public class Plant:Obj{public Skill?skill;public Buff?buffManager;}public class Projectile:Obj{}
public class Adventure:Obj{public Button?button;}public class Level:Obj{public Button?button;}
public class DeviceWindow:Obj{public Image?questionMark,devicePortrait;public Button?button;}public class ZombieWindow:Obj{public Image?questionMark,zombiePortrait;public Button?button;}
public class Page:Obj{public Plant?plant;public Game?skill;}
public static class State{
 public static Obj self=new();public static Plant plant=new(),plantB=new();public static Camera camera=new();public static Clip clip=new();public static Game game=new(),gameB=new();public static Transform transform=new(),transformB=new();public static Image image=new(),imageB=new();public static Button button=new(),buttonB=new();public static Skill skill=new(),skillB=new();public static Buff buff=new(),buffB=new();public static Stats stats=new();public static Audio audio=new();
 public static int token,mode,hook,active,enabled,audioCalls;public static ulong trace;public static bool argsOK;public static Vector3 value,alternate,initial,output;public static Color color;public static uint volume,capturedVolume,pitch;
 public static int Id(object?o){object?[]all={null,self,plant,plantB,camera,clip,game,gameB,transform,transformB,image,imageB,button,buttonB,skill,skillB,stats,buff,buffB,audio};for(int i=0;i<all.Length;i++)if(ReferenceEquals(o,all[i]))return i;throw new Exception("Unknown identity");}
 public static void Ev(int e,object?r=null)=>trace=unchecked(trace*131+(uint)(e*32+Id(r)));public static void Fail(){Ev(15);throw new DependencyException();}public static void Check(object?r){if(r==null)throw new NullReferenceException();}
 public static Camera?MainCamera(){Ev(1);if(mode==12)Fail();return mode==5?null:camera;}
 public static Transform?ComponentTransform(Obj?r){Check(r);Ev(2,r);if(mode==6)return null;return ReferenceEquals(r,plantB)?transformB:transform;}
 public static Transform?GameTransform(Game?r){Check(r);Ev(16,r);if(mode==5)return null;if(hook==3)value=alternate;return ReferenceEquals(r,gameB)?transformB:transform;}
 public static Vector3 Position(Transform?r){Check(r);Ev(3,r);if(mode==7)Fail();var v=value;if(hook==2){value=alternate;if(self is Page p)p.skill=gameB;}return v;}
 public static float Volume(){Ev(4);if(hook==1)value=alternate;if(mode==8)Fail();return Fixture.F(volume);}
 public static Audio?Create3(Clip?c,Vector3 v,float vol){Ev(5,c);audioCalls++;output=v;capturedVolume=Fixture.B(vol);pitch=0x3f800000;if(mode==9)Fail();return mode==11?null:audio;}
 public static Audio?Create4(Clip?c,Vector3 v,float vol,float pch){pitch=Fixture.B(pch);var a=Create3(c,v,vol);pitch=Fixture.B(pch);return a;}
 public static bool Implicit(Obj?r){Ev(6,r);if(token==0x0600066A){if(hook==1)((Page)self).plant=plantB;if(hook==4)((Page)self).plant=null;if(mode==3)Fail();return r!=null&&mode!=2;}if(mode==10)Fail();return r!=null&&mode!=4;}
 public static Game?ComponentGame(Obj?r){Check(r);Ev(7,r);if(mode==5)Fail();return mode==2?null:game;}
 static void Portrait(Image?v){if(self is DeviceWindow d)d.devicePortrait=v;else((ZombieWindow)self).zombiePortrait=v;}static void Btn(Button?v){if(self is DeviceWindow d)d.button=v;else((ZombieWindow)self).button=v;}
 public static void Active(Game?r,bool b){Check(r);Ev(8,r);active=b?1:0;if(hook==2)Portrait(imageB);if(hook==4)Portrait(null);if(mode==6)Fail();}
 public static void Color(Image?r,Color c){Check(r);Ev(9,r);color=c;if(hook==3)Btn(buttonB);if(hook==5)Btn(null);if(mode==7)Fail();}
 public static void Enabled(Button?r,bool b){Check(r);Ev(10,r);enabled=b?1:0;if(mode==8)Fail();}
 public static Vector3 Circle(Range?r,Vector3 v){Check(r);Ev(11,r);argsOK&=Fixture.B(v.x)==Fixture.B(initial.x)&&Fixture.B(v.y)==Fixture.B(initial.y)&&Fixture.B(v.z)==Fixture.B(initial.z);output=v;if(mode==9)Fail();return alternate;}
 public static void Summon(Plant?r){Ev(12,r);if(hook==1)r!.skill=skillB;if(hook==2)r!.buffManager=buffB;if(mode==4)Fail();}
 public static Stats?Find(Buff?r,string name){Check(r);Ev(13,r);argsOK&=name=="SSI_Characteristic_Atk";if(hook==3)stats.value=Fixture.F(0x87654321);if(mode==5)Fail();return mode==3?null:stats;}
 public static void SetPosition(Transform?r,Vector3 v){Check(r);Ev(17,r);output=v;if(mode==8)Fail();}
}
public static class Fixture{
 static Type T(TypeReference r)=>r.FullName switch{"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Color"=>typeof(Color),"UnityEngine.Transform"=>typeof(Transform),"UnityEngine.GameObject"=>typeof(Game),"UnityEngine.Camera"=>typeof(Camera),"UnityEngine.AudioClip"=>typeof(Clip),"UnityEngine.AudioSource"=>typeof(Audio),"UnityEngine.UI.Button" or "UnityEngine.UI.Selectable"=>typeof(Button),"UnityEngine.UI.Image" or "UnityEngine.UI.Graphic"=>typeof(Image),"UnityEngine.Behaviour"=>typeof(Button),"UnityEngine.Component" or "UnityEngine.Object"=>typeof(Obj),"System.Object"=>typeof(object),"System.Boolean"=>typeof(bool),"System.Int32" or "RangeType"=>typeof(int),"System.Single"=>typeof(float),"System.String"=>typeof(string),"System.IntPtr"=>typeof(IntPtr),"System.Void"=>typeof(void),"System.NullReferenceException"=>typeof(NullReferenceException),"ZombieAnimationEvent"=>typeof(ZombieAnimationEvent),"AttackRange"=>typeof(Range),"Plant"=>typeof(Plant),"Skill"=>typeof(Skill),"BuffManager"=>typeof(Buff),"StatsIncreased"=>typeof(Stats),"Projectile"=>typeof(Projectile),"AdventureMenu_ModeButton"=>typeof(Adventure),"LevelItem_HA"=>typeof(Level),"Almanac_DeviceWindow"=>typeof(DeviceWindow),"Almanac_ZombieWindow"=>typeof(ZombieWindow),"Plant_DetaiPage"=>typeof(Page),_=>throw new Exception("Unmapped type "+r)};
 static Delegate Emit(MethodDefinition m,string mutation){int rid=(int)m.MetadataToken.RID;var pars=(m.HasThis?new[]{T(m.DeclaringType)}:Array.Empty<Type>()).Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();var ret=T(m.ReturnType);var dm=new DynamicMethod(m.FullName+mutation,ret,pars,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var cachedPlant=il.DeclareLocal(typeof(Plant));var vol=il.DeclareLocal(typeof(float));var pitch=il.DeclareLocal(typeof(float));int plantReads=0;
 if(mutation=="illegal_stack"&&rid==0xCD)il.Emit(RO.Pop);
 foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];
 if(i.Operand is FieldReference f){if(mutation=="page_cache_plant"&&rid==0x66A&&f.Name=="plant"){plantReads++;if(plantReads==2){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cachedPlant);continue;}}il.Emit(op,T(f.DeclaringType).GetField(f.Name)??throw new Exception("Field missing "+f));if(mutation=="page_cache_plant"&&rid==0x66A&&f.Name=="plant"&&plantReads==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cachedPlant);}continue;}
 if(i.Operand is MethodReference r){if(r.DeclaringType.FullName=="UnityEngine.Vector3"&&r.Name=="get_zero"){il.Emit(op,typeof(Vector3).GetProperty("zero")!.GetMethod!);continue;}if(r.Name==".ctor"&&r.DeclaringType.FullName is "UnityEngine.Vector3" or "UnityEngine.Color"){il.Emit(op,T(r.DeclaringType).GetConstructor(r.Parameters.Select(p=>T(p.ParameterType)).ToArray())!);continue;}
 string name=r.Name switch{"get_main"=>nameof(State.MainCamera),"get_transform" when r.DeclaringType.FullName=="UnityEngine.GameObject"=>nameof(State.GameTransform),"get_transform"=>nameof(State.ComponentTransform),"get_position"=>nameof(State.Position),"AudioVolume"=>nameof(State.Volume),"CreateAudioAtPoint"=>r.Parameters.Count==4?nameof(State.Create4):nameof(State.Create3),"op_Implicit"=>nameof(State.Implicit),"get_gameObject"=>nameof(State.ComponentGame),"SetActive"=>nameof(State.Active),"set_color"=>nameof(State.Color),"set_enabled"=>nameof(State.Enabled),"RestraintTargetPosition_Circle"=>nameof(State.Circle),"PC_SSI_TrySummon"=>nameof(State.Summon),"FindStatsIncreased"=>nameof(State.Find),"set_position"=>nameof(State.SetPosition),_=>throw new Exception("Unmapped call "+r)};
 if(mutation=="omit_summon"&&rid==0x390&&r.Name=="PC_SSI_TrySummon"){il.Emit(RO.Pop);continue;}if(mutation=="audio_skip_volume"&&r.Name=="AudioVolume"){il.Emit(RO.Ldc_R4,1f);continue;}
 if(mutation=="audio_zero_position"&&r.Name=="CreateAudioAtPoint"){if(r.Parameters.Count==4)il.Emit(RO.Stloc,pitch);il.Emit(RO.Stloc,vol);il.Emit(RO.Pop);il.Emit(RO.Call,typeof(Vector3).GetProperty("zero")!.GetMethod!);il.Emit(RO.Ldloc,vol);if(r.Parameters.Count==4)il.Emit(RO.Ldloc,pitch);}
 il.Emit(RO.Call,typeof(State).GetMethod(name)!);continue;}
 if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="ui_flip_gate"&&rid is 0x532 or 0x632&&i.OpCode.Name=="brfalse.s")op=RO.Brtrue_S;il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(i.Operand is string str){il.Emit(op,str);continue;}if(i.Operand is float fval){if(mutation=="page_wrong_offset"&&rid==0x66A&&fval==30)fval=31;if(mutation=="color_wrong_rgb"&&rid is 0x568 or 0x5B8&&fval==0)fval=1;if(mutation=="page_keep_z"&&rid==0x66A&&fval==0){il.Emit(RO.Ldloc,locals[4]);il.Emit(RO.Ldfld,typeof(Vector3).GetField("z")!);continue;}il.Emit(op,fval);continue;}
 if(i.Operand!=null)throw new Exception("Unsupported operand "+i);if(mutation=="wrong_range_selector"&&rid==0xDD&&op.Value==RO.Ldc_I4_2.Value)op=RO.Ldc_I4_3;if(mutation=="wrong_skill_threshold"&&rid==0x390&&op.Value==RO.Ldc_I4_1.Value)op=RO.Ldc_I4_0;if(mutation=="wrong_formation"&&rid==0x3F5&&op.Value==RO.Ldc_I4_7.Value)op=RO.Ldc_I4_6;if(mutation=="wrong_lifetime"&&rid==0x3F5&&op.Value==RO.Ldarg_2.Value){il.Emit(RO.Ldc_R4,0f);continue;}if(mutation=="color_wrong_enabled"&&rid is 0x568 or 0x5B8&&op.Value==RO.Ldc_I4_0.Value&&i.Next?.Operand is MethodReference next&&next.Name=="set_enabled")op=RO.Ldc_I4_1;il.Emit(op);
 }return dm.CreateDelegate(System.Linq.Expressions.Expression.GetDelegateType(pars.Concat(new[]{ret}).ToArray()));}
 public static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));public static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static int I(ulong v)=>unchecked((int)v);static Vector3 Vec(ulong[]r,int i)=>new(F(r[i]),F(r[i+1]),F(r[i+2]));
 static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>functions,List<ulong[]>rows,bool stop=false){int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int t=(int)r[0];State.token=t;State.mode=(int)r[1];State.hook=(int)r[2];State.self=t switch{0x060000CD=>new ZombieAnimationEvent(),0x060000DD=>new Range(),0x06000390=>new Plant(),0x060003F5=>new Projectile(),0x06000532=>new Adventure(),0x06000568=>new DeviceWindow(),0x060005B8=>new ZombieWindow(),0x06000632=>new Level(),0x0600066A=>new Page(),0x0600013B=>new Obj(),_=>throw new Exception("Token")};State.value=State.initial=Vec(r,6);State.alternate=Vec(r,9);State.volume=(uint)r[12];State.trace=0;State.audioCalls=0;State.argsOK=true;State.active=State.enabled=2;State.output=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));State.color=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));State.capturedVolume=State.pitch=0xdeadbeef;State.skill.chargedLayer=I(r[3]);State.skillB.chargedLayer=I(r[4]);State.stats.value=F(0x12345678);State.self.speed=State.alternate;State.self.maxLivingTime=F(0x11111111);State.self.livingTime=F(0x22222222);object?clip=State.mode==3?null:State.clip;
 if(State.self is Range ar){ar.rangeType=I(r[3]);ar.plant=State.mode==1?null:State.plant;}if(State.self is Plant pl){pl.skill=State.mode==1?null:State.skill;pl.buffManager=State.mode==2?null:State.buff;}if(State.self is Adventure ad)ad.button=State.mode==1?null:State.button;if(State.self is Level le)le.button=State.mode==1?null:State.button;State.button.m_Interactable=State.mode!=2;
 if(State.self is DeviceWindow dw){dw.questionMark=State.mode==1?null:State.image;dw.devicePortrait=State.mode==3?null:State.image;dw.button=State.mode==4?null:State.button;}if(State.self is ZombieWindow zw){zw.questionMark=State.mode==1?null:State.image;zw.zombiePortrait=State.mode==3?null:State.image;zw.button=State.mode==4?null:State.button;}if(State.self is Page pg){pg.plant=State.mode==1?null:State.plant;pg.skill=State.mode==4?null:State.game;}
 int err=0,retid=0;Vector3 v=State.output;try{object?result=t switch{0x0600013B=>functions[t].DynamicInvoke(clip),0x060000DD=>functions[t].DynamicInvoke(State.self,State.initial),0x060003F5=>functions[t].DynamicInvoke(State.self,I(r[3]),F(r[5])),0x06000568 or 0x060005B8=>functions[t].DynamicInvoke(State.self,I(r[3])!=0),0x060000CD or 0x06000532 or 0x06000632=>functions[t].DynamicInvoke(State.self,clip),_=>functions[t].DynamicInvoke(State.self)};if(t==0x060000DD)v=(Vector3)result!;if(t==0x0600013B)retid=State.Id(result);}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(14);err=1;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){err=3;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
 if(t!=0x060000DD)v=State.output;object?child=State.self switch{Page pg2=>pg2.plant,DeviceWindow dw2=>dw2.devicePortrait,ZombieWindow zw2=>zw2.zombiePortrait,_=>null};object?sec=State.self switch{Page pg2=>pg2.skill,DeviceWindow dw2=>dw2.button,ZombieWindow zw2=>zw2.button,_=>null};bool vec=(t==0x060000DD&&err!=0)||(B(v.x)==r[16]&&B(v.y)==r[17]&&B(v.z)==r[18]);bool form=t!=0x060003F5||((uint)State.self.movementTracks==r[29]&&(uint)State.self.index==r[30]&&B(State.self.maxLivingTime)==r[31]&&B(State.self.livingTime)==r[32]&&B(State.self.speed.x)==r[33]&&B(State.self.speed.y)==r[34]&&B(State.self.speed.z)==r[35]);bool ok=State.trace==r[13]&&err==(int)r[14]&&retid==(int)r[15]&&vec&&B(State.color.r)==r[19]&&B(State.color.g)==r[20]&&B(State.color.b)==r[21]&&B(State.color.a)==r[22]&&State.active==(int)r[23]&&State.enabled==(int)r[24]&&State.audioCalls==(int)r[25]&&State.capturedVolume==r[26]&&State.pitch==r[27]&&B(State.stats.value)==r[28]&&form&&State.Id(child)==(int)r[36]&&State.Id(sec)==(int)r[37]&&State.argsOK&&r[38]==1;count++;if(!ok){fail++;if(samples.Count<12)samples.Add(t.ToString("X8")+":"+count+" trace="+State.trace+"/"+r[13]+" err="+err+"/"+r[14]+" vector="+vec+" form="+form+" args="+State.argsOK);if(stop)return(count,fail,samples);}}
 return(count,fail,samples);}
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x060000CD,0x060000DD,0x0600013B,0x06000390,0x060003F5,0x06000568,0x060005B8,0x0600066A};var ms=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).Where(r=>tokens.Contains((int)r[0])).ToList();if(rows.Count!=32768||rows.Any(r=>r.Length!=39||(r[0]!=0x060003F5&&r.Skip(29).Take(7).Any(x=>x!=0)))||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","audio_zero_position","audio_skip_volume","wrong_range_selector","wrong_skill_threshold","omit_summon","wrong_formation","wrong_lifetime","color_wrong_rgb","color_wrong_enabled","page_wrong_offset","page_keep_z","page_cache_plant"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=8,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Eight accepted actual original caller CIL methods with initialized metadata/static zero and supplied recording Unity/audio/truth/color/buff/exception dependencies. Pinned real public CoreModule Vector3/Color constructors/get_zero. Alias object graphs and virtual color wrapper explicit; no original helpers/engine/class-init/throw/game/iOS proof. All native caller bytes unchanged. Throwing range return has no managed return-value comparison; arguments and exception trace still checked. Full conversion/compiler deferred to accumulated 100 methods."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
