using System;
using System.IO;
using System.Linq;
using Mono.Cecil;
internal static class Program{
 static System.Collections.Generic.IEnumerable<TypeDefinition> Types(TypeDefinition t){yield return t;foreach(var n in t.NestedTypes)foreach(var x in Types(n))yield return x;}
 static System.Collections.Generic.IEnumerable<TypeDefinition> Types(ModuleDefinition m){foreach(var t in m.Types)foreach(var x in Types(t))yield return x;}
 static void Main(string[] a){if(a.Length!=1)throw new ArgumentException("usage: InspectNative12 <dll>");using var asm=AssemblyDefinition.ReadAssembly(Path.GetFullPath(a[0]));var m=asm.MainModule;var hits=Types(m).SelectMany(t=>t.Methods).Where(x=>x.Name=="CalculateAD").ToArray();Console.WriteLine($"MVID={m.Mvid}");Console.WriteLine($"CALCULATE_AD_COUNT={hits.Length}");foreach(var md in hits){Console.WriteLine($"TARGET token=0x{md.MetadataToken.ToUInt32():X8} declaring={md.DeclaringType.FullName} full={md.FullName} body={(md.HasBody?md.Body.CodeSize:0)} generic={md.HasGenericParameters} gp={md.GenericParameters.Count}");foreach(var gp in md.GenericParameters){Console.WriteLine($"GP name={gp.Name} attrs={gp.Attributes}");foreach(var c in gp.Constraints)Console.WriteLine($"  CONSTRAINT {c.ConstraintType.FullName}");}foreach(var p in md.Parameters)Console.WriteLine($"PARAM index={p.Index} name={p.Name} type={p.ParameterType.FullName}");if(md.HasBody){foreach(var v in md.Body.Variables)Console.WriteLine($"LOCAL index={v.Index} type={v.VariableType.FullName}");foreach(var i in md.Body.Instructions)Console.WriteLine($"IL {i.Offset:X4} {i.OpCode} {i.Operand}");}}
 foreach(var t in Types(m).Where(t=>t.Name=="Damage"||t.FullName.Contains("Damage"))){Console.WriteLine($"TYPE token=0x{t.MetadataToken.ToUInt32():X8} {t.FullName}");foreach(var f in t.Fields)Console.WriteLine($"FIELD token=0x{f.MetadataToken.ToUInt32():X8} name={f.Name} type={f.FieldType.FullName}");foreach(var md in t.Methods)Console.WriteLine($"METHOD token=0x{md.MetadataToken.ToUInt32():X8} {md.FullName}");}
 foreach(var r in m.GetMemberReferences().OrderBy(x=>x.MetadataToken.ToUInt32())){if(r.FullName.Contains("Damage")||r.FullName.Contains("op_")||r.FullName.Contains("Mathf")){if(r is MethodReference mr)Console.WriteLine($"METHODREF token=0x{mr.MetadataToken.ToUInt32():X8} {mr.FullName} scope={mr.DeclaringType.Scope?.Name}");else if(r is FieldReference fr)Console.WriteLine($"FIELDREF token=0x{fr.MetadataToken.ToUInt32():X8} {fr.FullName} scope={fr.DeclaringType.Scope?.Name}");}}
 Console.WriteLine("INSPECT_NATIVE12_PASS");}}
