using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;
public class DependencyException:Exception{}public class Save{public int adventureLevel;public int marker=123;}
public class Text{public int id;public string?text;public bool flag;public void SetText(string s,bool v){State.trace=State.trace*10+4;State.textId=id;State.boolOK&=v;if(State.fail=="text")throw new DependencyException();text=s;flag=v;if(State.mode==2){State.s!.playerSave=State.other;State.s.level=State.alt;}if(State.mode==3)State.s!.level=State.alt;if(State.mode==4)State.s!.playerSave=null;}}
public class Skip{public Save?playerSave;public int level,challenge;public Text?text_Level;public int marker=234;}
public static class State{public static Skip?s;public static Save original=new(),other=new();public static Text label1=new(),label2=new();public static int mode,alt,trace,formatted,textId;public static bool boolOK,formatOK;public static string fail="";
 public static void Reset(int level=12,int mode0=0,int alt0=-9,bool nullSave=false){mode=mode0;alt=alt0;trace=formatted=textId=0;boolOK=formatOK=true;fail="";original=new(){adventureLevel=777};other=new(){adventureLevel=999};label1=new(){id=1};label2=new(){id=2};s=new(){playerSave=nullSave?null:original,level=level,text_Level=label1};}
 public static string Render(ref int value,string format){trace=3;formatted=value;formatOK&=format=="当前关卡：0";if(State.fail=="format")throw new DependencyException();if(mode==1){value=alt;s!.text_Level=label2;}if(mode==3)s!.playerSave=other;return formatted.ToString(format,CultureInfo.CurrentCulture);}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["SystemSkipLevel"]=typeof(Skip),["Save"]=typeof(Save),["TMPro.TextMeshProUGUI"]=typeof(Text),["TMPro.TMP_Text"]=typeof(Text),["System.Int32"]=typeof(int),["System.String"]=typeof(string),["System.Boolean"]=typeof(bool),["System.Object"]=typeof(object)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t);
 static FieldInfo F(FieldReference f)=>T(f.DeclaringType).GetField(f.Name)!;
 static MethodInfo M(MethodReference m,bool real)=>m.Name=="ToString"?(real?typeof(int).GetMethod("ToString",new[]{typeof(string)})!:typeof(State).GetMethod(nameof(State.Render))!):typeof(Text).GetMethod(nameof(Text.SetText))!;
 static Action<Skip?,int> Emit(MethodDefinition m,string mutation,bool real=false){var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{typeof(Skip),typeof(int)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";LocalBuilder?cached=null;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}if(mutation=="null_this_return"){var good=il.DefineLabel();il.Emit(RO.Ldarg_0);il.Emit(RO.Brtrue,good);il.Emit(RO.Ret);il.MarkLabel(good);changed=true;}
  if(mutation=="cached_save"){cached=il.DeclareLocal(typeof(Save));il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(Skip).GetField(nameof(Skip.playerSave))!);il.Emit(RO.Stloc,cached);}
  var ins=m.Body.Instructions;bool afterText=false;
  for(int ix=0;ix<ins.Count;ix++){var i=ins[ix];il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(op==RO.Ldarg_0&&ix+1<ins.Count&&ins[ix+1].Operand is FieldReference next){
    if(mutation=="late_text"&&next.Name=="text_Level"){ix++;changed=true;continue;}
    if(afterText&&mutation=="cached_save"&&next.Name=="playerSave"){il.Emit(RO.Ldloc,cached!);ix++;changed=true;continue;}
    if(afterText&&mutation=="cached_sum"&&next.Name=="level"){il.Emit(RO.Ldloc,locals[7]);ix++;changed=true;continue;}
   }
   if(op==RO.Add&&mutation=="add_ovf"){op=RO.Add_Ovf;changed=true;}
   if(operand is FieldReference f){var fi=F(f);if(op==RO.Ldflda){if(mutation=="wrong_field"){fi=typeof(Skip).GetField(nameof(Skip.challenge))!;changed=true;}if(mutation=="copy_ref"){var copy=il.DeclareLocal(typeof(int));il.Emit(RO.Ldfld,fi);il.Emit(RO.Stloc,copy);il.Emit(RO.Ldloca,copy);changed=true;continue;}}
    if(op==RO.Stfld&&f.Name=="adventureLevel"&&mutation is "skip_commit" or "early_commit"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}il.Emit(op,fi);
    if(op==RO.Stfld&&f.Name=="level"&&mutation=="early_commit"){il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(Skip).GetField(nameof(Skip.playerSave))!);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(Skip).GetField(nameof(Skip.level))!);il.Emit(RO.Stfld,typeof(Save).GetField(nameof(Save.adventureLevel))!);changed=true;}continue;
   }
   if(operand is MethodReference method){if(method.Name=="SetText"){
     if(mutation=="late_text"){var temp=il.DeclareLocal(typeof(string));il.Emit(RO.Pop);il.Emit(RO.Stloc,temp);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,typeof(Skip).GetField(nameof(Skip.text_Level))!);il.Emit(RO.Ldloc,temp);il.Emit(RO.Ldc_I4_1);}
     if(mutation=="wrong_bool"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}il.Emit(op,M(method,real));afterText=true;
    }else il.Emit(op,M(method,real));continue;}
   if(operand is Mono.Cecil.Cil.Instruction target){if(op==RO.Ble_S&&mutation is "unsigned_guard" or "zero_allowed"){op=mutation=="unsigned_guard"?RO.Ble_Un_S:RO.Blt_S;changed=true;}il.Emit(op,labels[target]);continue;}
   if(operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(operand is string str){il.Emit(op,str);continue;}if(operand is int iv){il.Emit(op,iv);continue;}if(operand==null){il.Emit(op);continue;}throw new Exception("Unsupported "+operand);
  }
  if(!changed)throw new Exception("Mutation not applied "+mutation);return (Action<Skip?,int>)dm.CreateDelegate(typeof(Action<Skip?,int>));
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(Action<Skip?,int>fn,List<uint[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();void Check(bool ok,string label){count++;if(!ok)failures.Add(label);}
  foreach(var row in rows){State.Reset((int)row[0],(int)row[3],(int)row[4],row[2]!=0);bool ok=false;try{fn(State.s,(int)row[1]);ok=State.s!.level==(int)row[5]&&State.original.adventureLevel==(int)row[6]&&State.other.adventureLevel==(int)row[7]&&(ReferenceEquals(State.s.playerSave,State.original)?1u:ReferenceEquals(State.s.playerSave,State.other)?2u:0u)==row[8]&&State.textId==row[9]&&State.s.text_Level!.id==row[10]&&State.formatted==(int)row[11]&&State.trace==row[12]&&State.boolOK&&row[13]==1&&State.formatOK&&row[14]==1&&row[15]==1&&State.original.marker==123&&State.other.marker==123&&State.s.marker==234&&(State.trace==0?State.label1.text==null:State.label1.text==((int)row[11]).ToString("当前关卡：0",CultureInfo.CurrentCulture));}catch(Exception e)when(e is not InvalidProgramException){ok=false;}Check(ok,"native-row:"+index++);if(stop&&failures.Count>0)return new(count,failures);}
  State.Reset();bool npe=false;try{fn(null,1);}catch(NullReferenceException){npe=true;}Check(npe&&State.trace==0,"null-this");
  State.Reset(12,nullSave:true);State.s!.text_Level=null;fn(State.s,1);Check(State.trace==0&&State.s.level==12&&State.original.adventureLevel==777,"null-save-noop");
  State.Reset(1);State.s!.text_Level=null;npe=false;try{fn(State.s,1);}catch(NullReferenceException){npe=true;}Check(npe&&State.trace==3&&State.s.level==2&&State.original.adventureLevel==777,"null-text-partial");
  State.Reset(1);State.s!.text_Level=null;bool returned=true;try{fn(State.s,-1);}catch(Exception e)when(e is not InvalidProgramException){returned=false;}Check(returned&&State.trace==0&&State.s.level==1,"zero-sum-noop");
  State.Reset(12,4);npe=false;try{fn(State.s,1);}catch(NullReferenceException){npe=true;}Check(npe&&State.trace==34&&State.s!.level==13&&State.s.playerSave==null&&State.label1.text==13.ToString("当前关卡：0",CultureInfo.CurrentCulture)&&State.original.adventureLevel==777,"post-text-null-save");
  foreach(string fail in new[]{"format","text"}){State.Reset();State.fail=fail;bool thrown=false;try{fn(State.s,1);}catch(DependencyException){thrown=true;}Check(thrown&&State.trace==(fail=="format"?3:34)&&State.s!.level==13&&State.original.adventureLevel==777,"dependency:"+fail);}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var m=(MethodDefinition)a.MainModule.LookupToken(0x060000A5);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(r=>{if(r[0]!="0x060000A5")throw new Exception("Native scope");return r.Skip(1).Select(uint.Parse).ToArray();}).ToList();if(rows.Count!=8192)throw new Exception("Native rows");var result=Cases(Emit(m,"none"),rows);int count=result.Cases,errors=0;var failures=result.Failures;var controls=new List<object>();bool cp=true;
  foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","null_this_return","cached_save","cached_sum","late_text","add_ovf","wrong_field","copy_ref","wrong_bool","skip_commit","early_commit","unsigned_guard","zero_allowed"}){bool detected=false;string?error=null;try{detected=Cases(Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}
  var real=Emit(m,"none",true);var culture0=CultureInfo.CurrentCulture;try{foreach(string culture in new[]{"en-US","de-DE","ja-JP","ar-SA"})foreach(int delta in new[]{int.MinValue,-999,-1,0,1,2,127,1000,int.MaxValue}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(culture);State.Reset(0);real(State.s,delta);count++;bool positive=delta>0;if(State.s!.level!=(positive?delta:0)||State.original.adventureLevel!=(positive?delta:777)||State.trace!=(positive?4:0)||State.label1.text!=(positive?delta.ToString("当前关卡：0",CultureInfo.CurrentCulture):null)||positive&&!State.label1.flag)failures.Add("actual-format:"+culture+":"+delta);}}finally{CultureInfo.CurrentCulture=culture0;}
  bool pass=failures.Count==0&&errors==0&&cp;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=1,positive_cases=count,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Unchanged native caller with supplied objects and format identity; recorded formatter/text dependencies with explicit ref/receiver/Save/level stress mutations. CLR CIL executes signed wrap/guard/capture/reload/null/partial-effect behavior with public doubles; actual CLR custom numeric formatting runs separately in four cultures. No native formatter/UI/throw engine, Unity/Xcode or device acceptance.",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
