using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;using Vector3=UnityEngine.Vector3;using Quaternion=UnityEngine.Quaternion;
public class DependencyException:Exception{}
public class Dropdown{public int value;public void set_value(int v){State.events.Add("drop");State.dropValue=v;if(State.fail=="drop")throw new DependencyException();value=v;if(State.mode==1){State.grid!.passablePoint=State.alt;State.grid.inputField_passablePoint=State.input2;State.grid.isHome=!State.grid.isHome;}}}
public class InputField{public int id;public string?text;public void SetTextWithoutNotify(string s){State.events.Add("text");State.inputId=id;text=s;if(State.fail=="text")throw new DependencyException();if(State.mode==2){State.grid!.toggle_isHome=State.toggle2;State.grid.isHome=!State.grid.isHome;}}}
public class Toggle{public int id;public bool value;public void set_isOn(bool v){State.events.Add("toggle");State.toggleId=id;State.toggleValue=v;if(State.fail=="toggle")throw new DependencyException();value=v;}}
public class Grid{public int gridState,passablePoint;public bool isHome;public Dropdown?dropdown_gridState;public InputField?inputField_passablePoint;public Toggle?toggle_isHome;public int marker;}
public class MonoBehaviour{public MonoBehaviour(bool input){}public MonoBehaviour(){State.baseCalls++;State.baseReceiver=this;State.snapshot=this is Floating t?(t.lastPOS,t.lastRotation):null;if(State.fail=="base")throw new DependencyException();}}
public class Floating:MonoBehaviour{public Floating(bool input):base(input){}public Vector3 lastPOS;public Quaternion lastRotation;public int marker;public float untouched;}
public static class State{
 public static Grid?grid;public static int mode,alt,dropValue,stringValue,inputId,toggleId,baseCalls,zeroCalls,identityCalls;public static bool toggleValue;public static string fail="";public static List<string>events=new();public static InputField?input1,input2;public static Toggle?toggle2;public static Vector3 zero;public static Quaternion identity;public static object?baseReceiver;public static(Vector3,Quaternion)?snapshot;
 public static void Reset(){grid=null;mode=alt=dropValue=stringValue=inputId=toggleId=baseCalls=zeroCalls=identityCalls=0;toggleValue=false;events.Clear();fail="";input2=null;toggle2=null;baseReceiver=null;snapshot=null;}
 public static string Render(ref int v){events.Add("string");int input=v;stringValue=input;if(mode==3){grid!.inputField_passablePoint=input2;v=alt;}return input.ToString(CultureInfo.CurrentCulture);}
 public static Vector3 GetZero(){zeroCalls++;return zero;}public static Quaternion GetIdentity(){identityCalls++;return identity;}public static Vector3 WrongZero(){zeroCalls++;return new Vector3(1,1,1);}public static Quaternion WrongIdentity(){identityCalls++;var q=identity;q.w=0;return q;}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["GridConfig_A"]=typeof(Grid),["GridState"]=typeof(int),["TMPro.TMP_Dropdown"]=typeof(Dropdown),["TMPro.TMP_InputField"]=typeof(InputField),["UnityEngine.UI.Toggle"]=typeof(Toggle),["TMPro.Examples.TextMeshProFloatingText"]=typeof(Floating),["UnityEngine.MonoBehaviour"]=typeof(MonoBehaviour),["UnityEngine.Vector3"]=typeof(Vector3),["UnityEngine.Quaternion"]=typeof(Quaternion),["System.IntPtr"]=typeof(IntPtr),["System.String"]=typeof(string),["System.Int32"]=typeof(int),["System.Void"]=typeof(void),["System.Boolean"]=typeof(bool)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static FieldInfo F(FieldReference f)=>T(f.DeclaringType).GetField(f.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static)??throw new Exception("Missing field "+f);
 static MethodInfo M(MethodReference m,bool real,string mutation){if(m.FullName=="System.String System.Int32::ToString()")return real?typeof(int).GetMethod("ToString",Type.EmptyTypes)!:typeof(State).GetMethod(nameof(State.Render))!;if(m.FullName=="UnityEngine.Vector3 UnityEngine.Vector3::get_zero()")return real?typeof(Vector3).GetProperty("zero")!.GetMethod!:typeof(State).GetMethod(mutation=="wrong_zero"?nameof(State.WrongZero):nameof(State.GetZero))!;if(m.FullName=="UnityEngine.Quaternion UnityEngine.Quaternion::get_identity()")return real?typeof(Quaternion).GetProperty("identity")!.GetMethod!:typeof(State).GetMethod(mutation=="wrong_identity"?nameof(State.WrongIdentity):nameof(State.GetIdentity))!;return T(m.DeclaringType).GetMethod(m.Name,m.Parameters.Select(p=>T(p.ParameterType)).ToArray())??throw new Exception("Missing method "+m);}
 static Delegate Emit(MethodDefinition m,string mutation,bool real=false){var owner=T(m.DeclaringType);var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{owner},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=mutation=="none";
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}if(mutation=="base_first"){il.Emit(RO.Ldarg_0);il.Emit(RO.Call,typeof(MonoBehaviour).GetConstructor(Type.EmptyTypes)!);changed=true;}
  var ins=m.Body.Instructions;
  for(int ix=0;ix<ins.Count;ix++){var i=ins[ix];var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(mutation=="late_input"&&op==RO.Ldarg_0&&ix+4<ins.Count&&ins[ix+1].Operand is FieldReference inf&&inf.Name=="inputField_passablePoint"){
    if(ins[ix+2].OpCode!=Mono.Cecil.Cil.OpCodes.Ldarg_0||ins[ix+3].Operand is not FieldReference pf||pf.Name!="passablePoint"||ins[ix+4].Operand is not MethodReference render)throw new Exception("Late-input pattern mismatch");var str=il.DeclareLocal(typeof(string));il.Emit(RO.Ldarg_0);il.Emit(RO.Ldflda,F(pf));il.Emit(RO.Call,M(render,real,"none"));il.Emit(RO.Stloc,str);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,F(inf));il.Emit(RO.Ldloc,str);ix+=4;changed=true;continue;
   }
   if(operand is FieldReference field){var fi=F(field);if(field.Name=="passablePoint"&&op==RO.Ldflda){if(mutation=="wrong_field"){fi=typeof(Grid).GetField(nameof(Grid.gridState))!;changed=true;}if(mutation=="address_as_value"){il.Emit(RO.Ldfld,fi);changed=true;continue;}if(mutation=="copy_instead_of_ref"){var copy=il.DeclareLocal(typeof(int));il.Emit(RO.Ldfld,fi);il.Emit(RO.Stloc,copy);il.Emit(RO.Ldloca,copy);changed=true;continue;}}il.Emit(op,fi);continue;}
   if(operand is MethodReference method){if(method.Name==".ctor"){if(mutation is "skip_base" or "base_first"){il.Emit(RO.Pop);changed=true;}else il.Emit(op,T(method.DeclaringType).GetConstructor(method.Parameters.Select(p=>T(p.ParameterType)).ToArray())!);continue;}if(mutation=="skip_dropdown"&&method.Name=="set_value"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(mutation=="wrong_zero"&&method.Name=="get_zero"||mutation=="wrong_identity"&&method.Name=="get_identity")changed=true;il.Emit(op,M(method,real,mutation));continue;}
   if(operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(operand is int iv){il.Emit(op,iv);continue;}if(operand==null){il.Emit(op);continue;}throw new Exception("Unsupported operand "+operand);
  }
  if(!changed)throw new Exception("Mutation did not apply");return dm.CreateDelegate(typeof(Action<>).MakeGenericType(owner));
 }
 static uint[]Bits(Vector3 v)=>new[]{(uint)BitConverter.SingleToInt32Bits(v.x),(uint)BitConverter.SingleToInt32Bits(v.y),(uint)BitConverter.SingleToInt32Bits(v.z)};static uint[]Bits(Quaternion q)=>new[]{(uint)BitConverter.SingleToInt32Bits(q.x),(uint)BitConverter.SingleToInt32Bits(q.y),(uint)BitConverter.SingleToInt32Bits(q.z),(uint)BitConverter.SingleToInt32Bits(q.w)};static float Float(uint v)=>BitConverter.Int32BitsToSingle((int)v);
 record Result(int Cases,List<string>Failures);
 static Grid Input(int value=12){State.Reset();var g=new Grid{gridState=-3,passablePoint=value,isHome=true,dropdown_gridState=new(),inputField_passablePoint=new(){id=1},toggle_isHome=new(){id=1},marker=0x1234};State.grid=g;State.input1=g.inputField_passablePoint;State.input2=new(){id=2};State.toggle2=new(){id=2};return g;}
 static Result Cases(MethodDefinition m,Delegate fn,List<uint[]>rows,bool stop=false,bool extras=true){int cases=0,index=0;var fails=new List<string>();void Check(bool yes,string label){cases++;if(!yes)fails.Add(label);}if(m.MetadataToken.ToInt32()==0x0600061C){var call=(Action<Grid?>)fn;
   foreach(var row in rows){var g=Input((int)row[1]);g.gridState=(int)row[0];g.isHome=row[2]!=0;State.mode=(int)row[3];State.alt=(int)row[4];bool match=false;try{call(g);match=State.dropValue==(int)row[5]&&State.stringValue==(int)row[6]&&State.inputId==row[7]&&State.toggleId==row[8]&&State.toggleValue==(row[9]!=0)&&(g.inputField_passablePoint?.id??0)==row[10]&&row[11]==1&&row[12]==1&&g.passablePoint==(int)row[13]&&State.events.SequenceEqual(new[]{"drop","string","text","toggle"})&&g.marker==0x1234&&(State.inputId==1?State.input1:State.input2)?.text==((int)row[6]).ToString(CultureInfo.CurrentCulture);}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"grid-row:"+index++);if(stop&&fails.Count>0)return new(cases,fails);}
   if(extras){for(int which=0;which<4;which++){var g=Input();if(which==1)g.dropdown_gridState=null;if(which==2)g.inputField_passablePoint=null;if(which==3)g.toggle_isHome=null;bool npe=false;try{call(which==0?null:g);}catch(NullReferenceException){npe=true;}string[][]expected={Array.Empty<string>(),Array.Empty<string>(),new[]{"drop","string"},new[]{"drop","string","text"}};Check(npe&&State.events.SequenceEqual(expected[which]),"grid-null:"+which);}
    foreach(string stage in new[]{"drop","text","toggle"}){var g=Input();State.fail=stage;bool thrown=false;try{call(g);}catch(DependencyException){thrown=true;}int len=stage=="drop"?1:stage=="text"?3:4;Check(thrown&&State.events.SequenceEqual(new[]{"drop","string","text","toggle"}.Take(len))&&g.marker==0x1234,"grid-dependency:"+stage);}
   }
  }else{var call=(Action<Floating?>)fn;foreach(var row in rows){State.Reset();State.zero=new Vector3(Float(row[3]),Float(row[4]),Float(row[5]));State.identity=new Quaternion(Float(row[6]),Float(row[7]),Float(row[8]),Float(row[9]));var clip=new Floating(true){marker=0x5678,untouched=Float(0x80000000)};bool match=false;try{call(clip);match=row[0]==1&&row[1]==1&&row[2]==1&&Bits(clip.lastPOS).Concat(Bits(clip.lastRotation)).SequenceEqual(row.Skip(3))&&State.baseCalls==1&&ReferenceEquals(State.baseReceiver,clip)&&State.snapshot is{}snap&&Bits(snap.Item1).Concat(Bits(snap.Item2)).SequenceEqual(row.Skip(3))&&clip.marker==0x5678&&BitConverter.SingleToInt32Bits(clip.untouched)==unchecked((int)0x80000000)&&State.zeroCalls==1&&State.identityCalls==1;}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"ctor-row:"+index++);if(stop&&fails.Count>0)return new(cases,fails);}
   if(extras){State.Reset();bool npe=false;try{call(null);}catch(NullReferenceException){npe=true;}Check(npe&&State.zeroCalls==1&&State.identityCalls==0&&State.baseCalls==0,"ctor-null-store-order");State.Reset();State.zero=new Vector3(3,4,5);State.identity=new Quaternion(6,7,8,9);State.fail="base";var clip=new Floating(true){marker=123};bool thrown=false;try{call(clip);}catch(DependencyException){thrown=true;}Check(thrown&&State.baseCalls==1&&Bits(clip.lastPOS).SequenceEqual(Bits(State.zero))&&Bits(clip.lastRotation).SequenceEqual(Bits(State.identity))&&clip.marker==123,"ctor-writes-before-base-exception");}
  }return new(cases,fails);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var parsed=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();int count=0,errors=0;var failures=new List<string>();var controls=new List<object>();bool cp=true;foreach(int token in new[]{0x0600061C,0x0600079B}){var m=(MethodDefinition)a.MainModule.LookupToken(token);var rows=parsed.Where(r=>r[0]==$"0x{token:X8}").Select(r=>r.Skip(1).Select(uint.Parse).ToArray()).ToList();if(rows.Count!=4096)throw new Exception("Native row count");var result=Cases(m,Emit(m,"none"),rows);count+=result.Cases;failures.AddRange(result.Failures);foreach(string mutation in args.Length>3?Array.Empty<string>():token==0x0600061C?new[]{"illegal_stack","return_early","wrong_field","address_as_value","copy_instead_of_ref","late_input","skip_dropdown"}:new[]{"illegal_stack","return_early","wrong_zero","wrong_identity","base_first","skip_base"}){bool detected=false;string?error=null;try{detected=Cases(m,Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{token=$"0x{token:X8}",mutation,detected,tool_error=error});}}
   var originalCulture=CultureInfo.CurrentCulture;var realGrid=(Action<Grid?>)Emit((MethodDefinition)a.MainModule.LookupToken(0x0600061C),"none",true);foreach(string culture in new[]{"en-US","de-DE","ja-JP","ar-SA"})foreach(int value in new[]{int.MinValue,-999,-1,0,1,2,127,1000,int.MaxValue}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(culture);var g=Input(value);realGrid(g);count++;if(g.inputField_passablePoint!.text!=value.ToString(CultureInfo.CurrentCulture)||State.dropValue!=-3||State.toggleValue!=true||!State.events.SequenceEqual(new[]{"drop","text","toggle"}))failures.Add("actual-formatter:"+culture+":"+value);}CultureInfo.CurrentCulture=originalCulture;
   State.Reset();var realClip=new Floating(true);((Action<Floating?>)Emit((MethodDefinition)a.MainModule.LookupToken(0x0600079B),"none",true))(realClip);count++;if(!Bits(realClip.lastPOS).SequenceEqual(new uint[]{0,0,0})||!Bits(realClip.lastRotation).SequenceEqual(new uint[]{0,0,0,0x3f800000})||State.baseCalls!=1)failures.Add("actual-pinned-public-getters");
   bool pass=failures.Count==0&&errors==0&&cp;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=count,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,unity_core_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(typeof(Vector3).Assembly.Location))).ToLowerInvariant(),scope="Unchanged original UI/constructor callers with recorded setters/formatter/base constructor and supplied class/static layouts. CLR candidate CIL executes with public doubles and actual CoreModule Vector3/Quaternion value types. Formatter adapter records ref/address effects and stressful callbacks; separate actual CLR Int32.ToString and pinned public zero/identity getters execute. No original native formatter, Unity/UI/base/throw engine or iOS/device acceptance",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
  }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
