using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;
public class DependencyException:Exception{}
public class Component{}
public class Game{}
public class Entity{public int id;}
public class Manager:Component{public List<Entity?>?deviceList,plants,zombieList;}
public class Home:Component{public List<Entity?>?deviceWindowList,zombieWindowList;}
public class Board:Component{public Manager?plantManager,zombieManager,deviceManager;}
public class Save{public bool[]?almanac_DeviceLock,almanac_ZombieLock;}
public class Saves{public Save?playerSave;}
public class Lawn{public Saves?savesManager;}
public static class State{
 public static Lawn?gLawnApp;public static Manager[]managers=new Manager[3];public static Manager altManager=new();public static Home home=new();public static Board board=new();public static Save saveA=new(),saveB=new();public static Saves saves=new();public static Game game=new();public static List<Entity?>[]lists=new List<Entity?>[5],alternates=new List<Entity?>[5];public static bool[]array2=new bool[2];
 public static int mode,hook,token;public static bool argsOK;public static List<uint>trace=new();public static Dictionary<int,Action<object,int>>methods=new();
 public static void Ev(uint x)=>trace.Add(x);public static void Ev(int x)=>trace.Add(unchecked((uint)x));
 public static void SetList(int t,List<Entity?>?p){if(t==0)managers[t].deviceList=p;else if(t==1)managers[t].plants=p;else if(t==2)managers[t].zombieList=p;else if(t==3)home.deviceWindowList=p;else home.zombieWindowList=p;}
 public static List<Entity?>?List(int t)=>t switch{0=>managers[0].deviceList,1=>managers[1].plants,2=>managers[2].zombieList,3=>home.deviceWindowList,_=>home.zombieWindowList};
 public static void Change(int t){if(hook==1){if(t<3){var l=List(t);if(l!=null&&l.Count>0)l.RemoveAt(l.Count-1);}else SetList(t,alternates[t]);}if(hook==2)SetList(t,null);if(hook==3){SetList(t,alternates[t]);alternates[t].Clear();}if(t>=3){if(hook==4){if(t==3)saveA.almanac_DeviceLock=array2;else saveA.almanac_ZombieLock=array2;}if(hook==5)saves.playerSave=null;if(hook==6)saves.playerSave=saveB;if(hook==7){if(t==3)saveA.almanac_DeviceLock=null;else saveA.almanac_ZombieLock=null;}}
  else if(token==0x060002AA){if(t==1&&hook==5)board.zombieManager=null;if(t==2&&hook==6)board.zombieManager=altManager;if(t==2&&hook==7)board.deviceManager=null;}}
 public static Entity?Item(List<Entity?>?r,int ix,int t){if(r==null)throw new NullReferenceException();bool alt=ReferenceEquals(r,alternates[t]);argsOK&=alt||ReferenceEquals(r,lists[t]);Ev(1);Ev(t);Ev(ix);Ev(alt?1:0);if(mode==12)throw new DependencyException();return r[ix];}
 public static void Destroy(Entity?r,int t){if(r==null)throw new NullReferenceException();Ev(5);Ev(t);Ev(r.id);if(mode==14)throw new DependencyException();Change(t);}
 public static void SetState(Entity?r,bool v,int t){if(r==null)throw new NullReferenceException();Ev(6);Ev(t);Ev(r.id);Ev(v?1:0);if(mode==15)throw new DependencyException();Change(t);}
 public static Game?GetGame(Component r){if(r==null)throw new NullReferenceException();Ev(2);argsOK&=ReferenceEquals(r,token==0x060002AA?(Component)board:home);return mode==8?null:game;}
 public static void Active(Game?r,bool v){if(r==null)throw new NullReferenceException();Ev(3);Ev(v?1:0);argsOK&=ReferenceEquals(r,game)&&v;if(mode==13)saves.playerSave=saveB;}
 public static void DestroyGame(Game?r){Ev(7);Ev(r==null?1:0);argsOK&=r==null||ReferenceEquals(r,game);}
 public static void Check(Home r,int id,int t){Ev(4);Ev(t);Ev(id);argsOK&=ReferenceEquals(r,home);}
 public static void ClearPlant(Manager?r){if(r==null)throw new NullReferenceException();methods[0x060001EF](r,0);}
 public static void ClearDevice(Manager?r){if(r==null)throw new NullReferenceException();methods[0x06000182](r,0);}
 public static object Reset(int target,int k){token=target;mode=k%16;hook=(k/16)%8;int count=(k/128)%5;managers=Enumerable.Range(0,3).Select(_=>new Manager()).ToArray();home=new();board=new();saveA=new();saveB=new();saves=new();gLawnApp=new();altManager=new();
  for(int t=0;t<5;t++){var objects=Enumerable.Range(0,8).Select(j=>new Entity{id=10*t+j+1}).ToArray();lists[t]=objects.Take(count).Select((e,j)=>(mode==2||mode==3)&&j==0?null:e).ToList();alternates[t]=objects.Reverse().Take(3).Cast<Entity?>().ToList();if(t<3)SetList(t,mode==1?null:lists[t]);}
  int ht=target is 0x06000560 or 0x06000563?3:4;SetList(ht,mode==1?null:lists[ht]);bool[]arr0=Enumerable.Range(0,mode==3?0:8).Select(j=>(k+j)%2!=0).ToArray(),arr1=Enumerable.Range(0,mode==3?0:8).Select(j=>(k+j+1)%2!=0).ToArray();array2=Enumerable.Range(0,2).Select(j=>(k+j+2)%2!=0).ToArray();saveA.almanac_DeviceLock=saveA.almanac_ZombieLock=mode==4?null:arr0;saveB.almanac_DeviceLock=saveB.almanac_ZombieLock=arr1;saves.playerSave=mode==7?null:saveA;gLawnApp.savesManager=mode==6?null:saves;if(mode==5)gLawnApp=null;
  board.plantManager=mode==9?null:managers[1];board.zombieManager=mode==10?null:managers[2];board.deviceManager=mode==11?null:managers[0];altManager.zombieList=alternates[2];trace=new();argsOK=true;return target switch{0x06000182=>managers[0],0x060001EF=>managers[1],0x06000279=>managers[2],0x060002AA=>board,_=>home};
 }
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["DeviceManager"]=typeof(Manager),["PlantManager"]=typeof(Manager),["ZombieManager"]=typeof(Manager),["Board"]=typeof(Board),["Device"]=typeof(Entity),["Plant"]=typeof(Entity),["Zombie"]=typeof(Entity),["Almanac_DeviceWindow"]=typeof(Entity),["Almanac_ZombieWindow"]=typeof(Entity),["Almanac_DeviceHome"]=typeof(Home),["Almanac_ZombieHome"]=typeof(Home),["Save"]=typeof(Save),["SavesManager"]=typeof(Saves),["GlobalStaticVars/LawnApp"]=typeof(Lawn),["GlobalStaticVars"]=typeof(State),["UnityEngine.GameObject"]=typeof(Game),["UnityEngine.Component"]=typeof(Component),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.IntPtr"]=typeof(IntPtr)};
 static Type T(TypeReference r)=>r is ArrayType a?T(a.ElementType).MakeArrayType():r is GenericInstanceType g&&g.ElementType.FullName=="System.Collections.Generic.List`1"?typeof(List<>).MakeGenericType(T(g.GenericArguments.Single())):map.TryGetValue(r.FullName,out var t)?t:throw new Exception("Unmapped "+r);
 static int Kind(string owner)=>owner.Contains("Almanac_Device")?3:owner.Contains("Almanac_Zombie")?4:owner.Contains("Zombie")?2:owner.Contains("Plant")?1:owner.Contains("Device")?0:throw new Exception("Kind "+owner);
 static Action<object,int>Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.FullName+mutation,typeof(void),new[]{typeof(object),typeof(int)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var self=il.DeclareLocal(T(m.DeclaringType));il.Emit(RO.Ldarg_0);il.Emit(RO.Castclass,T(m.DeclaringType));il.Emit(RO.Stloc,self);var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";int countCalls=0;
  if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var o=i.Operand;
   if(o is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}
   if(o is MethodReference mr){string name=mr.Name;int kind=mr.DeclaringType.FullName.Contains("List`1")?Kind(((GenericInstanceType)mr.DeclaringType).GenericArguments.Single().FullName):name is "DestroyThis" or "DestroyZombie" or "SetState" or "CheckDevice" or "CheckZombie"?Kind(mr.DeclaringType.FullName):-1;
    if(name=="get_Count"){countCalls++;if(mutation=="zero_count"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}else il.Emit(op,typeof(List<Entity>).GetProperty("Count")!.GetMethod!);continue;}
    if(name=="get_Item"){if(mutation=="index_zero"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}il.Emit(RO.Ldc_I4,kind);il.Emit(RO.Call,typeof(State).GetMethod(nameof(State.Item))!);continue;}
    string dependency=name switch{"DestroyThis" or "DestroyZombie"=>nameof(State.Destroy),"SetState"=>nameof(State.SetState),"get_gameObject"=>nameof(State.GetGame),"SetActive"=>nameof(State.Active),"Destroy"=>nameof(State.DestroyGame),"CheckDevice" or "CheckZombie"=>nameof(State.Check),"ClearPlants"=>nameof(State.ClearPlant),"ClearDevices"=>nameof(State.ClearDevice),_=>throw new Exception("Method "+mr)};
    if(mutation=="false_lock"&&name=="SetState"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}if(mutation=="flip_lock"&&name=="SetState"){il.Emit(RO.Ldc_I4_0);il.Emit(RO.Ceq);changed=true;}
    if(mutation=="skip_destroy"&&name is "DestroyThis" or "DestroyZombie"){il.Emit(RO.Pop);changed=true;continue;}if(mutation=="skip_check"&&name is "CheckDevice" or "CheckZombie"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(mutation=="skip_device_clear"&&name=="ClearDevices"){il.Emit(RO.Pop);changed=true;continue;}
    if(kind>=0)il.Emit(RO.Ldc_I4,kind);il.Emit(RO.Call,typeof(State).GetMethod(dependency)!);continue;
   }
   if(o is Mono.Cecil.Cil.Instruction j){if(mutation=="exclusive_zero"&&op==RO.Bge){op=RO.Bgt;changed=true;}if(mutation=="inclusive_count"&&op==RO.Blt){op=RO.Ble;changed=true;}il.Emit(op,labels[j]);continue;}
   if(o is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(o is ParameterDefinition pd){il.Emit(op,(short)(pd.Index+1));continue;}if(o is int x){il.Emit(op,x);continue;}if(o is sbyte b){il.Emit(op,b);continue;}
   if(o==null){if(op==RO.Ldarg_0){il.Emit(RO.Ldloc,self);continue;}if(mutation=="wrong_direction"&&op==RO.Sub){op=RO.Add;changed=true;}if(mutation=="null_array"&&op==RO.Ldelem_U1){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;continue;}il.Emit(op);continue;}throw new Exception("Unsupported "+o);
  }
  if(!changed)throw new Exception("Mutation did not apply "+mutation+" "+m.FullName);return(Action<object,int>)dm.CreateDelegate(typeof(Action<object,int>));
 }
 record Row(int Token,int K,int Input,int Error,bool Args,string Trace);
 static (int,int,List<string>)Cases(Dictionary<int,Action<object,int>>functions,List<Row>rows,bool stop=false){State.methods=functions;int cases=0,fail=0;var failures=new List<string>();foreach(var r in rows){var self=State.Reset(r.Token,r.K);int err=0;try{functions[r.Token](self,r.Input);}catch(NullReferenceException){err=1;State.Ev(8);}catch(Exception e)when(e is IndexOutOfRangeException or ArgumentOutOfRangeException){err=2;State.Ev(9);}catch(DependencyException){err=3;State.Ev(10);}var trace=State.trace.Count==0?"-":string.Join(',',State.trace)+",";bool ok=err==r.Error&&State.argsOK==r.Args&&trace==r.Trace;cases++;if(!ok){fail++;if(failures.Count<20)failures.Add(r.Token.ToString("X8")+":"+r.K+" err="+err+" expected="+r.Error+" trace="+trace+" expected="+r.Trace);if(stop)return(cases,fail,failures);}}return(cases,fail,failures);}
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]targets={0x06000182,0x060001EF,0x06000279,0x06000560,0x06000563,0x060005AF,0x060005B0,0x060002AA};var ms=targets.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var functions=ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none"));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new Row(Convert.ToInt32(v[0],16),int.Parse(v[1]),unchecked((int)uint.Parse(v[2])),int.Parse(v[3]),v[4]=="1",v[5])).ToList();if(rows.Count!=16384||targets.Any(t=>rows.Count(r=>r.Token==t)!=2048))throw new Exception("Row cardinality");var result=Cases(functions,rows);var controls=new List<object>();int toolErrors=0;bool cp=true;
  foreach(var (t,names) in new[]{(0x06000182,new[]{"illegal_stack","return_early","zero_count","index_zero","skip_destroy","exclusive_zero","wrong_direction"}),(0x06000560,new[]{"false_lock","flip_lock","index_zero","skip_check","inclusive_count","null_array","zero_count"}),(0x060002AA,new[]{"skip_device_clear","skip_destroy","index_zero","exclusive_zero"})})foreach(string mutation in args.Length>3?Array.Empty<string>():names){bool detected=false;string?error=null;try{var f=new Dictionary<int,Action<object,int>>(functions);f[t]=Emit(ms[t],mutation);detected=Cases(f,rows.Where(r=>r.Token==t).ToList(),true).Item2>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();toolErrors++;}cp&=detected&&error==null;controls.Add(new{token=t,mutation,detected,tool_error=error});}
  bool pass=result.Item2==0&&cp&&toolErrors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=8,positive_cases=result.Item1,positive_failures=result.Item2,negative_controls=controls.Count,tool_errors=toolErrors,gate_pass=pass,failures=result.Item3,controls,scope="Actual candidate CIL emitted/executed with real public List.Count and indexer, real bool arrays; recorded external destroy/SetState/check/Unity/exception dependencies. Original PC native caller trace, including original nested Board clear methods, captured manager/save, callback mutation, lock-read and exception priority. Fixture aliases entity/home types; independent frozen type checker and exact metadata audit check actual signatures. No original engine/class-init/dependency implementation/iOS or whole-game acceptance."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
