using Mono.Cecil;using Mono.Cecil.Cil;using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Audit48{
 static void R(bool x,string m){if(!x)throw new Exception(m);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 public static int Main(string[]args){try{
  byte[]old=File.ReadAllBytes(args[0]),raw=File.ReadAllBytes(args[1]);R(H(old)=="7d4a2d733348df060a70070ab9a5842d386e1fffb5b57a3d6dc606c845e85aa8","Pinned Native47 parent");R(old.Length==raw.Length,"No append");using var a=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(old));using var pc=new PEReader(new MemoryStream(raw));var expected=(byte[])old.Clone();int off(int rva){var s=pe.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
  var targets=new HashSet<int>{0x06000225,0x06000230};var report=JsonDocument.Parse(File.ReadAllText(args[2]));R(report.RootElement.GetProperty("methods").EnumerateArray().Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).ToHashSet().SetEquals(targets),"Pinned targets");var edits=new List<object>();
  foreach(int token in targets){var m=(MD)a.MainModule.LookupToken(token);var ins=m.Body.Instructions;R(m.IsStatic&&m.Body.ExceptionHandlers.Count==0,"Static no EH target");var compare=ins.Select((i,k)=>(i,k)).Single(x=>x.i.OpCode==OpCodes.Ceq&&x.k>=2&&ins[x.k-1].OpCode==OpCodes.Ldc_I4&&(int)ins[x.k-1].Operand==0&&ins[x.k-2].Operand is VariableDefinition v&&v.Index==9&&v.VariableType.FullName==m.ReturnType.FullName);int zero=ins[compare.k-1].Offset;
   var bad=ins.Where(i=>i.OpCode==OpCodes.Ret&&i.Previous?.Operand is VariableDefinition v&&v.VariableType.FullName=="System.NullReferenceException").Single();R(bad.Previous!.Previous!.OpCode==OpCodes.Stloc&&bad.Previous.Previous.Operand==bad.Previous.Operand&&bad.Previous.Previous.Previous!.OpCode==OpCodes.Newobj&&((MethodReference)bad.Previous.Previous.Previous.Operand).FullName=="System.Void System.NullReferenceException::.ctor()","NRE-only block");
   int header=off(m.RVA),start=header+12;R((old[header]&3)==3&&(BitConverter.ToUInt16(old,header)>>12)==3,"Fat header");R(old[start+zero]==0x20&&BitConverter.ToInt32(old,start+zero+1)==0&&old[start+bad.Offset]==0x2a,"Expected old encodings");expected[start+zero]=0x14;Array.Clear(expected,start+zero+1,4);expected[start+bad.Offset]=0x7a;
   var row=report.RootElement.GetProperty("methods").EnumerateArray().Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(H(raw[start..(start+m.Body.CodeSize)])==row.GetProperty("code_sha256").GetString(),"Reopened code digest");edits.Add(new{token=$"0x{token:X8}",null_constant_offset=zero,exception_return_offset=bad.Offset});
  }
  R(expected.SequenceEqual(raw),"Independent exact patch scope: all other original bytes must match");IEnumerable<Mono.Cecil.TypeDefinition>Types(Mono.Cecil.TypeDefinition t)=>new[]{t}.Concat(t.NestedTypes.SelectMany(Types));int non=0;foreach(var owner in a.MainModule.Types.SelectMany(Types))foreach(var m in owner.Methods){if(!m.HasBody||targets.Contains(m.MetadataToken.ToInt32()))continue;int at=off(m.RVA);var body=pe.GetMethodBody(m.RVA);R(old.AsSpan(at,body.Size).SequenceEqual(raw.AsSpan(at,body.Size)),"Non-target raw body");non++;}
  int diffs=Enumerable.Range(0,old.Length).Count(i=>old[i]!=raw[i]);R(diffs==4,"Exactly four byte differences");R(pe.GetMetadata().GetContent().SequenceEqual(pc.GetMetadata().GetContent()),"Metadata exact");var result=new{input_sha256=H(old),candidate_sha256=H(raw),targets=2,non_target_raw_bodies_equal=non,existing_heaps_equal=true,existing_metadata_root_equal=true,original_sections_equal=true,old_file_changed_bytes=diffs,appended_bytes=0,independent_edits=edits,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(result));return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
