using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;
public class Board{}
public class Buff {public int marker;}
public class EnemyPath {public int marker;}
public class Device {public int marker;public Board? board;}
public class Zombie {public int marker;public List<EnemyPath>? prePath;}
public class BuffManager {public List<Buff>? buffs_toRemove;}
public class DeviceManager {public List<Device>? deviceList;public Board? board;}
public class ZombieManager {public List<Zombie>? zombieList;}
public static class Fixture{
 static Dictionary<string,Type> Map=new(){["Board"]=typeof(Board),["Buff"]=typeof(Buff),["Device"]=typeof(Device),["Zombie"]=typeof(Zombie),["EnemyPath"]=typeof(EnemyPath),["BuffManager"]=typeof(BuffManager),["DeviceManager"]=typeof(DeviceManager),["ZombieManager"]=typeof(ZombieManager),["System.Collections.Generic.List`1"]=typeof(List<>),["System.Object"]=typeof(object),["System.Int32"]=typeof(int),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>t is GenericInstanceType g?T(g.ElementType).MakeGenericType(g.GenericArguments.Select(T).ToArray()):t is ArrayType a?T(a.ElementType).MakeArrayType():Map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static Type Bound(TypeReference t,MethodReference m)=>t is GenericParameter p?T(((GenericInstanceType)m.DeclaringType).GenericArguments[p.Position]):T(t);
 static DynamicMethod Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,T(m.ReturnType),new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray(),typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="missing_operation"){il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="wrong_argument"&&((m.MetadataToken.ToInt32()==0x06000462&&op==RO.Ldarg_2)||(m.MetadataToken.ToInt32()!=0x06000462&&op==RO.Ldarg_1&&i.Next?.Operand is MethodReference))){il.Emit(RO.Ldnull);changed=true;continue;}
   if(mutation=="wrong_guard"&&op==RO.Brfalse_S){op=RO.Brtrue_S;changed=true;}
   if(mutation=="missing_board_write"&&op==RO.Stfld){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition p){il.Emit(op,(short)(p.Index+1));continue;}
   if(a is MethodReference mr){var mi=T(mr.DeclaringType).GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,mr.Parameters.Select(p=>Bound(p.ParameterType,mr)).ToArray(),null)??throw new Exception("Missing public method "+mr);il.Emit(op,mi);continue;}
   if(a is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation did not apply");return dm;
 }
 static void Throws(DynamicMethod dm,object?[] args,Type kind,List<string> failures){try{dm.Invoke(null,args);failures.Add("missing-exception:"+kind.Name);}catch(TargetInvocationException e)when(e.InnerException?.GetType()==kind){}}
 static List<string> Cases(MethodDefinition m,DynamicMethod dm,List<long[]> rows,bool stop=false){var failures=new List<string>();int token=m.MetadataToken.ToInt32(),ix=0;bool insert=token==0x06000462;var owner=T(m.DeclaringType);var listField=owner.GetField(insert?"prePath":token==0x06000103?"buffs_toRemove":token==0x06000181?"deviceList":"zombieList")!;var elem=T(m.Parameters[insert?1:0].ParameterType);var listType=typeof(List<>).MakeGenericType(elem);var version=listType.GetField("_version",BindingFlags.NonPublic|BindingFlags.Instance)!;
  foreach(var r in rows){int count=(int)r[insert?1:0],cap=insert?count+1:(int)r[1],value=(int)r[insert?3:3+count];object h=Activator.CreateInstance(owner)!;object?[] objects={null,Activator.CreateInstance(elem),Activator.CreateInstance(elem),Activator.CreateInstance(elem),Activator.CreateInstance(elem)};foreach(var o in objects.Where(o=>o!=null))elem.GetField("marker")!.SetValue(o,123);var list=(System.Collections.IList)Activator.CreateInstance(listType,cap)!;int start=insert?5:3;for(int i=0;i<count;i++)list.Add(objects[(int)r[start+i]]);version.SetValue(list,unchecked((int)r[insert?4:2]));listField.SetValue(h,insert&&r[0]==0?null:list);Board?[] boards={null,new Board(),new Board(),new Board()};if(token==0x06000181){((DeviceManager)h).board=boards[(int)r[4+count]];((Device)objects[value]!).board=boards[(int)r[5+count]];}
   bool match;try{dm.Invoke(null,insert?new object?[]{h,(int)r[2],objects[value]}:new object?[]{h,objects[value]});int at=insert?5+count:6+count;int calls=insert?(int)r[at++]:-1;int expectedCount=(int)r[at++];uint expectedVersion=(uint)r[at++];int[] expected=r.Skip(at).Take(expectedCount).Select(v=>(int)v).ToArray();int[] actual=list.Cast<object?>().Select(o=>Array.FindIndex(objects,x=>ReferenceEquals(x,o))).ToArray();match=list.Count==expectedCount&&unchecked((uint)(int)version.GetValue(list)!)==expectedVersion&&actual.SequenceEqual(expected)&&ReferenceEquals(listField.GetValue(h),insert&&r[0]==0?null:list)&&objects.Where(o=>o!=null).All(o=>(int)elem.GetField("marker")!.GetValue(o)! ==123);if(token==0x06000181)match&=ReferenceEquals(((Device)objects[value]!).board,((DeviceManager)h).board)&&(int)r[^1]==1;}
   catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){match=false;}
   if(!match){failures.Add("row:"+ix);if(stop)return failures;}ix++;
  }
  object?[] Args(object? h)=>insert?new object?[]{h,0,null}:new object?[]{h,null};Throws(dm,Args(null),typeof(NullReferenceException),failures);
  if(insert){var z=new Zombie();foreach(int index in new[]{int.MinValue,-1,0,1,int.MaxValue})dm.Invoke(null,new object?[]{z,index,null});z.prePath=new();foreach(int index in new[]{-1,1})Throws(dm,new object?[]{z,index,null},typeof(ArgumentOutOfRangeException),failures);}
  else{
   object manager=Activator.CreateInstance(owner)!;Throws(dm,Args(manager),typeof(NullReferenceException),failures);var l=(System.Collections.IList)Activator.CreateInstance(listType,0)!;listField.SetValue(manager,l);var value=Activator.CreateInstance(elem);var enumerator=(System.Collections.IEnumerator)listType.GetMethod("GetEnumerator",Type.EmptyTypes)!.Invoke(l,null)!;dm.Invoke(null,new object?[]{manager,value});if(l.Count!=1||!ReferenceEquals(l[0],value)||(int)listType.GetProperty("Capacity")!.GetValue(l)!<1)failures.Add("empty-capacity-growth");try{enumerator.MoveNext();failures.Add("enumerator-not-invalidated");}catch(InvalidOperationException){}
   if(token==0x06000181){var dev=new DeviceManager{deviceList=new(),board=new Board()};Throws(dm,new object?[]{dev,null},typeof(NullReferenceException),failures);if(dev.deviceList.Count!=1||dev.deviceList[0]!=null)failures.Add("null-device-must-append-before-failure");}
  }return failures;
 }
 public static int Main(string[] args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).GroupBy(l=>l[0]).ToDictionary(g=>g.Key,g=>g.Select(l=>l.Skip(1).Select(long.Parse).ToArray()).ToList());if(rows.Count!=4)throw new Exception("Expected4");int bad=0,errors=0,total=0;bool detected=true;var positives=new List<object>();var controls=new List<object>();foreach(var(key,rs)in rows){int token=Convert.ToInt32(key,16);var m=(MethodDefinition)a.MainModule.LookupToken(token);var fail=Cases(m,Emit(m,"none"),rs);bad+=fail.Count;int extra=token==0x06000462?8:token==0x06000181?5:4;total+=rs.Count+extra;positives.Add(new{token=key,cases=rs.Count+extra,failures=fail});foreach(string mut in(args.Length>3?Array.Empty<string>():new[]{"missing_operation","wrong_argument","illegal_stack"}.Concat(token==0x06000462?new[]{"wrong_guard"}:token==0x06000181?new[]{"missing_board_write"}:Array.Empty<string>()))){bool reject=false;string? err=null;try{reject=Cases(m,Emit(m,mut),rs,true).Count>0;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){reject=true;}catch(InvalidProgramException){reject=true;}catch(Exception e){err=e.ToString();errors++;}detected&=reject&&err==null;controls.Add(new{token=key,mutation=mut,detected=reject,tool_error=err});}}
  bool pass=bad==0&&errors==0&&detected;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=4,positive_cases=total,positive_failures=bad,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Three original inlined List.Add caller bodies execute unchanged with spare capacity; metadata flags supplied and GC-barrier dependency suppressed. Insert original caller runs with controlled public List.Insert dependency. Actual CLR candidate binds public typed List.Add/Insert; private version reflection is observational test setup/readback, never candidate IL. CLR adds growth/exception/enumerator and null-Device insertion-before-failure checks. No original resize/allocator/GC/Unity engine or iOS/device equivalence claim",positives,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
