using Mono.Cecil;using CI=Mono.Cecil.Cil.Instruction;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Linq.Expressions;
public class DependencyException:Exception{}
public class Object {public override bool Equals(object? other){State.Compare();return ReferenceEquals(this,other);}public override int GetHashCode()=>System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(this);public static void Destroy(Object? o){State.trace.Add("D");State.destroyed=o;if(State.failDestroy)throw new DependencyException();}}
public class GameObject:Object{}
public class Component:Object {public GameObject? go;public GameObject? gameObject{get{State.trace.Add("G");State.getReceiver=this;State.beforeDestroy=State.snapshot?.Invoke();if(State.hook==3)State.Mutate();if(State.failGetter)throw new DependencyException();return go;}}}
public class PreDevice:Object{}public class Enemy:Object{}
public class Device_boardEditor:Component {public PreDevice? preDevice;}
public class Enemy_boardEditor:Component {public Enemy? preEnemy;}
public class BoardConfig {public List<PreDevice?>? preDevices;public List<Enemy?>? preEnemies;}
public class Admin_system2_boardEdior {public BoardConfig? boardConfig;public List<Device_boardEditor?>? device_BoardEditors;public List<Enemy_boardEditor?>? enemy_BoardEditors;}
public class DeviceDataEditor {public Admin_system2_boardEdior? boardEdior;public Device_boardEditor? deviceOnCheck;public void LoadData(Device_boardEditor? v){State.trace.Add("L");State.loadReceiver=this;State.loadArgument=v;if(State.failLoad)throw new DependencyException();deviceOnCheck=v;}}
public class EnemyDataEditor {public Admin_system2_boardEdior? boardEdior;public Enemy_boardEditor? enemyOnCheck;public void LoadData(Enemy_boardEditor? v){State.trace.Add("L");State.loadReceiver=this;State.loadArgument=v;if(State.failLoad)throw new DependencyException();enemyOnCheck=v;}}
public static class State {public static List<string>trace=new();public static object? getReceiver,destroyed,loadReceiver,loadArgument;public static bool failGetter,failDestroy,failLoad,failCompare,hookFired;public static int hook;public static Action? Mutation;public static Func<int[][]>?snapshot;public static int[][]?beforeDestroy;public static void Mutate()=>Mutation?.Invoke();public static void Compare(){if(failCompare)throw new DependencyException();if(!hookFired){hookFired=true;if(hook==1||hook==2)Mutate();}}public static void Reset(){trace.Clear();getReceiver=destroyed=loadReceiver=loadArgument=null;failGetter=failDestroy=failLoad=failCompare=hookFired=false;hook=0;Mutation=null;snapshot=null;beforeDestroy=null;}}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["Admin_system2_boardEdior"]=typeof(Admin_system2_boardEdior),["BoardConfig"]=typeof(BoardConfig),["DeviceDataEditor"]=typeof(DeviceDataEditor),["EnemyDataEditor"]=typeof(EnemyDataEditor),["Device_boardEditor"]=typeof(Device_boardEditor),["Enemy_boardEditor"]=typeof(Enemy_boardEditor),["PreDevice"]=typeof(PreDevice),["Enemy"]=typeof(Enemy),["UnityEngine.Component"]=typeof(Component),["UnityEngine.GameObject"]=typeof(GameObject),["UnityEngine.Object"]=typeof(Object),["System.Object"]=typeof(object),["System.Boolean"]=typeof(bool),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>t is GenericInstanceType g&&g.ElementType.FullName=="System.Collections.Generic.List`1"?typeof(List<>).MakeGenericType(T(g.GenericArguments[0])):map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped type "+t.FullName);
 static Action<object?,object?> Emit(MethodDefinition m,string mutation){var signature=new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();var dm=new DynamicMethod(m.Name+mutation,typeof(void),signature,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);int remove=0;bool changed=false;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var a=i.Operand;
   if(a is MethodReference mr){if(mr.Name=="Remove"){int ix=remove++;if(mutation=="skip_remove"+ix){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;continue;}}if(mutation=="skip_destroy"&&mr.Name=="Destroy"){il.Emit(RO.Pop);changed=true;continue;}if(mutation=="skip_getter"&&mr.Name=="get_gameObject"){il.Emit(RO.Pop);il.Emit(RO.Ldnull);changed=true;continue;}if(mutation=="skip_load"&&mr.Name=="LoadData"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}var owner=T(mr.DeclaringType);var args=mr.Parameters.Select(p=>p.ParameterType is GenericParameter g?owner.GetGenericArguments()[g.Position]:T(p.ParameterType)).ToArray();var mi=owner.GetMethod(mr.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static,null,args,null)??throw new Exception("Missing public method "+mr);il.Emit(op,mi);continue;}
   if(a is CI target){il.Emit(op,labels[target]);continue;}if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is ParameterDefinition pd){il.Emit(op,(short)(pd.Index+1));continue;}if(a is FieldReference f){il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation not applied");var d=dm.CreateDelegate(Expression.GetActionType(signature));return m.MetadataToken.ToInt32()switch{0x0600001B=>(a,b)=>((Action<Admin_system2_boardEdior,Device_boardEditor>)d)((Admin_system2_boardEdior)a!,(Device_boardEditor)b!),0x0600001E=>(a,b)=>((Action<Admin_system2_boardEdior,Enemy_boardEditor>)d)((Admin_system2_boardEdior)a!,(Enemy_boardEditor)b!),0x0600002B=>(a,b)=>((Action<DeviceDataEditor>)d)((DeviceDataEditor)a!),0x06000040=>(a,b)=>((Action<EnemyDataEditor>)d)((EnemyDataEditor)a!),_=>throw new Exception("Scope")};
 }
 static int[] Removed(int[]a,int item){int ix=Array.IndexOf(a,item);return ix<0?a:a.Where((v,j)=>j!=ix).ToArray();}
 static bool Equal(int[][]a,int[][]b)=>a.Length==b.Length&&a.Zip(b).All(p=>p.First.SequenceEqual(p.Second));
 static bool Invalidated(System.Collections.IEnumerator e){try{e.MoveNext();return false;}catch(InvalidOperationException){return true;}}
 sealed class Graph {public bool enemy;public Admin_system2_boardEdior admin=new(){boardConfig=new()};public object ui;public Component component,other;public Object model,otherModel;public GameObject?game;public List<Device_boardEditor?>dd=new(),altdd=new();public List<Enemy_boardEditor?>ee=new(),altee=new();public List<PreDevice?>pp=new();public List<Enemy?>en=new();public Graph(bool isEnemy,bool modelPresent,bool gamePresent,int[]a,int[]b,int[]c){enemy=isEnemy;game=gamePresent?new():null;model=enemy?new Enemy():new PreDevice();otherModel=enemy?new Enemy():new PreDevice();component=enemy?new Enemy_boardEditor{preEnemy=modelPresent?(Enemy)model:null,go=game}:new Device_boardEditor{preDevice=modelPresent?(PreDevice)model:null,go=game};other=enemy?new Enemy_boardEditor():new Device_boardEditor();ui=enemy?new EnemyDataEditor{boardEdior=admin,enemyOnCheck=(Enemy_boardEditor)component}:new DeviceDataEditor{boardEdior=admin,deviceOnCheck=(Device_boardEditor)component};foreach(int v in a){if(enemy)en.Add(v==0?null:(Enemy)(v==1?model:otherModel));else pp.Add(v==0?null:(PreDevice)(v==1?model:otherModel));}foreach(int v in b){if(enemy)ee.Add(v==0?null:(Enemy_boardEditor)(v==4?component:other));else dd.Add(v==0?null:(Device_boardEditor)(v==4?component:other));}foreach(int v in c){if(enemy)altee.Add(v==0?null:(Enemy_boardEditor)(v==4?component:other));else altdd.Add(v==0?null:(Device_boardEditor)(v==4?component:other));}admin.boardConfig!.preDevices=pp;admin.boardConfig.preEnemies=en;admin.device_BoardEditors=dd;admin.enemy_BoardEditors=ee;}
  int Id(object?x)=>x==null?0:ReferenceEquals(x,model)?1:ReferenceEquals(x,otherModel)?2:ReferenceEquals(x,component)?4:ReferenceEquals(x,other)?5:-1;
  public int[][] Snapshot()=>new[]{enemy?en.Select(v=>Id(v)).ToArray():pp.Select(v=>Id(v)).ToArray(),enemy?ee.Select(v=>Id(v)).ToArray():dd.Select(v=>Id(v)).ToArray(),enemy?altee.Select(v=>Id(v)).ToArray():altdd.Select(v=>Id(v)).ToArray()};
  public void Mutate(int hook){if(hook==1){if(enemy)admin.enemy_BoardEditors=altee;else admin.device_BoardEditors=altdd;}else{if(enemy){var u=(EnemyDataEditor)ui;u.boardEdior=new();u.enemyOnCheck=(Enemy_boardEditor)other;}else{var u=(DeviceDataEditor)ui;u.boardEdior=new();u.deviceOnCheck=(Device_boardEditor)other;}}}
  public bool Cleared=>enemy?((EnemyDataEditor)ui).enemyOnCheck==null:((DeviceDataEditor)ui).deviceOnCheck==null;
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(Action<object?,object?>fn,int token,List<int[]>rows,bool stop=false){var failures=new List<string>();int count=0,ix=0;bool isEnemy=token is 0x0600001E or 0x06000040,isUI=token is 0x0600002B or 0x06000040;void Check(bool pass,string msg){count++;if(!pass)failures.Add(msg);}var rng=new Random(token);
  foreach(var r in rows){int hook=r[0];var a=Enumerable.Range(0,8).Select(_=>rng.Next(3)).ToArray();var b=Enumerable.Range(0,8).Select(_=>new[]{0,4,5}[rng.Next(3)]).ToArray();var c=Enumerable.Range(0,8).Select(_=>new[]{0,4,5}[rng.Next(3)]).ToArray();if(hook!=0)a[0]=1;var g=new Graph(isEnemy,r[1]!=0,r[2]!=0,a,b,c);int[][]expected={Removed(a,r[7]),b,c};expected[r[8]-1]=Removed(expected[r[8]-1],r[9]);var e1=(isEnemy?g.en.GetEnumerator():(System.Collections.IEnumerator)g.pp.GetEnumerator());var e2=(isEnemy?g.ee.GetEnumerator():(System.Collections.IEnumerator)g.dd.GetEnumerator());var e3=(isEnemy?g.altee.GetEnumerator():(System.Collections.IEnumerator)g.altdd.GetEnumerator());State.Reset();State.hook=hook;State.Mutation=()=>g.Mutate(hook);State.snapshot=g.Snapshot;bool match=false;try{fn(isUI?g.ui:g.admin,g.component);match=r[5]==2&&r[6]==1&&r[7]==(r[1]!=0?1:0)&&r[9]==4&&r[10]==1&&r[11]==1&&r[12]==(isUI?1:0)&&r[13]==1&&State.trace.SequenceEqual(isUI?new[]{"G","D","L"}:new[]{"G","D"})&&ReferenceEquals(State.getReceiver,g.component)&&ReferenceEquals(State.destroyed,g.game)&&(!isUI||ReferenceEquals(State.loadReceiver,g.ui)&&State.loadArgument==null&&g.Cleared)&&Equal(g.Snapshot(),expected)&&State.beforeDestroy!=null&&Equal(State.beforeDestroy,expected)&&Invalidated(e1)==(expected[0].Length<a.Length)&&Invalidated(e2)==(expected[1].Length<b.Length)&&Invalidated(e3)==(expected[2].Length<c.Length);}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"row:"+ix++);if(stop&&failures.Count>0)return new(count,failures);}
  void Throws(Type type,Graph g,object?receiver,string label,string[]trace,int[][]expected){State.Reset();State.snapshot=g.Snapshot;if(label=="getter")State.failGetter=true;if(label=="destroy")State.failDestroy=true;if(label=="load")State.failLoad=true;if(label=="comparer")State.failCompare=true;bool got=false;try{fn(receiver,g.component);}catch(Exception e)when(e.GetType()==type){got=true;}Check(got&&State.trace.SequenceEqual(trace)&&Equal(g.Snapshot(),expected),label);}
  Graph Fresh()=>new(isEnemy,true,true,new[]{1,1,2},new[]{4,4,5},new[]{4,5});
  var g0=Fresh();Throws(typeof(NullReferenceException),g0,null,"null-this",Array.Empty<string>(),g0.Snapshot());
  var g1=Fresh();g1.admin.boardConfig=null;Throws(typeof(NullReferenceException),g1,isUI?g1.ui:g1.admin,"null-config",Array.Empty<string>(),g1.Snapshot());
  var g2=Fresh();if(isEnemy)g2.admin.boardConfig!.preEnemies=null;else g2.admin.boardConfig!.preDevices=null;Throws(typeof(NullReferenceException),g2,isUI?g2.ui:g2.admin,"null-first-list",Array.Empty<string>(),g2.Snapshot());
  var g3=Fresh();if(isEnemy)g3.admin.enemy_BoardEditors=null;else g3.admin.device_BoardEditors=null;var expected3=g3.Snapshot();expected3[0]=Removed(expected3[0],1);Throws(typeof(NullReferenceException),g3,isUI?g3.ui:g3.admin,"null-second-list",Array.Empty<string>(),expected3);
  foreach(string stage in isUI?new[]{"getter","destroy","load","comparer"}:new[]{"getter","destroy","comparer"}){var g=Fresh();var exp=g.Snapshot();if(stage!="comparer"){exp[0]=Removed(exp[0],1);exp[1]=Removed(exp[1],4);}var trace=stage=="getter"?new[]{"G"}:stage=="destroy"?new[]{"G","D"}:stage=="load"?new[]{"G","D","L"}:Array.Empty<string>();Throws(typeof(DependencyException),g,isUI?g.ui:g.admin,stage,trace,exp);}
  var g4=Fresh();State.Reset();bool npe=false;try{if(isUI){if(isEnemy)((EnemyDataEditor)g4.ui).enemyOnCheck=null;else((DeviceDataEditor)g4.ui).deviceOnCheck=null;fn(g4.ui,null);}else fn(g4.admin,null);}catch(NullReferenceException){npe=true;}Check(npe&&State.trace.Count==0&&Equal(g4.Snapshot(),new[]{new[]{1,1,2},new[]{4,4,5},new[]{4,5}}),"null-item");
  if(isUI){var g=Fresh();if(isEnemy)((EnemyDataEditor)g.ui).boardEdior=null;else((DeviceDataEditor)g.ui).boardEdior=null;Throws(typeof(NullReferenceException),g,g.ui,"null-admin",Array.Empty<string>(),g.Snapshot());}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var asm=AssemblyDefinition.ReadAssembly(args[0]);var input=File.ReadLines(args[1]).Select(l=>l.Split(' ')).GroupBy(r=>Convert.ToInt32(r[0],16)).ToDictionary(g=>g.Key,g=>g.Select(r=>r.Skip(1).Select(int.Parse).ToArray()).ToList());if(!input.Keys.Order().SequenceEqual(new[]{0x0600001B,0x0600001E,0x0600002B,0x06000040}))throw new Exception("Scope");int cases=0,errors=0;bool controlsPass=true;var failures=new List<string>();var controls=new List<object>();foreach(var row in input){var m=(MethodDefinition)asm.MainModule.LookupToken(row.Key);var result=Cases(Emit(m,"none"),row.Key,row.Value);cases+=result.Cases;failures.AddRange(result.Failures.Select(f=>m.Name+":"+f));foreach(string mut in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","skip_remove0","skip_remove1","skip_destroy","skip_getter"}.Concat(row.Key is 0x0600002B or 0x06000040?new[]{"skip_load"}:Array.Empty<string>())){bool detected=false;string?error=null;try{detected=Cases(Emit(m,mut),row.Key,row.Value,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}controlsPass&=detected&&error==null;controls.Add(new{token=$"0x{row.Key:X8}",mutation=mut,detected,tool_error=error});}}bool pass=failures.Count==0&&errors==0&&controlsPass;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=4,positive_cases=cases,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Unchanged native delete callers with Remove/get_gameObject/Destroy/LoadData doubles. Candidate CLR public List.Remove with reference-equality fixture objects, duplicate/null entries, captured UI receivers, comparer callbacks, partial mutation and exception ordering. Engine/equality doubles and explicit layouts; not whole-game/Unity/iOS equivalence",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
