using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}
public class Game{}
public class Transform{}
public class Manager{public Game?image_SunBank,moneyBank_Coin,moneyBank_Diamond;}
public static class State{public static Manager manager=new();public static Game first=new(),second=new();public static Transform ta=new(),tb=new();public static int mode,hook,token;public static Vector3 va,vb;public static ulong trace;public static bool argsOK;
 public static void Ev(int n)=>trace=(trace<<4)|(uint)n;public static Game?Current()=>token==0x060000E9?manager.image_SunBank:token==0x06000204?manager.moneyBank_Coin:manager.moneyBank_Diamond;public static void Change(Game?g){if(token==0x060000E9)manager.image_SunBank=g;else if(token==0x06000204)manager.moneyBank_Coin=g;else manager.moneyBank_Diamond=g;}
 public static bool Inequality(Game?a,Game?b){Ev(1);argsOK&=ReferenceEquals(a,mode is 2 or 3?null:first)&&b==null;if(mode==5)throw new DependencyException();if(hook==1)Change(null);if(hook==2)Change(second);return mode is not 1 and not 2;}
 public static Transform?GetTransform(Game?r){if(r==null)throw new NullReferenceException();Ev(2);argsOK&=ReferenceEquals(r,hook==2?second:first);if(mode==6)throw new DependencyException();return mode==4?null:ReferenceEquals(r,second)?tb:ta;}
 public static Vector3 Position(Transform?r){if(r==null)throw new NullReferenceException();Ev(3);argsOK&=ReferenceEquals(r,hook==2?tb:ta);if(mode==7)throw new DependencyException();return ReferenceEquals(r,tb)?vb:va;}
}
public static class Fixture{
 static Type T(TypeReference r)=>r.FullName switch{"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Transform"=>typeof(Transform),"System.Boolean"=>typeof(bool),"System.NullReferenceException"=>typeof(NullReferenceException),"System.IntPtr"=>typeof(IntPtr),"Banks" or "ProjectManager"=>typeof(Manager),_=>throw new Exception("Unmapped "+r)};
 static Func<Manager,Vector3>Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.FullName+mutation,typeof(Vector3),new[]{typeof(Manager)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var cached=il.DeclareLocal(typeof(Game));int fields=0;bool changed=mutation=="none";
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_zero"){il.Emit(RO.Call,typeof(Vector3).GetProperty("zero")!.GetMethod!);il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];if(i.Operand is FieldReference f){if(fields++==1&&mutation=="cached_field"){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cached);changed=true;}else{il.Emit(op,typeof(Manager).GetField(f.Name)!);if(fields==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cached);}}continue;}if(i.Operand is MethodReference r){if(r.Name=="get_zero"){il.Emit(op,typeof(Vector3).GetProperty(mutation=="one_fallback"?"one":"zero")!.GetMethod!);if(mutation=="one_fallback")changed=true;continue;}string name=r.Name switch{"op_Inequality"=>nameof(State.Inequality),"get_transform"=>nameof(State.GetTransform),"get_position"=>nameof(State.Position),_=>throw new Exception("Unmapped "+r)};
    if(mutation=="skip_equality"&&r.Name=="op_Inequality"){il.Emit(RO.Pop);il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_1);changed=true;continue;}il.Emit(RO.Call,typeof(State).GetMethod(name)!);if(mutation=="negate_equality"&&r.Name=="op_Inequality"){il.Emit(RO.Ldc_I4_0);il.Emit(RO.Ceq);changed=true;}if(mutation=="swap_position"&&r.Name=="get_position"){il.Emit(RO.Pop);il.Emit(RO.Ldsfld,typeof(State).GetField(nameof(State.vb))!);changed=true;}continue;}
   if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="flip_branch"){op=RO.Brtrue_S;changed=true;}il.Emit(op,labels[j]);continue;}if(i.Operand==null){il.Emit(op);continue;}throw new Exception("Unsupported "+i);}
  if(!changed)throw new Exception("Mutation not applied "+mutation);return(Func<Manager,Vector3>)dm.CreateDelegate(typeof(Func<Manager,Vector3>));
 }
 static float F(ulong b)=>BitConverter.Int32BitsToSingle(unchecked((int)b));static uint B(float f)=>unchecked((uint)BitConverter.SingleToInt32Bits(f));
 static (int,int,List<string>)Cases(Dictionary<int,Func<Manager,Vector3>>functions,List<ulong[]>rows,bool stop=false){int count=0,fail=0;var failures=new List<string>();foreach(var r in rows){int token=(int)r[0];State.token=token;State.mode=(int)r[1];State.hook=(int)r[2];State.va=new(F(r[3]),F(r[4]),F(r[5]));State.vb=new(F(r[6]),F(r[7]),F(r[8]));State.manager=new(){image_SunBank=State.first,moneyBank_Coin=State.first,moneyBank_Diamond=State.second};State.Change(State.mode is 2 or 3?null:State.first);State.trace=0;State.argsOK=true;int err=0;Vector3 v=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));try{v=functions[token](State.manager);}catch(NullReferenceException){State.Ev(4);err=1;}catch(DependencyException){State.Ev(5);err=2;}bool ok=State.trace==r[9]&&err==(int)r[10]&&B(v.x)==r[11]&&B(v.y)==r[12]&&B(v.z)==r[13]&&State.argsOK&&r[14]==1&&r[15]==1;count++;if(!ok){fail++;if(failures.Count<10)failures.Add(token.ToString("X8")+":"+count+" trace="+State.trace+" expected="+r[9]+" error="+err);if(stop)return(count,fail,failures);}}return(count,fail,failures);}
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x060000E9,0x06000204,0x06000205};var methods=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var functions=methods.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none"));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=12288||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(functions,rows);var controls=new List<object>();int errors=0;bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_zero","cached_field","one_fallback","skip_equality","negate_equality","swap_position","flip_branch"}){bool detected=false;string?error=null;try{var f=methods.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation));detected=Cases(f,rows,true).Item2>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.Item2==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=3,positive_cases=positive.Item1,positive_failures=positive.Item2,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.Item3,controls,scope="Actual bank caller CIL with pinned real CoreModule Vector3/zero getter, recording Unity inequality/transform/position/exception doubles and public fixture fields. Original PC equality branch, field reread and bitwise Vector3 copies, initialized metadata/default zero fields. No original Unity equality/engine/class-init/throw/iOS or whole-game proof."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
