using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
static class RepairNative28 {
 record Site(int Token,int[] Nulls,int Throw);
 static readonly Site[] Sites={new(0x060001F1,new[]{95},88),new(0x060005BD,new[]{94},77),new(0x0600080E,new[]{121,30},114),new(0x0600025D,new[]{21},121),new(0x06000146,new[]{142},122),new(0x0600022C,new[]{149,110},99),new(0x06000189,new[]{140},123),new(0x060005D8,new[]{140},123),new(0x0600043B,new[]{166},161),new(0x060008B9,new[]{4,86},170),new(0x06000361,new[]{40,95,126},182),new(0x0600019C,new[]{51},239)};
 static void R(bool b,string msg){if(!b)throw new InvalidOperationException(msg);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static int Main(string[] a){try{Run(a);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[] a){
  R(a.Length==3,"input new-output new-report required");var input=Path.GetFullPath(a[0]);var output=Path.GetFullPath(a[1]);var report=Path.GetFullPath(a[2]);R(input!=output&&report!=input&&report!=output&&report!=output+".tmp"&&!File.Exists(output)&&!File.Exists(report)&&!File.Exists(output+".tmp"),"Outputs must be new and distinct");var before=File.ReadAllBytes(input);R(H(before)=="ae6ac972e0615666091b7359774f0c0ec70d01d8e5d05d0942324b7d13b34920","Native27 input hash mismatch");var after=(byte[])before.Clone();
  using var asm=AssemblyDefinition.ReadAssembly(input);using var fs=File.OpenRead(input);using var pe=new PEReader(fs);var allowed=new HashSet<int>();var rows=new List<object>();
  foreach(var s in Sites){
   var m=(MethodDefinition)asm.MainModule.LookupToken(s.Token);R(m.HasBody&&m.Body.ExceptionHandlers.Count==0,"EH unsupported");R(!m.Body.Instructions.Any(i=>i.OpCode==OpCodes.Ldstr&&i.Operand is string v&&(v.Contains("Indirect call:")||v.Contains("Method not found @")||v.Contains("Unknown call target operand:")||v.Contains("Unmanaged"))),"Unresolved placeholder in approved method");
   var sec=pe.PEHeaders.SectionHeaders.Single(x=>m.RVA>=x.VirtualAddress&&m.RVA<x.VirtualAddress+x.SizeOfRawData);int h=sec.PointerToRawData+m.RVA-sec.VirtualAddress;int size=(before[h]&3)==2?1:(BitConverter.ToUInt16(before,h)>>12)*4;R(size is 1 or 12,"Header mismatch");int start=h+size;var forbidden=new HashSet<int>();
   foreach(int n in s.Nulls){var z=m.Body.Instructions.Single(i=>i.Offset==n);R(z.OpCode==OpCodes.Ldc_I4&&Equals(z.Operand,0)&&z.Next.OpCode==OpCodes.Ceq&&z.GetSize()==5,"Pinned reference zero mismatch");R(before[start+n]==0x20&&BitConverter.ToInt32(before,start+n+1)==0,"Raw zero mismatch");after[start+n]=0x14;allowed.Add(start+n);for(int j=1;j<=4;j++)forbidden.Add(n+j);}
   var ret=m.Body.Instructions.Single(i=>i.Offset==s.Throw);var load=ret.Previous;var store=load.Previous;var ctor=store.Previous;R(ret.OpCode==OpCodes.Ret&&load.OpCode==OpCodes.Ldloc&&store.OpCode==OpCodes.Stloc&&load.Operand==store.Operand&&((VariableDefinition)load.Operand).VariableType.FullName=="System.NullReferenceException"&&ctor.OpCode==OpCodes.Newobj&&((MethodReference)ctor.Operand).FullName=="System.Void System.NullReferenceException::.ctor()","Pinned NRE sequence mismatch");foreach(var x in new[]{load.Offset,store.Offset,ret.Offset})forbidden.Add(x);R(before[start+s.Throw]==0x2A,"Raw return mismatch");after[start+s.Throw]=0x7A;allowed.Add(start+s.Throw);
   foreach(var i in m.Body.Instructions){if(i.Operand is Instruction j)R(!forbidden.Contains(j.Offset),"Alternate entry");if(i.Operand is Instruction[] js)R(js.All(j=>!forbidden.Contains(j.Offset)),"Alternate switch entry");}
   if(s.Token==0x0600080E){var old=m.Body.Instructions.Single(i=>i.Offset==74);R(old.OpCode==OpCodes.Ldloca&&((VariableDefinition)old.Operand).Index==9&&old.GetSize()==4&&m.Body.Variables[3].VariableType.FullName=="System.Single"&&m.Body.Variables[9].VariableType.FullName=="System.Single","Pinned comparer use-def mismatch");R(m.Body.Instructions.Single(i=>i.Offset==20).OpCode==OpCodes.Stloc&&((VariableDefinition)m.Body.Instructions.Single(i=>i.Offset==20).Operand).Index==3,"First get_Item not stored in V3");R(!m.Body.Instructions.Any(i=>i.OpCode==OpCodes.Stloc&&i.Operand==m.Body.Variables[9]),"V9 unexpectedly initialized");R(before[start+74]==0xFE&&before[start+75]==0x0D&&BitConverter.ToUInt16(before,start+76)==9,"Raw comparer mismatch");after[start+76]=3;allowed.Add(start+76);}
   rows.Add(new{token=$"0x{s.Token:X8}",method=m.FullName,code_start=start,code_size=m.Body.CodeSize,null_sites=s.Nulls,throw_site=s.Throw,comparer_receiver=s.Token==0x0600080E?"V9 -> V3 at IL_004A":null});
  }
  var diffs=Enumerable.Range(0,before.Length).Where(i=>before[i]!=after[i]).ToArray();R(diffs.Length==allowed.Count&&diffs.All(allowed.Contains)&&diffs.Length==30,"Exact byte scope mismatch");File.WriteAllBytes(output+".tmp",after);
  using(var reopen=AssemblyDefinition.ReadAssembly(output+".tmp")){foreach(var s in Sites){var m=(MethodDefinition)reopen.MainModule.LookupToken(s.Token);var p=(MethodDefinition)asm.MainModule.LookupToken(s.Token);R(m.RVA==p.RVA&&m.Body.CodeSize==p.Body.CodeSize&&m.Body.MaxStackSize==p.Body.MaxStackSize,"Layout drift");foreach(int n in s.Nulls){R(m.Body.Instructions.Single(i=>i.Offset==n).OpCode==OpCodes.Ldnull,"Null reopen mismatch");for(int j=1;j<=4;j++)R(m.Body.Instructions.Single(i=>i.Offset==n+j).OpCode==OpCodes.Nop,"Padding reopen mismatch");}R(m.Body.Instructions.Single(i=>i.Offset==s.Throw).OpCode==OpCodes.Throw,"Throw reopen mismatch");if(s.Token==0x0600080E)R(((VariableDefinition)m.Body.Instructions.Single(i=>i.Offset==74).Operand).Index==3,"Comparer reopen mismatch");}}
  File.Move(output+".tmp",output);var r=new{input_sha256=H(before),candidate_sha256=H(after),changed_bytes=diffs.Length,positions=diffs,methods=rows,metadata_headers_locals_unchanged=true,scope="Twelve native-reviewed bodies; explicit null and NRE sites plus one captured-float receiver operand; no global rewrite"};File.WriteAllText(report,JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(r));
 }
}
