using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Security.Cryptography;using System.Text.Json;using UnityEngine;
public class DependencyException:Exception{}public class BoundsException:Exception{}
public class Obj{}public class Game:Obj{}public class Image:Obj{}public class Transform:Obj{}public class Clip:Obj{}public class ClipList:Obj{}public class Audio:Obj{}public class Buff:Obj{}public class BuffManager:Obj{}public class Damage:Obj{}
public class Enemy:Obj{public string?inputFieldName;}public class Board:Obj{public float endTime,gameSpeed;public bool isWon;public Game?buttomButtons;public Vector3 cameraPosition;}
public class Data:Obj{public string?name;public int camp,num;}public class Plant:Obj{public bool isDied;public int ID;public float healthPoint,maxHealthPoint,pT_chomperviking_barrelsPoint,fY,fZ,fH;}
public class Prop:Obj{public Game?prop,propImagex;public Vector3 originalPosition;public float alTime;public int propState;}public class Zombie:Obj{public bool poleZombie_pole,poleZombie_jump;public int passablePoint,ID;public BuffManager?buffManager;}
public class Page:Obj{public Image?roll,skillAuto;}public static class Resource{public static ClipList?boardClips;}
public static class State{
public static Obj self=new();public static Obj arg=new();public static Game game=new(),gameB=new();public static Image image=new(),imageB=new();public static Transform transform=new(),transformB=new();public static Clip clip=new(),clipB=new();public static ClipList list=new(),listB=new();public static BuffManager manager=new(),managerB=new();public static Buff buff=new();public static Damage damage=new();public static Audio audio=new();public static string text="alpha",textB="beta";
public static int token,mode,hook,active,rotates,bankCalls,updateCalls,removeCalls,truthCalls;public static ulong trace;public static bool argsOK;public static Vector3 value,alternate,spare,output,axis;public static uint deltaValue,volumeValue,capturedVolume,capturedHeal,timeScale;public static uint[]angles=new uint[2];public static string?inputText;public static Clip?playedClip;public static Action<Plant,float,Plant>ActualHealed=null!;
public static int Id(object?o){object?[]all={null,self,arg,game,gameB,image,imageB,transform,transformB,clip,clipB,list,listB,manager,managerB,buff,damage,audio,text,textB,string.Empty};for(int i=0;i<all.Length;i++)if(ReferenceEquals(o,all[i]))return i;throw new Exception("Unknown identity");}
public static void Ev(int e,object?r=null)=>trace=unchecked(trace*131+(uint)(e*32+Id(r)));public static void Check(object?r){if(r==null)throw new NullReferenceException();}public static void Fail(){Ev(32);throw new DependencyException();}
public static bool Equal(Obj?r,Obj?other){Ev(1,r);argsOK&=other==null;if(hook==1)inputText=textB;if(mode==21)Fail();return r==null||mode==7;}
public static string?Name(Obj?r){Check(r);Ev(2,r);if(mode==22)Fail();return inputText;}
public static void SetTime(float t){Ev(3);timeScale=Fixture.B(t);argsOK&=timeScale==0x3f800000;if(hook==1){((Board)self).buttomButtons=gameB;((Board)self).cameraPosition=alternate;}if(hook==2)((Board)self).buttomButtons=null;if(mode==23)Fail();}
public static void SetActive(Game?r,bool state){Check(r);Ev(4,r);active=state?1:0;argsOK&=!state;if(hook==3){Resource.boardClips=listB;((Board)self).cameraPosition=alternate;}if(hook==4)Resource.boardClips=null;if(mode==24)Fail();}
public static Clip?Item(ClipList?r,int index){Check(r);Ev(5,r);argsOK&=index==10;if(hook==5)((Board)self).cameraPosition=alternate;if(mode==14){Ev(31);throw new BoundsException();}return mode==18?null:ReferenceEquals(r,listB)?clipB:clip;}
public static float Volume(){Ev(6);if(hook==6)((Board)self).cameraPosition=spare;if(mode==25)Fail();return Fixture.F(volumeValue);}
public static Audio CreateAudio(Clip?c,Vector3 p,float v){Ev(7,c);playedClip=c;output=p;capturedVolume=Fixture.B(v);if(mode==26)Fail();return audio;}
public static Transform?ComponentTransform(Obj?r){Check(r);Ev(8,r);if(token==0x06000378||token==0x0600035D){if(hook==1){var p=(Plant)self;p.fY=alternate.x;p.fZ=alternate.y;p.fH=alternate.z;}}if(token==0x06000669){if(hook==1)((Page)self).skillAuto=imageB;if(hook==2)((Page)self).skillAuto=null;}if(mode==4)return null;return ReferenceEquals(r,imageB)?transformB:transform;}
public static Vector3 Position(Transform?r){Check(r);Ev(9,r);var v=value;if(hook==3){var p=(Plant)self;p.fY=alternate.x;p.fZ=alternate.y;p.fH=alternate.z;}if(mode==5)Fail();return v;}
public static Damage DamageText(float healed,int type,Vector3 p){Ev(10);output=p;capturedHeal=Fixture.B(healed);argsOK&=type==1;if(hook==4){((Plant)self).healthPoint=alternate.x;((Plant)self).maxHealthPoint=alternate.y;}if(mode==6)Fail();return damage;}
public static void Healed(Plant?r,float amount,Plant from){Check(r);ActualHealed(r!,amount,from);}
public static void UpdateBarrels(Plant?r){Check(r);Ev(11,r);updateCalls++;if(hook==5)r!.healthPoint=spare.x;if(hook==6)r!.pT_chomperviking_barrelsPoint=spare.y;if(mode==8)Fail();}
public static Transform?GameTransform(Game?r){Check(r);Ev(12,r);if(hook==1)((Prop)self).originalPosition=alternate;if(hook==2)((Prop)self).propImagex=gameB;if(mode==4)return null;return transform;}
public static void SetLocalPosition(Transform?r,Vector3 p){Check(r);Ev(13,r);output=p;if(hook==3)((Prop)self).propImagex=gameB;if(hook==4)((Prop)self).propImagex=null;if(mode==6)Fail();}
public static bool Inequality(Obj?r,Obj?other){Ev(14,r);truthCalls++;argsOK&=other==null;if(hook==5)((Prop)self).propImagex=gameB;if(hook==6)((Prop)self).propImagex=null;if(mode==21)Fail();return r!=null&&mode!=7;}
public static void Destroy(Obj?r){Ev(15,r);if(mode==16)Fail();}
public static void BankState(Prop?r){Check(r);Ev(16,r);bankCalls++;if(mode==17)Fail();}
public static Buff?FindBuff(BuffManager?r,string s){Check(r);Ev(17,r);argsOK&=s=="PoleCommander.speed";if(hook==1)((Zombie)self).buffManager=managerB;if(hook==2)((Zombie)self).buffManager=null;if(mode==11)Fail();return mode==10?null:buff;}
public static void RemoveBuff(BuffManager?r,Buff b){Check(r);Ev(18,r);removeCalls++;argsOK&=ReferenceEquals(b,buff);if(mode==12)Fail();}
public static bool Path(Zombie?r){Check(r);Ev(19,r);if(hook==3)r!.poleZombie_jump=true;if(mode==13)Fail();return mode==14;}
public static float Delta(){Ev(20);if(mode==20)Fail();return Fixture.F(deltaValue);}
public static void Rotate(Transform?r,Vector3 v,float angle,int space){Check(r);Ev(21,r);axis=v;argsOK&=Fixture.B(v.x)==0&&Fixture.B(v.y)==0&&Fixture.B(v.z)==0x3f800000&&space==0;angles[rotates++]=Fixture.B(angle);if(hook==3)((Page)self).skillAuto=imageB;if(hook==4)((Page)self).skillAuto=null;if(hook==5)deltaValue=Fixture.B(spare.x);if(mode==19)Fail();}
}
public static class Fixture{
static Type T(TypeReference r)=>r.FullName switch{"System.Void"=>typeof(void),"System.Object"=>typeof(object),"System.String"=>typeof(string),"System.Boolean"=>typeof(bool),"System.Int32" or "Camp" or "PropState" or "UnityEngine.Space"=>typeof(int),"System.Single"=>typeof(float),"System.IntPtr"=>typeof(IntPtr),"UnityEngine.Vector3"=>typeof(Vector3),"UnityEngine.Transform"=>typeof(Transform),"UnityEngine.GameObject"=>typeof(Game),"UnityEngine.UI.Image"=>typeof(Image),"UnityEngine.AudioClip"=>typeof(Clip),"UnityEngine.AudioSource"=>typeof(Audio),"UnityEngine.Object" or "UnityEngine.Component"=>typeof(Obj),"System.Collections.Generic.List`1<UnityEngine.AudioClip>"=>typeof(ClipList),"EnemyDataEditor"=>typeof(Enemy),"Board"=>typeof(Board),"DeviceContent/ContentDeviceData"=>typeof(Data),"Plant"=>typeof(Plant),"Prop"=>typeof(Prop),"Zombie"=>typeof(Zombie),"Buff"=>typeof(Buff),"BuffManager"=>typeof(BuffManager),"DamageText"=>typeof(Damage),"Plant_DetaiPage"=>typeof(Page),"ResourceManager"=>typeof(Resource),_=>throw new Exception("Unmapped type "+r)};
static Delegate Emit(MethodDefinition m,string mutation){int rid=(int)m.MetadataToken.RID;var pars=new[]{T(m.DeclaringType)}.Concat(m.Parameters.Select(p=>T(p.ParameterType))).ToArray();Type ret=T(m.ReturnType);var dm=new DynamicMethod(m.FullName+mutation,ret,pars,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var cachedGame=il.DeclareLocal(typeof(Game));var cachedManager=il.DeclareLocal(typeof(BuffManager));int managerReads=0,imageReads=0;var amount=il.DeclareLocal(typeof(float));var vi=il.DeclareLocal(typeof(Vector3));
if(mutation=="illegal_stack"&&rid==0x45)il.Emit(RO.Pop);
foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];
if(i.Operand is FieldReference f){if(mutation=="pole_cache_manager"&&rid==0x4A1&&f.Name=="buffManager"){managerReads++;if(managerReads>1){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cachedManager);continue;}}if(mutation=="prop_cache_image"&&rid==0x409&&f.Name=="propImagex"){imageReads++;if(imageReads>1){il.Emit(RO.Pop);il.Emit(RO.Ldloc,cachedGame);continue;}}if(mutation=="pole_leave_jump"&&rid==0x4A1&&f.Name=="poleZombie_jump"&&op.Value==RO.Stfld.Value){il.Emit(RO.Pop);il.Emit(RO.Pop);continue;}il.Emit(op,T(f.DeclaringType).GetField(f.Name)??throw new Exception("Field missing "+f));if(mutation=="pole_cache_manager"&&rid==0x4A1&&f.Name=="buffManager"&&managerReads==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cachedManager);}if(mutation=="prop_cache_image"&&rid==0x409&&f.Name=="propImagex"&&imageReads==1){il.Emit(RO.Dup);il.Emit(RO.Stloc,cachedGame);}continue;}
if(i.Operand is MethodReference r){if(r.Name==".ctor"&&r.DeclaringType.FullName=="UnityEngine.Vector3"){il.Emit(op,typeof(Vector3).GetConstructor(new[]{typeof(float),typeof(float),typeof(float)})!);continue;}if(r.Name==".ctor"&&r.DeclaringType.FullName=="System.Object"){il.Emit(op,typeof(object).GetConstructor(Type.EmptyTypes)!);continue;}
string name=r.Name switch{"op_Equality"=>nameof(State.Equal),"get_name"=>nameof(State.Name),"set_timeScale"=>nameof(State.SetTime),"SetActive"=>nameof(State.SetActive),"get_Item"=>nameof(State.Item),"AudioVolume"=>nameof(State.Volume),"CreateAudioAtPoint"=>nameof(State.CreateAudio),"get_transform" when r.DeclaringType.FullName=="UnityEngine.GameObject"=>nameof(State.GameTransform),"get_transform"=>nameof(State.ComponentTransform),"get_position"=>nameof(State.Position),"CreatDamageText"=>nameof(State.DamageText),"Healed"=>nameof(State.Healed),"PC_ChompervikingUpdateBarrels"=>nameof(State.UpdateBarrels),"set_localPosition"=>nameof(State.SetLocalPosition),"op_Inequality"=>nameof(State.Inequality),"Destroy"=>nameof(State.Destroy),"PropBankStateSet"=>nameof(State.BankState),"FindBuff"=>nameof(State.FindBuff),"RemoveBuff"=>nameof(State.RemoveBuff),"Path_Finding"=>nameof(State.Path),"get_deltaTime"=>nameof(State.Delta),"Rotate"=>nameof(State.Rotate),_=>throw new Exception("Unmapped call "+r)};
if(mutation=="board_zero_position"&&rid==0x2C3&&r.Name=="CreateAudioAtPoint"){il.Emit(RO.Stloc,amount);il.Emit(RO.Pop);il.Emit(RO.Ldloca,vi);il.Emit(RO.Initobj,typeof(Vector3));il.Emit(RO.Ldloc,vi);il.Emit(RO.Ldloc,amount);}
if(mutation=="die_skip_update"&&rid==0x35D&&r.Name=="PC_ChompervikingUpdateBarrels"){il.Emit(RO.Pop);continue;}il.Emit(RO.Call,typeof(State).GetMethod(name)!);continue;}
if(i.Operand is Mono.Cecil.Cil.Instruction j){if(mutation=="die_unordered"&&rid==0x35D&&op.Value==RO.Bge_Un_S.Value)op=RO.Bge_S;if(mutation=="heal_nan_clamp"&&rid==0x378&&op.Value==RO.Blt_Un_S.Value)op=RO.Blt_S;il.Emit(op,labels[j]);continue;}if(i.Operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(i.Operand is string str){if(mutation=="pole_wrong_name"&&rid==0x4A1&&str=="PoleCommander.speed")str="PoleCommander.wrong";il.Emit(op,str);continue;}if(i.Operand is float fv){if(mutation=="heal_wrong_y"&&rid==0x378&&fv==10)fv=11;if(mutation=="rotate_wrong_angle"&&rid==0x669&&fv==-75)fv=-74;il.Emit(op,fv);continue;}if(i.Operand is sbyte sb){if(mutation=="board_wrong_clip"&&rid==0x2C3&&sb==10)sb=9;il.Emit(op,sb);continue;}if(i.Operand!=null)throw new Exception("Unsupported operand "+i);il.Emit(op);
}return dm.CreateDelegate(System.Linq.Expressions.Expression.GetDelegateType(pars.Concat(new[]{ret}).ToArray()));}
public static float F(ulong v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));public static uint B(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));static int I(ulong v)=>unchecked((int)v);static Vector3 Vec(ulong[]r,int i)=>new(F(r[i]),F(r[i+1]),F(r[i+2]));static void Add(List<ulong>x,Vector3 v){x.Add(B(v.x));x.Add(B(v.y));x.Add(B(v.z));}
static (int count,int fail,List<string>samples)Cases(Dictionary<int,Delegate>functions,List<ulong[]>rows,bool stop=false){State.ActualHealed=(Action<Plant,float,Plant>)functions[0x06000378];int count=0,fail=0;var samples=new List<string>();foreach(var r in rows){int t=(int)r[0];State.token=t;State.mode=(int)r[1];State.hook=(int)r[2];State.arg=new Data{name=State.mode==2?null:State.text,camp=I(r[3]),num=I(r[4])};State.self=t switch{0x06000045=>new Enemy{inputFieldName=State.textB},0x060002C3=>new Board{endTime=F(0x12345678),gameSpeed=F(0x87654321),buttomButtons=State.mode==1?null:State.game,cameraPosition=Vec(r,10)},0x06000301=>new Data{name=State.textB,camp=-7,num=-11},0x0600035D or 0x06000378=>new Plant{isDied=State.mode==1,ID=I(r[3]),healthPoint=F(r[4]),maxHealthPoint=F(r[5]),pT_chomperviking_barrelsPoint=F(r[6]),fY=F(r[7]),fZ=F(r[8]),fH=F(r[9])},0x06000409=>new Prop{prop=State.mode==1?null:State.game,propImagex=State.mode==2?null:State.game,originalPosition=Vec(r,10),alTime=F(0x12345678),propState=3},0x060004A1=>new Zombie{ID=I(r[3]),poleZombie_pole=true,poleZombie_jump=true,passablePoint=-100,buffManager=State.mode==1?null:State.manager},0x06000669=>new Page{roll=State.mode==1?null:State.image,skillAuto=State.mode==2?null:State.image},_=>throw new Exception("Token")};State.value=Vec(r,10);State.alternate=Vec(r,13);State.spare=Vec(r,16);State.deltaValue=(uint)r[20];State.volumeValue=(uint)r[21];State.trace=0;State.rotates=State.bankCalls=State.updateCalls=State.removeCalls=State.truthCalls=0;State.argsOK=true;State.active=-1;State.output=State.axis=new(F(0xdeadbeef),F(0xdeadbeef),F(0xdeadbeef));State.capturedVolume=State.capturedHeal=State.timeScale=State.angles[0]=State.angles[1]=0xdeadbeef;State.inputText=State.text;State.playedClip=null;Resource.boardClips=State.mode==9?null:State.list;int err=0;bool result=false;
try{object?ret;if(t==0x06000045)ret=functions[t].DynamicInvoke(State.self,State.mode==1?null:State.game);else if(t==0x060002C3)ret=functions[t].DynamicInvoke(State.self,F(r[19]));else if(t==0x06000301)ret=functions[t].DynamicInvoke(State.self,State.mode==1?null:State.mode==3?State.self:State.arg);else if(t==0x06000378)ret=functions[t].DynamicInvoke(State.self,F(r[19]),new Plant());else ret=functions[t].DynamicInvoke(State.self);if(t==0x0600035D)result=(bool)ret!;}catch(TargetInvocationException e)when(e.InnerException is NullReferenceException){State.Ev(30);err=1;}catch(TargetInvocationException e)when(e.InnerException is BoundsException){err=2;}catch(TargetInvocationException e)when(e.InnerException is DependencyException){err=3;}catch(TargetInvocationException e)when(e.InnerException is InvalidProgramException){throw e.InnerException;}
var observed=new List<ulong>{State.trace,(uint)err,State.argsOK?1UL:0UL,result?1UL:0UL};Add(observed,State.output);Plant?p=State.self as Plant;observed.AddRange(new ulong[]{p==null?0:B(p.healthPoint),p==null?0:B(p.maxHealthPoint),p==null?0:B(p.pT_chomperviking_barrelsPoint),p==null?0:B(p.fY),p==null?0:B(p.fZ),p==null?0:B(p.fH)});Board?b=State.self as Board;Add(observed,b?.cameraPosition??new Vector3());observed.AddRange(new ulong[]{b==null?0:B(b.endTime),b==null?0:B(b.gameSpeed),b?.isWon==true?1UL:0,State.timeScale,unchecked((uint)State.active)});Prop?pr=State.self as Prop;observed.AddRange(new ulong[]{pr==null?0:B(pr.alTime),unchecked((uint)(pr?.propState??0)),(uint)State.Id(pr?.prop),(uint)State.Id(pr?.propImagex)});Add(observed,pr?.originalPosition??new Vector3());Zombie?z=State.self as Zombie;observed.AddRange(new ulong[]{z?.poleZombie_pole==true?1UL:0,z?.poleZombie_jump==true?1UL:0,unchecked((uint)(z?.passablePoint??0)),(uint)State.Id(z?.buffManager),(uint)State.removeCalls,(uint)State.updateCalls,(uint)State.bankCalls,State.angles[0],State.angles[1]});Add(observed,State.axis);observed.Add((uint)State.rotates);observed.Add((uint)State.Id((State.self as Enemy)?.inputFieldName));Data?d=State.self as Data;observed.AddRange(new ulong[]{(uint)State.Id(d?.name),unchecked((uint)(d?.camp??0)),unchecked((uint)(d?.num??0)),(uint)State.Id(State.playedClip),State.capturedVolume,State.capturedHeal,(uint)State.Id((State.self as Page)?.roll),(uint)State.Id((State.self as Page)?.skillAuto),(uint)State.Id(b?.buttomButtons),(uint)State.Id(Resource.boardClips)});if(observed.Count!=52)throw new Exception("Observation schema "+observed.Count);
var bad=observed.Select((v,i)=>(v,i)).Where(x=>x.v!=r[x.i+22]).ToArray();count++;if(bad.Length>0){fail++;if(samples.Count<10)samples.Add(t.ToString("X8")+" case="+count+" mode="+State.mode+" hook="+State.hook+" diffs="+string.Join(',',bad.Select(x=>(x.i+22)+":"+x.v+"/"+r[x.i+22])));if(stop)return(count,fail,samples);}}
return(count,fail,samples);}
public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);int[]tokens={0x06000045,0x060002C3,0x06000301,0x0600035D,0x06000378,0x06000409,0x060004A1,0x06000669};var ms=tokens.ToDictionary(t=>t,t=>(MethodDefinition)a.MainModule.LookupToken(t));var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).Select(v=>new[]{(ulong)Convert.ToInt32(v[0],16)}.Concat(v.Skip(1).Select(ulong.Parse)).ToArray()).ToList();if(rows.Count!=32768||rows.Any(r=>r.Length!=74)||tokens.Any(t=>rows.Count(r=>r[0]==(ulong)t)!=4096))throw new Exception("Row set");var positive=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,"none")),rows);int errors=0;var controls=new List<object>();bool cp=true;foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","board_zero_position","board_wrong_clip","die_unordered","die_skip_update","heal_wrong_y","heal_nan_clamp","prop_cache_image","pole_leave_jump","pole_wrong_name","pole_cache_manager","rotate_wrong_angle"}){bool detected=false;string?error=null;try{detected=Cases(ms.ToDictionary(x=>x.Key,x=>Emit(x.Value,mutation)),rows,true).fail>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=positive.fail==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=8,positive_cases=positive.count,positive_failures=positive.fail,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,failures=positive.samples,controls,scope="Eight actual candidate CIL callers vs unchanged original native callers; DieTest executes actual candidate Healed transitively. Pinned Core Vector3 ctor CLR executes; CLR System.Object ctor used; other Unity/list/damage/buff/path/exception dependencies recorded with ready metadata. No complete Unity or game/iOS fidelity proof; full conversion/all units deferred to100."};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass,report.failures,report.controls}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
