using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using System.Globalization;
public class DependencyException:Exception{}
public class Supplies{}public class SuppliesInfo{}
public class Save{public int adventureLevel,coins;public int marker=123;}
public class Text{public int id;public string?text;public bool flag;public void SetText(string s,bool v){State.Event(4);State.textId=id;State.boolOK&=v;State.Throw("text");text=s;flag=v;}}
public class Skip{public Save?playerSave;public int level,challenge;public Text?text_Level;public int marker=234;}
public class Info{public Supplies?supplies=new();public SuppliesInfo?suppliesInfo=new();public int id;public void SetInfo(){State.Event(2);State.infoId=id;State.partialOK&=supplies==null&&suppliesInfo==null&&ReferenceEquals(State.w!.playerSave,State.old);State.Throw("info");if(State.mode==2){State.w!.suppliesInfoPage=State.info2;State.w.text_money=State.label2;}}}
public class Warehouse{public Save?playerSave;public Info?suppliesInfoPage;public Text?text_money;public int marker=345;public void ClearSuppliesItemList(){State.Event(1);_ = marker;State.partialOK&=ReferenceEquals(playerSave,State.old);State.Throw("clear");if(State.mode==1)suppliesInfoPage=State.info2;}public void CreatSuppliesItemList(){State.Event(5);_ = marker;State.Throw("create");}}
public static class State{
 public static Skip?s;public static Warehouse?w;public static Save input=new(),old=new();public static Info info1=new(),info2=new();public static Text label1=new(),label2=new();public static int token,mode,alt,trace,formatted,textId,infoId;public static bool partialOK,boolOK,formatOK;public static string fail="";
 public static void Event(int e){trace=trace*10+e;}public static void Throw(string stage){if(fail==stage)throw new DependencyException();}
 public static void Reset(int t,int adv=7,int coins=1234567,int level=12,int challenge=0,int mode0=0,int alt0=-9){token=t;mode=mode0;alt=alt0;trace=formatted=textId=infoId=0;partialOK=boolOK=formatOK=true;fail="";input=new(){adventureLevel=adv,coins=coins};old=new();label1=new(){id=1};label2=new(){id=2};info1=new(){id=1};info2=new(){id=2};s=new(){playerSave=old,level=level,challenge=challenge,text_Level=label1};w=new(){playerSave=old,suppliesInfoPage=info1,text_money=label1};}
 public static string Render(ref int value,string format){Event(3);formatted=value;formatOK&=format==(token==0x060000A4?"当前关卡：0":"N0");partialOK&=ReferenceEquals(token==0x060000A4?s!.playerSave:w!.playerSave,input);Throw("format");if(mode==3){value=alt;if(token==0x060000A4){s!.text_Level=label2;s.playerSave=old;}else{w!.text_money=label2;w.playerSave=old;}}return formatted.ToString(format,CultureInfo.CurrentCulture);}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["SystemSkipLevel"]=typeof(Skip),["WarehouseUIController"]=typeof(Warehouse),["Save"]=typeof(Save),["ChallengeType"]=typeof(int),["Warehouse_SuppliesInfoPage"]=typeof(Info),["Supplies"]=typeof(Supplies),["SuppliesInfo"]=typeof(SuppliesInfo),["TMPro.TextMeshProUGUI"]=typeof(Text),["TMPro.TMP_Text"]=typeof(Text),["System.String"]=typeof(string),["System.Int32"]=typeof(int),["System.Void"]=typeof(void),["System.Boolean"]=typeof(bool),["System.Object"]=typeof(object)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t);
 static FieldInfo F(FieldReference f)=>T(f.DeclaringType).GetField(f.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static)??throw new Exception("Missing field "+f);
 static MethodInfo M(MethodReference m,bool real){if(m.FullName=="System.String System.Int32::ToString(System.String)")return real?typeof(int).GetMethod("ToString",new[]{typeof(string)})!:typeof(State).GetMethod(nameof(State.Render))!;return T(m.DeclaringType).GetMethod(m.Name,m.Parameters.Select(p=>T(p.ParameterType)).ToArray())??throw new Exception("Missing method "+m);}
 static Delegate Emit(MethodDefinition m,string mutation,bool real=false){var owner=T(m.DeclaringType);var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{owner,typeof(Save)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}
  if(mutation=="null_save_throw"){var good=il.DefineLabel();il.Emit(RO.Ldarg_1);il.Emit(RO.Brtrue,good);il.Emit(RO.Newobj,typeof(NullReferenceException).GetConstructor(Type.EmptyTypes)!);il.Emit(RO.Throw);il.MarkLabel(good);changed=true;}
  if(mutation=="early_save_store"){il.Emit(RO.Ldarg_0);il.Emit(RO.Ldarg_1);il.Emit(RO.Stfld,typeof(Warehouse).GetField(nameof(Warehouse.playerSave))!);changed=true;}
  var ins=m.Body.Instructions;
  for(int ix=0;ix<ins.Count;ix++){var i=ins[ix];il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(mutation=="late_text"&&op==RO.Ldarg_0&&ix+5<ins.Count&&ins[ix+1].Operand is FieldReference tf&&tf.Name is "text_Level" or "text_money"){
    if(ins[ix+3].OpCode!=Mono.Cecil.Cil.OpCodes.Ldflda||ins[ix+3].Operand is not FieldReference vf||ins[ix+4].Operand is not string literal||ins[ix+5].Operand is not MethodReference fmt)throw new Exception("Late receiver pattern");var temp=il.DeclareLocal(typeof(string));il.Emit(ops[ins[ix+2].OpCode.Value]);il.Emit(RO.Ldflda,F(vf));il.Emit(RO.Ldstr,literal);il.Emit(RO.Call,M(fmt,real));il.Emit(RO.Stloc,temp);il.Emit(RO.Ldarg_0);il.Emit(RO.Ldfld,F(tf));il.Emit(RO.Ldloc,temp);ix+=5;changed=true;continue;
   }
   if(operand is FieldReference field){var fi=F(field);if(op==RO.Ldflda){if(mutation=="wrong_field"){fi=field.DeclaringType.Name=="Save"?typeof(Save).GetField(nameof(Save.adventureLevel))!:typeof(Skip).GetField(nameof(Skip.challenge))!;changed=true;}if(mutation=="copy_ref"){var copy=il.DeclareLocal(typeof(int));il.Emit(RO.Ldfld,fi);il.Emit(RO.Stloc,copy);il.Emit(RO.Ldloca,copy);changed=true;continue;}}
    if(op==RO.Stfld&&field.Name=="playerSave"&&mutation is "skip_store" or "early_save_store"||op==RO.Stfld&&field.Name=="suppliesInfo"&&mutation=="skip_info_clear"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}il.Emit(op,fi);continue;
   }
   if(operand is MethodReference method){if(mutation=="skip_clear"&&method.Name=="ClearSuppliesItemList"||mutation=="skip_create"&&method.Name=="CreatSuppliesItemList"){il.Emit(RO.Pop);changed=true;continue;}if(mutation=="wrong_bool"&&method.Name=="SetText"){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_0);changed=true;}il.Emit(op,M(method,real));continue;}
   if(operand is Mono.Cecil.Cil.Instruction target){if(mutation=="wrong_challenge"&&op==RO.Brtrue_S){op=RO.Brfalse_S;changed=true;}il.Emit(op,labels[target]);continue;}
   if(operand is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(operand is Mono.Cecil.ParameterDefinition parameter){il.Emit(op,(short)(parameter.Index+1));continue;}if(operand is string str){il.Emit(op,str);continue;}if(operand is int iv){il.Emit(op,iv);continue;}if(operand==null){il.Emit(op);continue;}throw new Exception("Unsupported "+operand);
  }
  if(!changed)throw new Exception("Mutation not applied "+mutation);return dm.CreateDelegate(typeof(Action<,>).MakeGenericType(owner,typeof(Save)));
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(MethodDefinition m,Delegate fn,List<uint[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();int token=m.MetadataToken.ToInt32();void Check(bool ok,string label){count++;if(!ok)failures.Add(label);}void Call(object?o,Save?save){if(token==0x060000A4)((Action<Skip?,Save?>)fn)((Skip?)o,save);else((Action<Warehouse?,Save?>)fn)((Warehouse?)o,save);}
  foreach(var row in rows){State.Reset(token,(int)row[0],(int)row[1],(int)row[2],(int)row[3],(int)row[4],(int)row[5]);bool ok=false;try{Call(token==0x060000A4?State.s:State.w,State.input);var currentLabel=token==0x060000A4?State.s!.text_Level:State.w!.text_money;var currentSave=token==0x060000A4?State.s!.playerSave:State.w!.playerSave;int final=token==0x060000A4?State.s!.level:State.input.coins;ok=State.formatted==(int)row[6]&&final==(int)row[7]&&State.textId==row[8]&&currentLabel!.id==row[9]&&(ReferenceEquals(currentSave,State.input)?1u:0u)==row[10]&&State.trace==row[11]&&State.formatOK&&row[12]==1&&row[13]==1&&State.boolOK&&row[14]==1&&State.infoId==row[15]&&(State.info1.supplies==null&&State.info1.suppliesInfo==null?1u:0u)==row[16]&&(State.info2.supplies==null&&State.info2.suppliesInfo==null?1u:0u)==row[17]&&row[18]==1&&row[19]==(token==0x060000A4?1u:3u)&&State.partialOK&&row[20]==1&&State.input.marker==123&&State.s!.marker==234&&State.w!.marker==345&&(State.textId==1?State.label1:State.label2).text==((int)row[6]).ToString(token==0x060000A4?"当前关卡：0":"N0",CultureInfo.CurrentCulture);}catch(Exception e)when(e is not InvalidProgramException){ok=false;}Check(ok,"native-row:"+index++);if(stop&&failures.Count>0)return new(count,failures);}
  if(token==0x060000A4){for(int k=0;k<4;k++){State.Reset(token);if(k==3)State.s!.text_Level=null;bool npe=false;try{Call(k==1||k==2?null:State.s,k<=1?null:State.input);}catch(NullReferenceException){npe=true;}Check(k<=1?!npe&&State.trace==0&&ReferenceEquals(State.s!.playerSave,State.old):npe&&State.trace==(k==2?0:3)&& (k!=3||ReferenceEquals(State.s!.playerSave,State.input)&&State.s.level==7),"skip-null:"+k);}}
  else{for(int k=0;k<4;k++){State.Reset(token);if(k==1)State.w!.suppliesInfoPage=null;if(k==2)State.w!.text_money=null;bool npe=false;try{Call(k==3?null:State.w,k==0?null:State.input);}catch(NullReferenceException){npe=true;}int[]traces={12,1,123,1};Check(npe&&State.trace==traces[k]&&(k==1||k==3||State.info1.supplies==null&&State.info1.suppliesInfo==null)&& (k!=0||State.w!.playerSave==null),"warehouse-null:"+k);}}
  foreach(string stage in token==0x060000A4?new[]{"format","text"}:new[]{"clear","info","format","text","create"}){State.Reset(token);State.fail=stage;bool thrown=false;try{Call(token==0x060000A4?State.s:State.w,State.input);}catch(DependencyException){thrown=true;}int expected=token==0x060000A4?(stage=="format"?3:34):stage=="clear"?1:stage=="info"?12:stage=="format"?123:stage=="text"?1234:12345;Check(thrown&&State.trace==expected&&State.partialOK&&State.input.marker==123&&(token==0x060000A4?ReferenceEquals(State.s!.playerSave,State.input):ReferenceEquals(State.w!.playerSave,stage is "clear" or "info"?State.old:State.input)),"dependency:"+stage);}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var asm=AssemblyDefinition.ReadAssembly(args[0]);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();int count=0,errors=0;var failures=new List<string>();var controls=new List<object>();bool cp=true;
  foreach(int token in new[]{0x060000A4,0x060006E8}){var m=(MethodDefinition)asm.MainModule.LookupToken(token);var data=rows.Where(r=>r[0]==$"0x{token:X8}").Select(r=>r.Skip(1).Select(uint.Parse).ToArray()).ToList();if(data.Count!=4096)throw new Exception("Native row count");var result=Cases(m,Emit(m,"none"),data);count+=result.Cases;failures.AddRange(result.Failures);
   foreach(string mutation in args.Length>3?Array.Empty<string>():token==0x060000A4?new[]{"illegal_stack","return_early","wrong_field","copy_ref","late_text","wrong_bool","wrong_challenge","skip_store","null_save_throw"}:new[]{"illegal_stack","return_early","wrong_field","copy_ref","late_text","wrong_bool","skip_clear","skip_info_clear","skip_create","early_save_store"}){bool detected=false;string?error=null;try{detected=Cases(m,Emit(m,mutation),data,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{token=$"0x{token:X8}",mutation,detected,tool_error=error});}
   var call=Emit(m,"none",true);var culture0=CultureInfo.CurrentCulture;try{foreach(string culture in new[]{"en-US","de-DE","ja-JP","ar-SA"})foreach(int value in new[]{int.MinValue,-999,-1,0,1,2,127,1000,int.MaxValue}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(culture);State.Reset(token,value,value,12,0);if(token==0x060000A4)((Action<Skip?,Save?>)call)(State.s,State.input);else((Action<Warehouse?,Save?>)call)(State.w,State.input);count++;string expected=value.ToString(token==0x060000A4?"当前关卡：0":"N0",CultureInfo.CurrentCulture);if(State.label1.text!=expected||!State.label1.flag||State.trace!=(token==0x060000A4?4:1245))failures.Add("actual-format:"+token+":"+culture+":"+value);}}finally{CultureInfo.CurrentCulture=culture0;}
  }
  bool pass=failures.Count==0&&errors==0&&cp;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=count,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Original caller instructions execute with supplied objects and recorded helper/GC/formatter/TMP dependencies. CLR candidate CIL executes with public doubles; ref-write and receiver-change stressors establish pointer alias/capture. Separate actual CLR Int32.ToString(string) executes under four cultures. Null and dependency exceptions assert partial effects from native CFG. No native formatter/UI/helper/GC/throw engine or Unity/Xcode/device acceptance.",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
