using Mono.Cecil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher59{
static void R(bool x,string s){if(!x)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Off(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
sealed class Code{public List<byte>b=new();Dictionary<string,int>labels=new();List<(int,string)>fix=new();public void O(params byte[]x)=>b.AddRange(x);public void Ref(byte op,IMetadataTokenProvider r){O(op);b.AddRange(BitConverter.GetBytes(r.MetadataToken.ToInt32()));}public void Token(byte op,int t){O(op);b.AddRange(BitConverter.GetBytes(t));}public void F(float f){O(0x22);b.AddRange(BitConverter.GetBytes(f));}public void Label(string n)=>labels.Add(n,b.Count);public void Br(byte op,string n){O(op);fix.Add((b.Count,n));O(0);}public void L(byte n)=>O(0x11,n);public void S(byte n)=>O(0x13,n);public byte[]Finish(){foreach(var(p,n)in fix){int d=labels[n]-p-1;R(d>=-128&&d<=127,"Branch extent");b[p]=unchecked((byte)(sbyte)d);}return b.ToArray();}}
static int Main(string[]args){try{R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs");var b=File.ReadAllBytes(args[0]);R(H(b)=="6e9c634587ffad5bc3b4cf8e9c20858c770c13eed8e99498333053c0f3cb3e64","Pinned Native58");var c=(byte[])b.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(b));var rows=new List<object>();foreach(int token in new[]{0x06000356,0x06000408,0x0600046E,0x0600046F,0x06000726,0x06000856}){var m=(MD)a.MainModule.LookupToken(token);R(m.HasThis&&m.Body.ExceptionHandlers.Count==0,"Target shape");var il=new Code();FieldReference field(string owner,string name)=>a.MainModule.GetTypes().Single(t=>t.FullName==owner).Fields.Single(f=>f.Name==name);MethodReference call(string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MethodReference>().First(f=>f.Name==name);MethodReference exact(string name)=>a.MainModule.GetMemberReferences().OfType<MethodReference>().Single(r=>r.FullName==name);FieldReference vf(string name)=>a.MainModule.GetMemberReferences().OfType<FieldReference>().Single(r=>r.FullName=="System.Single UnityEngine.Vector3::"+name);
void Load(string owner,string name){il.O(2);il.Ref(0x7b,field(owner,name));}void StoreFloat(string owner,string name,float value){il.O(2);il.F(value);il.Ref(0x7d,field(owner,name));}void V3()=>il.Ref(0x73,exact("System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)"));void GetShadow(string owner){Load(owner,"shadow");il.Ref(0x6f,exact("UnityEngine.Transform UnityEngine.GameObject::get_transform()"));}void VecPart(byte local,string part){il.L(local);il.Ref(0x7b,vf(part));}void String(string value){var i=m.Body.Instructions.First(i=>i.OpCode.Name=="ldstr"&&i.Operand is string s&&s==value);il.Token(0x72,BitConverter.ToInt32(b,Off(pe,m.RVA)+12+i.Offset+1));}
int sig=m.Body.LocalVarToken.ToInt32(),max=3;
switch(token){
case 0x06000356:{max=4;Load("Plant","board");il.O(0x25);il.Ref(0x7b,field("Board","boardConfig"));il.Br(0x2c,"cleanBoard");il.Ref(0x7b,field("Board","map"));il.O(0x25);il.Br(0x2c,"cleanMap");il.Ref(0x7b,field("Map","senarioState"));il.O(0x25,0x17);il.Br(0x2e,"rate25");il.O(0x25,0x1e);il.Br(0x2e,"rate125");il.O(0x25,0x1f,10);il.Br(0x2e,"rate150");il.O(0x26);il.F(0);il.Br(0x2b,"rate");il.Label("rate25");il.O(0x26);il.F(25);il.Br(0x2b,"rate");il.Label("rate125");il.O(0x26);il.F(125);il.Br(0x2b,"rate");il.Label("rate150");il.O(0x26);il.F(150);il.Label("rate");il.S(7);il.O(0x16);il.Ref(0x28,call("get_deltaTime"));il.L(7);il.O(0x5a,0x14,0x17);il.Ref(0x73,call(".ctor"));il.S(9);Load("Plant","elementManager");il.L(9);il.Ref(0x6f,call("ToEffect"));il.O(0x2a);il.Label("cleanBoard");il.O(0x26,0x2a);il.Label("cleanMap");il.O(0x26,0x2a);break;}
case 0x06000408:{max=3;il.O(0x03);il.Br(0x2c,"a");il.O(0x03,0x17);il.Br(0x2e,"s");il.O(0x03,0x18);il.Br(0x2e,"d");String("");il.Br(0x2b,"chosen");il.Label("a");String("A");il.Br(0x2b,"chosen");il.Label("s");String("S");il.Br(0x2b,"chosen");il.Label("d");String("D");il.Label("chosen");il.S(5);Load("Prop","keyText");il.L(5);il.O(0x17);il.Ref(0x6f,call("SetText"));Load("Prop","keyText");il.Ref(0x6f,call("get_gameObject"));il.O(0x17);il.Ref(0x6f,call("SetActive"));il.O(0x2a);break;}
case 0x0600046E:{max=3;Load("Zombie","board");il.Ref(0x7b,field("Board","zombieManager"));il.Ref(0x7b,field("ZombieManager","audioClip_zombie"));il.O(0x1f,61,0x1f,63);il.Ref(0x28,call("Range"));il.Ref(0x6f,call("get_Item"));il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.Ref(0x28,call("AudioVolume"));il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26,0x2a);break;}
case 0x0600046F:{max=4;il.Ref(0x28,call("AudioVolume"));il.S(0);il.O(0x14);il.S(5);il.F(1);il.S(6);Load("Zombie","ID");il.O(0x1c,0x59,0x18);il.Br(0x36,"special");Load("Zombie","ID");il.O(0x1f,19,0x59,0x18);il.Br(0x35,"audio");il.Label("special");il.Ref(0x7e,field("ResourceManager","plantClips"));il.O(0x17);il.Ref(0x6f,call("get_Item"));il.S(5);il.F(0.9f);il.F(1.1f);il.Ref(0x28,call("Range"));il.S(6);il.F(0.6f);il.F(0.8f);il.Ref(0x28,call("Range"));il.S(8);il.L(0);il.L(0);il.O(0xfe,0x01);il.Br(0x2c,"leftNan");il.L(8);il.L(8);il.O(0xfe,0x01);il.Br(0x2c,"rightNan");il.L(0);il.L(8);il.O(0x5a);il.Br(0x2b,"product");il.Label("leftNan");il.L(0);il.F(0);il.O(0x58);il.Br(0x2b,"product");il.Label("rightNan");il.L(8);il.F(0);il.O(0x58);il.Label("product");il.S(0);il.Label("audio");il.L(5);il.Ref(0x28,call("get_main"));il.Ref(0x6f,call("get_transform"));il.Ref(0x6f,call("get_position"));il.L(0);il.L(6);il.Ref(0x28,call("CreateAudioAtPoint"));il.O(0x26,0x2a);break;}
case 0x06000726:{max=4;il.O(0x05,0x1f,48,0x59,0xd1,0x1f,9);il.Br(0x35,"invalid");il.O(0x03,0x25,0x50,0x0f,3);il.Ref(0x28,call("ToString"));il.Ref(0x28,call("Concat"));il.Ref(0x81,call("Concat").DeclaringType);il.O(0x04,0x25);var intType=m.Body.Instructions.Select(i=>i.Operand).OfType<TypeReference>().First(t=>t.FullName=="System.Int32");il.Ref(0x71,intType);il.O(0x17,0x58);il.Ref(0x81,intType);il.O(0x05,0x2a);il.Label("invalid");il.O(0x16,0x2a);break;}
case 0x06000856:{max=3;Load("FTRuntime.SwfClipAsset/Frame","_cachedMesh");il.Ref(0x28,call("op_Implicit"));il.Br(0x2d,"result");il.O(2);il.Ref(0x73,call(".ctor"));il.Ref(0x7d,field("FTRuntime.SwfClipAsset/Frame","_cachedMesh"));Load("FTRuntime.SwfClipAsset/Frame","_cachedMesh");il.O(0x1f,20);il.Ref(0x6f,call("set_hideFlags"));Load("FTRuntime.SwfClipAsset/Frame","_cachedMesh");Load("FTRuntime.SwfClipAsset/Frame","MeshData");il.Ref(0x28,call("FillGeneratedMesh"));il.Label("result");Load("FTRuntime.SwfClipAsset/Frame","_cachedMesh");il.O(0x2a);break;}
}
var code=il.Finish();R(code.Length<=m.Body.CodeSize,"Bounded slot "+m.FullName+" "+code.Length+"/"+m.Body.CodeSize);int h=Off(pe,m.RVA);R((b[h]&3)==3&&(BitConverter.ToUInt16(b,h)>>12)==3,"Fat header");Array.Clear(c,h+12,m.Body.CodeSize);code.CopyTo(c,h+12);BitConverter.GetBytes((ushort)max).CopyTo(c,h+2);BitConverter.GetBytes(code.Length).CopyTo(c,h+4);BitConverter.GetBytes(sig).CopyTo(c,h+8);rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,old_local_sig=m.Body.LocalVarToken.ToInt32(),local_sig=sig,code_sha256=H(code)});}
File.WriteAllBytes(args[1],c);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(b),candidate_sha256=H(c),methods=rows},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(H(c));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}}
