using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using Vector3=UnityEngine.Vector3;using Vector2=UnityEngine.Vector2;
public class DependencyException:Exception{}public enum ItemType:int{}
public class Prop{public ItemType propType;public Vector2 mousePosition;public GameObject?propImagex;public int marker;}
public class Card_Choose{public int page,marker;}
public class SeedChooserScreen{}
public class GameObject{public Transform?transform{get{return State.Get(this);}}public T?GetComponent<T>()where T:class{return State.Component<T>(this);}}
public class Transform{public Vector3 position{set{State.Set(this,value);}}public Vector3 localPosition{set{State.Set(this,value);}}}
public static class State{
 public static Prop prop=new();public static GameObject game=new(),otherGame=new();public static Transform transform=new();public static Card_Choose cardA=new(),cardB=new();public static Card_Choose?selected;public static int token,mode,hook,error,gets,sets,components;public static ulong trace;public static uint x,y,z;public static bool argsOK;public static string fail="";
 public static uint Bits(float v)=>unchecked((uint)BitConverter.SingleToInt32Bits(v));public static float Value(uint v)=>BitConverter.Int32BitsToSingle(unchecked((int)v));
 public static void Reset(int t,uint bx,uint by,int type,int m,int h){token=t;mode=m;hook=h;prop=new(){propType=(ItemType)type,mousePosition=new Vector2(Value(bx),Value(by)),propImagex=m==1?null:game,marker=77};cardA=new(){page=7,marker=11};cardB=new(){page=8,marker=22};selected=cardA;trace=0;error=gets=sets=components=0;x=y=z=0xdeadbeef;argsOK=true;fail="";}
 public static void Event(int n){trace=(trace<<4)|(uint)n;}public static void Throw(string s){if(fail==s)throw new DependencyException();}
 public static Transform?Get(GameObject r){Event(1);gets++;argsOK&=ReferenceEquals(r,game);Throw("getter");if(hook==1){prop.mousePosition=new Vector2(Value(0x44fa0000),Value(0x457a0000));prop.propType=0;prop.propImagex=otherGame;}return mode==2?null:transform;}
 public static void Set(Transform r,Vector3 v){Event(2);sets++;argsOK&=ReferenceEquals(r,transform);Throw("setter");x=Bits(v.x);y=Bits(v.y);z=Bits(v.z);if(hook==2)selected=cardB;}
 public static T?Component<T>(GameObject r)where T:class{Event(3);components++;argsOK&=ReferenceEquals(r,game)&&typeof(T)==typeof(Card_Choose);Throw("component");if(hook==3)selected=cardB;return mode==3?null:(T)(object)selected!;}
}
public static class Fixture{
 static Dictionary<string,Type>map=new(){["Prop"]=typeof(Prop),["SeedChooserScreen"]=typeof(SeedChooserScreen),["ItemType"]=typeof(ItemType),["Card_Choose"]=typeof(Card_Choose),["UnityEngine.GameObject"]=typeof(GameObject),["UnityEngine.Transform"]=typeof(Transform),["UnityEngine.Vector2"]=typeof(Vector2),["UnityEngine.Vector3"]=typeof(Vector3),["System.Single"]=typeof(float),["System.Int32"]=typeof(int)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t);
 static Action<Prop?,GameObject?,int>Emit(MethodDefinition m,string mutation){bool prop=m.MetadataToken.ToInt32()==0x06000404;Type[]signature=prop?new[]{typeof(Prop)}:new[]{typeof(SeedChooserScreen),typeof(GameObject),typeof(int)};var dm=new DynamicMethod(m.Name+mutation,typeof(void),signature,typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);var labels=m.Body.Instructions.ToDictionary(i=>i,i=>il.DefineLabel());bool changed=mutation=="none";
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){il.MarkLabel(labels[i]);var op=ops[i.OpCode.Value];var operand=i.Operand;
   if(operand is FieldReference f){if(mutation=="wrong_page"&&f.Name=="page"&&op==RO.Stfld){il.Emit(RO.Pop);il.Emit(RO.Ldc_I4_1);changed=true;}il.Emit(op,T(f.DeclaringType).GetField(f.Name)!);continue;}
   if(operand is MethodReference mr){if(mr.Name==".ctor"){il.Emit(op,typeof(Vector3).GetConstructor(new[]{typeof(float),typeof(float),typeof(float)})!);continue;}MethodInfo mi;if(mr is GenericInstanceMethod g){mi=typeof(GameObject).GetMethod("GetComponent")!.MakeGenericMethod(T(g.GenericArguments.Single()));if(mutation=="skip_component"){il.Emit(RO.Pop);il.Emit(RO.Ldnull);changed=true;continue;}}else{mi=T(mr.DeclaringType).GetMethod(mr.Name)!;if(mr.Name.StartsWith("set_")&&mutation=="skip_setter"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(mr.Name=="get_transform"&&mutation=="wrong_receiver"){il.Emit(RO.Pop);il.Emit(RO.Ldsfld,typeof(State).GetField("otherGame")!);changed=true;}}il.Emit(op,mi);continue;}
   if(operand is Mono.Cecil.Cil.Instruction branch){if(mutation=="flip_type_gate"){op=RO.Beq;changed=true;}il.Emit(op,labels[branch]);continue;}if(operand is Mono.Cecil.Cil.VariableDefinition v){if(op==RO.Ldloc_0&&mutation=="byref_vector"){il.Emit(RO.Ldloca,locals[v.Index]);changed=true;}else il.Emit(op,locals[v.Index]);continue;}if(operand is Mono.Cecil.ParameterDefinition pd){il.Emit(op,(short)(pd.Index+1));continue;}
   if(operand is int iv){if(mutation=="wrong_stride"&&iv==230){iv=231;changed=true;}il.Emit(op,iv);continue;}if(operand is float fv){if(mutation=="wrong_offset"&&fv==(prop?50f:140f)){fv+=1;changed=true;}il.Emit(op,fv);continue;}
   if(operand==null){if(mutation=="byref_vector"&&op==RO.Ldloc_0){il.Emit(RO.Ldloca,locals[0]);changed=true;continue;}if(mutation=="wrong_divisor"&&op==RO.Ldc_I4_3){op=RO.Ldc_I4_2;changed=true;}if(mutation=="unsigned_math"&&op==RO.Rem){op=RO.Rem_Un;changed=true;}if(mutation=="unsigned_math"&&op==RO.Div){op=RO.Div_Un;changed=true;}if(mutation=="checked_multiply"&&op==RO.Mul){op=RO.Mul_Ovf;changed=true;}il.Emit(op);continue;}throw new Exception("Unsupported "+operand);
  }if(!changed)throw new Exception("Mutation not applied "+mutation);if(prop){var fn=(Action<Prop?>)dm.CreateDelegate(typeof(Action<Prop?>));return(p,g,index)=>fn(p);}else{var fn=(Action<SeedChooserScreen?,GameObject?,int>)dm.CreateDelegate(typeof(Action<SeedChooserScreen?,GameObject?,int>));return(p,g,index)=>fn(null,g,index);}
 }
 record Result(int Cases,List<string>Failures);
 static Result Cases(int token,Action<Prop?,GameObject?,int>fn,List<ulong[]>rows,bool stop=false){int count=0,index=0;var failures=new List<string>();void Check(bool ok,string label){count++;if(!ok)failures.Add(label);}bool prop=token==0x06000404;
  foreach(var r in rows){State.Reset(token,(uint)r[0],(uint)r[1],(int)r[2],(int)r[4],(int)r[5]);try{fn(State.prop,State.mode==1?null:State.game,unchecked((int)r[3]));}catch(NullReferenceException){State.Event(4);State.error=1;}catch(OverflowException){State.error=2;}catch(Exception e)when(e is not InvalidProgramException){State.error=3;}bool ok=State.trace==r[6]&&State.error==(int)r[7]&&State.gets==(int)r[8]&&State.sets==(int)r[9]&&State.components==(int)r[10]&&State.x==(uint)r[11]&&State.y==(uint)r[12]&&State.z==(uint)r[13]&&State.cardA.page==(int)r[14]&&State.cardB.page==(int)r[15]&&State.argsOK&&r[16]==1&&State.prop.marker==77&&State.cardA.marker==11&&State.cardB.marker==22;Check(ok,"native-row:"+index++);if(stop&&failures.Count>0)return new(count,failures);}
  foreach(string stage in prop?new[]{"getter","setter"}:new[]{"getter","setter","component"}){State.Reset(token,0x3f800000,0x40000000,5,0,0);State.fail=stage;bool got=false;try{fn(State.prop,State.game,-1);}catch(DependencyException){got=true;}catch(Exception e)when(e is not InvalidProgramException){}ulong expected=stage=="getter"?0x1UL:stage=="setter"?0x12UL:0x123UL;Check(got&&State.trace==expected&&State.cardA.page==7&&State.cardB.page==8&&State.argsOK,"partial-exception:"+stage);}
  if(prop){State.Reset(token,0,0,0,0,0);bool got=false;try{fn(null,State.game,0);}catch(NullReferenceException){got=true;}Check(got&&State.trace==0,"CLR-null-this-not-native-executed");}
  return new(count,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var all=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();var controls=new List<object>();var failures=new List<string>();int count=0,errors=0;bool cp=true;
  foreach(int token in new[]{0x06000404,0x060006BE}){var m=(MethodDefinition)a.MainModule.LookupToken(token);var rows=all.Where(r=>r[0]==$"0x{token:X8}").Select(r=>r.Skip(1).Select(ulong.Parse).ToArray()).ToList();if(rows.Count!=4096)throw new Exception("Native rows");var result=Cases(token,Emit(m,"none"),rows);count+=result.Cases;failures.AddRange(result.Failures.Select(f=>token+":"+f));foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","wrong_receiver","wrong_offset","skip_setter","byref_vector"}.Concat(token==0x06000404?new[]{"flip_type_gate"}:new[]{"wrong_stride","wrong_divisor","unsigned_math","checked_multiply","wrong_page","skip_component"})){bool detected=false;string?error=null;try{detected=Cases(token,Emit(m,mutation),rows,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}cp&=detected&&error==null;controls.Add(new{token=$"0x{token:X8}",mutation,detected,tool_error=error});}}
  bool pass=failures.Count==0&&cp&&errors==0;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=2,positive_cases=count,positive_failures=failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,scope="Two original coordinate callers execute unchanged native integer/SSE arithmetic with recorded Unity getter/setter/component/exception dependencies and initialized metadata. Candidate real public Vector2/Vector3 values and Vector3 ctor from pinned Unity CoreModule; public fixture object graph. Exact float bits including NaN/subnormal/signed-zero, getter-induced mutations, int32 overflow and negative remainder, partial effects, page store tested. Seed null-this permitted; Prop CLR null-this is additional coverage, not native-executed. No original Unity/throw/class-init/game/iOS proof.",failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
