using Mono.Cecil;using Mono.Cecil.Cil;using System.Reflection.PortableExecutable;using System.Security.Cryptography;using System.Text.Json;using MD=Mono.Cecil.MethodDefinition;
static class Patcher48{
 static void R(bool x,string m){if(!x)throw new Exception(m);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 public static int Main(string[]args){try{
  R(args.Length==3,"Input/output/report");R(!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh output required");byte[]old=File.ReadAllBytes(args[0]);R(H(old)=="7d4a2d733348df060a70070ab9a5842d386e1fffb5b57a3d6dc606c845e85aa8","Pinned Native47 input");var raw=(byte[])old.Clone();using var a=AssemblyDefinition.ReadAssembly(args[0]);using var pe=new PEReader(new MemoryStream(old));var rows=new List<object>();
  foreach(int token in new[]{0x06000225,0x06000230}){
   var m=(MD)a.MainModule.LookupToken(token);R(m.IsStatic&&m.Body.ExceptionHandlers.Count==0&&m.ReturnType.Name==(token==0x06000225?"DeviceInfo":"ZombieInfo"),"Pinned static resource loader");var ins=m.Body.Instructions;var zero=ins.Select((i,k)=>(i,k)).Single(x=>x.i.OpCode==OpCodes.Ldc_I4&&(int)x.i.Operand==0&&x.k>0&&ins[x.k-1].Operand is VariableDefinition v&&v.Index==9&&v.VariableType.FullName==m.ReturnType.FullName&&ins[x.k+1].OpCode==OpCodes.Ceq).i;
   var ret=ins.Select((i,k)=>(i,k)).Single(x=>x.i.OpCode==OpCodes.Ret&&x.k>0&&ins[x.k-1].Operand is VariableDefinition v&&v.VariableType.FullName=="System.NullReferenceException").i;
   var sec=pe.PEHeaders.SectionHeaders.Single(s=>m.RVA>=s.VirtualAddress&&m.RVA<s.VirtualAddress+s.SizeOfRawData);int header=sec.PointerToRawData+m.RVA-sec.VirtualAddress;R((old[header]&3)==3&&(BitConverter.ToUInt16(old,header)>>12)==3,"Pinned fat body");int start=header+12;R(raw[start+zero.Offset]==0x20&&BitConverter.ToInt32(raw,start+zero.Offset+1)==0&&raw[start+ret.Offset]==0x2a,"Pinned raw opcodes");raw[start+zero.Offset]=0x14;Array.Clear(raw,start+zero.Offset+1,4);raw[start+ret.Offset]=0x7a;
   rows.Add(new{token=$"0x{token:X8}",method=m.FullName,header,code_start=start,reserved_code_size=m.Body.CodeSize,new_code_size=m.Body.CodeSize,old_max=m.Body.MaxStackSize,new_max=m.Body.MaxStackSize,local_sig=m.Body.LocalVarToken.ToInt32(),code_sha256=H(raw[start..(start+m.Body.CodeSize)]),null_constant_offset=zero.Offset,exception_return_offset=ret.Offset});
  }
  R(old.Length==raw.Length,"No file growth");File.WriteAllBytes(args[1],raw);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(old),candidate_sha256=H(raw),methods=rows,scope="Exactly four opcode bytes change in two resource loaders; five-byte integer-zero encoding becomes ldnull plus four Nops, and the NRE-only return becomes throw. All headers, offsets, locals, branches, metadata and other instructions unchanged."},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine("CANDIDATE "+H(raw));return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
