using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Security.Cryptography;
using System.Text;

if(args.Length!=2){Console.Error.WriteLine("Usage: Stage9SaveLoadBaseDataPatch <input.dll> <output.dll>");return 2;}
const string ExpectedSha="59b193dd670f0a4d0c8d1540ed38d2dea7c53c6d3e6c51ff2158481638ae0e01";
const int ExpectedMethods=2317;
const uint TargetToken=0x06000243u;
static IEnumerable<TypeDefinition> Ts(IEnumerable<TypeDefinition> xs){foreach(var t in xs){yield return t;foreach(var n in Ts(t.NestedTypes))yield return n;}}
static uint R(IMetadataTokenProvider p)=>p.MetadataToken.ToUInt32();
static string O(object? x,MethodDefinition m)=>x switch{null=>"",Instruction i=>$"I#{m.Body.Instructions.IndexOf(i)}",Instruction[] a=>"SW["+string.Join(',',a.Select(i=>m.Body.Instructions.IndexOf(i)))+"]",MethodReference mr=>$"M:{mr.FullName}",FieldReference f=>$"F:{f.FullName}",TypeReference t=>$"T:{t.FullName}",VariableDefinition v=>$"V:{v.Index}:{v.VariableType.FullName}",ParameterDefinition p=>$"P:{p.Index}:{p.ParameterType.FullName}",string s=>$"S:{Convert.ToBase64String(Encoding.UTF8.GetBytes(s))}",_=>$"C:{Convert.ToString(x,System.Globalization.CultureInfo.InvariantCulture)}"};
static string S(MethodDefinition m){var b=new StringBuilder();b.Append(m.FullName).Append('|').Append(m.Attributes).Append('|').Append(m.ImplAttributes).Append('|');if(!m.HasBody)return b.Append("NOBODY").ToString();foreach(var v in m.Body.Variables)b.Append("L:").Append(v.Index).Append(':').Append(v.VariableType.FullName).Append(';');foreach(var i in m.Body.Instructions)b.Append("I:").Append(i.OpCode.Code).Append(':').Append(O(i.Operand,m)).Append(';');return b.ToString();}
var input=Path.GetFullPath(args[0]);var output=Path.GetFullPath(args[1]);var sha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(input))).ToLowerInvariant();Console.WriteLine($"INPUT_SHA256 {sha}");if(sha!=ExpectedSha)throw new InvalidDataException("input SHA mismatch");
using var mod=ModuleDefinition.ReadModule(input,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate});var all=Ts(mod.Types).SelectMany(t=>t.Methods).ToList();if(all.Count!=ExpectedMethods)throw new InvalidDataException("MethodDef count drift");var target=mod.LookupToken(new MetadataToken(TokenType.Method,(int)(TargetToken&0xffffff))) as MethodDefinition??throw new InvalidDataException("target missing");if(target.FullName!="System.Void SavesManager::LoadBaseData()")throw new InvalidDataException("target drift");var before=all.Where(m=>R(m)!=TargetToken).ToDictionary(R,S);
var ins=target.Body.Instructions.Single(i=>i.Offset==0x00F3);var store=target.Body.Instructions.Single(i=>i.Offset==0x00FC);if(ins.OpCode.Code!=Code.Ldc_I8||Convert.ToInt64(ins.Operand)!=4294967295L)throw new InvalidDataException("IL_00F3 drift");if(store.OpCode.Code!=Code.Stfld||store.Operand is not FieldReference fr||fr.FullName!="ChallengeType GlobalStaticVars/LawnApp::challengeTypeOnPlay")throw new InvalidDataException("challenge field drift");ins.OpCode=OpCodes.Ldc_I4_M1;ins.Operand=null;Console.WriteLine("PATCH_LOADBASEDATA challengeTypeOnPlay=-1 opcode=ldc.i4.m1");
mod.Write(output);var outSha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(output))).ToLowerInvariant();Console.WriteLine($"OUTPUT_SHA256 {outSha}");using var re=ModuleDefinition.ReadModule(output,new ReaderParameters{InMemory=true,ReadingMode=ReadingMode.Immediate});var after=Ts(re.Types).SelectMany(t=>t.Methods).ToList();var rt=re.LookupToken(new MetadataToken(TokenType.Method,(int)(TargetToken&0xffffff))) as MethodDefinition??throw new InvalidDataException("reopen target missing");if(rt.Body.Instructions.Single(i=>i.Offset==0x00F3).OpCode.Code!=Code.Ldc_I4_M1)throw new InvalidDataException("reopen patch missing");var ua=after.Where(m=>R(m)!=TargetToken).ToDictionary(R,S);var drift=before.Where(kv=>!ua.TryGetValue(kv.Key,out var v)||v!=kv.Value).ToList();if(drift.Count!=0)throw new InvalidDataException("semantic drift outside LoadBaseData");Console.WriteLine("REOPEN_LOADBASEDATA_PASS enum_width=int32");Console.WriteLine($"SEMANTIC_ISOLATION_PASS untouched_methods={ua.Count} changed_methods=1");return 0;
