using System.Reflection.PortableExecutable;using System.Reflection.Metadata;using System.Reflection.Metadata.Ecma335;using System.Security.Cryptography;using System.Text.Json;using Mono.Cecil;using MD=Mono.Cecil.MethodDefinition;using MR=Mono.Cecil.MethodReference;using FR=Mono.Cecil.FieldReference;
static class RepairNative43{
 static void R(bool b,string s){if(!b)throw new Exception(s);}static string H(byte[]b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();static int Align(int x,int a)=>(x+a-1)/a*a;
 class IL{public List<byte>B=new();Dictionary<string,int>labels=new();List<(int,string)>branches=new();public IL O(params byte[]b){B.AddRange(b);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}public IL Ref(byte op,IMetadataTokenProvider t)=>O(op).I(t.MetadataToken.ToInt32());public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Arg(int i)=>O((byte)(2+i));public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Br(byte op,string s){O(op);branches.Add((B.Count,s));I(0);return this;}public byte[]Done(){foreach(var(p,s)in branches)BitConverter.GetBytes(labels[s]-p-4).CopyTo(B,p);return B.ToArray();}}
 static void CopyTo(this byte[]b,List<byte>l,int p){for(int i=0;i<b.Length;i++)l[p+i]=b[i];}
 static int Off(PEReader pe,int rva){var s=pe.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static int Main(string[]args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[]args){R(args.Length==3&&!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh input/output/report");byte[]before=File.ReadAllBytes(args[0]);R(H(before)=="50959644506ab0bc33f8ca1d28cfe753fc7b29ca38d98142b2a015dd05ccaaa2","Pinned Native42 input");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);var module=asm.MainModule;using var pe=new PEReader(new MemoryStream(before));var md=pe.GetMetadataReader();var m=(MD)module.LookupToken(0x0600084F);R(m.Body.ExceptionHandlers.Count==0&&m.HasThis&&m.IsConstructor&&m.Parameters.Count==0,"Pinned SwfClip constructor signature");
  FR Field(string name)=>module.Types.Single(t=>t.FullName=="FTRuntime.SwfClip").Fields.Single(f=>f.Name==name);
  var empty=m.Body.Instructions.Select(i=>i.Operand).OfType<FR>().Where(f=>f.FullName=="System.String System.String::Empty").DistinctBy(f=>f.MetadataToken).Single();var color=(MR)module.LookupToken(0x0A0000BE);R(color.FullName=="System.Void UnityEngine.Color::.ctor(System.Single,System.Single,System.Single,System.Single)","Pure public Color value constructor");var baseCtor=m.Body.Instructions.Select(i=>i.Operand).OfType<MR>().Single(c=>c.FullName=="System.Void UnityEngine.MonoBehaviour::.ctor()");
  var il=new IL().Arg(0).Int(1).Ref(0x7D,Field("_dirtyMesh")).Arg(0).Ref(0x7E,empty).Ref(0x7D,Field("_sortingLayer")).Arg(0);for(int i=0;i<4;i++)il.O(0x22).I(0x3F800000);il.Ref(0x73,color).Ref(0x7D,Field("_tint")).Arg(0).Ref(0x7E,empty).Ref(0x7D,Field("_sequence")).Arg(0).Ref(0x28,baseCtor).O(0x2A);
  byte[]code=il.Done();R(code.Length>m.Body.CodeSize,"Append mechanism intentionally exercised by full reconstruction");var last=pe.PEHeaders.SectionHeaders.Last();var ph=pe.PEHeaders;var opt=ph.PEHeader!;R(last.Name==".n29meta"&&last.PointerToRawData+last.SizeOfRawData==before.Length&&last.SectionCharacteristics==(SectionCharacteristics)0x40000040&&ph.CorHeader!.StrongNameSignatureDirectory.Size==0&&opt.CertificateTableDirectory.Size==0,"Pinned unsigned EOF section");
  int oldRoot=Off(pe,ph.CorHeader.MetadataDirectory.RelativeVirtualAddress),rootSize=ph.CorHeader.MetadataDirectory.Size;byte[]meta=before[oldRoot..(oldRoot+rootSize)];int bodyOffset=before.Length,newRva=last.VirtualAddress+bodyOffset-last.PointerToRawData,rootOffset=Align(bodyOffset+12+code.Length,4);var after=new byte[Align(rootOffset+rootSize,opt.FileAlignment)];before.CopyTo(after,0);
  ushort flags=(ushort)(0x3003|(m.Body.InitLocals?0x10:0));BitConverter.GetBytes(flags).CopyTo(after,bodyOffset);BitConverter.GetBytes((ushort)5).CopyTo(after,bodyOffset+2);BitConverter.GetBytes(code.Length).CopyTo(after,bodyOffset+4);BitConverter.GetBytes(m.Body.LocalVarToken.ToInt32()).CopyTo(after,bodyOffset+8);code.CopyTo(after,bodyOffset+12);
  int row=md.GetTableMetadataOffset(TableIndex.MethodDef)+(checked((int)m.MetadataToken.RID)-1)*md.GetTableRowSize(TableIndex.MethodDef);BitConverter.GetBytes(newRva).CopyTo(meta,row);meta.CopyTo(after,rootOffset);
  int sh=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+(ph.CoffHeader.NumberOfSections-1)*40,virtualSize=rootOffset-last.PointerToRawData+rootSize;BitConverter.GetBytes(virtualSize).CopyTo(after,sh+8);BitConverter.GetBytes(after.Length-last.PointerToRawData).CopyTo(after,sh+16);BitConverter.GetBytes(opt.SizeOfInitializedData+after.Length-before.Length).CopyTo(after,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(last.VirtualAddress+virtualSize,opt.SectionAlignment)).CopyTo(after,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(after,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(last.VirtualAddress+rootOffset-last.PointerToRawData).CopyTo(after,ph.CorHeaderStartOffset+8);
  File.WriteAllBytes(args[1],after);var report=new{input_sha256=H(before),candidate_sha256=H(after),methods=new[]{new{token="0x0600084F",method=m.FullName,old_rva=m.RVA,new_rva=newRva,body_offset=bodyOffset,code_size=code.Length,code_sha256=H(code),max_stack=5,local_sig=m.Body.LocalVarToken.ToInt32(),init_locals=m.Body.InitLocals}},metadata=new{old_root=oldRoot,new_root=rootOffset,size=rootSize},scope="One appended complete method body and one existing MethodDef RVA change; no other row/heap/old-body edit"};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(report));
 }
}
