using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Reflection.PortableExecutable;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using MD=Mono.Cecil.MethodDefinition;
using MR=Mono.Cecil.MethodReference;
using FR=Mono.Cecil.FieldReference;
static class RepairNative29 {
 static void R(bool x,string m){if(!x)throw new InvalidOperationException(m);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static int Align(int x,int a)=>checked((x+a-1)/a*a);
 class IL {
  public List<byte> B=new();Dictionary<string,int> labels=new();List<(int p,string l)> branches=new();
  public IL O(params byte[] x){B.AddRange(x);return this;}public IL I(int x){B.AddRange(BitConverter.GetBytes(x));return this;}
  public IL Ref(byte op,IMetadataTokenProvider r)=>O(op).I(r.MetadataToken.ToInt32());public IL Ref(byte op,int t)=>O(op).I(t);
  public IL Int(int x)=>x>=-1&&x<=8?O((byte)(x+0x16)):O(0x20).I(x);public IL Float(float x)=>O(0x22).I(BitConverter.SingleToInt32Bits(x));
  public IL L(int i)=>i<4?O((byte)(6+i)):O(0x11,(byte)i);public IL S(int i)=>i<4?O((byte)(10+i)):O(0x13,(byte)i);public IL A(int i)=>O(0x12,(byte)i);
  public IL Arg(int i)=>i<4?O((byte)(2+i)):O(0x0E,(byte)i);
  public IL Label(string s){labels.Add(s,B.Count);return this;}public IL Branch(byte op,string s){O(op);branches.Add((B.Count,s));O(0);return this;}
  public byte[] Done(){foreach(var(p,l)in branches){int d=labels[l]-p-1;R(d>=-128&&d<=127,"Short branch overflow");B[p]=unchecked((byte)(sbyte)d);}return B.ToArray();}
 }
 record Stream(string Name,byte[] Data);
 record Added(string Name,int Token,int Parent,int NameIndex,int SignatureIndex);
 static (byte[] Image,object Evidence) Metadata(byte[] input,PEReader pe,Mono.Cecil.ModuleDefinition module){
  var md=pe.GetMetadataReader();int rootRva=pe.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress;var section=pe.PEHeaders.SectionHeaders.Single(s=>rootRva>=s.VirtualAddress&&rootRva<s.VirtualAddress+s.SizeOfRawData);int rootOffset=section.PointerToRawData+rootRva-section.VirtualAddress;int rootSize=pe.PEHeaders.CorHeader.MetadataDirectory.Size;byte[] root=input[rootOffset..(rootOffset+rootSize)];R(BitConverter.ToUInt32(root,0)==0x424A5342,"Metadata root");int vlen=BitConverter.ToInt32(root,12);int countAt=Align(16+vlen,4)+2;int count=BitConverter.ToUInt16(root,countAt);int p=countAt+2;var streams=new List<Stream>();
  for(int i=0;i<count;i++){int off=BitConverter.ToInt32(root,p),len=BitConverter.ToInt32(root,p+4);int end=Array.IndexOf(root,(byte)0,p+8);R(end>=0,"Stream name");string name=Encoding.ASCII.GetString(root,p+8,end-p-8);streams.Add(new(name,root[off..(off+len)]));p=Align(end+1,4);}int headEnd=p;
  int ti=streams.FindIndex(s=>s.Name=="#~");R(ti>=0,"Compressed table stream required");var table=streams[ti].Data;var stringStream=streams.Single(s=>s.Name=="#Strings").Data;var blobStream=streams.Single(s=>s.Name=="#Blob").Data;R((table[6]&3)==0,"Pinned 2-byte string/blob indexes");int rows=md.GetTableRowCount(TableIndex.MemberRef);int rowSize=md.GetTableRowSize(TableIndex.MemberRef);R(rows==1021&&rowSize==6,"Pinned MemberRef layout");R(md.GetTableRowCount(TableIndex.TypeSpec)<8192&&md.GetTableRowCount(TableIndex.TypeDef)<8192&&md.GetTableRowCount(TableIndex.TypeRef)<8192&&md.GetTableRowCount(TableIndex.ModuleRef)<8192&&md.GetTableRowCount(TableIndex.MethodDef)<8192,"Parent index width");
  int ts(string name){var hits=Enumerable.Range(1,md.GetTableRowCount(TableIndex.TypeSpec)).Select(i=>module.LookupToken(0x1B000000+i)).OfType<Mono.Cecil.TypeReference>().Where(t=>t.FullName==name).ToArray();R(hits.Length==1,"Exact TypeSpec "+name);return hits[0].MetadataToken.RID is uint r?checked((int)r):throw new Exception();}
  int nameIndex(string name){for(int i=0;i<stringStream.Length-name.Length;i++){if(Encoding.UTF8.GetString(stringStream,i,name.Length)==name&&stringStream[i+name.Length]==0)return i;}throw new Exception("Existing string missing "+name);}
  int sig(byte[] desired){foreach(var h in md.MemberReferences){var m=md.GetMemberReference(h);if(md.GetBlobBytes(m.Signature).SequenceEqual(desired))return MetadataTokens.GetHeapOffset(m.Signature);}throw new Exception("Existing signature missing");}
  var specs=new[]{("Invoke",ts("System.Action`1<FTRuntime.SwfClipController>"),sig(new byte[]{0x20,1,1,0x13,0})),("Remove",ts("System.Collections.Generic.HashSet`1<System.String>"),sig(new byte[]{0x20,1,2,0x13,0})),("Contains",ts("System.Collections.Generic.HashSet`1<System.String>"),sig(new byte[]{0x20,1,2,0x13,0}))};
  ulong valid=BitConverter.ToUInt64(table,8);R((valid&(1UL<<10))!=0,"MemberRef missing");int countPos=24+4*Enumerable.Range(0,10).Count(i=>(valid&(1UL<<i))!=0);R(BitConverter.ToInt32(table,countPos)==rows,"Row count pin");int tableStart=md.GetTableMetadataOffset(TableIndex.MemberRef);int streamRootOffset=Array.FindIndex(root,_=>false); // replaced with exact stream offset below
  int scan=countAt+2;for(int i=0;i<count;i++){int e=Array.IndexOf(root,(byte)0,scan+8);if(Encoding.ASCII.GetString(root,scan+8,e-scan-8)=="#~")streamRootOffset=BitConverter.ToInt32(root,scan);scan=Align(e+1,4);}R(streamRootOffset>=0,"Table stream root offset");int insert=tableStart-streamRootOffset+rows*rowSize;R(insert>=24&&insert<=table.Length,"MemberRef table end");var add=new List<byte>();var added=new List<Added>();foreach(var(name,parent,signature)in specs){int ni=nameIndex(name);R(ni<65536&&signature<65536&&parent<8192,"Index overflow");int coded=parent*8+4;add.AddRange(BitConverter.GetBytes((ushort)coded));add.AddRange(BitConverter.GetBytes((ushort)ni));add.AddRange(BitConverter.GetBytes((ushort)signature));added.Add(new(name,0x0A000000+rows+added.Count+1,0x1B000000+parent,ni,signature));}
  byte[] expanded=table[..insert].Concat(add).Concat(table[insert..]).ToArray();BitConverter.GetBytes(rows+added.Count).CopyTo(expanded,countPos);ulong sorted=BitConverter.ToUInt64(expanded,16);BitConverter.GetBytes(sorted&~(1UL<<10)).CopyTo(expanded,16);streams[ti]=new("#~",expanded);
  var nr=new List<byte>(root[..headEnd]);scan=countAt+2;foreach(var s in streams){while(nr.Count%4!=0)nr.Add(0);BitConverter.GetBytes(nr.Count).CopyTo(nr,scan);BitConverter.GetBytes(s.Data.Length).CopyTo(nr,scan+4);nr.AddRange(s.Data);int e=Array.IndexOf(root,(byte)0,scan+8);scan=Align(e+1,4);}byte[] meta=nr.ToArray();
  var ph=pe.PEHeaders;var opt=ph.PEHeader!;R(opt.Magic==PEMagic.PE32&&opt.CertificateTableDirectory.Size==0&&ph.CorHeader.StrongNameSignatureDirectory.Size==0&&(ph.CorHeader.Flags&CorFlags.StrongNameSigned)==0,"Unsupported signed/input layout");int newHeader=ph.PEHeaderStartOffset+ph.CoffHeader.SizeOfOptionalHeader+ph.CoffHeader.NumberOfSections*40;int firstRaw=ph.SectionHeaders.Min(s=>s.PointerToRawData);R(newHeader+40<=firstRaw&&input[newHeader..(newHeader+40)].All(b=>b==0),"Section header capacity");int raw=Align(input.Length,opt.FileAlignment),va=Align(ph.SectionHeaders.Max(s=>s.VirtualAddress+Math.Max(s.VirtualSize,s.SizeOfRawData)),opt.SectionAlignment),rawSize=Align(meta.Length,opt.FileAlignment);var output=new byte[raw+rawSize];input.CopyTo(output,0);meta.CopyTo(output,raw);Encoding.ASCII.GetBytes(".n29meta").CopyTo(output,newHeader);BitConverter.GetBytes(meta.Length).CopyTo(output,newHeader+8);BitConverter.GetBytes(va).CopyTo(output,newHeader+12);BitConverter.GetBytes(rawSize).CopyTo(output,newHeader+16);BitConverter.GetBytes(raw).CopyTo(output,newHeader+20);BitConverter.GetBytes(0x40000040).CopyTo(output,newHeader+36);
  BitConverter.GetBytes((ushort)(ph.CoffHeader.NumberOfSections+1)).CopyTo(output,ph.CoffHeaderStartOffset+2);BitConverter.GetBytes(opt.SizeOfInitializedData+rawSize).CopyTo(output,ph.PEHeaderStartOffset+8);BitConverter.GetBytes(Align(va+meta.Length,opt.SectionAlignment)).CopyTo(output,ph.PEHeaderStartOffset+56);new byte[4].CopyTo(output,ph.PEHeaderStartOffset+64);BitConverter.GetBytes(va).CopyTo(output,ph.CorHeaderStartOffset+8);BitConverter.GetBytes(meta.Length).CopyTo(output,ph.CorHeaderStartOffset+12);
  return(output,new{old_root_offset=rootOffset,old_root_size=rootSize,new_root_offset=raw,new_root_size=meta.Length,new_section_header=newHeader,new_section_va=va,added,table_sorted_bit_cleared=(sorted&(1UL<<10))!=0,existing_heaps_unchanged=true});
 }
 static void CopyTo(this byte[] b,List<byte> list,int p){for(int j=0;j<b.Length;j++)list[p+j]=b[j];}
 static int Main(string[] args){try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
 static void Run(string[] args){R(args.Length==3,"input new-output report");R(!File.Exists(args[1])&&!File.Exists(args[2]),"Fresh outputs required");byte[] before=File.ReadAllBytes(args[0]);R(H(before)=="02390a90a9ced312c67b4b8ff085b5329234920c8f6e03bb3a2cdb294d1be465","Pinned Native28 input");using var asm=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);var module=asm.MainModule;using var fs=File.OpenRead(args[0]);using var pe=new PEReader(fs);var(after,metadata)=Metadata(before,pe,module);int firstRef=0x0A000000+pe.GetMetadataReader().GetTableRowCount(TableIndex.MemberRef)+1;int invoke=firstRef,remove=firstRef+1,contains=firstRef+2;
  MD M(int t)=>(MD)module.LookupToken(t);FR F(MD m,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<FR>().FirstOrDefault(f=>f.Name==name) ?? module.GetMemberReferences().OfType<FR>().First(f=>f.Name==name && f.DeclaringType.FullName=="UnityEngine.Vector3");MR C(MD m,string name)=>m.Body.Instructions.Select(i=>i.Operand).OfType<MR>().First(c=>c.Name==name);var targets=new Dictionary<int,(byte[] code,int max)>();var report=new List<object>();
  void Set(int token,IL il,int max=4){targets.Add(token,(il.Done(),max));}
  var m=M(0x0600019B);var il=new IL();il.Arg(0).Ref(0x7B,F(m,"board")).O(0x14).Ref(0x28,module.GetMemberReferences().OfType<MR>().First(c=>c.FullName=="System.Boolean UnityEngine.Object::op_Equality(UnityEngine.Object,UnityEngine.Object)")).Branch(0x2D,"no");il.Arg(0).Arg(1).Ref(0x7B,F(m,"dialogueTriggerType").DeclaringType.FullName=="BoardDialogue"?F(m,"dialogueTriggerType"):throw new Exception());var outField=m.Body.Instructions.Select(i=>i.Operand).OfType<FR>().First(f=>f.Name=="dialogueTriggerType"&&f.DeclaringType.FullName=="DialogueManager_OnBoard");il.Ref(0x7D,outField);var inField=m.Body.Instructions.Select(i=>i.Operand).OfType<FR>().First(f=>f.DeclaringType.FullName=="BoardDialogue");il.Arg(1).Ref(0x7B,inField).O(0x25).Branch(0x2C,"zero").Int(1).Branch(0x33,"no").Arg(0).Ref(0x7B,F(m,"board")).Ref(0x7B,F(m,"gameStart")).O(0x2A).Label("zero").O(0x26).Int(1).O(0x2A).Label("no").Int(0).O(0x2A);Set(0x0600019B,il);
  foreach(int token in new[]{0x060008AA,0x060008AC,0x060008AE,0x060008B6,0x060008B7}){m=M(token);il=new IL();bool play=token is 0x060008AA or 0x060008AC or 0x060008AE;bool seq=token==0x060008B7;int prior=1;R(m.Body.Variables[prior].VariableType.FullName=="System.Boolean"||seq,"Saved boolean local");if(seq)prior=2;il.Arg(0).Branch(0x2D,"nonnull").Ref(0x73,C(m,".ctor").DeclaringType.FullName=="System.NullReferenceException"?C(m,".ctor"):throw new Exception()).O(0x7A).Label("nonnull");
   if(seq)il.Arg(0).Ref(0x7B,F(m,"_clip")).Ref(0x28,C(m,"op_Implicit")).Branch(0x2C,"afterseq").Arg(0).Ref(0x7B,F(m,"_clip")).Arg(1).Ref(0x6F,C(m,"set_sequence")).Label("afterseq");
   il.Arg(0).Ref(0x7B,F(m,"_isPlaying")).S(prior).L(prior).Branch(play?(byte)0x2D:(byte)0x2C,"skipwrite").Arg(0).Int(play?1:0).Ref(0x7D,F(m,"_isPlaying")).Arg(0).Float(0).Ref(0x7D,F(m,"_tickTimer")).Label("skipwrite");
   if(!seq)il.Arg(1).Branch(0x2C,"afterrewind");il.Arg(0).Ref(0x28,C(m,"Rewind"));if(!seq)il.Label("afterrewind");il.L(prior).Branch(play?(byte)0x2D:(byte)0x2C,"wait");var ev=F(m,play?"OnPlayStoppedEvent":"OnStopPlayingEvent");il.Arg(0).Ref(0x7B,ev).Branch(0x2C,"wait").Arg(0).Ref(0x7B,ev).Arg(0).Ref(0x6F,invoke).Label("wait");var ctor=m.Body.Instructions.Select(i=>i.Operand).OfType<MR>().Single(c=>c.Name==".ctor"&&c.DeclaringType.FullName.StartsWith("FTRuntime.Yields."));il.O(0x14).Ref(0x73,ctor).O(0x25).Arg(0).Ref(0x28,C(m,"Subscribe")).O(0x26,0x2A);Set(token,il);}
  m=M(0x0600082C);Set(0x0600082C,new IL().Arg(0).Ref(0x7B,F(m,"_tint")).O(0x2A));m=M(0x0600082D);Set(0x0600082D,new IL().Arg(0).Arg(1).Ref(0x7D,F(m,"_tint")).Arg(0).Ref(0x28,C(m,"UpdatePropBlock")).O(0x2A));
  m=M(0x060008A1);R(m.Body.InitLocals,"Default settings needs initialized local");var settings=module.Types.Single(t=>t.FullName=="FTRuntime.SwfSettingsData");il=new IL();foreach(var f in settings.Fields.Where(f=>!f.IsStatic)){il.A(0);if(f.Name=="PixelsPerUnit")il.Float(100);else il.Int(f.Name switch{"MaxAtlasSize"=>2048,"AtlasPadding"=>1,"BitmapTrimming"=>1,"GenerateMipMaps"=>0,"AtlasPowerOfTwo"=>1,"AtlasForceSquare"=>1,"AtlasTextureFilter"=>1,"AtlasTextureFormat"=>2,_=>throw new Exception("Unknown settings field")});il.Ref(0x7D,f);}il.L(0).O(0x2A);Set(0x060008A1,il);
  m=M(0x060008A3);Set(0x060008A3,new IL().Arg(0).Ref(0x28,M(0x060008A1)).Ref(0x7D,F(m,"Settings")).O(0x2A));m=M(0x06000820);var byteType=m.Body.Instructions.Single(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Newarr).Operand as Mono.Cecil.TypeReference;il=new IL().Arg(0).Int(0).Ref(0x8D,byteType!).Ref(0x7D,F(m,"Data")).Arg(0).Ref(0x7E,F(m,"Empty")).Ref(0x7D,F(m,"Hash")).Arg(0).O(0x14).Ref(0x7D,F(m,"Atlas")).Arg(0).Ref(0x28,M(0x060008A1)).Ref(0x7D,F(m,"Settings")).Arg(0).Ref(0x28,M(0x060008A1)).Ref(0x7D,F(m,"Overridden")).O(0x2A);Set(0x06000820,il);
  foreach(int token in new[]{0x06000160,0x06000161,0x06000162,0x0600015D,0x0600015E,0x0600015F}){m=M(token);bool direct=token>=0x06000160;int local=direct?-1:1;il=new IL();if(!direct){R(m.Body.Variables[local].VariableType.FullName=="UnityEngine.Vector3","Position local");il.Arg(0).Arg(1).Arg(2).Ref(0x28,C(m,"GetGridPosition")).S(local);}foreach(var(name,k)in new[]{("x",57f),("y",token is 0x06000162 or 0x0600015E?28f:44f)}){if(direct)il.O(0x0F,1);else il.A(local);il.O(0x25).Ref(0x7B,F(m,name)).Float(k).O(0x58).Ref(0x7D,F(m,name));}if(direct)il.Arg(1);else il.L(local);il.O(0x2A);Set(token,il);}
  Set(0x060000DF,new IL().Arg(1).O(0x2A));
  // These eight call sites preserve their original CFG and helper order. Only the native-pinned argument producer changes.
  foreach(var(token,offset,local,arg)in new[]{(0x0600013C,18,-1,1),(0x060000A8,37,3,-1),(0x060000AF,37,3,-1),(0x060000BB,55,4,-1),(0x060002C6,55,3,-1),(0x0600046C,55,3,-1),(0x060006D3,45,4,-1),(0x06000203,30,-1,2)}){m=M(token);var i=m.Body.Instructions.Single(i=>i.Offset==offset);R(i.OpCode==Mono.Cecil.Cil.OpCodes.Ldloca&&i.GetSize()==4,"Argument site shape");var sec=pe.PEHeaders.SectionHeaders.Single(s=>m.RVA>=s.VirtualAddress&&m.RVA<s.VirtualAddress+s.SizeOfRawData);int h=sec.PointerToRawData+m.RVA-sec.VirtualAddress;int hs=(BitConverter.ToUInt16(before,h)>>12)*4;R(hs==12,"Fat site header");byte[] code=before[(h+hs)..(h+hs+m.Body.CodeSize)];code[offset]=0xFE;code[offset+1]=(byte)(local>=0?0x0C:0x09);BitConverter.GetBytes((ushort)(local>=0?local:arg)).CopyTo(code,offset+2);foreach(var call in m.Body.Instructions.Where(q=>q.OpCode==Mono.Cecil.Cil.OpCodes.Call && q.Operand is MR cc && (cc.Name=="get_transform" || cc.Name=="get_position" || cc.Name=="SetEndPosition"))){R(code[call.Offset]==0x28,"Native physical call guard site");code[call.Offset]=0x6F;}targets.Add(token,(code,m.Body.MaxStackSize));}
  foreach(int token in new[]{0x0600088B,0x0600088C,0x0600088D,0x0600088E,0x0600088F}){m=M(token);il=new IL();if(token==0x0600088B||token==0x0600088E)il.Arg(1).Ref(0x28,C(m,"IsNullOrEmpty")).Branch(0x2D,"ret");if(token==0x0600088E){il.Arg(0).Ref(0x7B,F(m,"_groupUnscales")).Arg(1).Arg(2).Branch(0x2D,"add").Ref(0x6F,remove).Branch(0x2B,"discard").Label("add").Ref(0x6F,C(m,"Add")).Label("discard").O(0x26).Label("ret").O(0x2A);}else {il.Arg(0).Ref(0x7B,F(m,token==0x0600088F?"_groupUnscales":"_groupPauses")).Arg(1).Ref(0x6F,token==0x0600088B?remove:contains);if(token==0x0600088B)il.O(0x26).Label("ret");if(token==0x0600088D)il.Int(0).O(0xFE,0x01);il.O(0x2A);}Set(token,il);}
  foreach(var(token,(code,max))in targets){m=M(token);R(m.Body.ExceptionHandlers.Count==0,"EH relocation unsupported");var sec=pe.PEHeaders.SectionHeaders.Single(s=>m.RVA>=s.VirtualAddress&&m.RVA<s.VirtualAddress+s.SizeOfRawData);int h=sec.PointerToRawData+m.RVA-sec.VirtualAddress;int hs=(BitConverter.ToUInt16(before,h)>>12)*4;R((before[h]&3)==3&&hs==12,"Pinned fat body");R(code.Length<=m.Body.CodeSize,"Body exceeds reserved slot "+m.FullName+" "+code.Length+" > "+m.Body.CodeSize);Array.Clear(after,h+hs,m.Body.CodeSize);code.CopyTo(after,h+hs);BitConverter.GetBytes(code.Length).CopyTo(after,h+4);BitConverter.GetBytes((ushort)max).CopyTo(after,h+2);report.Add(new{token=$"0x{token:X8}",method=m.FullName,header=h,code_start=h+hs,reserved_code_size=m.Body.CodeSize,new_code_size=code.Length,old_max=m.Body.MaxStackSize,new_max=max,local_sig=m.Body.LocalVarToken.ToInt32(),code_sha256=H(code)});}
  R(targets.Count==31,"Pinned scope 31");File.WriteAllBytes(args[1],after);File.WriteAllText(args[2],JsonSerializer.Serialize(new{input_sha256=H(before),candidate_sha256=H(after),metadata,methods=report,scope="31 native-pinned methods; existing metadata rows/heaps and method RVAs preserved; three appended closed MemberRefs"},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine("CANDIDATE "+H(after));
 }
}
