using System;
using System.Collections.Generic;
namespace UnityEngine {
 public class Object { public bool destroyed; public static bool operator ==(Object a,Object b){bool na=ReferenceEquals(a,null)||(!ReferenceEquals(a,null)&&a.destroyed);bool nb=ReferenceEquals(b,null)||(!ReferenceEquals(b,null)&&b.destroyed);return na&&nb||!na&&!nb&&ReferenceEquals(a,b);}public static bool operator !=(Object a,Object b){return !(a==b);}public static implicit operator bool(Object a){return a!=null;}public override bool Equals(object b){return ReferenceEquals(this,b);}public override int GetHashCode(){return base.GetHashCode();} }
 public class GameObject:Object {public bool active=true;public bool activeSelf {get{return active;}}}
 public class Component:Object {public GameObject go=new GameObject(); public GameObject gameObject{get{return go;}}}
 public class Behaviour:Component{} public class MonoBehaviour:Behaviour{}
 public struct Vector3 {public float x,y,z;}
}
public enum ChallengeType {None=-1,Adventure=0,Rescue=1,HardAdventure=2,Branch=3}
public enum BoardEntryType {Zero=0,Point=1}
public class BoardEntry {public bool must,select;public BoardEntryType boardEntryType;public float value;public float GetValue(){return value;}}
public class BoardConfig {public List<BoardEntry> boardEntries;}
public class Save {public int adventureLevel;public int[] rescuePassNum,adventureHardMaxStarNum;public bool[] adventureHardPassed;}
public class SavesManager {public Save playerSave;public void PassLevel(ChallengeType t,int level,BoardConfig config){throw new Exception("UNPATCHED");}}
public class Zombie:UnityEngine.MonoBehaviour {public float fX,fY,fW=2,fD=2,fH=2;public bool attackable=true;public int attackCalls;public bool CanAttacked(){attackCalls++;return attackable;}}
public class ZombieManager {public List<Zombie> zombieList;}
public class Board {public ZombieManager zombieManager;}
public class BoardPreview:UnityEngine.MonoBehaviour {public List<Zombie> enemyPreviews;}
public class PrepareUIController {public BoardPreview boardPreview;public static PrepareUIController instance;public static PrepareUIController Instance {get{return instance;}}}
public class MouseManager {public bool onBoard;public Board board;public UnityEngine.Vector3 mouseWorldPosition;public Zombie GetZombieUnderMouse(int plantID){throw new Exception("UNPATCHED");}}
public class ZombieInfo {public int id,enemyPoint,minWave;public float enemyWeight;public bool isElite,isBoss;public bool[] enemyRequirements;}
public class ZombieSelect {public int id,point,minFlag,minWave;public float weight;public bool exist,elite;public bool[] requirements;public ZombieSelect(ZombieInfo info){throw new Exception("UNPATCHED");}}
public class EnemySelecter {public List<ZombieSelect> zombieSelects=new List<ZombieSelect>();public int enemyPoint_Base;public Board board;public EnemyManager enemyManager;}
public class ResourceManager {public static List<ZombieInfo> infos;public static List<ZombieInfo> Load_zombieInfo_all(){return infos;}}
public class EnemyManager {public Board board;public int enemyPoint_Base;public List<BoardEntry> boardEntries;public List<int> zombieTypes;public EnemySelecter CreateEnemySelecter(){throw new Exception("UNPATCHED");}}
class Harness {
 static int n;
 static void A(bool c,string s){if(!c)throw new Exception("FAIL "+s);n++;Console.WriteLine("PASS "+s);}
 static void Throws<T>(Action a,string s) where T:Exception {try{a();}catch(T){A(true,s);return;}throw new Exception("did not throw "+s);}
 static ZombieInfo Info(int n){return new ZombieInfo{id=n,enemyPoint=10+n,enemyWeight=.5f+n,minWave=3+n,enemyRequirements=new bool[]{true,false,true,false,true,false,true,false,true,false}};}
 public static void Main(){
  var info=Info(2);info.isBoss=true;var zs=new ZombieSelect(info);A(zs.id==2&&zs.point==12&&zs.weight==2.5f&&zs.minWave==5&&zs.minFlag==0&&!zs.exist&&zs.elite,"constructor scalar fields");A(zs.requirements.Length==10&&!ReferenceEquals(zs.requirements,info.enemyRequirements)&&zs.requirements[8]&&!zs.requirements[9],"constructor copies ten bools");info.enemyRequirements[0]=false;A(zs.requirements[0],"constructor does not alias array");Throws<NullReferenceException>(()=>new ZombieSelect(null),"constructor null info throws");var shortInfo=Info(1);shortInfo.enemyRequirements=new bool[9];Throws<IndexOutOfRangeException>(()=>new ZombieSelect(shortInfo),"constructor short array throws");
  var sm=new SavesManager{playerSave=new Save{adventureLevel=180,rescuePassNum=new int[3],adventureHardMaxStarNum=new int[3],adventureHardPassed=new bool[3]}};sm.PassLevel(ChallengeType.Adventure,-99,null);A(sm.playerSave.adventureLevel==181,"adventure increments 180 to 181");sm.PassLevel(ChallengeType.Adventure,0,null);A(sm.playerSave.adventureLevel==181,"adventure stops above 180");sm.PassLevel(ChallengeType.Rescue,2,null);A(sm.playerSave.rescuePassNum[2]==1,"rescue increments indexed counter");
  var config=new BoardConfig{boardEntries=new List<BoardEntry>{new BoardEntry{must=true,select=true},new BoardEntry{select=true},new BoardEntry{select=false},new BoardEntry{select=true}}};sm.PassLevel(ChallengeType.HardAdventure,1,config);A(sm.playerSave.adventureHardMaxStarNum[1]==2&&sm.playerSave.adventureHardPassed[1],"hard counts only optional selected entries");sm.playerSave.adventureHardMaxStarNum[1]=5;sm.PassLevel(ChallengeType.HardAdventure,1,config);A(sm.playerSave.adventureHardMaxStarNum[1]==5,"hard maximum never decreases");sm.playerSave=null;sm.PassLevel((ChallengeType)77,-1,null);A(true,"unhandled challenge has no dereferences");Throws<NullReferenceException>(()=>sm.PassLevel(ChallengeType.Adventure,0,null),"adventure null save throws");sm.playerSave=new Save{rescuePassNum=new int[1]};Throws<IndexOutOfRangeException>(()=>sm.PassLevel(ChallengeType.Rescue,-1,null),"rescue negative index throws");Throws<NullReferenceException>(()=>sm.PassLevel(ChallengeType.HardAdventure,0,null),"hard null config throws");
  var z1=new Zombie();var z2=new Zombie();var inactive=new Zombie();inactive.go.active=false;var destroyed=new Zombie{destroyed=true};var mouse=new MouseManager{onBoard=true,board=new Board{zombieManager=new ZombieManager{zombieList=new List<Zombie>{null,destroyed,inactive,z1,z2}}}};A(ReferenceEquals(mouse.GetZombieUnderMouse(0),z2),"mouse returns LAST eligible overlap");z2.attackable=false;A(ReferenceEquals(mouse.GetZombieUnderMouse(0),z1),"plantID zero applies CanAttacked");A(ReferenceEquals(mouse.GetZombieUnderMouse(1),z2),"nonzero plantID bypasses CanAttacked");A(inactive.attackCalls==0&&destroyed.attackCalls==0,"inactive and destroyed skipped before attack filter");mouse.mouseWorldPosition.x=1;A(ReferenceEquals(mouse.GetZombieUnderMouse(1),z2),"right boundary inclusive");mouse.mouseWorldPosition.x=1.001f;A(mouse.GetZombieUnderMouse(1)==null,"outside right boundary rejected");mouse.mouseWorldPosition.x=float.NaN;A(ReferenceEquals(mouse.GetZombieUnderMouse(1),z2),"NaN follows native ordered comparisons");mouse.board=null;Throws<NullReferenceException>(()=>mouse.GetZombieUnderMouse(1),"board null preserves exception");
  mouse.onBoard=false;mouse.mouseWorldPosition.x=0;PrepareUIController.instance=new PrepareUIController();A(mouse.GetZombieUnderMouse(0)==null,"missing preview returns null through Unity bool");PrepareUIController.instance.boardPreview=new BoardPreview{enemyPreviews=new List<Zombie>{z2}};int calls=z2.attackCalls;A(ReferenceEquals(mouse.GetZombieUnderMouse(0),z2)&&z2.attackCalls==calls,"preview skips CanAttacked even plantID zero");PrepareUIController.instance=null;Throws<NullReferenceException>(()=>mouse.GetZombieUnderMouse(1),"preview null singleton throws");
  ResourceManager.infos=new List<ZombieInfo>{Info(0),Info(1),Info(2)};var manager=new EnemyManager{board=new Board(),enemyPoint_Base=101,boardEntries=new List<BoardEntry>{new BoardEntry{boardEntryType=BoardEntryType.Point,value=.5f},new BoardEntry{boardEntryType=BoardEntryType.Zero,value=99}},zombieTypes=new List<int>{2,0}};var es=manager.CreateEnemySelecter();A(ReferenceEquals(es.board,manager.board)&&ReferenceEquals(es.enemyManager,manager),"selector owner links");A(es.enemyPoint_Base==151,"selector base times additive multiplier truncates");A(es.zombieSelects.Count==2&&es.zombieSelects[0].id==0&&es.zombieSelects[1].id==2&&es.zombieSelects.TrueForAll(z=>z.exist),"selector flags and filters preserves source order");manager.zombieTypes=new List<int>();A(manager.CreateEnemySelecter().zombieSelects.Count==0,"empty selection removes all");manager.zombieTypes=new List<int>{99};Throws<ArgumentOutOfRangeException>(()=>manager.CreateEnemySelecter(),"invalid selection index throws");manager.zombieTypes=new List<int>{0};manager.boardEntries=null;Throws<NullReferenceException>(()=>manager.CreateEnemySelecter(),"null boardEntries throws");
  Console.WriteLine("NATIVE3_CLR_HARNESS_PASS assertions="+n);
 }
}
