using Mono.Cecil;
using Mono.Cecil.Cil;
using System.Buffers.Binary;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
static class RepairNative26 {
 static void R(bool b,string s){if(!b)throw new InvalidOperationException(s);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static int Main(string[] a){try{Run(a);return 0;}catch(Exception e){Console.Error.WriteLine("REJECT: "+e.Message);return 3;}}
 static void Run(string[] a){
  R(a.Length==3,"usage input new-output report");var input=Path.GetFullPath(a[0]);var output=Path.GetFullPath(a[1]);R(input!=output&&!File.Exists(output),"New distinct output required");var before=File.ReadAllBytes(input);R(H(before)=="9cbf08472d6c22f1b68393656ac2d36576fd6b21d49c4738f80aec2e2cbe749a","Native25 input hash mismatch");using var asm=AssemblyDefinition.ReadAssembly(input);var module=asm.MainModule;var type=module.Types.Single(t=>t.FullName=="AttackRange");var m=type.Methods.Single(m=>m.MetadataToken.ToUInt32()==0x060000D9);var donor=type.Methods.Single(m=>m.MetadataToken.ToUInt32()==0x060000D8);
  R(m.FullName=="System.Boolean AttackRange::TestInRange_Device(Device)"&&m.Body.CodeSize==348&&m.Body.ExceptionHandlers.Count==0,"Target shape mismatch");
  var expected=new[]{"Device","Plant","Projectile","Zombie","UnityEngine.Rect","UnityEngine.Vector3","System.Single","System.Single","System.Single","System.Single","System.Single","System.Single","System.Single","RangeType"};R(donor.Body.Variables.Select(v=>v.VariableType.FullName).SequenceEqual(expected)&&donor.Body.Variables.All(v=>!v.VariableType.ContainsGenericParameter),"Local signature is not closed and pinned");
  using var fs=File.OpenRead(input);using var pe=new PEReader(fs);int Header(MethodDefinition d){var s=pe.PEHeaders.SectionHeaders.Single(s=>d.RVA>=s.VirtualAddress&&d.RVA<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+d.RVA-s.VirtualAddress;}
  var header=Header(m);var hsize=(BinaryPrimitives.ReadUInt16LittleEndian(before.AsSpan(header,2))>>12)*4;R(hsize==12&&(before[header]&3)==3,"Expected fat header");var sig=BinaryPrimitives.ReadUInt32LittleEndian(before.AsSpan(Header(donor)+8,4));R(sig==0x110000AB,"Donor StandaloneSig mismatch");var start=header+hsize;
  FieldReference F(uint tok,string name){var f=(FieldReference)module.LookupToken((int)tok);R(f.FullName==name,"Field mismatch "+name);return f;}
  MethodReference M(uint tok,string name){var c=(MethodReference)module.LookupToken((int)tok);R(c.FullName==name,"Call mismatch "+name);return c;}
  var fw=F(0x0400046A,"System.Single Device::fW");var fd=F(0x0400046B,"System.Single Device::fD");var fx=F(0x04000466,"System.Single Device::fX");var fy=F(0x04000467,"System.Single Device::fY");var range=F(0x040000E2,"RangeType AttackRange::rangeType");
  var rect=M(0x0A00009B,"System.Void UnityEngine.Rect::.ctor(System.Single,System.Single,System.Single,System.Single)");var vector=M(0x0A00009C,"System.Void UnityEngine.Vector3::.ctor(System.Single,System.Single,System.Single)");var rectTest=M(0x060000D7,"System.Boolean AttackRange::TestInRects_Rect(UnityEngine.Rect)");var circleTest=M(0x060000D4,"System.Boolean AttackRange::TestInCircles_Position(UnityEngine.Vector3)");var nre=M(0x0A000022,"System.Void System.NullReferenceException::.ctor()");
  var code=new List<byte>();var labels=new Dictionary<string,int>();var fixups=new List<(int Offset,int Base,string Target)>();void O(byte op)=>code.Add(op);void U(uint n)=>code.AddRange(BitConverter.GetBytes(n));void T(byte op,IMetadataTokenProvider v){O(op);U(v.MetadataToken.ToUInt32());}void C(float n){O(0x22);code.AddRange(BitConverter.GetBytes(n));}void L(int i){O(0x11);O((byte)i);}void S(int i){O(0x13);O((byte)i);}void Label(string s)=>labels.Add(s,code.Count);void Branch(byte op,string target){O(op);var pos=code.Count;U(0);fixups.Add((pos,pos+4,target));}void Field(FieldReference f){O(0x03);T(0x7b,f);}void RectCall(){O(0x02);L(7);L(8);L(9);L(10);T(0x73,rect);T(0x28,rectTest);}void CircleCall(){O(0x02);L(11);L(12);C(0);T(0x73,vector);T(0x28,circleTest);}
  // Null Device is tested before any AttackRange or Device field access.
  O(0x03);Branch(0x3a,"snapshot");T(0x73,nre);O(0x7a);Label("snapshot");
  // Preserve native field read order and float32 rounding; capture both shapes before callbacks.
  Field(fw);C(.5f);O(0x5a);S(6);O(0x02);T(0x7b,range);S(13);Field(fx);S(7);Field(fy);S(8);Field(fw);S(9);L(7);L(6);O(0x59);S(7);Field(fd);C(.5f);O(0x5a);S(10);Field(fx);S(11);L(8);L(10);O(0x59);S(8);Field(fd);S(10);Field(fy);S(12);
  L(13);O(0x45);U(5);var positions=new List<(int,string)>();foreach(var s in new[]{"false","rect","circle","both","true"}){positions.Add((code.Count,s));U(0);}var switchBase=code.Count;foreach(var (pos,s) in positions)fixups.Add((pos,switchBase,s));
  Label("false");O(0x16);O(0x2a);Label("true");O(0x17);O(0x2a);Label("both");RectCall();Branch(0x3a,"true");Label("circle");CircleCall();O(0x2a);Label("rect");RectCall();O(0x2a);
  var live=code.ToArray();foreach(var (pos,b,s) in fixups)BitConverter.GetBytes(labels[s]-b).CopyTo(live,pos);R(live.Length<=348,"Reserved slot overflow");
  var after=(byte[])before.Clone();Array.Clear(after,start,348);live.CopyTo(after,start);BinaryPrimitives.WriteUInt16LittleEndian(after.AsSpan(header+2,2),5);BinaryPrimitives.WriteUInt32LittleEndian(after.AsSpan(header+4,4),(uint)live.Length);BinaryPrimitives.WriteUInt32LittleEndian(after.AsSpan(header+8,4),sig);var changed=Enumerable.Range(0,before.Length).Where(i=>before[i]!=after[i]).ToArray();R(changed.All(i=>i>=start&&i<start+348||i>=header+2&&i<header+12),"Target boundary violation");
  var tmp=output+".tmp";R(!File.Exists(tmp),"Temporary output exists");File.WriteAllBytes(tmp,after);using(var reopened=AssemblyDefinition.ReadAssembly(tmp)){var target=(MethodDefinition)reopened.MainModule.LookupToken(0x060000D9);R(target.Body.Variables.Select(v=>v.VariableType.FullName).SequenceEqual(expected)&&target.Body.CodeSize==live.Length&&target.Body.MaxStackSize==5,"Reopened shape mismatch");var set=target.Body.Instructions.ToHashSet();foreach(var i in set){if(i.Operand is Instruction jump)R(set.Contains(jump),"Branch target outside body");if(i.Operand is Instruction[] jumps)R(jumps.All(set.Contains),"Switch target outside body");}}
  File.Move(tmp,output);var report=new{input_sha256=H(before),candidate_sha256=H(after),token="0x060000D9",code_size=live.Length,max_stack=5,local_sig=$"0x{sig:X8}",header,start,reserved_slot=348,changed_bytes=changed.Length,positions=changed,labels,metadata_unchanged=true,scope="Native call contract; original helper bodies still damaged"};File.WriteAllText(a[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(report));
 }
}
