using Mono.Cecil;using RO=System.Reflection.Emit.OpCodes;using System.Reflection;using System.Reflection.Emit;using System.Text.Json;using System.Security.Cryptography;using Color=UnityEngine.Color;
public class DependencyException:Exception{}
public class MonoBehaviour {public MonoBehaviour(bool fixtureInput){}public MonoBehaviour(){State.calls++;State.receiver=this;State.snapshot=this is SwfClip s?(s._dirtyMesh,s._sortingLayer,s._sequence,s._tint):null;if(State.failBase)throw new DependencyException();}}
public class SwfClip:MonoBehaviour {public bool _dirtyMesh;public string? _sortingLayer,_sequence;public Color _tint;public int marker;public float untouched;public SwfClip(bool fixtureInput):base(fixtureInput){}}
public static class State {public static int calls;public static object?receiver;public static(bool Dirty,string?Sorting,string?Sequence,Color Tint)?snapshot;public static bool failBase;public static void Reset(){calls=0;receiver=null;snapshot=null;failBase=false;}}
public static class Fixture {
 static Dictionary<string,Type>map=new(){["FTRuntime.SwfClip"]=typeof(SwfClip),["UnityEngine.MonoBehaviour"]=typeof(MonoBehaviour),["UnityEngine.Color"]=typeof(Color),["System.String"]=typeof(string),["System.Single"]=typeof(float),["System.Boolean"]=typeof(bool),["System.IntPtr"]=typeof(IntPtr),["System.Void"]=typeof(void)};
 static Type T(TypeReference t)=>map.TryGetValue(t.FullName,out var type)?type:throw new Exception("Unmapped "+t.FullName);
 static Action<SwfClip?>Emit(MethodDefinition m,string mutation){var dm=new DynamicMethod(m.Name+mutation,typeof(void),new[]{typeof(SwfClip)},typeof(Fixture).Module,false){InitLocals=m.Body.InitLocals};var il=dm.GetILGenerator();var locals=m.Body.Variables.Select(v=>il.DeclareLocal(T(v.VariableType))).ToArray();var ops=typeof(RO).GetFields().Where(f=>f.FieldType==typeof(System.Reflection.Emit.OpCode)).Select(f=>(System.Reflection.Emit.OpCode)f.GetValue(null)!).ToDictionary(o=>o.Value);bool changed=false;int floatIndex=0;
  if(mutation=="illegal_stack"){il.Emit(RO.Pop);changed=true;}if(mutation=="return_early"){il.Emit(RO.Ret);changed=true;}
  foreach(var i in m.Body.Instructions){var op=ops[i.OpCode.Value];var a=i.Operand;
   if(mutation=="dirty_false"&&op==RO.Ldc_I4_1){il.Emit(RO.Ldc_I4_0);changed=true;continue;}
   if(op==RO.Ldc_R4){float value=(float)a;if(mutation=="alpha_zero"&&floatIndex==3){value=0;changed=true;}floatIndex++;il.Emit(op,value);continue;}
   if(a is MethodReference mr){if(mutation=="missing_base"&&mr.DeclaringType.FullName=="UnityEngine.MonoBehaviour"){il.Emit(RO.Pop);changed=true;continue;}var ctor=T(mr.DeclaringType).GetConstructor(mr.Parameters.Select(p=>T(p.ParameterType)).ToArray())??throw new Exception("Missing ctor "+mr);il.Emit(op,ctor);continue;}
   if(a is FieldReference f){if(mutation=="missing_tint"&&op==RO.Stfld&&f.Name=="_tint"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}if(mutation=="missing_sequence"&&op==RO.Stfld&&f.Name=="_sequence"){il.Emit(RO.Pop);il.Emit(RO.Pop);changed=true;continue;}il.Emit(op,T(f.DeclaringType).GetField(f.Name,BindingFlags.Public|BindingFlags.Instance|BindingFlags.Static)!);continue;}
   if(a is Mono.Cecil.Cil.VariableDefinition v){il.Emit(op,locals[v.Index]);continue;}if(a is int iv){il.Emit(op,iv);continue;}if(a==null){il.Emit(op);continue;}throw new Exception("Operand "+a);
  }if(mutation!="none"&&!changed)throw new Exception("Mutation not applied");return(Action<SwfClip?>)dm.CreateDelegate(typeof(Action<SwfClip>));
 }
 static uint[]Bits(Color c)=>new[]{(uint)BitConverter.SingleToInt32Bits(c.r),(uint)BitConverter.SingleToInt32Bits(c.g),(uint)BitConverter.SingleToInt32Bits(c.b),(uint)BitConverter.SingleToInt32Bits(c.a)};
 record Result(int Cases,List<string>Failures);
 static Result Cases(Action<SwfClip?>fn,List<uint[]>rows,bool stop=false){int cases=0,index=0;var failures=new List<string>();void Check(bool pass,string message){cases++;if(!pass)failures.Add(message);}var rng=new Random(43);float Float()=>BitConverter.Int32BitsToSingle((int)rng.NextInt64(int.MinValue,(long)int.MaxValue+1));
  foreach(var row in rows){var clip=new SwfClip(true){_dirtyMesh=rng.Next(2)!=0,_sortingLayer="old layer",_sequence="old sequence",_tint=new Color(Float(),Float(),Float(),Float()),marker=rng.Next(),untouched=Float()};int marker=clip.marker;int untouched=BitConverter.SingleToInt32Bits(clip.untouched);State.Reset();bool match=false;try{fn(clip);match=row[0]==2&&row.Skip(1).Take(7).All(v=>v==1)&&clip._dirtyMesh&&ReferenceEquals(clip._sortingLayer,string.Empty)&&ReferenceEquals(clip._sequence,string.Empty)&&Bits(clip._tint).SequenceEqual(row.Skip(8))&&State.calls==1&&ReferenceEquals(State.receiver,clip)&&State.snapshot is{}snapshot&&snapshot.Dirty&&ReferenceEquals(snapshot.Sorting,string.Empty)&&ReferenceEquals(snapshot.Sequence,string.Empty)&&Bits(snapshot.Tint).SequenceEqual(row.Skip(8))&&clip.marker==marker&&BitConverter.SingleToInt32Bits(clip.untouched)==untouched;}catch(Exception e)when(e is not InvalidProgramException){match=false;}Check(match,"row:"+index++);if(stop&&failures.Count>0)return new(cases,failures);}
  State.Reset();bool npe=false;try{fn(null);}catch(NullReferenceException){npe=true;}Check(npe&&State.calls==0,"null-this-before-base");
  var beforeThrow=new SwfClip(true){_sortingLayer="old",_sequence="old",marker=123,_tint=new Color(0,0,0,0)};State.Reset();State.failBase=true;bool thrown=false;try{fn(beforeThrow);}catch(DependencyException){thrown=true;}Check(thrown&&State.calls==1&&State.snapshot is{}snap&&snap.Dirty&&ReferenceEquals(snap.Sorting,string.Empty)&&ReferenceEquals(snap.Sequence,string.Empty)&&Bits(snap.Tint).All(v=>v==0x3f800000)&&beforeThrow.marker==123,"writes-before-base-exception");return new(cases,failures);
 }
 public static int Main(string[]args){try{using var a=AssemblyDefinition.ReadAssembly(args[0]);var m=(MethodDefinition)a.MainModule.LookupToken(0x0600084F);var rows=File.ReadLines(args[1]).Select(l=>l.Split(' ')).ToArray();if(rows.Any(r=>r[0]!="0x0600084F"))throw new Exception("Scope");var values=rows.Select(r=>r.Skip(1).Select(uint.Parse).ToArray()).ToList();var result=Cases(Emit(m,"none"),values);int errors=0;bool controlsPass=true;var controls=new List<object>();foreach(string mutation in args.Length>3?Array.Empty<string>():new[]{"illegal_stack","return_early","dirty_false","alpha_zero","missing_base","missing_tint","missing_sequence"}){bool detected=false;string?error=null;try{detected=Cases(Emit(m,mutation),values,true).Failures.Count>0;}catch(InvalidProgramException){detected=true;}catch(Exception e){error=e.ToString();errors++;}controlsPass&=detected&&error==null;controls.Add(new{mutation,detected,tool_error=error});}bool pass=result.Failures.Count==0&&errors==0&&controlsPass;var report=new{candidate_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))).ToLowerInvariant(),methods=1,positive_cases=result.Cases,positive_failures=result.Failures.Count,negative_controls=controls.Count,tool_errors=errors,gate_pass=pass,unity_core_sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(typeof(Color).Assembly.Location))).ToLowerInvariant(),scope="Unchanged native ctor with inline Color constant, supplied String.Empty/class and recorded GC/base ctor dependencies. Actual candidate ctor body and real pure CoreModule Color(float,float,float,float) execute under CLR/public fake base ctor. Exact state-before-base, other-field preservation, null/base-throw order tested. No original Unity/GC/startup engine, game/iOS or device acceptance",failures=result.Failures,controls};File.WriteAllText(args[2],JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.positive_cases,report.positive_failures,report.negative_controls,report.tool_errors,report.gate_pass}));return pass?0:2;}catch(Exception e){Console.Error.WriteLine(e);return 3;}}
}
