using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text;
using Mono.Cecil;
static class AuditNative35 {
 static void R(bool b,string s){if(!b)throw new Exception(s);}
 static string H(byte[] b)=>Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant();
 static byte[] Root(PEReader p)=>p.GetMetadata().GetContent().ToArray();
 static int Offset(PEReader p,int rva){var s=p.PEHeaders.SectionHeaders.Single(s=>rva>=s.VirtualAddress&&rva<s.VirtualAddress+s.SizeOfRawData);return s.PointerToRawData+rva-s.VirtualAddress;}
 static (int Offset,int Size) StreamInfo(byte[] r,string name){int v=BitConverter.ToInt32(r,12),p=((16+v+3)/4)*4+2,count=BitConverter.ToUInt16(r,p);p+=2;for(int i=0;i<count;i++){int e=Array.IndexOf(r,(byte)0,p+8);if(Encoding.ASCII.GetString(r,p+8,e-p-8)==name)return(BitConverter.ToInt32(r,p),BitConverter.ToInt32(r,p+4));p=((e+1+3)/4)*4;}throw new Exception("Missing stream "+name);}
 static int Main(string[] args){try{var b=File.ReadAllBytes(args[0]);var c=File.ReadAllBytes(args[1]);R(H(b)=="a900440ee29c135761e0b5bdd7c3eace315d344769de945ff94c0438eba43e4d","Pinned parent");using var pb=new PEReader(new MemoryStream(b));using var pc=new PEReader(new MemoryStream(c));var mb=pb.GetMetadataReader();var mc=pc.GetMetadataReader();var rb=Root(pb);var rc=Root(pc);using var ab=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[0]);using var ac=Mono.Cecil.AssemblyDefinition.ReadAssembly(args[1]);var report=JsonDocument.Parse(File.ReadAllText(args[2]));var targets=report.RootElement.GetProperty("methods").EnumerateArray().Select(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)).ToHashSet();R(targets.SetEquals(new[]{0x0600090C,0x0600073A,0x0600073B,0x0600073C}),"Target cardinality");var allowed=new HashSet<int>();void Allow(int p,int n){for(int j=0;j<n;j++)allowed.Add(p+j);}var tableRows=new List<object>();
  foreach(TableIndex t in Enum.GetValues<TableIndex>()){int n=mb.GetTableRowCount(t);int delta=t==TableIndex.MemberRef?3:0;R(mc.GetTableRowCount(t)==n+delta,"Table count "+t);if(n==0)continue;int size=mb.GetTableRowSize(t);R(size==mc.GetTableRowSize(t),"Row width "+t);int x=mb.GetTableMetadataOffset(t),y=mc.GetTableMetadataOffset(t);R(rb[x..(x+n*size)].SequenceEqual(rc[y..(y+n*size)]),"Existing row drift "+t);tableRows.Add(new{table=t.ToString(),rows=n,row_size=size});}
  var sb=StreamInfo(rb,"#Strings");var sc=StreamInfo(rc,"#Strings");byte[] oldStrings=rb[sb.Offset..(sb.Offset+sb.Size)];byte[] lengthName=Encoding.UTF8.GetBytes("get_Length\0");bool nameExists=Enumerable.Range(0,Math.Max(0,oldStrings.Length-lengthName.Length+1)).Any(i=>oldStrings[i..(i+lengthName.Length)].SequenceEqual(lengthName));int stringDelta=nameExists?0:lengthName.Length;
  R(sc.Size==sb.Size+stringDelta&&oldStrings.SequenceEqual(rc[sc.Offset..(sc.Offset+sb.Size)]),"Entire String stream prefix including padding");if(stringDelta>0)R(rc[(sc.Offset+sb.Size)..(sc.Offset+sc.Size)].SequenceEqual(lengthName),"Only approved String name appended");
  foreach(HeapIndex h in Enum.GetValues<HeapIndex>()){if(h==HeapIndex.String)continue;int n=mb.GetHeapSize(h);R(mc.GetHeapSize(h)==n,"Heap size "+h);int x=mb.GetHeapMetadataOffset(h),y=mc.GetHeapMetadataOffset(h);R(rb[x..(x+n)].SequenceEqual(rc[y..(y+n)]),"Heap bytes "+h);}
  int non=0;foreach(var h in mb.MethodDefinitions){int token=MetadataTokens.GetToken(h);var bm=mb.GetMethodDefinition(h);var cm=mc.GetMethodDefinition(h);R(bm.RelativeVirtualAddress==cm.RelativeVirtualAddress,"RVA drift");if(bm.RelativeVirtualAddress==0)continue;var ob=pb.GetMethodBody(bm.RelativeVirtualAddress);var nb=pc.GetMethodBody(cm.RelativeVirtualAddress);int off=Offset(pb,bm.RelativeVirtualAddress);if(targets.Contains(token)){R(ob.LocalSignature==nb.LocalSignature&&ob.LocalVariablesInitialized==nb.LocalVariablesInitialized&&ob.ExceptionRegions.Length==0&&nb.ExceptionRegions.Length==0,"Target local/header flags");var row=report.RootElement.GetProperty("methods").EnumerateArray().Single(x=>Convert.ToInt32(x.GetProperty("token").GetString(),16)==token);R(row.GetProperty("header").GetInt32()==off,"Pinned body offset");Allow(off+2,6);Allow(off+12,ob.GetILBytes()!.Length);var md=(Mono.Cecil.MethodDefinition)ac.MainModule.LookupToken(token);R(md.Body.Instructions.All(i=>i.Operand is not Mono.Cecil.Cil.Instruction j||md.Body.Instructions.Contains(j)),"Invalid branch");R(!md.Body.Instructions.Any(i=>i.OpCode==Mono.Cecil.Cil.OpCodes.Ldstr&&i.Operand is string s&&(s.Contains("Indirect call:")||s.Contains("Warning:"))),"Unresolved reconstruction");R(H(nb.GetILBytes()!)==row.GetProperty("code_sha256").GetString(),"Reopened code digest");}else{R(ob.Size==nb.Size,"Non-target size");R(b[off..(off+ob.Size)].SequenceEqual(c[off..(off+nb.Size)]),"Non-target raw body "+token.ToString("X8"));non++;}}
  var pe=pb.PEHeaders;int lastHeader=pe.PEHeaderStartOffset+pe.CoffHeader.SizeOfOptionalHeader+(pe.CoffHeader.NumberOfSections-1)*40;Allow(lastHeader+8,4);Allow(lastHeader+16,4);Allow(pe.PEHeaderStartOffset+8,4);Allow(pe.PEHeaderStartOffset+56,4);Allow(pe.PEHeaderStartOffset+64,4);Allow(pe.CorHeaderStartOffset+8,8);var diffs=Enumerable.Range(0,b.Length).Where(i=>b[i]!=c[i]).ToArray();R(diffs.All(allowed.Contains),"Unapproved original-file difference");R(pc.PEHeaders.SectionHeaders.Length==pb.PEHeaders.SectionHeaders.Length,"Section count");for(int i=0;i<pb.PEHeaders.SectionHeaders.Length-1;i++)R(pb.PEHeaders.SectionHeaders[i].Equals(pc.PEHeaders.SectionHeaders[i]),"Original PE section changed");int first=mb.GetTableRowCount(TableIndex.MemberRef)+1;string[] names={"System.Int32 System.String::get_Length()","System.Void UnityEngine.Events.UnityEvent`3<System.String,System.Int32,System.Int32>::Invoke(!0,!1,!2)","System.Void UnityEngine.Events.UnityEvent`3<System.String,System.String,System.Int32>::Invoke(!0,!1,!2)"};var added=new List<object>();for(int i=0;i<3;i++){var m=(MethodReference)ac.MainModule.LookupToken(0x0A000000+first+i);R(m.FullName==names[i]&&m.HasThis,"Public/closed member binding");if(i==0){R(m.Parameters.Count==0&&m.DeclaringType.MetadataToken.ToInt32()==0x0100000B,"Public String length owner");}else{R(m.Parameters.Count==3,"Invoke arity");for(int j=0;j<3;j++)R(m.Parameters[j].ParameterType is Mono.Cecil.GenericParameter g&&g.Type==GenericParameterType.Type&&g.Position==j,"Generic parameter binding");}added.Add(new{token=$"0x{m.MetadataToken.ToInt32():X8}",name=m.FullName});}
  var ns=pc.PEHeaders.SectionHeaders.Last();var os=pb.PEHeaders.SectionHeaders.Last();R(ns.Name==".n29meta"&&ns.Name==os.Name&&ns.PointerToRawData==os.PointerToRawData&&ns.VirtualAddress==os.VirtualAddress&&ns.SectionCharacteristics==os.SectionCharacteristics&&ns.PointerToRelocations==os.PointerToRelocations&&ns.PointerToLineNumbers==os.PointerToLineNumbers&&ns.NumberOfRelocations==os.NumberOfRelocations&&ns.NumberOfLineNumbers==os.NumberOfLineNumbers,"Extended section identity");int rootRva=pc.PEHeaders.CorHeader!.MetadataDirectory.RelativeVirtualAddress,metaSize=pc.PEHeaders.CorHeader.MetadataDirectory.Size,raw=Offset(pc,rootRva);R(raw==b.Length&&ns.VirtualSize==raw-ns.PointerToRawData+metaSize&&c.Length==ns.PointerToRawData+ns.SizeOfRawData&&c[(raw+metaSize)..].All(z=>z==0),"Appended metadata root extent and padding");R(pc.PEHeaders.PEHeader!.SizeOfInitializedData==pb.PEHeaders.PEHeader!.SizeOfInitializedData+c.Length-b.Length,"Initialized data increment");R(pc.PEHeaders.PEHeader.SizeOfImage==((ns.VirtualAddress+ns.VirtualSize+pc.PEHeaders.PEHeader.SectionAlignment-1)/pc.PEHeaders.PEHeader.SectionAlignment)*pc.PEHeaders.PEHeader.SectionAlignment,"SizeOfImage extent");
  var r=new{input_sha256=H(b),candidate_sha256=H(c),targets=targets.Count,non_target_raw_bodies_equal=non,existing_table_rows_equal=tableRows,existing_heap_prefixes_equal=true,string_heap_added_bytes=stringDelta,original_section_locations_equal=true,non_metadata_sections_equal=true,metadata_section_extended=true,old_file_changed_bytes=diffs.Length,appended_bytes=c.Length-b.Length,new_member_refs=added,pass=true};File.WriteAllText(args[3],JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{r.targets,r.non_target_raw_bodies_equal,r.old_file_changed_bytes,r.appended_bytes,r.pass}));return 0;}catch(Exception e){Console.Error.WriteLine(e);return 2;}}
}
